### PR TITLE
feat(net): fix peer backoffs to not interfere with reputation

### LINKED ISSUE #2410: Retain peer reputation in the backoff process
### Describe the bug

Currently, backing off from a peer uses the same mechanism as banning a peer (slashing reputation under the threshold), but with a shorter duration. The problem is that when peers are unbanned, their reputation is reset to 0. This means that any reputation assigned to the peer before that will be lost (wether positive or negative).

I propose using a separate mechanism for backing off from peers. I see 2 ways to do this:
1. Don't modify the `Peer` reputation, but put them in the `BanList`. `fill_outbound_slots` (responsible for dialing new peers), can then just check if the peer is in the `BanList`. **Downside**: performance hit on additional map lookups cc @mattsse.
2. Add a field to `Peer` to keep track of backoffs: `backed_off: bool`. We also keep a `HashMap<PeerId, std::time::Duration>` in `PeerManager`, that we can use to keep track of backoff deadlines. We can then check this map on every `unban_interval` expiring.

I can submit a PR for this based on your feedback.

### Steps to reproduce

-

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

main

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mempirate**
Closes #2410

Implements a fix whereby the backoff mechanism interferes with peer reputation:

* Adds `backed_off: bool` field to `Peer`
* Adds `backoff_list: HashMap<PeerId, std::time::Instant>` to `PeersManager`
* When peers need to be backed off from, we mark them with `backed_off` and save the backoff expiration in `backoff_list`
* Every `unban_interval`, check the `backoff_list` and see which ones expire. We can clear those entries and mark the peers as not backed off.
* On dialing (`fill_outbound_slots` > `best_unconnected`), we check if the peer is backed off as well as banned before dialing

### CODE REVIEW

**Comment by mattsse** [comment]
haven't reviewed, yet, but would be nice to have a new metric for number of backed off peers

**Comment by jonasbostoen** [comment]
@mattsse only the network manager has access to metrics, so I could do this through an additional event? Or just set the metric on another event happening (like the PendingSessionClosed events)?

**Comment by mattsse** [comment]
> Or just set the metric on another event happening (like the PendingSessionClosed events)?

yeh that is reasonable

File: crates/net/network/src/peers/manager.rs [hunk 1]
```diff
@@ -245,8 +254,8 @@ impl PeersManager {
     /// be scheduled.
     pub(crate) fn on_incoming_session_established(&mut self, peer_id: PeerId, addr: SocketAddr) {
         // we only need to check the peer id here as the ip address will have been checked at
-        // on_inbound_pending_session
-        if self.ban_list.is_banned_peer(&peer_id) {
+        // on_inbound_pending_session. We also check if the peer is in the backoff list here.
+        if self.ban_list.is_banned_peer(&peer_id) || self.backoff_list.contains_key(&peer_id) {
```
Comment (mattsse) [inline crates/net/network/src/peers/manager.rs:258]: hmm, I think we only backoff if we failed to establish a connection, so rejecting an incoming connection because we backed off is not reasonable imo

I think we can just neglect this

File: crates/net/network/src/peers/manager.rs [hunk 2]
```diff
@@ -95,8 +95,10 @@ pub(crate) struct PeersManager {
     reputation_weights: ReputationChangeWeights,
     /// Tracks current slot stats.
     connection_info: ConnectionInfo,
-    /// Tracks unwanted ips/peer ids,
+    /// Tracks unwanted ips/peer ids.
     ban_list: BanList,
+    /// Tracks currently backed off peers.
+    backoff_list: HashMap<PeerId, std::time::Instant>,
```
Comment (mattsse) [inline crates/net/network/src/peers/manager.rs:101]: `list` doesn't really fit, but since we also have `BanList`, this is fine

**Review by mattsse — CHANGES_REQUESTED** [review]
nice, only smol nits,

I think we should also consider renaming `unban_interval` to something more appropriate.
but no suggestions atm

File: crates/net/network/src/peers/manager.rs (hunk 1 above)
Comment (jonasbostoen) [reply crates/net/network/src/peers/manager.rs:258]: No I actually agree but somehow the `test_shutdown` integration depends on this behaviour. I can rewrite the test as well?

Comment (jonasbostoen) [reply crates/net/network/src/peers/manager.rs:258]: So the `test_shutdown` final assert relies on a `DisconnectRequested`, seeming to assume that its coming from the peer that actually shut down (P1). But that `DisconnectRequested` actually comes from the peer it's trying to connect to (P2), because P1 was banned (backed off) and therefore the connection was killed. I guess what should really happen when trying to connect to a peer after shutdown is it should just be ignored right?

File: crates/net/network/src/peers/manager.rs [hunk 3]
```diff
@@ -716,6 +728,18 @@ impl PeersManager {
                     }
                     self.queued_actions.push_back(PeerAction::UnBanPeer { peer_id });
                 }
+
+                // clear the backoff list of expired backoffs, and mark the relevant peers as
+                // ready to be dialed
+                self.backed_off_peers.retain(|peer_id, until| {
+                    if std::time::Instant::now() > *until {
```
Comment (mattsse) [inline crates/net/network/src/peers/manager.rs:735]: perf:
only call `::now` once, outside  
see line 721

**Review by mattsse — CHANGES_REQUESTED** [review]
yeh, I like this

**Review by mattsse — APPROVED** [review]
nice!
