### PR TITLE
fix: respect --p2p-secret-key argument

### LINKED ISSUE #2548: --p2p-secret-key setting is not used
### Describe the bug

default value for --p2p-secret-key is always used.

#### Writing to custom location that isn't possible, does NOT throw error.
1. ./reth node --p2p-secret-key /some/non-writable/path
2. Reth still uses default key and does not throw error

#### Disable using default key location, now it throws an error even though custom location defined.
1. chmod a-r ~/.local/share/reth/mainnet/discovery-secret
2. ./reth node --p2p-secret-key /some/non-writable/path
3. Reth throws error

### Node logs

_No response_

### Platform(s)

Linux (x86)

### What version/commit are you on?

010b600f392b349a1584ff5e3193d706c54a959f

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### LINKED ISSUE #2551: Cli paths broken, user input ignored
### Describe the feature

as highlighted here #2508

user input is now ignored ref https://github.com/paradigmxyz/reth/pull/2495

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
Closes https://github.com/paradigmxyz/reth/issues/2551
Closes #2548

needs followup to adhere to the suggestions made in #2498, should fail if p2p-secret file does not exist.

configuring the network has grown a bit, there's potential for simplifying it a bit.

### CODE REVIEW

File: bin/reth/src/args/secret_key.rs [hunk 1]
```diff
@@ -10,8 +14,14 @@ use thiserror::Error;
...
-    #[error("An I/O error occurred: {0}")]
-    IOError(#[from] std::io::Error),
+    #[error("Failed to create parent directory {dir:?} for secret key: {error}")]
+    FailedToCreateSecretParentDir { error: io::Error, dir: PathBuf },
+    #[error("Failed to write secret key file {secret_file:?}: {error}")]
+    FailedToWriteSecretKeyFile { error: io::Error, secret_file: PathBuf },
+    #[error("Failed to read secret key file {secret_file:?}: {error}")]
+    FailedToReadSecretKeyFile { error: io::Error, secret_file: PathBuf },
+    #[error("Failed to access key file {secret_file:?}: {error}")]
+    FailedToAccessKeyFile { error: io::Error, secret_file: PathBuf },
```
Comment (Rjected) [inline bin/reth/src/args/secret_key.rs:24]: ah these are much nicer errors

**Review by Rjected — APPROVED** [review]
LGTM, moving this to the `NetworkArgs` makes sense given how many commands we had with a standalone `p2p_secret_key` arg
