### PR TITLE
fix(op): ensure `EthApiServer` helper trait method default impls, call `OpEthApi` overrides

### LINKED ISSUE #9868: Rework `OpEthApi` type
### Describe the feature

`OpEthApi` should wrap `EthApiInner<...>`, just like `EthApi` struct does, instead of the generic `Eth`. Calling `Eth::some_trait_method` in implementation of `EthApiServer` helper traits is bug prone, since any default trait method overrides for `OpEthApi`, won't be considered if called inside scope of `Eth::some_trait_method`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/9868

- Replaces inner type on `OpEthApi` with `EthApiInner`. This ensure that the default trait method impls kept by `OpEthApi`, will actually invoke the `OpEthApi` overrides of other trait methods.
- Inlines getters in `EthApiServer` helper trait impls for `OpEthApi`
- Adds getter trait methods for `EthState` and `EthApiSpec`, and moves impl of trait methods for `EthApi`, into default impl, to simplify impl for re-worked `OpEthApi` type

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
> This ensure that the default trait method impls kept by OpEthApi, will actually invoke the OpEthApi overrides of other trait methods.

can you please elaborate on this, not obvious to me what this pr fixes.

> Adds getter trait methods for EthState and EthApiSpec, and moves impl of trait methods for EthApi, into default impl, to simplify impl for re-worked OpEthApi type

isn't the approach then implement everything that's required on opapi directly and not move more stuff to default impls or did I misunderstood this?

**Comment by emhane** [comment]
hope this is helpful to understand @mattsse <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f22868e00a2b877425802be4fbbf2f65>

**Comment by mattsse** [comment]
gotcha, where do we have this problem rn?

this sounds more like a general design problem due to the many helper traits with default impls

File: crates/optimism/rpc/src/eth/mod.rs [hunk 1]
```diff
@@ -7,30 +7,53 @@ mod block;
...
-use reth_rpc_eth_types::EthStateCache;
-use reth_rpc_types::SyncStatus;
-use reth_tasks::{pool::BlockingTaskPool, TaskSpawner};
 use reth_transaction_pool::TransactionPool;
-use tokio::sync::{AcquireError, OwnedSemaphorePermit};
 
 use crate::OpEthApiError;
 
+/// Adapter for [`EthApiInner`], which holds all the data required to serve core `eth_` API.
+pub type EthApiHandles<N> = EthApiInner<
```
Comment (mattsse) [inline crates/optimism/rpc/src/eth/mod.rs:40]:
```suggestion
pub type EthApiFor<N> = EthApiInner<
```

File: crates/optimism/rpc/src/eth/mod.rs [hunk 2]
```diff
@@ -7,30 +7,53 @@ mod block;
...
+>;
+
+/// Adapter for [`EthApiBuilderCtx`].
+pub type EthApiBuilderCtx<N> = reth_rpc_eth_types::EthApiBuilderCtx<
+    <N as FullNodeTypes>::Provider,
+    <N as FullNodeComponents>::Pool,
+    <N as FullNodeComponents>::Evm,
+    NetworkHandle,
+    TaskExecutor,
+    <N as FullNodeTypes>::Provider,
```
Comment (mattsse) [inline crates/optimism/rpc/src/eth/mod.rs:54]: now your pr about the AT network type makes perfect sense to me,

perhaps we start by removing the taskexecutor generic and replace with `Box<dyn>`? don't think the generic is actually useful

**Review by mattsse — APPROVED** [review]
okay, now that I had some time to think about this, this makes perfect sense and we need to wrap the inner type as you highlighted

only have naming suggestion

File: crates/optimism/rpc/src/eth/mod.rs (hunk 2 above)
Comment (emhane) [reply crates/optimism/rpc/src/eth/mod.rs:54]: actually, I'd like to replace both consensus trait object and task executor trait object with generics eventually. trait objects are great for things that aren't in scope for the whole program, but for consensus and task executor that isn't the case and we can make the smol perf gain by resolving them at compile time. also because we already have a great way to pass the components down to the `FullNode` type, which is via the `FullNodeComponents` trait.

made an issue https://github.com/paradigmxyz/reth/issues/9872, will tackle it before continuing with https://github.com/paradigmxyz/reth/pull/9774
