### PR TITLE
dev: track invalid transactions by sender in pool

### LINKED ISSUE #12136: Track invalid transactions by sender
### Describe the feature

The docs state

https://github.com/paradigmxyz/reth/blob/87a615fe265137fab0831fb9047268addbbe4d2c/crates/transaction-pool/src/traits.rs#L748-L753

but we only track the hash here:

https://github.com/paradigmxyz/reth/blob/87a615fe265137fab0831fb9047268addbbe4d2c/crates/transaction-pool/src/pool/best.rs#L95-L98

the docs even mention this but the impl is incorrect

## TODO
* track SenderId here

perhaps @greged93 ?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by greged93**
This PR modifies the tracking of invalid transactions in the pool by tracking them by sender id instead of transaction hash.

Resolves #12136

### CODE REVIEW

File: crates/transaction-pool/src/pool/best.rs [hunk 1]
```diff
@@ -95,6 +95,13 @@ impl<T: TransactionOrdering> BestTransactions<T> {
     /// Mark the transaction and it's descendants as invalid.
     pub(crate) fn mark_invalid(&mut self, tx: &Arc<ValidPoolTransaction<T::Transaction>>) {
         self.invalid.insert(*tx.hash());
+
+        // Mark all descendants as invalid
+        let mut descendant_id = tx.id().descendant();
+        while let Some(descendant) = self.all.get(&descendant_id) {
+            self.invalid.insert(*descendant.transaction.hash());
+            descendant_id = descendant.transaction.id().descendant();
+        }
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/best.rs:104]: we kinda already have an euqivalent check for this in `next`, so what we actually need to check instead is marking the `SenderId` as `self.invalid` and not the hash. so instead of `self.invalid.insert(*tx.hash());` we need to track the tx.sender_id instead

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
