### PR TITLE
fix(discv5): get `fork_id` from `Enr` for all network stacks

### LINKED ISSUE #18924: Discv5 doesn't get `fork_id` from `Enr` when discovering peer on OPEL network stack
### Describe the bug

Image

After looking at the code , I've seen that only `ETH` network stack is handled, others are ignored (there is a todo comment):
https://github.com/paradigmxyz/reth/blob/6f96a328128eb79a3009669b0a32f232971a99c9/crates/net/discv5/src/lib.rs#L323-L326

Once modified to accept also `OPEL`:

Image
 

Are there any side effects that I might have missed with this modification? Is this relevant and would you like to have this modified ? Thanks 👍

### Steps to reproduce

```bash
RUST_LOG=info,net::discv5=trace ./target/release/op-reth node --dev\
  --disable-dns-discovery\
  --disable-discv4-discovery\
  --enable-discv5-discovery\
  --disable-nat\
   --no-persist-peers\
```

### Node logs

```text

```

### Platform(s)

Mac (Apple Silicon)

### Container Type

Not running in a container

### What version/commit are you on?

master (6f96a328128eb79a3009669b0a32f232971a99c9)

### What database version are you on?

2

### Which chain / network are you on?

dev

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

cargo build -r -p op-reth

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mablr**
Fix #18924

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

pending @emhane

**Review by emhane — APPROVED** [review]

**Comment by emhane** [comment]
thanks @mablr ! ETH is EL and ETH2 is CL.

ok so based on op-geth behaviour, let's do this
here
https://github.com/paradigmxyz/reth/blob/856ad087766476f9fd20624c136951f654d5fdaa/crates/net/discv5/src/lib.rs#L387-L391
we want to do smthg like this
```rust
        let Some(key) = self.fork_key else { return Err(Error::NetworkStackIdNotConfigured) };
        let fork_id = enr
            .get_decodable::<EnrForkIdEntry>(key)
            .ok_or(enr
                .get_decodable::<EnrForkIdEntry>(NetworkStackId::ETH)
                .ok_or(Error::ForkMissing(key)?
            )?
            .map(Into::into)?;
```
the syntax in my example is a bit off but I think you get the point? would you mind implementing it? would be good if we had a trace log for the case when the configured key isn't found. we will also need to change the error message for `Error::ForkMissing(key)` to say that neither `{key}` nor 'eth' were found among the ENR kv-pairs. need to double check also that metrics are update correctly so they don't increment the count for e.g. 'opel' hits when actually it just found the 'eth' key.

File: crates/net/discv5/src/error.rs [hunk 1]
```diff
@@ -13,7 +13,7 @@ pub enum Error {
     #[error("network stack identifier is not configured")]
     NetworkStackIdNotConfigured,
     /// Missing key used to identify rlpx network.
-    #[error("fork missing on enr, key missing")]
+    #[error("fork missing on enr, with local network id '{id}', and 'eth' always accepted as fallback", id = String::from_utf8_lossy(.0))]
```
Comment (emhane) [inline crates/net/discv5/src/error.rs]:
```suggestion
    #[error("fork missing on enr, key {0} and key 'eth' missing"}]
```
can be simplified to. don't need to decode it.

File: crates/net/discv5/src/lib.rs [hunk 2]
```diff
@@ -384,7 +384,23 @@ impl Discv5 {
...
             .get_decodable::<EnrForkIdEntry>(key)
-            .ok_or(Error::ForkMissing(key))?
+            .or({
+                (key != NetworkStackId::ETH)
+                    .then(|| {
+                        // Fallback: trying to get fork id from Enr with 'eth' as network stack id
+                        trace!(
+                            target: "net::discv5",
+                            "fork id not found for '{key}' network stack id, trying 'eth'",
+                            key = String::from_utf8_lossy(key),
```
Comment (emhane) [inline crates/net/discv5/src/lib.rs]:
```suggestion
                            key = String::from_utf8_lossy(key),
                            "Fork id not found for key, trying 'eth'...",
```
message usually goes last. since we have the kv pairs we don't substitute values into the message.

File: crates/net/discv5/src/lib.rs [hunk 3]
```diff
@@ -384,7 +384,23 @@ impl Discv5 {
         let Some(key) = self.fork_key else { return Err(Error::NetworkStackIdNotConfigured) };
         let fork_id = enr
             .get_decodable::<EnrForkIdEntry>(key)
-            .ok_or(Error::ForkMissing(key))?
+            .or({
+                (key != NetworkStackId::ETH)
+                    .then(|| {
+                        // Fallback: trying to get fork id from Enr with 'eth' as network stack id
+                        trace!(
+                            target: "net::discv5",
```
Comment (emhane) [inline crates/net/discv5/src/lib.rs]:
```suggestion
                        trace!(target: "net::discv5",
```
can save some whitespace with target on same line like that and then put the next values in column like you have done, nice.

**Review by emhane — APPROVED** [review]
nice! nitpicks remaining

File: crates/net/discv5/src/lib.rs [hunk 4]
```diff
@@ -388,11 +388,7 @@ impl Discv5 {
                 (key != NetworkStackId::ETH)
                     .then(|| {
                         // Fallback: trying to get fork id from Enr with 'eth' as network stack id
-                        trace!(
-                            target: "net::discv5",
-                            "fork id not found for '{key}' network stack id, trying 'eth'",
-                            key = String::from_utf8_lossy(key),
-                        );
+                        trace!(target: "net::discv5", "Fork id not found for key, trying 'eth'...");
```
Comment (emhane) [inline crates/net/discv5/src/lib.rs]:
```suggestion
                        trace!(target: "net::discv5",
                            key = String::from_utf8_lossy(key),
                            "Fork id not found for key, trying 'eth'..."
                        );
```
excuse me if wasn't clear, we want to keep the key kv-pair like it was!

Comment (mablr) [reply crates/net/discv5/src/lib.rs]: no problem, I reverted it. Assuming decoding here is useful.

File: crates/net/discv5/src/lib.rs [hunk 5]
```diff
@@ -388,7 +388,10 @@ impl Discv5 {
                 (key != NetworkStackId::ETH)
                     .then(|| {
                         // Fallback: trying to get fork id from Enr with 'eth' as network stack id
-                        trace!(target: "net::discv5", "Fork id not found for key, trying 'eth'...");
+                        trace!(target: "net::discv5",
+                            "Fork id not found for '{key}' network stack id, trying 'eth'...",
+                            key = String::from_utf8_lossy(key)
+                        );
```
Comment (emhane) [inline crates/net/discv5/src/lib.rs:394]:
```suggestion
                        trace!(target: "net::discv5",
                            key = String::from_utf8_lossy(key),
                            "Fork id not found for key, trying 'eth'..."
                        );
```

**Comment by emhane** [comment]
Screenshot 2025-10-16 at 11 19 44
check out how it looks with the message and then the kv-pairs
