### PR TITLE
fix: dont panic on invalid l1 blockinfo calldata

### LINKED ISSUE #7833: Transfers fail in op-reth dev mode
If you use `op-reth --dev`, for example `alphanet --dev`, and attempt to send funds:
```
dan@Dans-MacBook-Pro-4 ~> cast send --account reth-dev 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --chain 1337
Enter keystore password:
```

This happens:
```
2024-04-23T22:06:31.605423Z  INFO Canonical chain committed number=594 hash=0xd11c205ce7f02536414b651d52f2e88498bcb8f93f9ff3afb64cbdf2ebbdd6a4 elapsed=1.786416ms
2024-04-23T22:06:31.605718Z  INFO Static File Producer started targets=StaticFileTargets { headers: Some(594..=594), receipts: Some(594..=594), transactions: Some(594..=594) }
2024-04-23T22:06:31.641521Z  INFO Static File Producer finished targets=StaticFileTargets { headers: Some(594..=594), receipts: Some(594..=594), transactions: Some(594..=594) } elapsed=35.753708ms
2024-04-23T22:06:32.606298Z  INFO Live sync in progress, downloading blocks remaining_blocks=1 target_block_hash=0x92646f06cbcfcc0b59e6458f9d03dd6786c59a329d395eaac93faef72b77fc08
2024-04-23T22:06:32.606366Z  INFO Received forkchoice updated message when syncing head_block_hash=0x92646f06cbcfcc0b59e6458f9d03dd6786c59a329d395eaac93faef72b77fc08 safe_block_hash=0x92646f06cbcfcc0b59e6458f9d03dd6786c59a329d395eaac93faef72b77fc08 finalized_block_hash=0x92646f06cbcfcc0b59e6458f9d03dd6786c59a329d395eaac93faef72b77fc08
2024-04-23T22:06:32.610254Z  INFO Block is already canonical, ignoring. block_hash=0x92646f06cbcfcc0b59e6458f9d03dd6786c59a329d395eaac93faef72b77fc08
thread 'tokio-runtime-worker' panicked at /Users/dan/.cargo/git/checkouts/reth-36d3ea1d1152b20c/fa9f23d/crates/revm/src/optimism/mod.rs:45:23:
range end index 4 out of range for slice of length 0
2024-04-23T22:06:32.610424Z  INFO Canonical chain committed number=595 hash=0x92646f06cbcfcc0b59e6458f9d03dd6786c59a329d395eaac93faef72b77fc08 elapsed=3.050334ms
stack backtrace:
2024-04-23T22:06:32.610865Z  INFO Static File Producer started targets=StaticFileTargets { headers: Some(595..=595), receipts: Some(595..=595), transactions: Some(595..=595) }
thread 'tokio-runtime-worker' panicked at /Users/dan/.cargo/git/checkouts/reth-36d3ea1d1152b20c/fa9f23d/crates/revm/src/optimism/mod.rs:45:23:
range end index 4 out of range for slice of length 0
2024-04-23T22:06:32.650637Z  INFO Static File Producer finished targets=StaticFileTargets { headers: Some(595..=595), receipts: Some(595..=595), transactions: Some(595..=595) } elapsed=39.794ms
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
   4: reth_revm::optimism::extract_l1_info
   5: reth_node_optimism::txpool::OpTransactionValidator<Client,Tx>::update_l1_block_info
   6: <reth_transaction_pool::Pool<V,T,S> as reth_transaction_pool::traits::TransactionPoolExt>::on_canonical_state_change
   7: reth_transaction_pool::maintain::maintain_transaction_pool::{{closure}}
   8: reth_transaction_pool::maintain::maintain_transaction_pool_future::{{closure}}
   9: reth_tasks::TaskExecutor::spawn_critical_as::{{closure}}
  10: tokio::runtime::task::raw::poll
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  12: tokio::runtime::scheduler::multi_thread::worker::run
  13: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
2024-04-23T22:06:32.701486Z ERROR Critical task `txpool maintenance task` panicked: `range end index 4 out of range for slice of length 0`
2024-04-23T22:06:32.701566Z ERROR shutting down due to error
Error: Critical task `txpool maintenance task` panicked: `range end index 4 out of range for slice of length 0`

Location:
   4: reth_revm::optimism::extract_l1_info
   5: <reth_rpc::eth::api::EthApi<Provider,Pool,Network,EvmConfig> as reth_rpc::eth::api::transactions::EthTransactions>::transaction_receipt::{{closure}}
    /Users/dan/.cargo/git/checkouts/reth-36d3ea1d1152b20c/fa9f23d/crates/cli/runner/src/lib.rs:147:32
   6: reth_rpc::eth::api::server::<impl reth_rpc_api::eth::EthApiServer for reth_rpc::eth::api::EthApi<Provider,Pool,Network,EvmConfig>>::transaction_receipt::{{closure}}
   7: jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_async_method::{{closure}}::{{closure}}
   8: <reth_rpc_builder::metrics::MeteredRequestFuture<F> as core::future::future::Future>⏎
```

This is because the dev mode places the transaction as the first transaction, this transaction has no calldata, and this line is run:
https://github.com/paradigmxyz/reth/blob/c659e28aa0e3ea5e83341b8a9eead0f0c89c296a/crates/revm/src/optimism/mod.rs#L27-L50

### PR DESCRIPTION
**Pull request by mattsse**
closes #7833
the --dev mode wasn't really designed for OP and likely lacks some L2 specific things,

need to check if the executor also has some issues due to this,
maybe in OP --dev mode we need to inject a fake L1 block info tx

### CODE REVIEW

**Review by DaniPopes — APPROVED** [review]
lgmt

File: crates/revm/src/optimism/mod.rs [hunk 1]
```diff
@@ -100,18 +105,21 @@ pub fn parse_l1_info_tx_bedrock(data: &[u8]) -> Result<L1BlockInfo, BlockExecuti
 }
 
 /// Parses the calldata of the [L1BlockInfo] transaction post-Ecotone hardfork.
+///
+/// This will fail if the call data is not exactly 160 bytes long:
```
Comment (DaniPopes) [inline crates/revm/src/optimism/mod.rs:109]: Now doc does not match parse_l1_info_tx_bedrock : (
