### PR TITLE
fix: crash ExEx task when the ExEx future returns

### LINKED ISSUE #7630: Crash ExEx task when the ExEx future returns
### Describe the feature

If an ExEx future returns it means it has stopped processing incoming notifications which we will (at least for now) treat as a fatal error. We assume that users running ExEx's want them to be up to date, and we have built the system under this assumption.

Because of this, we should panic here even if the ExEx returns `Ok(())`: https://github.com/paradigmxyz/reth/blob/4d799673357d69927059854aa2231d34dc4dbe18/crates/node-builder/src/builder.rs#L630-L631 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AbnerZheng**
close https://github.com/paradigmxyz/reth/issues/7630

### CODE REVIEW

File: crates/node-builder/src/builder.rs [hunk 1]
```diff
@@ -627,7 +627,10 @@ where
                 // spawn it as a crit task
                 executor.spawn_critical("exex", async move {
                     info!(target: "reth::cli", id, "ExEx started");
-                    exex.await.unwrap_or_else(|_| panic!("exex {} crashed", id))
+                    match exex.await {
+                        Ok(_) => panic!("ExEx {id} finished"),
```
Comment (onbjerg) [inline crates/node-builder/src/builder.rs:631]:
```suggestion
                        Ok(_) => panic!("ExEx {id} finished. ExEx's should run indefinitely"),
```

**Review by onbjerg — COMMENTED** [review]
just to explain why this is bad behavior shortly

**Review by onbjerg — APPROVED** [review]
