### PR TITLE
fix(op-interop): incorrect parsing of `supervisor_checkAccessList` error

### LINKED ISSUE #15669: Remove outdated error parsing
### Describe the feature

Remove error parsing of `supervisor_checkMessages` error message string. It is not identical to `supervisor_checkAccesList` error message string.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/15669

have opened an issue to make this error more helpful once unblocked https://github.com/paradigmxyz/reth/issues/15671

### CODE REVIEW

File: crates/optimism/txpool/src/supervisor/errors.rs [hunk 1]
```diff
@@ -1,245 +1,23 @@
...
-    }
-
-    /// Returns `true` if message is at least [`SafetyLevel::CrossUnsafe`].
-    pub fn is_msg_at_least_cross_unsafe(&self) -> bool {
-        self.is_msg_cross_unsafe() || self.is_msg_local_safe() || self.is_msg_safe()
-    }
-
-    /// Parses error message. Returns `None`, if message is not recognized.
-    // todo: match on error code instead of message string once resolved <https://github.com/ethereum-optimism/optimism/issues/14603>
-    pub fn parse_err_msg(err_msg: &str) -> Option<Self> {
```
Comment (mattsse) [inline crates/optimism/txpool/src/supervisor/errors.rs:87]: so much better without this

**Review by mattsse — APPROVED** [review]
