### PR TITLE
fix(trie): fix trie changesets checkpoint handling

### LINKED ISSUE #18903: Trie ChangSets: Fix pipeline checkpoints
### Describe the feature

There are two bugs regarding the pipeline checkpoint for the new MerkleChangeSets stage:

* Inside of the OverlayStateProviderFactory we are checking the checkpoint range within the StageCheckpoint, but in reality only the outer block_number field gets updated by the engine when processing blocks.

* When running on a dev box I noted that the pipeline sync stage is running with a massive range:
```
2025-10-08T09:49:23.823777Z  INFO Status connected_peers=130 stage=MerkleChangeSets checkpoint=23503319 target=23526851
```

This is because the pipeline was restarted after the node was down for a time. 23503319 was indeed the finalized block at the time the node was shut down, but we should limit the sync stage so as to not end up in this situation.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mediocregopher**
Closes #18903

Fixes the two bugs described in that ticket

### CODE REVIEW

File: crates/stages/stages/src/stages/merkle_changesets.rs [hunk 1]
```diff
@@ -73,8 +75,11 @@ impl MerkleChangeSets {
         // Calculate the fallback start position based on retention blocks
         let retention_based_start = merkle_checkpoint.saturating_sub(self.retention_blocks);
 
-        // Use minimum of finalized_block and retention_based_start if finalized_block exists,
-        // otherwise just use retention_based_start
+        // If the finalized block was way in the past then we don't want to generate changesets for
+        // all of those past blocks; we only care about the recent history.
+        //
+        // Use maximum of finalized_block and retention_based_start if finalized_block exists,
```
Comment (Rjected) [inline crates/stages/stages/src/stages/merkle_changesets.rs:81]: This says maximum but the code still uses min?

**Review by Rjected — COMMENTED** [review]
yeah I think using `checkpoint.block_number` is correct, just one question about the comment otherwise lgtm

File: crates/stages/stages/src/stages/merkle_changesets.rs (hunk 1 above)
Comment (mediocregopher) [reply crates/stages/stages/src/stages/merkle_changesets.rs:81]: good catch, i don't know how I missed this :facepalm:
