### PR TITLE
fix: update block interval properly

### LINKED ISSUE #11544: Pruner doesn't respect reth.toml
### Describe the bug

I'm running an archive node, so running the pruner every 5 blocks is pretty useless (Maybe the defaults should be changed?).
To avoid that I've set my `reth.toml` like so:

```
[prune]
block_interval = 999999999
```

Reth doesn't respect that, and instead runs the pruner every 5 blocks.
My start args include `--config /chain/reth/reth.toml `

### Steps to reproduce

1. Set the toml file
2. Run reth

### Node logs

```text
2024-09-29T17:01:51.658181Z  INFO Pruner initialized prune_config=PruneConfig { block_interval: 5, segments: PruneModes { sender_recovery: None, transaction_lookup: None, receipts: None, account_history: None, storage_history: None, receipts_log_filter: ReceiptsLogPruneConfig({}) } }
.
.
.
.
2024-09-29T17:04:12.030185Z  INFO Pruner started tip_block_number=20857669
2024-09-29T17:04:12.030265Z  INFO Pruner finished tip_block_number=20857669 elapsed=36.129µs stats=[]
2024-09-29T17:04:12.174513Z  INFO Canonical chain committed number=20857670 hash=0xfbc9aae9fc6bf0f33bbd3cb005325f4b6c5e7adb7a68d4f245c465e51d361446 elapsed=5.199669ms
2024-09-29T17:04:26.291802Z  INFO Block added to canonical chain number=20857671 hash=0xdff94bd988891d655fbdb526d51318dcc7c396e2367b385c90fdca74bc2ad2a2 peers=4 txs=314 gas=29.74 Mgas gas_throughput=48.39 Mgas/second full=99.1% base_fee=8.41gwei blobs=0 excess_blobs=0 elapsed=614.697335ms
2024-09-29T17:04:26.915397Z  INFO Canonical chain committed number=20857671 hash=0xdff94bd988891d655fbdb526d51318dcc7c396e2367b385c90fdca74bc2ad2a2 elapsed=471.476886ms
2024-09-29T17:04:37.431099Z  INFO Block added to canonical chain number=20857672 hash=0xb5b4c07b3027bd8c31d3a633d351b7a3f53de2ceb0afee5ef9287f078ca5e04f peers=4 txs=187 gas=18.22 Mgas gas_throughput=55.89 Mgas/second full=60.7% base_fee=9.44gwei blobs=0 excess_blobs=0 elapsed=325.965194ms
2024-09-29T17:04:37.825102Z  INFO Canonical chain committed number=20857672 hash=0xb5b4c07b3027bd8c31d3a633d351b7a3f53de2ceb0afee5ef9287f078ca5e04f elapsed=247.612145ms
2024-09-29T17:04:49.429057Z  INFO Block added to canonical chain number=20857673 hash=0xc9ee2c3c58354df89ee5a1579aa4d2ae8e6142733eb02d0ed5ca18151f3e77c6 peers=4 txs=149 gas=14.33 Mgas gas_throughput=56.07 Mgas/second full=47.8% base_fee=9.70gwei blobs=0 excess_blobs=0 elapsed=255.622755ms
2024-09-29T17:04:49.779746Z  INFO Canonical chain committed number=20857673 hash=0xc9ee2c3c58354df89ee5a1579aa4d2ae8e6142733eb02d0ed5ca18151f3e77c6 elapsed=202.166124ms
2024-09-29T17:05:01.955236Z  INFO Block added to canonical chain number=20857674 hash=0xe97f79b369320609ccea5079d0bd5058d8d31d27c991de4769192d2429a50702 peers=6 txs=172 gas=15.12 Mgas gas_throughput=51.34 Mgas/second full=50.4% base_fee=9.64gwei blobs=6 excess_blobs=0 elapsed=294.568121ms
2024-09-29T17:05:02.374190Z  INFO Canonical chain committed number=20857674 hash=0xe97f79b369320609ccea5079d0bd5058d8d31d27c991de4769192d2429a50702 elapsed=266.192532ms
2024-09-29T17:05:02.374232Z  INFO Pruner started tip_block_number=20857674
2024-09-29T17:05:02.374341Z  INFO Pruner finished tip_block_number=20857674 elapsed=52.531µs stats=[]
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

Commit SHA: ab069979867087b72c1dfe24b535cd997b3b5f4b

### What database version are you on?

2

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

[prune]
block_interval = 999999999

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
closes #11544

the block interval update was incorrect.

~~this is also likely not entirely correct, due to how we use this, and this should perhaps check against the default interval, because merge operation is ambiguous here...~~

~~actually this is fine because we don't expose this via cli~~

this is also incorrect, we just don't respect it currently

https://github.com/paradigmxyz/reth/blob/731dde6b7f69e94485fb851837da7aa38037f56a/crates/node/core/src/args/pruning.rs#L19-L22

unsure how to make this sound @emhane

### CODE REVIEW

**Comment by emhane** [comment]
need to replace the block interval type with `Option<usize>`

**Comment by mattsse** [comment]
the update for block interval is still ambiguous but best what we can do here

File: crates/config/src/config.rs [hunk 1]
```diff
@@ -397,27 +400,33 @@ impl PruneConfig {
...
+                    receipts,
+                    account_history,
+                    storage_history,
+                    receipts_log_filter,
+                },
+        } = other;
+
+        // Merge block_interval, only update if it's the default interval
+        if self.block_interval == DEFAULT_BLOCK_INTERVAL {
+            self.block_interval = block_interval;
```
Comment (Rjected) [inline crates/config/src/config.rs:418]: hmm yeah also not sure how we could deal with this differently

**Review by Rjected — APPROVED** [review]
