### PR TITLE
fix: `BlockSource` check for pending block

### LINKED ISSUE #14099: Fix BlockSource check for pending block
### Describe the feature

this is currently incorrect:

https://github.com/paradigmxyz/reth/blob/6b134098124815bd8b4b097f425df21364d0bfd4/crates/storage/provider/src/providers/consistent.rs#L800-L809

the intended behaviour here is that this arm should also be entered if `BlockSource::Any`

https://github.com/paradigmxyz/reth/blob/6b134098124815bd8b4b097f425df21364d0bfd4/crates/storage/provider/src/providers/consistent.rs#L809-L809

## TODO

* also check pending block if `BlockSource::Any`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xMaze**
Closes #14099

### CODE REVIEW

**Comment by 0xMaze** [comment]
@mattsse

File: crates/storage/provider/src/providers/consistent.rs [hunk 1]
```diff
@@ -797,20 +797,32 @@ impl<N: ProviderNodeTypes> BlockReader for ConsistentProvider<N> {
         source: BlockSource,
     ) -> ProviderResult<Option<Self::Block>> {
         match source {
```
Comment (mattsse) [inline crates/storage/provider/src/providers/consistent.rs:799]: this match requires us to duplicate both arms, we can simplify this if we use two matches!(Canonical|Any) matches!(Pending|Any) and only return if some

and fallback is None

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/storage/provider/src/providers/consistent.rs [hunk 2]
```diff
@@ -796,22 +796,26 @@ impl<N: ProviderNodeTypes> BlockReader for ConsistentProvider<N> {
...
-                // Note: it's fine to return the unsealed block because the caller already has
-                // the hash
-                self.get_in_memory_or_storage_by_block(
-                    hash.into(),
-                    |db_provider| db_provider.find_block_by_hash(hash, source),
-                    |block_state| Ok(Some(block_state.block_ref().recovered_block().clone_block())),
-                )
-            }
-            BlockSource::Pending => Ok(self
+        if matches!(source, BlockSource::Any | BlockSource::Pending) {
```
Comment (mattsse) [inline crates/storage/provider/src/providers/consistent.rs:799]: I'd like to restore the previous order where we checked canonical first

and also swap the order in the matches! macro to Pending | any and canonical | any

**Review by mattsse — CHANGES_REQUESTED** [review]
last pedantic nits

**Review by mattsse — APPROVED** [review]
ty
