### PR TITLE
fix(cli): fix `ImportReceiptsOp`

### LINKED ISSUE #10580: Broken command `ImportReceiptsOp`
### Describe the feature

Importing receipts on commit 16577e0 throws error

```
-08-27T20:56:35.768013Z  INFO reth::cli: Importing receipt file chunk first_receipts_block=104896808 total_receipts_chunk=338256
[crates/net/downloaders/src/file_client.rs:410:13] self.chunk.is_empty() = true
2024-08-27T20:56:38.042297Z ERROR reth::cli: Receipts were partially imported total_decoded_receipts=105235062 total_imported_receipts=105235057 total_filtered_out_dup_txns=6
2024-08-27T20:56:38.042312Z ERROR reth::cli: Receipts inconsistent with transactions total_imported_receipts=105235057 total_imported_txns=105235056
2024-08-27T20:56:38.042320Z ERROR reth::cli: Height of receipts inconsistent with transactions highest_block_receipts=105235065 highest_block_transactions=105235063
2024-08-27T20:56:38.042325Z  INFO reth::cli: Receipt file imported total_imported_receipts=105235057 total_decoded_receipts=105235062 total_filtered_out_dup_txns=6
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joshieDo**
closes https://github.com/paradigmxyz/reth/issues/10580

* **does not** commit to storage unless receipts count and block height match transaction's. 
* `bedrock-blocks.rlp` or the decoder(didn't look) issues:
  * Block `1` is repeated and out of place - skipped
  * There seems to exist an extra block `105235064` - now we stop once we hit transactions block height
* Set `ExecutionStageCheckpoint` to the highest block, otherwise an unwind of the receipts will be attempted on a `RW` environment.
 
Tested on commit 2995031eb117f2d966d6d171a86ebbc5b190997c
```bash
$ op-reth import-receipts-op ../bedrock-receipts.rlp --datadir op-mainnet

(...)
2024-09-25T16:42:11.569980Z  INFO Importing receipt file chunk first_receipts_block=104143590 total_receipts_chunk=753218
2024-09-25T16:42:16.825862Z  WARN skipping receipt from a lower block: 1 previous_block_number=105235064
2024-09-25T16:42:16.913226Z  INFO Importing receipt file chunk first_receipts_block=104896808 total_receipts_chunk=338255
2024-09-25T16:42:16.913249Z  WARN Too many decoded blocks, ignoring the last 1. highest_block_receipts=105235063
2024-09-25T16:42:18.927763Z  INFO Receipt file imported
```
```bash
$ op-reth db --datadir op-mainnet stats

| Segment      | Block Range   | Transaction Range | Shape (columns x rows) | Size      |
|--------------|---------------|-------------------|------------------------|-----------|
| Headers      | 0..=105235063 | N/A               | 3 x 105235064          | 44 GiB    |
| Transactions | 0..=105235063 | 0..=105235055     | 1 x 105235056          | 22 GiB    |
| Receipts     | 0..=105235063 | 0..=105235055     | 1 x 105235056          | 34.2 GiB  |
| ------------ | ------------- | ----------------- | ---------------------- | --------  |
| Total        |               |                   |                        | 100.3 GiB |
(...)
```

Tested with:
```bash
$ b3sum 
09f82818cffa448a6fafa627cf9d9ba600aad5138eabd4488659988068016c43  bedrock-blocks.rlp
927f227dfb52a7ec8008f269cf08af53a8b112ac115ee6c22118ade1cc838b0e  bedrock-receipts.rlp
c25d4a790b011a4e0d84ca4340827be397fb63fe7c874ff4987ea4fb2b725fea world_trie_state_op_mainnet_b2c2b6e7edb919a0b856b9fd9aa02b11ead5305e63cdb33386babd82b9bc4cfe.jsonl
```

```
reth init-state ✅ 
reth node --debug.tip 0xeb54d19c714ed434ffb34c50d0619d17890b6b0932042039e2a2dd5ecf3f2e0b ✅ 
```

### CODE REVIEW

File: crates/optimism/cli/src/commands/import_receipts.rs [hunk 1]
```diff
@@ -221,23 +199,54 @@ where
             // this ensures the execution outcome and static file producer start at block 1
             first_block = 1;
         }
+        highest_block_receipts = first_block + receipts.len() as u64 - 1;
+
+        // RLP file may have too many blocks. We ignore the excess, but warn the user.
```
Comment (mattsse) [inline crates/optimism/cli/src/commands/import_receipts.rs:204]: when would this happen?
if the file has more blocks than the bedrock transition block? or duplicated blocks?

> There seems to exist an extra block 105235064

File: crates/optimism/cli/src/commands/import_receipts.rs [hunk 2]
```diff
@@ -246,7 +255,9 @@ where
 /// Result of importing receipts in chunks.
 #[derive(Debug)]
 pub struct ImportReceiptsResult {
+    #[allow(unused)]
     total_decoded_receipts: usize,
+    #[allow(unused)]
     total_filtered_out_dup_txns: usize,
```
Comment (mattsse) [inline crates/optimism/cli/src/commands/import_receipts.rs:261]: this is only used for testing?

let's make those pub instead?

**Review by mattsse — APPROVED** [review]
lgtm
