### PR TITLE
fix: throw error if genesis header found on static files, but empty db

### LINKED ISSUE #11934: Rolling unwinding w/ an error ... v1.1.0
### Describe the bug

rolling unwinding... restarting doesnt help

### Steps to reproduce

run..
ExecStart=reth node --full --authrpc.jwtsecret jwtsecret --authrpc.addr 0.0.0.0 --authrpc.port 8551 --http --http.addr 0.0.0.0 --http.port 8545  --ws --ws.addr 0.0.0.0 --datadir reth_storage --log.file.directory reth_storage --http.api trace,web3,eth,debug --ws.api trace,web3,eth,debug

wait

### Node logs

```text
2024-10-21T15:41:34.743731Z  INFO Recovering senders tx_range=2549956880..2550668156 
2024-10-21T15:41:43.075985Z  INFO Finished stage pipeline_stages=3/14 stage=SenderRecovery checkpoint=21007831 target=21007831 stage_progress=100.00% stage_eta=unknown 
2024-10-21T15:41:43.092262Z  INFO Preparing stage pipeline_stages=4/14 stage=Execution checkpoint=0 target=21007831 
2024-10-21T15:41:43.093331Z  INFO Executing stage pipeline_stages=4/14 stage=Execution checkpoint=0 target=21007831 
2024-10-21T15:41:43.413121Z  INFO Status connected_peers=100 stage=Execution checkpoint=0 target=21007831 
2024-10-21T15:41:56.497039Z ERROR Stage encountered an execution error: EVM reported invalid transaction (0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060): transaction validation error: lack of funds (0) for max fee (1050000000000031337) stage=Execution bad_block=46147 
2024-10-21T15:41:56.498646Z  INFO Unwinding{stage=Finish}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499017Z  INFO Unwinding{stage=Prune}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499265Z  INFO Unwinding{stage=IndexAccountHistory}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499287Z  INFO Unwinding{stage=IndexStorageHistory}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499586Z  INFO Unwinding{stage=TransactionLookup}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499608Z  INFO Unwinding{stage=MerkleExecute}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499630Z  INFO Unwinding{stage=StorageHashing}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499644Z  INFO Unwinding{stage=AccountHashing}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499658Z  INFO Unwinding{stage=MerkleUnwind}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499913Z  INFO Unwinding{stage=PruneSenderRecovery}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499932Z  INFO Unwinding{stage=Execution}: Starting unwind from=0 to=0 bad_block=Some(46147) 
2024-10-21T15:41:56.499954Z  INFO Unwinding{stage=SenderRecovery}: Starting unwind from=21007831 to=0 bad_block=Some(46147) 
2024-10-21T15:42:08.413302Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:42:33.413123Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:42:58.412602Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:43:23.412866Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:43:48.412546Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:44:13.412983Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:44:22.536619Z  INFO Received forkchoice updated message when syncing head_block_hash=0x66bf9049f2c58c461ed1fdc92fc65969e92805f0f3ab3f5463a9df9661345a7d safe_block_hash=0xf961444ada5f580b7a935be5babd51aa5a3acc41fe3afcdb454abd5da9c5a407 finalized_block_hash=0xa4a48738dd86610350565ecbf5f1d087beab38c5d62267e21dc1b53dc50dd66b 
2024-10-21T15:44:38.412797Z  INFO Status connected_peers=99 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:45:03.412630Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:45:28.413265Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:45:53.413401Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:46:18.412598Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:46:43.413124Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:47:08.413363Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:47:33.413307Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:47:58.412840Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:48:23.412538Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:48:48.412621Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:49:13.412819Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:49:38.412646Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:50:03.413027Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:50:28.412531Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:50:46.536958Z  INFO Received forkchoice updated message when syncing head_block_hash=0xc80f0b2112324d03ea7b9a3f29ebf54d6497ccc0221a34b23a118803cce35cde safe_block_hash=0x9bb1e381cd35153ad7b8b1f31cfe26a997fdfeda2c4a83979fc5ef787ebfa098 finalized_block_hash=0xf961444ada5f580b7a935be5babd51aa5a3acc41fe3afcdb454abd5da9c5a407 
2024-10-21T15:50:53.412449Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:51:18.413058Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:51:43.412931Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:52:08.412923Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:52:33.412719Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:52:58.412491Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:53:23.412931Z  INFO Status connected_peers=101 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:53:48.412439Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:54:13.412536Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:54:38.413282Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:55:03.412714Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:55:28.412676Z  INFO Status connected_peers=99 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:55:53.412757Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:56:18.412639Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:56:43.412736Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:57:08.412771Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:57:10.536948Z  INFO Received forkchoice updated message when syncing head_block_hash=0x3893e496d3a1ad55ab3ebe7dd00ac2e928a8e44cb73112e802a22d3682e0837f safe_block_hash=0x6584fe827dfc7830a12711cac446dcfc46585fdb194cca078abbc5c4b412a3e5 finalized_block_hash=0x9bb1e381cd35153ad7b8b1f31cfe26a997fdfeda2c4a83979fc5ef787ebfa098 
2024-10-21T15:57:33.412864Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:57:58.412740Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:58:23.412609Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=21007831 target=0 stage_progress=100.00% 
2024-10-21T15:58:38.338725Z  INFO Unwinding{stage=SenderRecovery}: Stage unwound stage=SenderRecovery unwind_to=0 progress=16007830 done=false 
2024-10-21T15:58:48.413032Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T15:59:13.412661Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T15:59:38.412414Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:00:03.413115Z  INFO Status connected_peers=102 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:00:28.412627Z  INFO Status connected_peers=102 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:00:53.412666Z  INFO Status connected_peers=101 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:01:18.412814Z  INFO Status connected_peers=101 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:01:43.413348Z  INFO Status connected_peers=101 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:02:08.412544Z  INFO Status connected_peers=101 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:02:33.413265Z  INFO Status connected_peers=101 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:02:58.412991Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:03:23.412674Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:03:34.536253Z  INFO Received forkchoice updated message when syncing head_block_hash=0xc9f5704c8e54354cd2115aa5871187b9c0fdc63e5fe125c53c90981657e23e11 safe_block_hash=0xf0659753e047be3675e5566736de84d2a135e7f07cff38561d58eb0e4dcb15dd finalized_block_hash=0x6584fe827dfc7830a12711cac446dcfc46585fdb194cca078abbc5c4b412a3e5 
2024-10-21T16:03:48.412469Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:04:13.412387Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:04:38.413381Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:05:03.413060Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
2024-10-21T16:05:28.412990Z  INFO Status connected_peers=100 stage=SenderRecovery checkpoint=16007830 target=0 stage_progress=69.93% 
```
```


### Platform(s)

Linux (x86)

### What version/commit are you on?

v1.1.0

### What database version are you on?

v1.1.0

### Which chain / network are you on?

mainnet 

### What type of node are you running?

Full via --full flag

### What prune config do you use, if any?

nothing

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by joshieDo**
closes https://github.com/paradigmxyz/reth/issues/13136
closes https://github.com/paradigmxyz/reth/issues/11934

Some users will at times attempt to re-sync from scratch by just deleting the database. Since `factory.block_hash` will only query the static files, we need to make sure that our database has been written to, and throw error if it's empty.
Otherwise, it will proceed and eventually fail on the `ExecutionStage`, after going through a lengthy `SenderRecoveryStage`

### CODE REVIEW

File: crates/storage/db-common/src/init.rs [hunk 1]
```diff
@@ -96,13 +100,20 @@ where
         Ok(None) | Err(ProviderError::MissingStaticFileBlock(StaticFileSegment::Headers, 0)) => {}
         Ok(Some(block_hash)) => {
             if block_hash == hash {
+                // Some users will at times attempt to re-sync from scratch by just deleting the
+                // database. Since `factory.block_hash` will only query the static files, we need to
+                // make sure that our database has been written to, and throw error if it's empty.
+                if factory.get_stage_checkpoint(StageId::Headers)?.is_none() {
+                    return Err(InitStorageError::UninitializedDatabase)
```
Comment (mattsse) [inline crates/storage/db-common/src/init.rs:107]: can we log an error here so in case this happens we know where this is thrown?

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
