### PR TITLE
test: Modify can_serde_config_test

### LINKED ISSUE #1046: Modify `can_serde_config` test to reduce maintenance burden
### Describe the bug

After some recent changes, the test fails with a message similar to:

```
thread 'config::tests::can_serde_config' panicked at 'called `Result::unwrap()` on an `Err` value: 
BadTomlData(Error { inner: ErrorInner { kind: Custom, line: Some(40), col: 0, at: Some(792), 
message: "missing field `downloader_batch_size`", key: ["stages", "headers"] } })', 
crates/staged-sync/src/config.rs:156:51
```

This can be solved by deleting the config file manually, but it can reappear when changing configuration structs (for example, adding an attribute to `BodiesConfig`). Because of this, I propose changing the test to check if the file exists and deleting it before loading. This should fix this for once and for all.

### Steps to reproduce

1. delete one of the lines in the file (e.g. `commit_threshold = 10000`)

- Linux: `$XDG_DATA_HOME/rs.test/default-config.toml` or `$HOME/.local/share/rs.test/default-config.toml`
- Windows: `{FOLDERID_RoamingAppData}/rs.test/default-config.toml`
- macOS: `$HOME/Library/Application Support/rs.test/default-config.toml`

2. run the tests with `cargo test --all --all-features`

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

d6bd075e7bfb37339bea2caafeef303d2bfcedd5

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by fkrause98**
## Changes:
- Closes #1046

### CODE REVIEW

File: crates/staged-sync/src/config.rs [hunk 1]
```diff
@@ -153,6 +153,12 @@ mod tests {
     use super::Config;
     #[test]
     fn can_serde_config() {
+        // Delete config file if it exists, as it can be outdated and
+        // make the test fail. It will be then created.
+        let config_path = confy::get_configuration_file_path("test", None).unwrap();
```
Comment (rkrasiuk) [inline crates/staged-sync/src/config.rs:158]: we should use tempdir for this instead since we are testing ... ser/deser ... i guess @onbjerg? let's make a test name more descriptive as well

**Review by rkrasiuk — CHANGES_REQUESTED** [review]

File: crates/staged-sync/src/config.rs (hunk 1 above)
Comment (mattsse) [inline crates/staged-sync/src/config.rs:158]: I see `get_configuration_file_path`

> Load an application configuration from disk

we should not use that here and instead use a tmpdir as @rkrasiuk suggested

we also want an additional test for breaking changes with the config itself, because this will become an issue with `confy::load` in the CLI

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/staged-sync/src/config.rs (hunk 1 above)
Comment (onbjerg) [reply crates/staged-sync/src/config.rs:158]: What else could the test be named?

**Comment by xqft** [comment]
Wrote two tests based on your suggestions, I’m not sure how would you test breaking changes

File: crates/staged-sync/src/config.rs (hunk 1 above)
Comment (rkrasiuk) [reply crates/staged-sync/src/config.rs]: since it's only loading & deserializing, let's call it `can_load_and_deserialize_config`

File: crates/staged-sync/src/config.rs [hunk 2]
```diff
@@ -121,7 +121,7 @@ impl Default for BodiesConfig {
 }
 
 /// Sender recovery stage configuration.
-#[derive(Debug, Clone, Deserialize, Serialize)]
+#[derive(Debug, Clone, Deserialize, PartialEq, Serialize)]
```
Comment (mattsse) [inline crates/staged-sync/src/config.rs]: nit: also derive `Eq` where `PartialEq`

**Review by mattsse — CHANGES_REQUESTED** [review]
lgtm, pending `Eq` nit

**Comment by gakonst** [comment]
My recommendation would be to do the following to simplify a bit, I don't love the closure pattern here

```patch,rust
commit 13906d489037c43781da7ebc51678e6b8dac878f
Author: Georgios Konstantopoulos <me@gakonst.com>
Date:   Sun Jan 29 19:23:36 2023 -0800

    chore: remove fn with callback from config tests

diff --git a/crates/staged-sync/src/config.rs b/crates/staged-sync/src/config.rs
index 14c5b6cc..de7e8d56 100644
--- a/crates/staged-sync/src/config.rs
+++ b/crates/staged-sync/src/config.rs
@@ -154,30 +154,21 @@ mod tests {
 
     const EXTENSION: &str = "toml";
 
-    fn with_tempdir(filename: &str, proc: fn(&std::path::Path)) {
-        let temp_dir = tempfile::tempdir().unwrap();
-        let config_path = temp_dir.path().join(filename).with_extension(EXTENSION);
-
-        proc(&config_path);
-
-        temp_dir.close().unwrap()
-    }
-
     #[test]
     fn test_store_config() {
-        with_tempdir("config-store-test", |config_path| {
-            let config = Config::default();
-            confy::store_path(config_path, config).unwrap();
-        })
+        let temp_dir = tempfile::tempdir().unwrap();
+        let config_path = temp_dir.path().join("config-store-test").with_extension(EXTENSION);
+        let config = Config::default();
+        confy::store_path(config_path, config).unwrap();
     }
 
     #[test]
     fn test_load_config() {
-        with_tempdir("config-load-test", |config_path| {
-            let config = Config::default();
-            confy::store_path(config_path, &config).unwrap();
+        let temp_dir = tempfile::tempdir().unwrap();
+        let config_path = temp_dir.path().join("config-load-test").with_extension(EXTENSION);
+        let config = Config::default();
+        confy::store_path(&config_path, &config).unwrap();
 
-            let _: Config = confy::load_path(config_path).unwrap();
-        })
+        let _: Config = confy::load_path(config_path).unwrap();
     }
 }
```

**Comment by xqft** [comment]
@gakonst I refactored into that fn so it would be easier to implement other config tests, like a breaking changes one. Though I like the simpler approach while redundancy isn't a problem yet, I'll take it.

One thing missing in your proposal is to `close()` the tempdir, did you skip it for some reason in particular?

**Comment by gakonst** [comment]
Yeah

> // By closing the `TempDir` explicitly, we can check that it has
>     // been deleted successfully. If we don't close it explicitly,
>     // the directory will still be deleted when `tmp_dir` goes out
>     // of scope, but we won't know whether deleting the directory
>     // succeeded.

**Review by gakonst — APPROVED** [review]
