### PR TITLE
fix: sepolia paris block

### LINKED ISSUE #14764: Cannot sync Sepolia on v1.2.0
### Describe the bug

I've been syncing Sepolia and it has been taking a week+ (which is kind of odd as my mainnet sync finished). Trying to debug why, here are some logs from it:
```sh
2025-02-25T03:14:19.576569Z  INFO Committed stage progress pipeline_stages=2/12 stage=Bodies checkpoint=7245002 target=7779670 stage_progress=93.12%
2025-02-25T03:14:19.587454Z  INFO Preparing stage pipeline_stages=2/12 stage=Bodies checkpoint=7245002 target=7779670
```
a day later:
```sh
2025-02-25T18:32:33.889035Z  INFO Committed stage progress pipeline_stages=2/12 stage=Bodies checkpoint=4135002 target=7784270 stage_progress=53.11%
2025-02-25T18:32:33.915350Z  INFO Preparing stage pipeline_stages=2/12 stage=Bodies checkpoint=4135002 target=7784270
```

It seems like it failed to progres through pipeline_stage 2 and restarted.

This is on Reth v1.2.0 w/ Lighthouse v6.0.1.

If I search logs for invalid block, I see this:
```sh
d logs eth-docker-execution-1 | grep 'invalid'
2025-02-26T05:09:01.572886Z  WARN Bad block detected in unwind invalid_block=BlockWithParent { parent: 0xee25b2818a55650e5e72ea1a5720443025287974e24c3ba990dc685ccb430f0b, block: NumHash { number: 1464868, hash: 0x5823c40f00dd4e213b0a8cdbead2aea3b88d5e50da29dc3847e1dddb3ee4e906 } }
2025-02-26T06:29:47.150059Z  WARN Bad block detected in unwind invalid_block=BlockWithParent { parent: 0xee25b2818a55650e5e72ea1a5720443025287974e24c3ba990dc685ccb430f0b, block: NumHash { number: ...
```

More context around that error:
```sh
2025-02-26T09:04:41.713379Z  INFO Committed stage progress pipeline_stages=3/12 stage=SenderRecovery checkpoint=7742186 target=7788213 stage_progress=98.18% stage_eta=13s
2025-02-26T09:04:41.715164Z  INFO Preparing stage pipeline_stages=3/12 stage=SenderRecovery checkpoint=7742186 target=7788213
2025-02-26T09:04:41.715176Z  INFO Recovering senders tx_range=420053816..425053956
2025-02-26T09:04:41.715183Z  INFO Executing stage pipeline_stages=3/12 stage=SenderRecovery checkpoint=7742186 target=7788213 stage_eta=13s
2025-02-26T09:04:43.544308Z  INFO Status connected_peers=55 stage=SenderRecovery checkpoint=7742186 target=7788213 stage_progress=98.18% stage_eta=11s
2025-02-26T09:04:50.099385Z  INFO Committed stage progress pipeline_stages=3/12 stage=SenderRecovery checkpoint=7772374 target=7788213 stage_progress=99.35% stage_eta=4s
2025-02-26T09:04:50.149859Z  INFO Preparing stage pipeline_stages=3/12 stage=SenderRecovery checkpoint=7772374 target=7788213
2025-02-26T09:04:50.149871Z  INFO Recovering senders tx_range=425053956..427831981
2025-02-26T09:04:50.149879Z  INFO Executing stage pipeline_stages=3/12 stage=SenderRecovery checkpoint=7772374 target=7788213 stage_eta=4s
2025-02-26T09:04:54.848262Z  INFO Finished stage pipeline_stages=3/12 stage=SenderRecovery checkpoint=7788213 target=7788213 stage_progress=100.00% stage_eta=unknown
2025-02-26T09:04:54.884277Z  INFO Preparing stage pipeline_stages=4/12 stage=Execution checkpoint=1000002 target=7788213
2025-02-26T09:04:54.884301Z  INFO Executing stage pipeline_stages=4/12 stage=Execution checkpoint=1000002 target=7788213
2025-02-26T09:05:07.255198Z  INFO Executed block range start=1000003 end=1416942 throughput="2.05 Ggas/second"
2025-02-26T09:05:08.544646Z  INFO Status connected_peers=55 stage=Execution checkpoint=1000002 target=7788213
2025-02-26T09:05:15.228917Z ERROR Stage encountered a validation error: receipt root mismatch: got 0xc5ccb36beaeb7921f88d5872f705efdc5502a7530d09ed153af8cae14f216a46, expected 0x3791134995966a6f7be2a7cc92efb2ca94e2455e484593d8e0fc8abb0c980ca4 stage=Execution bad_block=1464868
2025-02-26T09:05:15.229019Z  INFO Unwinding{stage=MerkleExecute}: Starting unwind from=1000002 to=1000002 bad_block=Some(1464868)
2025-02-26T09:05:15.229036Z  INFO Unwinding{stage=Execution}: Starting unwind from=1000002 to=1000002 bad_block=Some(1464868)
2025-02-26T09:05:15.229041Z  INFO Unwinding{stage=SenderRecovery}: Starting unwind from=7788213 to=1000002 bad_block=Some(1464868)
2025-02-26T09:05:33.543869Z  INFO Status connected_peers=55 stage=SenderRecovery checkpoint=7788213 target=1000002 stage_progress=100.00%
2025-02-26T09:05:35.502600Z  INFO Received forkchoice updated message when syncing head_block_hash=0xc3d44a10a2ba5fd573f54cb9be44a6ab6f0e8f3dd71f0cec085330d71fa129f5 safe_block_hash=0xfafc2b7f3832a9dd953cc32bb18d87f688801087498514da83f24e02dcfd82f1 finalized_block_hash=0x21ffb6da1b2df91c9b51473bf1fdd232ec3a41b1d3bca20791413e2b09225be2
2025-02-26T09:05:58.544184Z  INFO Status connected_peers=55 stage=SenderRecovery checkpoint=7788213 target=1000002 stage_progress=100.00%
2025-02-26T09:06:23.544043Z  INFO Status connected_peers=55 stage=SenderRecovery checkpoint=7788213 target=1000002 stage_progress=100.00%
2025-02-26T09:06:29.233972Z  INFO Unwinding{stage=SenderRecovery}: Stage unwound stage=SenderRecovery unwind_to=1000002 progress=2788212 done=false
2025-02-26T09:06:30.135426Z  INFO Unwinding{stage=SenderRecovery}: Stage unwound stage=SenderRecovery unwind_to=1000002 progress=1000002 done=true
2025-02-26T09:06:30.136648Z  INFO Unwinding{stage=Bodies}: Starting unwind from=7788213 to=1000002 bad_block=Some(1464868)
2025-02-26T09:06:35.751886Z  INFO Unwinding{stage=Bodies}: Stage unwound stage=Bodies unwind_to=1000002 progress=1000002 done=true
2025-02-26T09:06:48.544233Z  INFO Status connected_peers=55 stage=Bodies checkpoint=7788213 target=1000002 stage_progress=100.00%
2025-02-26T09:07:13.543969Z  INFO Status connected_peers=55 stage=Bodies checkpoint=7788213 target=1000002 stage_progress=100.00%
2025-02-26T09:07:13.714993Z  INFO Unwinding{stage=Headers}: Starting unwind from=7788213 to=1000002 bad_block=Some(1464868)
2025-02-26T09:07:29.635100Z  INFO Unwinding{stage=Headers}: Stage unwound stage=Headers unwind_to=1000002 progress=1000002 done=true
2025-02-26T09:07:30.452356Z  WARN Bad block detected in unwind invalid_block=BlockWithParent { parent: 0xee25b2818a55650e5e72ea1a5720443025287974e24c3ba990dc685ccb430f0b, block: NumHash { number: 1464868, hash: 0x5823c40f00dd4e213b0a8cdbead2aea3b88d5e50da29dc3847e1dddb3ee4e906 } }
2025-02-26T09:07:32.933761Z  INFO Preparing stage pipeline_stages=1/12 stage=Headers checkpoint=1000002 target=None
2025-02-26T09:07:34.075825Z  INFO Received headers total=10000 from_block=7788584 to_block=7778585
2025-02-26T09:07:34.567940Z  INFO Received headers total=10000 from_block=7778584 to_block=7768585
2025-02-26T09:07:34.623011Z  INFO Received headers total=10000 from_block=7768584 to_block=7758585
2025-02-26T09:07:34.673269Z  INFO Received headers total=10000 from_block=7758584 to_block=7748585
```

### Steps to reproduce

Sync a fresh node Reth v1.2.0 w/ Lighthouse v6.0.1 for Sepolia chain.

### Node logs

```text

```

### Platform(s)

_No response_

### Container Type

Docker

### What version/commit are you on?

v1.2.0

### What database version are you on?

Latest

### Which chain / network are you on?

sepolia

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by klkvr**
Closes https://github.com/paradigmxyz/reth/issues/14764

Sets correct `activation_block_number` for paris hardfork

### CODE REVIEW

File: crates/ethereum-forks/src/hardfork/ethereum.rs [hunk 1]
```diff
@@ -380,7 +380,7 @@ impl EthereumHardfork {
             (
                 Self::Paris,
                 ForkCondition::TTD {
-                    activation_block_number: 1735371,
+                    activation_block_number: 1450409,
                     fork_block: Some(1735371),
```
Comment (mattsse) [inline crates/ethereum-forks/src/hardfork/ethereum.rs:384]: smol issue introduced in #13362 where the exclusive sepolia fork_block was incorrectly taken as the activation block here -.-

**Review by mattsse — APPROVED** [review]
