### PR TITLE
fix(exex): prevent ExExManager deadlock when buffer clears after being full

### LINKED ISSUE #19665: ExEx stops receiving notifications if not processed fast enough
### Describe the bug

Sending a bunch of notifications without acknowledging seems to cause the ExExManager to stop sending notifications, even for new blocks.

### Steps to reproduce

1. Checkout this branch: https://github.com/paradigmxyz/reth/compare/main...meyer9:reth:meyer9/demo-exex-deadlock
2. Run the test
3. See that none of the notifications are received
4. Modify the `MAX_CAPACITY` const to a lower number (I think 256 works)
5. See that all of the notifications are properly received

### Platform(s)

_No response_

### Container Type

Not running in a container

### What version/commit are you on?

Tested on `main` and `v1.8.2`

### What database version are you on?

N/A

### Which chain / network are you on?

N/A

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by dhyaniarun1993**
# Description

This PR fixes a deadlock scenario in the `ExExManager` where the manager could stop processing new notifications permanently after its internal buffer filled up and subsequently cleared.

Closes https://github.com/paradigmxyz/reth/issues/19665

### CODE REVIEW

File: crates/exex/exex/src/manager.rs [hunk 1]
```diff
@@ -536,6 +537,12 @@ where
         // Update capacity
         this.update_capacity();
 
+        // If the buffer was full and we made space, we need to wake up to accept new notifications
+        if buffer_full && this.buffer.len() < this.max_capacity {
+            debug!(target: "exex::manager", "Buffer has space again, waking up senders");
+            cx.waker().wake_by_ref();
+        }
```
Comment (mattsse) [inline crates/exex/exex/src/manager.rs:544]: right because we have

> while this.buffer.len() < this.max_capacity { 

in front of the poll loop -.-

**Review by mattsse — APPROVED** [review]
very nice find, tysm

this should do it
