### PR TITLE
fix: make eth requests channel bounded

### LINKED ISSUE #2766: Make eth requests channel bounded
### Describe the feature

The channel to the eth requests service is currently unbounded. 
The channel that originally receives and bundles all requests from all session is already bounded. However, since handling an eth request (headers+bodies) is more expensive (disk IO) than delegating them from the bounded channel to the eth-request channel, it is possible that this builds up if the node is flooded with requests. Even though nonmalicious requests are relatively cheap (Headerrequest is a single object, body request is a list of hashes), it's possible to craft body requests with bogus data up until the allowed max message size limit.

https://github.com/paradigmxyz/reth/blob/238eea37cf23bd212823d76d2d07065a59ce7e2a/crates/net/network/src/manager.rs#L101-L103

## TODO
* to prevent unbounded request build-up in the request channel, it should be a bounded channel instead.

I guess we could use the same value of the SessionConfig's event buffer
https://github.com/paradigmxyz/reth/blob/238eea37cf23bd212823d76d2d07065a59ce7e2a/crates/net/network/src/session/config.rs#L54-L54

if the channel is full, requests should be dropped

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TechieBoy**
Closes #2766

### CODE REVIEW

File: crates/net/network/src/builder.rs [hunk 1]
```diff
@@ -49,7 +51,9 @@ impl<C, Tx, Eth> NetworkBuilder<C, Tx, Eth> {
         client: Client,
     ) -> NetworkBuilder<C, Tx, EthRequestHandler<Client>> {
         let NetworkBuilder { mut network, transactions, .. } = self;
-        let (tx, rx) = mpsc::unbounded_channel();
+        // We use twice the maximum number of available slots, if all slots are occupied
+        // This is the same as session_event_buffer size in [`SessionsConfig`]
+        let (tx, rx) = mpsc::channel((DEFAULT_MAX_PEERS_OUTBOUND + DEFAULT_MAX_PEERS_INBOUND) * 2);
```
Comment (mattsse) [inline crates/net/network/src/builder.rs:56]: hmm, I thought about this again, and this differs from the p2p event buffer because there's only a single sender/receiver pair.

this also does not respect the actual configured values for the session config.

I think we can make the channel capacity 256
this should be more than enough, since this sits already behind a bounded event channel.

256 requests with malicious 10MB body requests is 2.6GB however this should be absorbed.

File: crates/net/network/src/manager.rs [hunk 2]
```diff
@@ -363,7 +366,7 @@ where
     /// configured.
     fn delegate_eth_request(&self, event: IncomingEthRequest) {
         if let Some(ref reqs) = self.to_eth_request_handler {
-            let _ = reqs.send(event);
+            let _ = reqs.try_send(event);
```
[the remark this answers is not in the document]
Comment (mattsse) [reply crates/net/network/src/manager.rs:369]: I'd also like a metric for `total_dropped_eth_requests_at_full_capacity` so we can monitor if we run into this.

**Review by mattsse — CHANGES_REQUESTED** [review]
ty!
two smol nits

I'd also like to see some docs for the sender field, why this is bounded, see issue

File: crates/net/network/src/manager.rs [hunk 3]
```diff
@@ -366,7 +374,12 @@ where
     /// configured.
     fn delegate_eth_request(&self, event: IncomingEthRequest) {
         if let Some(ref reqs) = self.to_eth_request_handler {
-            let _ = reqs.try_send(event);
+            let _ = reqs.try_send(event).map_err(|e| {
+                if let TrySendError::Full(request) = e {
+                    debug!(target:"net", ?request, "EthRequestHandler channel is full!");
```
Comment (mattsse) [inline crates/net/network/src/manager.rs:379]: this will dump the entire message to the log, if which could be massive.
can omitt this here.

**Review by mattsse — CHANGES_REQUESTED** [review]
smol nit

**Review by mattsse — APPROVED** [review]
lgtm
