### PR TITLE
fix(rpc-trace): add after and count to `trace_filter`

### LINKED ISSUE #9608: handling additional trace_filter fields
### Describe the feature

we're currently ignoring fields after and count:

https://github.com/paradigmxyz/reth/blob/42182f531e94108be3aa9f4a838df6a2edd93185/crates/rpc/rpc/src/trace.rs#L254-L254

ref https://github.com/foundry-rs/foundry/pull/8458

FYI @EdwardJES 

## TODO
* handle count and offset

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tsnewnami**
closes https://github.com/paradigmxyz/reth/issues/9608

### CODE REVIEW

File: crates/rpc/rpc/src/trace.rs [hunk 1]
```diff
@@ -341,6 +341,21 @@ where
...
+        } else {
+            all_traces
+        };
+
+        // at most, return count of traces
+        let all_traces: Vec<_> = if let Some(count) = count {
+            all_traces.into_iter().take(count as usize).collect()
+        } else {
+            all_traces
+        };
```
Comment (mattsse) [inline crates/rpc/rpc/src/trace.rs:357]: we can solve this without allocating by using Vec::split_off for after 
and Vec::truncate for count but checking the len of all_traces

**Review by mattsse — CHANGES_REQUESTED** [review]
nice, nits

File: crates/rpc/rpc/src/trace.rs (hunk 1 above)
Comment (EdwardJES) [reply crates/rpc/rpc/src/trace.rs]: Thanks for the tips here @mattsse. Good callouts on avoiding `collect` wrt allocation. Have also included a check to ensure that `split_off` does not panic where `after > len`

**Review by mattsse — APPROVED** [review]
