### PR TITLE
fix(rpc): commit call state in trace call many

### LINKED ISSUE #3436: commit state changes in trace_callMany
### Describe the feature

currently, state changes are not committed, but the should be committed after each call

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
Closes #3436

the expected behaviour was already mentioned in the docs

> /// Note: Allows tracing dependent transactions, hence all transactions are traced in sequence

### CODE REVIEW

File: crates/rpc/rpc/src/trace.rs [hunk 1]
```diff
@@ -204,12 +206,30 @@ where
...
+                    }
+
                     results.push(trace_res);
+
+                    // need to apply the state changes of this call before executing the
+                    // next call
+                    if calls.peek().is_some() {
+                        // need to apply the state changes of this call before executing
+                        // the next call
+                        db.commit(state)
```
Comment (gakonst) [inline crates/rpc/rpc/src/trace.rs:231]: this is only temporary right - won't actually write to disk

**Review by gakonst — APPROVED** [review]

File: crates/rpc/rpc/src/trace.rs (hunk 1 above)
Comment (mattsse) [reply crates/rpc/rpc/src/trace.rs:231]: yes, this is only the cached, in mem db
