### PR TITLE
docs: inline mermaid diagrams while aquamarine is fixed

### LINKED ISSUE #4430: Mermaid diagrams are not rendered in `reth` crate docs
### Describe the bug

Rendered:
- https://paradigmxyz.github.io/reth/docs/reth_network/struct.NetworkManager.html
- https://paradigmxyz.github.io/reth/docs/reth_transaction_pool/pool/txpool/struct.TxPool.html

Not rendered:
- https://paradigmxyz.github.io/reth/docs/reth/network/struct.NetworkManager.html
- https://paradigmxyz.github.io/reth/docs/reth/transaction_pool/pool/txpool/struct.TxPool.html

### PR DESCRIPTION
**Pull request by vcastellm**
Re-exports doesn't work well with include_mmd! so we're embedding the diagrams in the code meanwhile.

Fixes https://github.com/paradigmxyz/reth/issues/4430

### CODE REVIEW

File: crates/transaction-pool/src/pool/txpool.rs [hunk 1]
```diff
@@ -43,7 +43,40 @@ use tracing::trace;
 ///
 /// This pool maintains the state of all transactions and stores them accordingly.
 ///
-/// `include_mmd!("docs/mermaid/txpool.mmd`")
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:46]: could we keep this as // doc below and add an additional note

**Review by mattsse — CHANGES_REQUESTED** [review]
this seems fine, in case we need to update the mermaid file, the additional effort is negligible,

would like to keep the include_mmd macro as comments though

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
pending clippy

**Comment by vcastellm** [comment]
Fixed clippy and squashed 😅 thx @mattsse

**Review by mattsse — APPROVED** [review]
