### PR TITLE
reafctor: improve tx count

### LINKED ISSUE #10881: inconsistent JSON RPC API responses: eth_getTransactionCount(address, 'pending') returns used nonce
### Describe the bug

When running reth in dev mode with a small block-time (e.g. 300ms) JSON RPC API returns inconsistent results. After transaction with nonce X is included in the block (node returns receipt for it with blockNumber set) node may still return nonce X as a response for `eth_getTransactionCount(address, 'pending')`.

### Steps to reproduce

Here is [repo](https://github.com/perekopskiy/reth-race-example) with a small script that reproduces the issue. It sends transactions in loop from a single address. The script fails after some time with "nonce has already been used" error. It's better to run it on a resource-constrained machine and/or make all the CPUs busy so it reproduces faster.

### Node logs

_No response_

### Platform(s)

Linux (x86), Linux (ARM), Mac (Apple Silicon)

### What version/commit are you on?

reth Version: 1.0.6
Commit SHA: c228fe15808c3acbf18dc3af1a03ef5cbdcda07a
Build Timestamp: 2024-08-29T18:34:24.773465330Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf

### What database version are you on?

Error: Datadir does not exist: "/root/.local/share/reth/mainnet"

### Which chain / network are you on?

dev

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by malik672**
closes #10881

### CODE REVIEW

File: crates/rpc/rpc-eth-api/src/helpers/state.rs [hunk 1]
```diff
@@ -269,25 +269,28 @@ pub trait LoadState: EthApiTypes {
         Self: SpawnBlocking,
     {
         self.spawn_blocking_io(move |this| {
+            let state = this.state_at_block_id_or_latest(block_id)?;
+            let base_nonce = state
```
Comment (mattsse) [inline crates/rpc/rpc-eth-api/src/helpers/state.rs:273]:
```suggestion
            let nonce = state
```

File: crates/rpc/rpc-eth-api/src/helpers/state.rs [hunk 2]
```diff
@@ -269,25 +269,28 @@ pub trait LoadState: EthApiTypes {
...
-                {
-                    let tx_count = highest_nonce.checked_add(1).ok_or(Self::Error::from(
+                let highest_pool_nonce = address_txs
+                    .iter()
+                    .map(|item| item.transaction.nonce())
+                    .max()
+                    .unwrap_or(base_nonce);
+
+                let tx_count =
+                    highest_pool_nonce.max(base_nonce).checked_add(1).ok_or(Self::Error::from(
```
Comment (mattsse) [inline crates/rpc/rpc-eth-api/src/helpers/state.rs:287]: this can now return incorrect values if there are no txs in the pool.

so the checked_add needs to be applied to the `max` nonce above

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
