### PR TITLE
fix: add debug namespace to auth module in op-reth

### LINKED ISSUE #15043: Enabled entire debug namespace on auth port for op-reth if configured
### Describe the feature

we need to mirror:

https://github.com/ethereum-optimism/op-geth/pull/512

by merging all debug_ endpoints into the auth modules:

https://github.com/paradigmxyz/reth/blob/b8f7a345d022df159caeb81a989020cec4acbd65/crates/optimism/node/src/node.rs#L313-L315

if debug is configured

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alessandromazza98**
Closes https://github.com/paradigmxyz/reth/issues/15043

@mattsse

### CODE REVIEW

File: crates/node/builder/src/rpc.rs [hunk 1]
```diff
@@ -448,7 +448,11 @@ where
         ext: F,
     ) -> eyre::Result<RpcHandle<N, EthB::EthApi>>
     where
-        F: FnOnce(&mut TransportRpcModules, &mut AuthRpcModule) -> eyre::Result<()>,
+        F: FnOnce(
+            &mut TransportRpcModules,
+            &mut AuthRpcModule,
+            &mut RpcRegistry<N, EthB::EthApi>,
```
Comment (mattsse) [inline crates/node/builder/src/rpc.rs:454]: this works, this is quite low level so making this more verbose isn't an issue

File: crates/optimism/node/src/node.rs [hunk 2]
```diff
@@ -322,10 +324,16 @@ where
...
                 if modules.module_config().contains_any(&RethRpcModule::Miner) {
-                    debug!(target: "reth::cli", "Installing miner DA rpc enddpoint");
+                    debug!(target: "reth::cli", "Installing miner DA rpc endpoint");
                     auth_modules.merge_auth_methods(miner_ext.into_rpc())?;
                 }
 
+                // install the debug namespace in the authenticated if configured
+                if modules.module_config().contains_any(&RethRpcModule::Debug) {
+                    debug!(target: "reth::cli", "Installing debug rpc endpoint");
+                    auth_modules.merge_auth_methods(debug_api.into_rpc())?;
```
Comment (mattsse) [inline crates/optimism/node/src/node.rs:334]: intellisense likely sucks here but this should be available via:

 let debug_api = registry.debug_api();

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/optimism/node/src/node.rs (hunk 2 above)
Comment (alessandromazza98) [reply crates/optimism/node/src/node.rs:334]: yes sorry i'm doing it now, rust-analyzer is slow and it wasn't correctly show me the error

**Review by mattsse — APPROVED** [review]
