### PR TITLE
fix(engine): future payload handling

### LINKED ISSUE #2101: Incorrect Payload Status For Future Blocks
### Describe the bug

The node returns invalid payload status for future blocks. `syncing` status should be returned instead

### Steps to reproduce

1. Start reth alongside CL client
2. Sync chain (sepolia) to the tip
3. Observe node logs

### Node logs

```text
2023-04-04T08:51:23.702147Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:23.708296Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:23.893777Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:23.898882Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:25.542724Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:25.547993Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:26.786323Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:26.791558Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:27.389204Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:27.394312Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:29.692740Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:29.697945Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:30.194091Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:30.199319Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:31.435194Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:31.440320Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:31.655430Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:31.660536Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:32.454829Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:32.460267Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:32.657452Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
2023-04-04T08:51:32.662594Z TRACE Returning payload status block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191 status=PayloadStatus { status: Invalid { validation_error: "Can't insert block  #3224191 0xfd18…250f to far in future, as last finalized block number is 3224120" }, latest_valid_hash: None }
2023-04-04T08:51:33.659058Z TRACE Received new payload block_hash=0xfd18bf6f3fb3b78d7b31276a8aeea6de1ff4d6422cb1eecc52a208b102b7250f block_number=3224191
```

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by rkrasiuk**
closes #2101

### Summary
:recycle::sparkles::mag:

This pull request improves the error handling and logging of the `BeaconEngine` in the `consensus/beacon` crate, and fixes a minor issue with the error message formatting of the `ExecutorError` enum in the `interfaces` crate.

> _`on_new_payload`_
> _returns `Result`, handles errors_
> _autumn leaves falling_

### Walkthrough
*  Change `on_new_payload` function signature to return a `Result<PayloadStatus, reth_interfaces::Error>` instead of a `PayloadStatus` ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544L196-R199))
*  Update `on_new_payload` function to return `Ok(PayloadStatus::from_status(...))` instead of just `PayloadStatus::from_status(...)` to match the new return type ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544L204-R209), [link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544L237-R254))
*  Handle `Error::Execution(ExecutorError::PendingBlockIsInFuture { .. })` error in `on_new_payload` function and return `PayloadStatusEnum::Syncing` variant if the payload block is too far ahead of the last finalized block ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544L227-R247))
*  Trigger a pipeline run in `on_new_payload` function if the head block hash from the forkchoice state is unknown to the database ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544L227-R247))
*  Handle errors from `on_new_payload` function in `poll` method of `BeaconEngine` struct and terminate the future with the error ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544L344-R368))
*  Add tracing statements to `poll` method of `BeaconEngine` struct to log informational and error messages when processing messages from the channel, reaching the maximum block number, or being idle ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544R336), [link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544R374-R375), [link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544R400-R402), [link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-6422221acf035d27429c58dd93438246d53b548efb00b9b3cfbd610c94f8c544R433))
*  Change error message for `ExecutorError::PendingBlockIsInFuture` variant to be more concise and consistent with the other error messages in `crates/interfaces/src/executor.rs` ([link](https://github.com/paradigmxyz/reth/pull/2124/files?diff=unified&w=0#diff-8d1a8029bf39542a9dfd4cd5664105789d3822bbe413ec0698fe4ac62f336cb6L51-R51))

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -316,6 +333,7 @@ where
 
         // Set the next pipeline state.
         loop {
+            tracing::info!("processing msgs");
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:336]: is the info target inside a loop reasonable?

Comment (rkrasiuk) [reply crates/consensus/beacon/src/engine/mod.rs]: removed this, idk how it got into this PR. maybe some staged changes locally

File: crates/consensus/beacon/src/engine/mod.rs [hunk 2]
```diff
@@ -193,17 +193,20 @@ where
...
         trace!(target: "consensus::engine", ?block_hash, block_number, "Received new payload");
         let block = match SealedBlock::try_from(payload) {
             Ok(block) => block,
             Err(error) => {
                 error!(target: "consensus::engine", ?block_hash, block_number, ?error, "Invalid payload");
-                return PayloadStatus::from_status(PayloadStatusEnum::InvalidBlockHash {
+                return Ok(PayloadStatus::from_status(PayloadStatusEnum::InvalidBlockHash {
                     validation_error: error.to_string(),
-                })
+                }))
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:209]: this is not always correct, see #2123

because this can fail due to other reasons as well.

But if I read this correctly, then "InvalidBlockHash" error on newPayload is not even returned here
https://github.com/ethereum/go-ethereum/blob/2adce0b06640aa665706d014a92cd06f0720dcab/eth/catalyst/api.go#L454-L458
so I'm no longer sure about https://github.com/paradigmxyz/reth/pull/2123

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
but this response is unrelated to this PR, I just realized

**Comment by rkrasiuk** [comment]
@mattsse right, we can chat about #2123 separately
