### PR TITLE
fix(rpc): add fee/value and balance to insufficient funds RPC error

### LINKED ISSUE #10464: op-reth outputs less information than op-geth regarding requests
### Describe the bug

I've been testing the op-reth client on base mainnet and found some differences when comparing the results from the node running on op-reth to the results from a node running op-geth. 
Main issue here is that op-reth client doesn't behave exactly like op-geth when it comes to errors for various requests, op-reth giving less information for the `message` parameter.

### Steps to reproduce

- first request:

payload: `{"method": "eth_sendRawTransaction", "params": ["0x02f87182210547830f4240833ab04d825208947449061f45d7b39b3b80b4159286cd8682f60a3c87096bfaddf1c00080c080a093b87bd8122c1daaba521a62d2dd6094cf5e49d319f794b98e77b0710c1546dfa04556c9919658ef514600b656d8da40f1a118266f2221692a6b3bef2446de5df5"], "id": 51, "jsonrpc": "2.0"}`

- second request:
payload: `{"method": "eth_estimateGas", "params": [{"value": "0x96bfaddf1c000", "from": "0x889ebdac39408782b5165c5185c1a769b4dd3ce6", "to": "0x7449061f45d7b39b3b80b4159286cd8682f60a3c"}], "id": 44, "jsonrpc": "2.0"}`

### Node logs

```text
first request:
op-reth client
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "nonce too low"
  },
  "id": 51
}
op-geth client
{
  "jsonrpc": "2.0",
  "id": 51,
  "error": {
    "code": -32000,
    "message": "nonce too low: next nonce 72, tx nonce 71"
  }
}


second request:
op-reth client
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "insufficient funds for gas * price + value"
  },
  "id": 44
}
op-geth client
{
  "jsonrpc": "2.0",
  "id": 44,
  "error": {
    "code": -32000,
    "message": "failed with 50000000 gas: insufficient funds for gas * price + value: address 0x889eBDAc39408782B5165c5185C1A769B4Dd3ce6 have 1444840609176611 want 2652000000000000"
  }
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

op-reth --version reth Version: 1.0.3 Commit SHA: https://github.com/paradigmxyz/reth/commit/390f30aadebcdd509e72cc04327c3b854de076a6 Build Timestamp: 2024-08-05T23:59:17.371843433Z Build Features: jemalloc,optimism Build Profile: maxperf

### What database version are you on?

op-reth db version
2024-08-22T18:23:51.766359Z INFO Initialized tracing, debug log directory: /root/.cache/reth/logs/optimism
Error: Datadir does not exist: "/root/.local/share/reth/optimism"

### Which chain / network are you on?

base mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

source "$HOME/.cargo/env" && RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf --features jemalloc,asm-keccak,optimism --bin op-reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10498
- [ ] https://github.com/paradigmxyz/reth/issues/10732
```

### LINKED ISSUE #10732: Add data to `RpcInvalidTransactionError::InsufficientFunds`
### Describe the feature

Add necessary data to error variant to produce error message like geth `'failed with 50000000 gas: insufficient funds for gas * price + value: address 0x889eBDAc39408782B5165c5185C1A769B4Dd3ce6 have 1444840609176611 want 2652000000000000'`

https://github.com/paradigmxyz/reth/blob/5af62b75d4c74d97b4eaa6087651bd78f02d85d2/crates/rpc/rpc-eth-types/src/error.rs#L292-L294

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/10732. Closes https://github.com/paradigmxyz/reth/issues/10464.

Adds fee/value and balance to error message for RPC error insufficient funds.

This doesn't report the exact same error message as geth now @AntonieDavid, if that doesn't suffice an issue to revm would need to be opened to add address and gas used to error variant

https://github.com/bluealloy/revm/blob/f57e3e639ee157c7e659e740bd175a7357003570/crates/primitives/src/result.rs#L334-L336

https://github.com/paradigmxyz/reth/blob/817b1527e9daf30e838e14b49171db86be266219/crates/rpc/rpc-eth-types/src/error.rs#L479

### CODE REVIEW

File: crates/transaction-pool/src/error.rs [hunk 1]
```diff
@@ -203,8 +203,15 @@ pub enum InvalidPoolTransactionError {
...
     Underpriced,
     /// Thrown if the transaction's would require an account to be overdrawn
-    #[error("transaction overdraws from account")]
-    Overdraft,
+    #[error(
+        "transaction overdraws from account, value or fee: {value_or_fee}, balance: {balance}"
+    )]
+    Overdraft {
+        /// Cost transaction is allowed to consume. See `reth_transaction_pool::PoolTransaction`.
+        value_or_fee: U256,
```
Comment (mattsse) [inline crates/transaction-pool/src/error.rs:211]: this isn't quite accurate because this is the cost this tx requires.

imo we can keep overdraft as is, this provides sufficient context

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/transaction-pool/src/error.rs (hunk 1 above)
Comment (emhane) [reply crates/transaction-pool/src/error.rs:211]: this isn't possible if we do the conversion from overdraft error to rpc error

File: crates/rpc/rpc-eth-types/src/error.rs [hunk 2]
```diff
@@ -305,8 +305,15 @@ pub enum RpcInvalidTransactionError {
     #[error("max initcode size exceeded")]
     MaxInitCodeSizeExceeded,
     /// Represents the inability to cover max cost + value (account balance too low).
-    #[error("insufficient funds for gas * price + value")]
-    InsufficientFunds,
+    #[error(
+        "insufficient funds for gas * price + value: value or fee {value_or_fee}, balance {balance}"
```
Comment (mattsse) [inline crates/rpc/rpc-eth-types/src/error.rs:309]: this doesn't quite match the sample of the issue
this only includes value of fee not `want`

> have 1444840609176611 want 2652000000000000'

**Review by mattsse — CHANGES_REQUESTED** [review]
okay I looked at the issue again, looks like the Overdraft field is actually what we want here `cost`, but `InsufficientFund` only includes value or fee. which can be lower than balance, so this error could be confusing to users.

this should also be the expected cost.

**Review by mattsse — APPROVED** [review]
