### PR TITLE
fix(download): body consecutive range

### LINKED ISSUE #2195: Body Downloader Panic
### Describe the bug

The body downloader
https://github.com/paradigmxyz/reth/blob/ddf23058af88dc96f154f143790acb61ccecf302/crates/net/downloaders/src/bodies/bodies.rs#L217

cc @mattsse 

### Steps to reproduce

No obvious steps to repro other than syncing to the tip with CL and leaving it running 

### Node logs

```text
2023-04-11T19:14:52.366077Z  INFO Peer connected connected_peers=3 peer_id=0x24ea…093b best_block=0xfa8c…ed83
2023-04-11T19:14:52.366152Z  WARN Peer disconnected. connected_peers=2 peer_id=0x24ea…093b reason=None
2023-04-11T19:14:59.287972Z  INFO Status connected_peers=2 stage=None checkpoint=3271281
2023-04-11T19:15:00.102196Z TRACE Received new payload block_hash=0x012ce040b230555af2b17ffe56786dca8a9067d842c7f6ff94484ede59ae86f3 block_number=3271285
2023-04-11T19:15:00.142735Z TRACE Returning payload status block_hash=0x012ce040b230555af2b17ffe56786dca8a9067d842c7f6ff94484ede59ae86f3 block_number=3271285 status=PayloadStatus { status: Valid, latest_valid_hash: Some(0x012ce040b230555af2b17ff
e56786dca8a9067d842c7f6ff94484ede59ae86f3) }
2023-04-11T19:15:00.146025Z TRACE Received new forkchoice state state=ForkchoiceState { head_block_hash: 0x012ce040b230555af2b17ffe56786dca8a9067d842c7f6ff94484ede59ae86f3, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f58435
4952ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c }
2023-04-11T19:15:00.193453Z TRACE Returning forkchoice status state=ForkchoiceState { head_block_hash: 0x012ce040b230555af2b17ffe56786dca8a9067d842c7f6ff94484ede59ae86f3, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f5843549
52ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c } status=PayloadStatus { status: Valid, latest_valid_hash: Some(0x012ce040b230555af2b17ffe56786dca8a9067d842c7f6ff94484ede59ae86f3) }
2023-04-11T19:15:12.261032Z TRACE Received new payload block_hash=0xb28ffd47b4452bddb7ebfd1ed1510a3061e2c07f467114e351ac7298de14f1f5 block_number=3271286
2023-04-11T19:15:12.294684Z TRACE Returning payload status block_hash=0xb28ffd47b4452bddb7ebfd1ed1510a3061e2c07f467114e351ac7298de14f1f5 block_number=3271286 status=PayloadStatus { status: Valid, latest_valid_hash: Some(0xb28ffd47b4452bddb7ebfd1
ed1510a3061e2c07f467114e351ac7298de14f1f5) }
2023-04-11T19:15:12.299004Z TRACE Received new forkchoice state state=ForkchoiceState { head_block_hash: 0xb28ffd47b4452bddb7ebfd1ed1510a3061e2c07f467114e351ac7298de14f1f5, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f58435
4952ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c }
2023-04-11T19:15:12.617462Z TRACE Returning forkchoice status state=ForkchoiceState { head_block_hash: 0xb28ffd47b4452bddb7ebfd1ed1510a3061e2c07f467114e351ac7298de14f1f5, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f5843549
52ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c } status=PayloadStatus { status: Valid, latest_valid_hash: Some(0xb28ffd47b4452bddb7ebfd1ed1510a3061e2c07f467114e351ac7298de14f1f5) }
2023-04-11T19:15:24.194346Z TRACE Received new payload block_hash=0x0ad38e485c3863643db95a5347665c9fb6ef0466ccc2912f5288208d234fab22 block_number=3271287
2023-04-11T19:15:24.207654Z TRACE Returning payload status block_hash=0x0ad38e485c3863643db95a5347665c9fb6ef0466ccc2912f5288208d234fab22 block_number=3271287 status=PayloadStatus { status: Valid, latest_valid_hash: Some(0x0ad38e485c3863643db95a5
347665c9fb6ef0466ccc2912f5288208d234fab22) }
2023-04-11T19:15:24.212019Z TRACE Received new forkchoice state state=ForkchoiceState { head_block_hash: 0x0ad38e485c3863643db95a5347665c9fb6ef0466ccc2912f5288208d234fab22, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f58435
4952ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c }
2023-04-11T19:15:24.551901Z TRACE Returning forkchoice status state=ForkchoiceState { head_block_hash: 0x0ad38e485c3863643db95a5347665c9fb6ef0466ccc2912f5288208d234fab22, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f5843549
52ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c } status=PayloadStatus { status: Valid, latest_valid_hash: Some(0x0ad38e485c3863643db95a5347665c9fb6ef0466ccc2912f5288208d234fab22) }
2023-04-11T19:15:29.288497Z  INFO Status connected_peers=2 stage=None checkpoint=3271281
2023-04-11T19:15:36.201561Z TRACE Received new payload block_hash=0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b block_number=3271288
2023-04-11T19:15:36.203687Z TRACE Returning payload status block_hash=0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b block_number=3271288 status=PayloadStatus { status: Syncing, latest_valid_hash: None }
2023-04-11T19:15:36.208219Z TRACE Received new forkchoice state state=ForkchoiceState { head_block_hash: 0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f58435
4952ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c }
2023-04-11T19:15:36.208258Z  WARN Error canonicalizing the head hash state=ForkchoiceState { head_block_hash: 0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f
584354952ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c } error=Execution(BlockHashNotFoundInChain { block_hash: 0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b })
2023-04-11T19:15:36.208278Z TRACE Returning forkchoice status state=ForkchoiceState { head_block_hash: 0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b, safe_block_hash: 0x511d296aff4c5a3516ea4f158c2b647dc8733152b13def3f5843549
52ae20e38, finalized_block_hash: 0x185dc8c8e93fb2d0174e6c20673e8a5a8ff05980af41e67417bd3b7b9d557a4c } status=PayloadStatus { status: Syncing, latest_valid_hash: None }
2023-04-11T19:15:36.208299Z TRACE Starting the pipeline tip=0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b
2023-04-11T19:15:36.208386Z TRACE Executing stage stage=Headers
2023-04-11T19:15:36.208524Z DEBUG Commencing sync tip=Hash(0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b) head=0x0ad38e485c3863643db95a5347665c9fb6ef0466ccc2912f5288208d234fab22
2023-04-11T19:15:36.208576Z TRACE Update sync target current=Some(0x8e19d378b4ffe6ea6bedeb5937a1c0afee00f438d125e4715eec2e7b069f95bf) new=0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b
2023-04-11T19:15:36.208589Z TRACE Request new sync target new=Tip(0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b)
2023-04-11T19:15:36.208591Z  INFO Executing stage stage=Headers from=3271287
2023-04-11T19:15:36.214984Z TRACE Received sync target head=Some(3271287) hash=0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b number=3271288
2023-04-11T19:15:36.215027Z  INFO Received headers len=1
2023-04-11T19:15:36.215040Z TRACE writing headers len=1
2023-04-11T19:15:36.215153Z  INFO Stage made progress stage=Headers stage_progress=3271288 done=true
2023-04-11T19:15:36.215311Z TRACE Completed stage stage=Headers next=Continue { progress: 3271288 }
2023-04-11T19:15:36.215327Z TRACE Executing stage stage=TotalDifficulty
2023-04-11T19:15:36.215361Z DEBUG Commencing sync start_block=3271288 end_block=3271288
2023-04-11T19:15:36.215382Z DEBUG Last total difficulty entry td=0x000000000000000000000000000000000000000000000000003c656d23029ab0_U256 block_number=3271287
2023-04-11T19:15:36.215424Z  INFO Sync iteration finished stage_progress=3271288 done=true
2023-04-11T19:15:36.215441Z  INFO Stage made progress stage=TotalDifficulty stage_progress=3271288 done=true
2023-04-11T19:15:36.215544Z TRACE Completed stage stage=TotalDifficulty next=Continue { progress: 3271288 }
2023-04-11T19:15:36.215558Z TRACE Executing stage stage=Bodies
2023-04-11T19:15:36.215598Z DEBUG Commencing sync stage_progress=3271287 target=3271288 start_tx_id=10763021 next_transition_id=12493795
2023-04-11T19:15:36.215615Z TRACE New download range set range=3271288..3271289
2023-04-11T19:15:36.215627Z  INFO Stage finished executing stage=Headers checkpoint=3271288
2023-04-11T19:15:36.215643Z  INFO Executing stage stage=TotalDifficulty from=3271287
2023-04-11T19:15:36.215648Z TRACE Requesting bodies request_len=7
2023-04-11T19:15:36.215651Z  INFO Stage finished executing stage=TotalDifficulty checkpoint=3271288
2023-04-11T19:15:36.215659Z  INFO Executing stage stage=Bodies from=3271287
2023-04-11T19:15:36.254984Z ERROR Error requesting bodies peer_id=None error=Connection to a peer dropped while handling the request.
2023-04-11T19:15:36.255002Z  WARN Peer disconnected. connected_peers=1 peer_id=0x6615…e3b6 reason=None
2023-04-11T19:15:36.255003Z TRACE Requesting bodies request_len=7
2023-04-11T19:15:36.642711Z TRACE Received bodies request_len=7 response_len=7 peer_id=0xcafd9478569c947f7083959b47d8cdabc55d49c9f6e3ccca01cf2f6037144f36a9794bdf8965c22a5d5feff00482fb215a9c5aaa98e0d49c083a9858af8c378e
thread 'tokio-runtime-worker' panicked at 'is not empty', /root/reth/crates/net/downloaders/src/bodies/bodies.rs:217:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-04-11T19:15:36.646957Z ERROR Stage encountered a fatal error: Download channel closed. stage=Bodies
2023-04-11T19:15:36.647069Z TRACE Pipeline finished tip=0x9cf039b189cf98b16c42a936356a8ab34b819343d808db8e715d3a0e0f26611b result=Err(Stage(ChannelClosed))
2023-04-11T19:15:36.655162Z TRACE Saving current peers peers_file="/root/.local/share/reth/net/known-peers.json" num_peers=980632
2023-04-11T19:15:36.656245Z  INFO Wrote network peers to file peers_file="/root/.local/share/reth/net/known-peers.json"
Error: A stage encountered an irrecoverable error.

Caused by:
    Download channel closed

Location:
    bin/reth/src/node/mod.rs:346:9
```

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by rkrasiuk**
Closes #2195

## Problem

Previously the downloader reset its data only during unwind. However, BlockchainTree also introduces irregular body inserts which makes the downloader state inconsistent. 

## Solution

The downloader should preserve its state only upon receiving the next **consecutive** download range. In any other case, the downloader should reset.

### Summary
🐛📝🚀

Fixed a bug and improved documentation in the `bodies` module of the `net` crate. The bug could cause inconsistent block syncing in the `reth` client.

> _There once was a bug in `bodies downloader`_
> _That made the block chain look like a clown's collar_
> _To fix this mess_
> _They added a reset_
> _And documented the logic much sounder_

### Walkthrough
* Fix the condition for accepting consecutive block ranges in the bodies downloader ([link](https://github.com/paradigmxyz/reth/pull/2198/files?diff=unified&w=0#diff-5bfda9652b22310557eeed1ed88ec0dffd12806986ec3f411cc6f61fc869d1f8L298-R299))
* Update the comment for the block range reset to include external services as a possible cause ([link](https://github.com/paradigmxyz/reth/pull/2198/files?diff=unified&w=0#diff-5bfda9652b22310557eeed1ed88ec0dffd12806986ec3f411cc6f61fc869d1f8L306-R307))

### CODE REVIEW

File: crates/net/downloaders/src/bodies/bodies.rs [hunk 1]
```diff
@@ -295,15 +295,16 @@ where
         }
 
         // Check if the provided range is the next expected range.
-        let is_next_range = range.start >= self.download_range.end;
-        if is_next_range {
+        let is_next_consecutive_range = range.start == self.download_range.end;
+        if is_next_consecutive_range {
```
Comment (mattsse) [inline crates/net/downloaders/src/bodies/bodies.rs:299]: right, this makes sense,

this ensures we clear if we get a higher block from the CL

**Review by mattsse — APPROVED** [review]
