### PR TITLE
fix(optimism): Fail if latest and base flashblock parent are different

### LINKED ISSUE #18102: Ensure flashblocks build on parent block and pending flashblock is cleared when a new chain is committed
### Describe the feature

currently we always use the latest state

https://github.com/paradigmxyz/reth/blob/615bd4a30fc719de384be55bba0270a36664a47b/crates/optimism/flashblocks/src/service.rs#L112-L116

however this might not be 

https://github.com/paradigmxyz/reth/blob/615bd4a30fc719de384be55bba0270a36664a47b/crates/optimism/flashblocks/src/payload.rs#L50-L51

so we should not build the block if parent_hash != latest

we also must clear the block when a new block was mined,

for this we can install a Canonstatesubscription via the provider and remove the pending block on tick

### Additional context

Checklist: 
- [x] Prevent old pending flashblock from being returned from pending_flashblock
- [x] State check to ensure we only keep and return a pending flashblock if it is still valid

### PR DESCRIPTION
**Pull request by RomanHodulak**
Part of #17858 
Closes #18102 

Makes the pending block execution fail on base flashblock and latest block mismatch.

### CODE REVIEW

File: crates/optimism/flashblocks/src/service.rs [hunk 1]
```diff
@@ -129,6 +129,10 @@ impl<
             .find_map(|v| v.base.clone())
             .ok_or_eyre("Missing base flashblock")?;
 
+        if attrs.parent_hash == latest.hash() {
+            return Err(eyre!("The base flashblock is old"));
+        }
```
Comment (mattsse) [inline crates/optimism/flashblocks/src/service.rs]: we want to ensure that flashblock is latest + 1

```suggestion
        if attrs.parent_hash != latest.hash() {
            return Err(eyre!("The base flashblock is old"));
        }
```

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
