### PR TITLE
fix(tree): save caches only after prewarm tasks finish 

### LINKED ISSUE #16007: Terminate prewarm tasks after termination was requested
### Describe the feature

we have:

https://github.com/paradigmxyz/reth/blob/4d46962a658ab21edffa76a32012768e39dae291/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L139-L142

that should terminate all perwarming execution right away, we can do this via a simple atomicbool flag that we would check here:

https://github.com/paradigmxyz/reth/blob/4d46962a658ab21edffa76a32012768e39dae291/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L226-L226

In addition, we need to delay state updates after all prewarm tasks completed:

https://github.com/paradigmxyz/reth/blob/4d46962a658ab21edffa76a32012768e39dae291/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L147-L151

for this we need to keep track of received outcomes:

https://github.com/paradigmxyz/reth/blob/4d46962a658ab21edffa76a32012768e39dae291/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L143-L146

## TODO
* add Atomicbool to prewarmctx

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rjected**
Fixes https://github.com/paradigmxyz/reth/issues/16007

### CODE REVIEW

File: crates/engine/tree/src/tree/payload_processor/prewarm.rs [hunk 1]
```diff
@@ -134,26 +143,40 @@ where
...
-                    if let Some(state) = block_output {
-                        self.save_cache(state);
-                    }
+                    final_block_output = Some(block_output);
 
-                    break
+                    if self.prewarm_tasks_left == 0 {
+                        // all tasks are done, we can exit, which will save caches and exit
+                        break
+                    }
```
Comment (mattsse) [inline crates/engine/tree/src/tree/payload_processor/prewarm.rs:171]: I think this is fine, I'm only concerned about the case where the spawned prewarm task would panic which would then violate this, so

I think, now that we're spawning all tasks upfront, we should drop this one

https://github.com/paradigmxyz/reth/blob/ff04aee216fb7413501244bf7cfc721d27dd35e1/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L47-L48

so that we can't have a case where this loop remains active indefinitely?

**Review by mattsse — COMMENTED** [review]
all of this looks correct to me, I only have one condition for the exit condition

we could either solve this by not keeping the channel open or introducing a secondary loop that uses recv_timeout

File: crates/engine/tree/src/tree/payload_processor/prewarm.rs (hunk 1 above)
Comment (Rjected) [reply crates/engine/tree/src/tree/payload_processor/prewarm.rs:171]: yes, I think dropping the `actions_tx` after we `spawn_all` would be the easiest thing here that would work

Comment (Rjected) [reply crates/engine/tree/src/tree/payload_processor/prewarm.rs:185]: added `drop_actions_tx`, to get around partial move issues

File: crates/engine/tree/src/tree/payload_processor/prewarm.rs [hunk 2]
```diff
@@ -123,6 +132,15 @@ where
         self.ctx.metrics.cache_saving_duration.set(start.elapsed().as_secs_f64());
     }
 
+    /// Removes the `actions_tx` currently stored in the struct, replacing it with a new one that
+    /// does not point to any active receiver.
+    ///
+    /// This is used to drop the `actions_tx` after all tasks have been spawned, and should not be
+    /// used in any context other than the `run` method.
+    fn drop_actions_tx(&mut self) {
+        self.actions_tx = channel().0;
```
Comment (mattsse) [inline crates/engine/tree/src/tree/payload_processor/prewarm.rs:141]: I think this is fine, less invasive than using an option which would then require a bunch of .expect calls

**Review by mattsse — APPROVED** [review]
