### PR TITLE
fix(tree): remove_blocks fixes, return hash and number in persistence task

### LINKED ISSUE #10570: Tracking: On-disk reorg handling
This tracks all of the things we need to do to properly handle on-disk reorgs in the new engine.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10552
- [ ] https://github.com/paradigmxyz/reth/issues/10558
- [ ] https://github.com/paradigmxyz/reth/pull/10551
- [ ] https://github.com/paradigmxyz/reth/issues/10572
```

### PR DESCRIPTION
**Pull request by Rjected**
This does many things:
 * Make `remove_blocks_above` and `save_blocks` output both a block number and hash.
 * Make `remove_until` take an upper bound block number, a last_persisted_block_num and hash, and an optional `finalized_hash`.
 * `remove_until` will now make sure that it only removes canonical in-memory blocks if they are in the same chain as the last persisted block. This was motivated by hive tests where the persistence task would run in between a reorg. In this case, we were removing canonical blocks that were not actually persisted yet.
 * `remove_until` is split into two methods, `remove_canonical_until` and `prune_finalized_sidechains`.
 * `is_canonical` is introduced as a helper for `remove_until`
 * `remove_persisted_blocks` is modified to only remove blocks if they are actually part of the persisted chain.
 * Blocks that have been reorged, but are not on-disk, are reinserted into the tree.
 * `remove_blocks_above` was incorrect, removing exclusively for some pieces of data, and inclusively for others. This is fixed.
 * There is now a `VecDeque` in case there are multiple reorgs in a row.

closes https://github.com/paradigmxyz/reth/issues/10570

### CODE REVIEW

File: crates/engine/tree/src/persistence.rs [hunk 1]
```diff
@@ -140,13 +148,13 @@ pub enum PersistenceAction {
     ///
     /// First, header, transaction, and receipt-related data should be written to static files.
     /// Then the execution history-related data will be written to the database.
-    SaveBlocks(Vec<ExecutedBlock>, oneshot::Sender<Option<B256>>),
+    SaveBlocks(Vec<ExecutedBlock>, oneshot::Sender<Option<(B256, u64)>>),
```
Comment (mattsse) [inline crates/engine/tree/src/persistence.rs:151]: can we do `BlockNumHash` here?

**Review by mattsse — CHANGES_REQUESTED** [review]
only nits

I was able to follow and the vecque for queued disk reorgs makes sense

File: crates/engine/tree/src/persistence.rs (hunk 1 above)
Comment (Rjected) [reply crates/engine/tree/src/persistence.rs:151]: yep

**Review by mattsse — APPROVED** [review]
