### PR TITLE
fix: set parent beacon block to zero hash if parent's beacon block is Some

### LINKED ISSUE #16734: Set correct parent beacon block hash to zero for pending block for eth_simulateV1
### Describe the feature

parent beacon block should be zero hash for eth_simulateV1

we're currently reusing the block's parent hash parent beacon block

https://github.com/paradigmxyz/reth/blob/75ffcdac32acd323e34b9ae97079b8beb570f0d3/crates/rpc/rpc/src/eth/helpers/pending_block.rs#L74-L74

we should instead use the zero hash here if the parent's beacon block is some

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iTranscend**
resolves https://github.com/paradigmxyz/reth/issues/16734

### CODE REVIEW

File: crates/rpc/rpc/src/eth/helpers/pending_block.rs [hunk 1]
```diff
@@ -71,7 +71,7 @@ where
             suggested_fee_recipient: parent.beneficiary(),
             prev_randao: B256::random(),
             gas_limit: parent.gas_limit(),
-            parent_beacon_block_root: parent.parent_beacon_block_root(),
+            parent_beacon_block_root: parent.parent_beacon_block_root().map(|_| B256::ZERO),
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/helpers/pending_block.rs:74]: this should do it

**Review by mattsse — APPROVED** [review]
lgtm
