### PR TITLE
fix(txpool): respect propagate setting in the full tx stream

### LINKED ISSUE #4351: Don't include non propagateable transaction origin in pending tx stream
### Describe the feature

This will include all transactions added to the pending pool
https://github.com/paradigmxyz/reth/blob/0beaf85f4bfbed26956fae488268db3ec626c9ba/crates/rpc/rpc/src/eth/pubsub.rs#L275-L280

# TODO

add new functions for

https://github.com/paradigmxyz/reth/blob/0beaf85f4bfbed26956fae488268db3ec626c9ba/crates/transaction-pool/src/traits.rs#L132-L150

that also take:

https://github.com/paradigmxyz/reth/blob/0beaf85f4bfbed26956fae488268db3ec626c9ba/crates/transaction-pool/src/traits.rs#L327-L339

as argument, see 

https://github.com/paradigmxyz/reth/blob/0beaf85f4bfbed26956fae488268db3ec626c9ba/crates/transaction-pool/src/traits.rs#L118-L120

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alexfertel**
This PR reuses some of the work in https://github.com/paradigmxyz/reth/pull/4050 to avoid including non-propagatable tx in the full tx stream. Closes https://github.com/paradigmxyz/reth/issues/4351.

### CODE REVIEW

File: crates/transaction-pool/src/pool/mod.rs [hunk 1]
```diff
@@ -745,6 +754,14 @@ struct PendingTransactionListener {
     kind: PendingTransactionListenerKind,
 }
 
+/// An active listener for new pending transactions.
+#[derive(Debug)]
+struct TransactionListener<T: PoolTransaction> {
+    sender: mpsc::Sender<NewTransactionEvent<T>>,
+    /// Whether to include transactions that should not be propagated over the network.
+    kind: PendingTransactionListenerKind,
```
Comment (alexfertel) [inline crates/transaction-pool/src/pool/mod.rs:762]: Not that happy about reusing `PendingTransactionListenerKind` here. If this change is correct, how would you design this?

File: crates/transaction-pool/src/traits.rs [hunk 2]
```diff
@@ -138,7 +147,10 @@ pub trait TransactionPool: Send + Sync + Clone {
     fn new_pending_pool_transactions_listener(
         &self,
     ) -> NewSubpoolTransactionStream<Self::Transaction> {
-        NewSubpoolTransactionStream::new(self.new_transactions_listener(), SubPool::Pending)
+        NewSubpoolTransactionStream::new(
+            self.new_transactions_listener_for(PendingTransactionListenerKind::PropagateOnly),
+            SubPool::Pending,
+        )
```
Comment (alexfertel) [inline crates/transaction-pool/src/traits.rs:153]: I didn't do the same refactor for `SubPool::BaseFee` or `SubPool::Queued` (right below this function) because I didn't see them used anywhere.

File: crates/transaction-pool/src/pool/mod.rs (hunk 1 above)
Comment (onbjerg) [reply crates/transaction-pool/src/pool/mod.rs:762]: probably just rename it to `TransactionListenerKind` and replace the references in the docs for "pending" with something like "in this pool", wdyt @mattsse?

Comment (mattsse) [reply crates/transaction-pool/src/pool/mod.rs]: yeah I like that, `TransactionListenerKind` is more appropriate

File: crates/transaction-pool/src/traits.rs (hunk 2 above)
Comment (mattsse) [reply crates/transaction-pool/src/traits.rs]: this is reasonable, and we don't really have a usecase for this anyway

**Review by mattsse — APPROVED** [review]
awesome, sorry for the delay.

this is great, exactly what we wanted,

I only renamed the enum
