### PR TITLE
fix: do not truncate blocks to persist

### LINKED ISSUE #9978: dont truncate blocks to persist
currently we only try to persist `threshold` blocks at a time:

https://github.com/paradigmxyz/reth/blob/93ab09821b0d24aa56f58a1386c901fa4d782bd7/crates/engine/tree/src/tree/mod.rs#L788-L792

this can lead to a build up of buffered blocks if new blocks arrive faster than how long it takes to flush them.

what we should do here instead is write all available blocks `[last_persisted .. canonicalhead - threshold]`

### PR DESCRIPTION
**Pull request by fgimenez**
Closes #9978

### CODE REVIEW

**Review by rkrasiuk — APPROVED** [review]
lgtm

File: crates/engine/tree/src/tree/mod.rs [hunk 1]
```diff
@@ -766,31 +766,34 @@ where
             self.config.persistence_threshold()
     }
 
-    /// Returns a batch of consecutive canonical blocks to persist. The expected order is
-    /// oldest -> newest.
+    /// Returns a batch of consecutive canonical blocks to persist in the range
+    /// `(last_persisted_number .. canonical_head - threshold]` . The expected
+    /// order is oldest -> newest.
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:771]: sg!

File: crates/engine/tree/src/tree/mod.rs [hunk 2]
```diff
@@ -766,31 +766,34 @@ where
...
 
+        let canonical_head_number = self.state.tree_state.canonical_block_number();
+
+        let target_number =
+            canonical_head_number.saturating_sub(self.config.persistence_threshold());
+
         while let Some(block) = self.state.tree_state.blocks_by_hash.get(&current_hash) {
             if block.block.number <= last_persisted_number {
                 break;
             }
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:785]: I believe this should actually be enforced by the tree invariants, but better be safe here

File: crates/engine/tree/src/tree/mod.rs [hunk 3]
```diff
@@ -766,31 +766,34 @@ where
...
 
-            blocks_to_persist.push(block.clone());
+            if block.block.number <= target_number {
+                blocks_to_persist.push(block.clone());
+            }
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:789]: this will work because we have a guarantee that canonical head always has its parent blocks

File: crates/engine/tree/src/tree/mod.rs [hunk 4]
```diff
@@ -766,31 +766,34 @@ where
             self.config.persistence_threshold()
     }
 
-    /// Returns a batch of consecutive canonical blocks to persist. The expected order is
-    /// oldest -> newest.
+    /// Returns a batch of consecutive canonical blocks to persist in the range
+    /// `(last_persisted_number .. canonical_head - threshold]` . The expected
+    /// order is oldest -> newest.
     fn get_canonical_blocks_to_persist(&self) -> Vec<ExecutedBlock> {
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:772]: could this return an empty vec?
if so we likely should add a sanity check before we send that vec to the persistence task

**Review by mattsse — APPROVED** [review]
lgtm

File: crates/engine/tree/src/tree/mod.rs (hunk 4 above)
Comment (fgimenez) [reply crates/engine/tree/src/tree/mod.rs:776]: sure, added here https://github.com/paradigmxyz/reth/commit/45fbe9edad2c86076653335885eecd462fad05c4
