### PR TITLE
fix: add test for truncating parked with large transactions

### LINKED ISSUE #6346: endless discarding parked pool loop if it exceeds size but not txs
### Describe the feature

The discard_worst loop runs as long as:

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/transaction-pool/src/pool/txpool.rs#L783-L787

but `ParkedPool::truncate_pool` exits early if it has capacity for transactions without checking the size:

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/transaction-pool/src/pool/parked.rs#L152-L155

this results in an endless loop if the pool exceeds the size but not the number of allowed transactions

## TODO

replace drop target with a check against pool limit

https://github.com/paradigmxyz/reth/blob/4e5ae6c540fb8085ee102586c5caf1cd20379e4b/crates/transaction-pool/src/pool/parked.rs#L160-L160

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rjected**
Fixes https://github.com/paradigmxyz/reth/issues/6346 and adds more tests for parked and blob pool eviction. Now both the length and the size are taken into account when the truncate method decides to remove another transaction or return.

### CODE REVIEW

**Comment by Rjected** [comment]
going to rebase on https://github.com/paradigmxyz/reth/pull/6368 once it's merged

File: crates/transaction-pool/src/pool/txpool.rs [hunk 1]
```diff
@@ -785,9 +785,26 @@ impl<T: TransactionOrdering> TxPool<T> {
                         .$limit
                         .is_exceeded($this.$pool.len(), $this.$pool.size())
                     {
+                        tracing::trace!(
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:788]: drop the prefix
```suggestion
                       trace!(
```

File: crates/transaction-pool/src/pool/parked.rs [hunk 2]
```diff
@@ -95,6 +95,18 @@ impl<T: ParkedOrd> ParkedPool<T> {
...
+    pub(crate) fn get_txs_by_sender_with_size(
+        &self,
+        sender: SenderId,
+    ) -> Vec<(TransactionId, usize)> {
+        self.by_id
+            .range((sender.start_bound(), Unbounded))
+            .take_while(move |(other, _)| sender == other.sender)
+            .map(|(tx_id, tx)| (*tx_id, tx.transaction.size()))
+            .collect()
+    }
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/parked.rs:108]: do we need this if we don't use the size in the truncate loop?

**Review by mattsse — CHANGES_REQUESTED** [review]
nice, one more eviction bug down

File: crates/transaction-pool/src/pool/parked.rs (hunk 2 above)
Comment (mattsse) [reply crates/transaction-pool/src/pool/parked.rs:108]: I think we can solve this even with out allocating a vec and instead find the highest nonce of the sender and remove that

Comment (Rjected) [reply crates/transaction-pool/src/pool/parked.rs:108]: Ah, we don't, artifact of an earlier fix

Comment (mattsse) [reply crates/transaction-pool/src/pool/parked.rs:108]: actually maybe allocating is better than several lookups

**Review by mattsse — APPROVED** [review]
