### PR TITLE
Removed manual implementations of `core::error::Error`

### LINKED ISSUE #13284: Remove manual implementations of `core::error::Error`
### Describe the feature

Remove manual implementations of `core::error::Error` in favor of using `thiserror` v2, which includes support for `no_std`.

`From<>` implementation must be moved to `#[from]` where applicable.

You can search for "core::error::Error for" in the codebase to find all of the relevant instances.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PelleKrab**
Closes #13284

Should this manual implementation be removed too?:
https://github.com/paradigmxyz/reth/blob/a212e1b36f199429ff541a7e7d3d6a98b6022164/crates/transaction-pool/src/error.rs#L22C1-L27C2

### CODE REVIEW

File: crates/storage/errors/src/provider.rs [hunk 1]
```diff
@@ -10,169 +10,176 @@ use reth_static_file_types::StaticFileSegment;
...
-    )]
+    #[error("storage change set for address {address} and key {storage_key} at block #{block_number} does not exist")]
     StorageChangesetNotFound {
         /// The block number found for the address and storage key.
         block_number: BlockNumber,
         /// The account address.
         address: Address,
         /// The storage key.
-        // NOTE: This is a Box only because otherwise this variant is 16 bytes larger than the
-        // second largest (which uses `BlockHashOrNumber`).
```
Comment (mattsse) [inline crates/storage/errors/src/provider.rs:49]: please don't remove docs

File: crates/blockchain-tree-api/src/error.rs [hunk 2]
```diff
@@ -187,42 +187,18 @@ impl InsertBlockErrorData {
...
-    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
-        f.debug_struct("InsertBlockError")
-            .field("error", &self.kind)
-            .field("hash", &self.block.hash())
-            .field("number", &self.block.number())
-            .field("parent_hash", &self.block.parent_hash())
-            .field("num_txs", &self.block.body.transactions().len())
-            .finish_non_exhaustive()
-    }
-}
```
Comment (mattsse) [inline crates/blockchain-tree-api/src/error.rs:218]: this is no longer equivalent to the derived code

File: crates/storage/errors/src/provider.rs [hunk 3]
```diff
@@ -10,169 +10,176 @@ use reth_static_file_types::StaticFileSegment;
...
+
+    /// When required header related data was not found but was required.
+    #[error("no header found for {_0:?}")]
     HeaderNotFound(BlockHashOrNumber),
+
     /// The specific transaction identified by hash or id is missing.
-    #[display("no transaction found for {_0:?}")]
+    #[error("no transaction found for {_0:?}")]
     TransactionNotFound(HashOrNumber),
+
```
Comment (mattsse) [inline crates/storage/errors/src/provider.rs:78]: please undo unrelated new lines changes

**Review by mattsse — CHANGES_REQUESTED** [review]
ty,

some nits

**Review by mattsse — APPROVED** [review]
