### PR TITLE
fix: share `DatabaseProviderRW` on `PersistenceAction::SaveBlocks`

### LINKED ISSUE #9923: Improve persistence action commits

### PR DESCRIPTION
**Pull request by joshieDo**
closes https://github.com/paradigmxyz/reth/issues/9923

We should only commit, once we have written everything.

### CODE REVIEW

File: crates/engine/tree/src/persistence.rs [hunk 1]
```diff
@@ -145,15 +149,18 @@ impl<DB: Database> PersistenceService<DB> {
     ///
     /// The [`update_transaction_meta`](Self::update_transaction_meta) method should be called
     /// after this, to update the checkpoints for headers and block bodies.
-    #[instrument(level = "trace", skip(self), target = "engine")]
-    fn write_transactions(&self, block: Arc<SealedBlock>) -> ProviderResult<(u64, U256)> {
+    #[instrument(level = "trace", skip(self, provider_rw), target = "engine")]
```
Comment (mattsse) [inline crates/engine/tree/src/persistence.rs:152]: this should only trace the blocks num_hash, because this is very noisy otherwise

**Review by mattsse — CHANGES_REQUESTED** [review]
observability nit

**Review by mattsse — APPROVED** [review]
