### PR TITLE
fix(rpc): return empty log set for invalid filter block ranges

### LINKED ISSUE #18098: eth_getLogs's Filter replaces fromBlock and toBlock with `latest`
### Describe the bug

Reth's log filtering updates the fromBlock and toBlock conditions with the latest block's logs.

The implementation isn't standardized across the EL clients (geth throw an error where erigon and besu reply with an empty list), but transparently replacing the filter's condition can lead to confusion.

### Steps to reproduce

```
cast logs --from-block 0xfffffffff --to-block 0xfffffffff  --json -r localhost:8545 | jq '.[0]'
{
  "address": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  "topics": [
    "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c",
    "0x0000000000000000000000003a10dc1a145da500d5fba38b9ec49c8ff11a981f"
  ],
  "data": "0x00000000000000000000000000000000000000000000000000afdbfcdc61c000",
  "blockHash": "0x2d7b2f6b86d95ca9f1e5f496d9dafa31850793963b5119b519ef51589649dbca",
  "blockNumber": "0x1628041",
  "blockTimestamp": "0x68aeff87",
  "transactionHash": "0xb83e9e78f854dc787447c401000f42c618da24bc2ded24342f7434a8758c7430",
  "transactionIndex": "0x0",
  "logIndex": "0x0",
  "removed": false
}
```

### Node logs

```text

```

### Platform(s)

Linux (x86)

### Container Type

Kubernetes

### What version/commit are you on?

1.6.0

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

*

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by dharmvr1**
close #18098

### CODE REVIEW

**Comment by dharmvr1** [comment]
hi @mattsse @Rjected @RomanHodulak
I noticed in [filter.rs:L493](https://github.com/paradigmxyz/reth/blob/615bd4a30fc719de384be55bba0270a36664a47b/crates/rpc/rpc/src/eth/filter.rs?utm_source=chatgpt.com#L493)
 that start_block is set to info.best_number.
This seems confusing, since start_block sounds like the earliest available block (prune floor), but here it’s the latest (head). That’s why handling from_block < start_block felt odd.
Should start_block actually represent the prune floor instead of the head?

File: crates/rpc/rpc-eth-types/src/logs_utils.rs
Comment (mattsse) [inline crates/rpc/rpc-eth-types/src/logs_utils.rs:1]: I'd like to keep this here unchanged and instead only add a check for the ::Range variant where we check from,to explicitly

File: crates/rpc/rpc/src/eth/filter.rs [hunk 1]
```diff
@@ -502,6 +502,11 @@ where
                     .flatten();
                 let (from_block_number, to_block_number) =
                     logs_utils::get_filter_block_range(from, to, start_block, info);
+                // if function signaled empty range:
+                if from_block_number == 0 && to_block_number == 0 {
+                    return Ok(Vec::new()); // returns empty log set, not an error
+                }
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/filter.rs]: this isn't very intuitive that we now need to check for == 0

we can add the check directly to the variants from,to blocks

**Review by mattsse — CHANGES_REQUESTED** [review]

**Comment by dharmvr1** [comment]
hi @mattsse  
Made the changes, let me know if anything else is needed.

**Comment by dharmvr1** [comment]
hi @mattsse  just want to remind u about this ,  please review changes ,
or let me know if need any change
thanks

**Review by mattsse — APPROVED** [review]

**Review by yongkangc — APPROVED** [review]
nice
