### PR TITLE
fix: ignore BlockHashNotFoundInChain error for unexpected canonical error log

### LINKED ISSUE #7289: `BlockHashNotFoundInChain` error is expected during the live sync
```console
2024-03-21T21:06:39.526357Z Live sync in progress, downloading blocks remaining_blocks=29 target_block_hash=0x0c6c2f136a89a4c3a0b6c90505a112df8ccf754958451ee3a34a5e0f142acef9
2024-03-21T21:06:40.980383Z ERROR Unexpected error while making sync target canonical: BlockchainTree(BlockHashNotFoundInChain { block_hash: 0x2060ae79f50df847d62c6a7a5502ccb3bcc5090fe56f5ea6c40406b8495b4bc2 }), 0x2060ae79f50df847d62c6a7a5502ccb3bcc5090fe56f5ea6c40406b8495b4bc2
```

This error isn't a sign of something bad happening, but it can make the user think that something is wrong with the sync.

https://github.com/paradigmxyz/reth/blob/ea5535cc28fd09412744a8982ea2cb46d2bbb5a2/crates/consensus/beacon/src/engine/mod.rs#L1434-L1439

### PR DESCRIPTION
**Pull request by Rjected**
Checking this error and logging it led to some unintended error logs:
```
2024-03-21T21:06:40.980383Z ERROR Unexpected error while making sync target canonical: BlockchainTree(BlockHashNotFoundInChain { block_hash: 0x2060ae79f50df847d62c6a7a5502ccb3bcc5090fe56f5ea6c40406b8495b4bc2 }), 0x2060ae79f50df847d62c6a7a5502ccb3bcc5090fe56f5ea6c40406b8495b4bc2
```

This now only logs when the error is __not__ `BlockHashNotFoundInChain`.

Fixes #7289

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -1431,12 +1431,19 @@ where
...
-                                target: "consensus::engine",
-                                "Unexpected error while making sync target canonical: {:?}, {:?}",
+                            if !matches!(
                                 error,
-                                hash
-                            )
+                                CanonicalError::BlockchainTree(
+                                    BlockchainTreeError::BlockHashNotFoundInChain { .. }
+                                )
+                            ) {
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:1439]: there are more error variants like this that don't deserve the error! level, see BlockchainTreeError variants

this needs an evaluation what should actually be logged on error

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
