### PR TITLE
fix: gracefully handle missing `persisted_trie_updates`

### LINKED ISSUE #13940: `persisted_trie_updates` data lost on restart prevents node from handling reorgs
### Describe the feature

If node is restarted, then we are losing `persisted_trie_updates` data in `TreeState`. This results in `executed_block_by_hash` always returning `None` for canonical blocks https://github.com/paradigmxyz/reth/blob/f93d307a45fb46e538081c57a4e02ecbd2f4951f/crates/engine/tree/src/tree/mod.rs#L1593-L1595

This results in node not being able to handle reorgs by ending up here https://github.com/paradigmxyz/reth/blob/f93d307a45fb46e538081c57a4e02ecbd2f4951f/crates/engine/tree/src/tree/mod.rs#L943-L945

Solution for this is to ignore cache misses in `persisted_trie_updates` for canonical blocks because we don't need `TrieUpdates` for reorg of the canonical chain, and for sidechains they are always present because those live fully in memory

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by klkvr**
Closes https://github.com/paradigmxyz/reth/issues/13940

This PR divides `ExecutedBlock` into `ExecutedBlockWithTrieUpdates` and `ExecutedBlock`. in-memory state only contains  `ExecutedBlockWithTrieUpdates` without tracking the `persisted_trie_updates` separately.

`NewCanonicalChain::Reorg` variant now only contains a `Vec<ExecutedBlock>` for reorg chain, thus not requiring us to obtain TrieUpdates for those. 

Reorged blocks are no longer re-inserted into in-memory state

### CODE REVIEW

File: crates/chain-state/src/in_memory.rs [hunk 1]
```diff
@@ -837,13 +862,13 @@ pub enum NewCanonicalChain<N: NodePrimitives = EthPrimitives> {
...
+        new: Vec<ExecutedBlockWithTrieUpdates<N>>,
     },
     /// A reorged chain consists of two chains that trace back to a shared ancestor block at which
     /// point they diverge.
     Reorg {
         /// All blocks of the _new_ chain
-        new: Vec<ExecutedBlock<N>>,
+        new: Vec<ExecutedBlockWithTrieUpdates<N>>,
         /// All blocks of the _old_ chain
         old: Vec<ExecutedBlock<N>>,
```
Comment (mattsse) [inline crates/chain-state/src/in_memory.rs:873]: this makes sense.

can we document why these are different block types?

**Review by mattsse — COMMENTED** [review]
I'm a bit torn about this because this could be very confusing

and not really a fan of introducing another type here.

but having the trienodes separate from the actual block makes a ton of sense and I have a feeling that this will be beneficial in the future.

leaning towards we should make this change
wdyt @rkrasiuk @Rjected

File: crates/chain-state/src/in_memory.rs [hunk 2]
```diff
@@ -824,6 +826,32 @@ impl<N: NodePrimitives> ExecutedBlock<N> {
...
         &self.hashed_state
     }
+}
+
+/// An [`ExecutedBlock`] with its [`TrieUpdates`].
+///
+/// We store it as separate type because [`TrieUpdates`] are only available for blocks stored in
+/// memory and can't be obtained for canonical persisted blocks.
+#[derive(Clone, Debug, PartialEq, Eq, Default, derive_more::Deref, derive_more::DerefMut)]
+pub struct ExecutedBlockWithTrieUpdates<N: NodePrimitives = EthPrimitives> {
```
Comment (mattsse) [inline crates/chain-state/src/in_memory.rs:836]: can we also add an Into impl for ExecutedBlock

because this would be a breaking change and users are currently using the executedBlock

File: crates/chain-state/src/in_memory.rs (hunk 1 above)
Comment (mattsse) [reply crates/chain-state/src/in_memory.rs:876]: @klkvr this type is the common way users will encounter this change, so we should add a note about the old chain here as well, why trieupdates are missing for the reorged chain

**Review by mattsse — COMMENTED** [review]
this change kinda grew on me,

one caveat here is that this now always excludes trieupdates for reorged blocks so if users are currently relying on that this will no longer be possible.
but I don't think this is the case or is even something that is useful?

**Comment by klkvr** [comment]
> but I don't think this is the case or is even something that is useful?

yeah I would expect that you wouldn't need this info generally, gvien that TrieUpdates are only useful when applying blocks to db, @rkrasiuk wdyt?

**Review by rkrasiuk — APPROVED** [review]
lgtm

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
didn't find a better name than executedblockwithtrieupdates, so let's go with that
