### PR TITLE
fix: park descendant when delete a pending tx

### LINKED ISSUE #15911: Treat TransactionPoll::remove_transaction correctly
### Describe the feature

currently, this behaves incorrectly if we remove descendant transactions

https://github.com/paradigmxyz/reth/blob/4d77608be166905111079adde8e3add93fde0623/crates/transaction-pool/src/traits.rs#L316-L322

here:

https://github.com/paradigmxyz/reth/blob/4d77608be166905111079adde8e3add93fde0623/crates/transaction-pool/src/pool/txpool.rs#L765-L769

because this doesn't update the descendant txs

https://github.com/paradigmxyz/reth/blob/4d77608be166905111079adde8e3add93fde0623/crates/transaction-pool/src/pool/txpool.rs#L822-L830

and for the pending pool especially

https://github.com/paradigmxyz/reth/blob/4d77608be166905111079adde8e3add93fde0623/crates/transaction-pool/src/pool/pending.rs#L319-L323

this promotes the descendant tx to pending

what we should do here instead is treating this as if this would introduce a new nonce gap.

the simplest solution for this is probably:

remove the tx and all descendants from the global set and the subpools, reinsert all the descendants.

maybe @int88 ?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by int88**
fixes: #15911

### CODE REVIEW

File: crates/transaction-pool/src/pool/txpool.rs [hunk 1]
```diff
@@ -3077,15 +3105,15 @@ mod tests {
...
 
         // Now add transaction with nonce 2
         let _res = pool.add_transaction(v2, on_chain_balance, on_chain_nonce).unwrap();
 
-        // v2 is in the queue now. v1 is still in 'pending'.
-        assert_eq!(1, pool.queued_transactions().len());
-        assert_eq!(1, pool.pending_transactions().len());
+        // v1 and v2 should both be in the queue now.
+        assert_eq!(2, pool.queued_transactions().len());
+        assert!(pool.pending_transactions().is_empty());
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:3116]: this is actually the bug you spotted earlier, right?

File: crates/transaction-pool/src/pool/txpool.rs [hunk 2]
```diff
@@ -1455,13 +1457,39 @@ impl<T: PoolTransaction> AllTransactions<T> {
     pub(crate) fn remove_transaction_by_hash(
         &mut self,
         tx_hash: &B256,
-    ) -> Option<(Arc<ValidPoolTransaction<T>>, SubPool)> {
+        update_descendant: bool,
+    ) -> Option<(Arc<ValidPoolTransaction<T>>, SubPool, Vec<PoolUpdate>)> {
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:1461]: instead of making this conditional I'd prefer having a new dedicated function for this instead, that we can call after `remove_transaction_by_hash` in `fn remove_transaction(`

File: crates/transaction-pool/src/pool/txpool.rs [hunk 3]
```diff
@@ -1455,13 +1457,39 @@ impl<T: PoolTransaction> AllTransactions<T> {
...
+        if !update_descendant {
+            return Some((tx, internal.subpool, vec![]));
+        }
+
+        let mut updates = Vec::new();
+
+        for (id, tx) in self.descendant_txs_mut(tx.id()) {
+            let current_pool = tx.subpool;
+
+            tx.state.remove(TxState::NO_NONCE_GAPS);
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:1477]: cool, this should actually do it, this is basically equivalent to reinserting them

**Review by mattsse — CHANGES_REQUESTED** [review]
nice, only have a style request,

perhaps we add one more test case?
and document this behaviour on `fn remove_transaction`

File: crates/transaction-pool/src/pool/txpool.rs (hunk 3 above)
Comment (int88) [reply crates/transaction-pool/src/pool/txpool.rs:1477]: yes, similar to the operations in `insert_tx`

File: crates/transaction-pool/src/pool/txpool.rs (hunk 1 above)
Comment (int88) [reply crates/transaction-pool/src/pool/txpool.rs:3116]: Yes! The status of these two txs should be same, as they are continuous, and the balance is sufficient

File: crates/transaction-pool/src/pool/txpool.rs (hunk 2 above)
Comment (int88) [reply crates/transaction-pool/src/pool/txpool.rs:1461]: 👌

**Comment by SozinM** [comment]
This remove also invoked when tx is mined -> won't cause nonce gap

File: crates/transaction-pool/src/pool/txpool.rs [hunk 4]
```diff
@@ -827,14 +827,19 @@ impl<T: TransactionOrdering> TxPool<T> {
...
+        self.process_updates(updates);
         self.remove_from_subpool(pool, tx.id())
     }
 
     /// This removes the transaction from the pool and advances any descendant state inside the
     /// subpool.
     ///
     /// This is intended to be used when a transaction is included in a block,
-    /// [`Self::on_canonical_state_change`]
+    /// [`Self::on_canonical_state_change`]. So its descendants will not change from pending to
```
Comment (int88) [inline crates/transaction-pool/src/pool/txpool.rs:841]: @SozinM this one will be used when tx was mined.

File: crates/transaction-pool/src/pool/txpool.rs [hunk 5]
```diff
@@ -827,14 +827,19 @@ impl<T: TransactionOrdering> TxPool<T> {
         tx_hash: &B256,
     ) -> Option<Arc<ValidPoolTransaction<T::Transaction>>> {
         let (tx, pool) = self.all_transactions.remove_transaction_by_hash(tx_hash)?;
+
+        // After tx is removed, its descendants must become parked due to the nonce gap
+        let updates = self.all_transactions.park_descendant_pending_txs(tx.id());
```
Comment (0xjingle) [inline crates/transaction-pool/src/pool/txpool.rs:832]: This change makes sense for mined txs but does it also need to consider whether this path could be called for re-org scenarios? If a mined tx is reverted due to a chain re-org, would its descendants be requeued correctly, or could it end up with inconsistent subpool state?

File: crates/transaction-pool/src/pool/txpool.rs [hunk 6]
```diff
@@ -1464,6 +1469,31 @@ impl<T: PoolTransaction> AllTransactions<T> {
         Some((tx, internal.subpool))
     }
 
+    pub(crate) fn park_descendant_pending_txs(&mut self, tx_id: &TransactionId) -> Vec<PoolUpdate> {
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:1472]: this needs some docs

File: crates/transaction-pool/src/pool/txpool.rs [hunk 7]
```diff
@@ -827,14 +827,19 @@ impl<T: TransactionOrdering> TxPool<T> {
         tx_hash: &B256,
     ) -> Option<Arc<ValidPoolTransaction<T::Transaction>>> {
         let (tx, pool) = self.all_transactions.remove_transaction_by_hash(tx_hash)?;
+
+        // After a tx is removed, its descendants must become parked due to the nonce gap
+        let updates = self.all_transactions.park_descendant_pending_txs(tx.id());
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/txpool.rs:832]: I'd like this function to be a separate function because is remove_transaction_by_hash is called in two places:

https://github.com/paradigmxyz/reth/blob/main/crates/transaction-pool/src/pool/txpool.rs#L779-L786

and processing updates for this one is redundant.

**Review by mattsse — CHANGES_REQUESTED** [review]
this looks good, I pushed some docs and test feature fixes.

I only have one more pedantic nitpick

File: crates/transaction-pool/src/pool/txpool.rs (hunk 7 above)
Comment (int88) [reply crates/transaction-pool/src/pool/txpool.rs:832]: 👍

**Review by mattsse — APPROVED** [review]
lgtm, ty

**Comment by SozinM** [comment]
@mattsse @int88
Seems there is little corner case:
When i use this function inner pool gets updated, tx is places in queue, but txpool_content will return incorrect data (with tx in pending and not in queue)

**Comment by mattsse** [comment]
can you open a new issue with the scenario, not obvious to me how this could happen now
