### PR TITLE
fix: add unknown block error

### LINKED ISSUE #3713: Add Unknown block error variant
### Describe the feature

> earliest`: The lowest numbered block the client has available; `finalized`: The most recent crypto-economically secure block, cannot be re-orged outside of manual intervention driven by community coordination; `safe`: The most recent block that is safe from re-orgs under honest majority and certain synchronicity assumptions; `latest`: The most recent block in the canonical chain observed by the client, this block may be re-orged out of the canonical chain even under healthy/normal conditions; `pending`: A sample next block built by the client on top of `latest` and containing the set of transactions usually taken from local mempool. Before the merge transition is finalized, any call querying for `finalized` or `safe` block MUST be responded to with `-39001: Unknown block` error

https://github.com/ethereum/execution-apis/blob/6d17705a875e52c26826124c2a8a15ed542aeca2/src/schemas/block.yaml#L109

## TODO

* add unknown block variant to EthApiError (there's already `UnknownBlockNumber` perhaps we can use this instead? needs investigation by sending some sample requests for nonexisting eth_getBlockByNumber to other clients)

* if finalized/safe is queried and we don't have the block, we should return the error:

https://github.com/ledgerwatch/erigon/blob/eae2d9a79cb70dbe30b3a6b79c436872e4605458/turbo/rpchelper/rpc_block.go#L36-L46

ref https://github.com/ledgerwatch/erigon/pull/4436/files

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Gooong**
Closes #3713 

`UnknownBlock: -39001` should only be returned when querying `finalized` or `safe` block before the merge transition is finalized. Therefore we shouldn't reuse `UnknownBlockNumber`.

### CODE REVIEW

File: crates/rpc/rpc-types/src/eth/error.rs [hunk 1]
```diff
@@ -13,6 +13,9 @@ pub enum EthRpcErrorCode {
     /// > If the block is not found, the callee SHOULD raise a JSON-RPC error (the recommended
     /// > error code is -32001: Resource not found).
     ResourceNotFound,
+    /// Thrown when Querying for `finalized` or `safe` block before the merge transition is
+    /// finalized, <https://github.com/ethereum/execution-apis/blob/6d17705a875e52c26826124c2a8a15ed542aeca2/src/schemas/block.yaml#L109>
+    UnknownBlock,
```
Comment (mattsse) [inline crates/rpc/rpc-types/src/eth/error.rs:18]: nice, we definitely want the reference here

File: crates/rpc/rpc/src/eth/error.rs [hunk 2]
```diff
@@ -26,6 +26,9 @@ pub enum EthApiError {
     PoolError(RpcPoolError),
     #[error("Unknown block number")]
     UnknownBlockNumber,
+    /// Thrown when querying for `finalized` or `safe` before the merge transition is finalized
+    #[error("Unknown block")]
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/error.rs:30]: I'd also like to add the execution api reference here

I'd like to rename this no `UnknownSafeOrFinalizedBlock` just to prevent any confusion because we also have `UnknownBlockNumber` already

**Review by mattsse — CHANGES_REQUESTED** [review]
nice, smol nit

**Review by mattsse — APPROVED** [review]
