### PR TITLE
feat: :bug: fix using latest header

### LINKED ISSUE #16613: Improve eth_gasPrice basefee lookup
### Describe the feature

currently, this fetches the entire block:

https://github.com/paradigmxyz/reth/blob/4686778cb9dac57345ebf1a7799e5f763a881eae/crates/rpc/rpc-eth-api/src/helpers/fee.rs#L338-L338

but we only need the most recent header which we could fethc from

https://github.com/paradigmxyz/reth/blob/4686778cb9dac57345ebf1a7799e5f763a881eae/crates/storage/storage-api/src/block.rs#L304-L310

but the trait bounds currently only require `BlockReader`

https://github.com/paradigmxyz/reth/blob/4686778cb9dac57345ebf1a7799e5f763a881eae/crates/rpc/rpc-eth-api/src/node.rs#L84-L84

but we need `BlockReaderIdExt` for this

## TODO
* extend the Provider bound in LoadFee trait to BlockReaderIdExt
* use latest_header for fetching the fee

we could maybe even bump the trait bound here entirely:

https://github.com/paradigmxyz/reth/blob/4686778cb9dac57345ebf1a7799e5f763a881eae/crates/rpc/rpc-eth-api/src/node.rs#L84-L84

which is maybe easier long term but more invasive

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tbelleng**
close #16613

### CODE REVIEW

File: crates/rpc/rpc-eth-api/src/helpers/fee.rs [hunk 1]
```diff
@@ -335,10 +338,13 @@ pub trait LoadFee: LoadBlock {
...
     fn gas_price(&self) -> impl Future<Output = Result<U256, Self::Error>> + Send {
-        let header = self.recovered_block(BlockNumberOrTag::Latest.into());
+        let header = self.provider().latest_header();
         let suggested_tip = self.suggested_priority_fee();
         async move {
-            let (header, suggested_tip) = futures::try_join!(header, suggested_tip)?;
+            let (header, suggested_tip) = futures::try_join!(
+                async { header.map_err(Self::Error::from_eth_err) },
+                suggested_tip
+            )?;
```
Comment (mattsse) [inline crates/rpc/rpc-eth-api/src/helpers/fee.rs]: we can now remove the try_join and simply await the suggested_tip future here

File: crates/rpc/rpc-eth-api/src/helpers/fee.rs [hunk 2]
```diff
@@ -335,10 +338,13 @@ pub trait LoadFee: LoadBlock {
     ///
     /// See also: <https://github.com/ethereum/pm/issues/328#issuecomment-853234014>
     fn gas_price(&self) -> impl Future<Output = Result<U256, Self::Error>> + Send {
-        let header = self.recovered_block(BlockNumberOrTag::Latest.into());
+        let header = self.provider().latest_header();
         let suggested_tip = self.suggested_priority_fee();
```
Comment (mattsse) [inline crates/rpc/rpc-eth-api/src/helpers/fee.rs]: let's move all fo this into the async block so that they are executed together

**Review by mattsse — CHANGES_REQUESTED** [review]
cool, tiny suggestion

**Review by mattsse — APPROVED** [review]
