### PR TITLE
fix: shrink queued bodies and headers when drained or split

### LINKED ISSUE #3175: Ever expanding memory in downloaders due to `split_off` and `drain`
### Describe the bug

as @Rjected discovered:

https://github.com/paradigmxyz/reth/blob/3a90eac8b101ff5a5f459595d7a716ba6522d695/crates/net/downloaders/src/headers/reverse_headers.rs#L617-L618

is very memory expensive because split_off does not change the source vec's capacity

https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.split_off

This is also the case for `drain` https://www.reddit.com/r/rust/comments/pakdaa/does_drain_leave_the_vecs_memory_allocated/

https://github.com/paradigmxyz/reth/blob/3a90eac8b101ff5a5f459595d7a716ba6522d695/crates/net/downloaders/src/bodies/bodies.rs#L272-L272

this means, that these buffers only grow to their max size, but never shrink

although this is more performant, we should always use shrink_to_fit here, as the performance of the downloader is negligible compared to the pipeline overall and a smaller memory footprint is desired

### Steps to reproduce

-

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
This fixes an OOM in the bodies stage and reduces overall memory allocations in the downloaders, by shrinking vectors whenever we `split` or `drain` them. Previously the headers downloader would effectively clone `queued_validated_headers` in terms of allocations, because `split_off` does not change the original vec's capacity. Because `queued_validated_headers` could be on the order of gigabytes, this caused an OOM.

Fixes #3175

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
supportive as discussed - any way of testing this?

File: crates/net/downloaders/src/headers/reverse_headers.rs [hunk 1]
```diff
@@ -333,6 +333,7 @@ where
                     .count();
                 // removes all headers that are higher than current target
                 self.queued_validated_headers.drain(..skip);
+                self.queued_validated_headers.shrink_to_fit();
```
Comment (mattsse) [inline crates/net/downloaders/src/headers/reverse_headers.rs:336]: I don't think this is necessary here, because this merely removes a few headers from the front, and we will go through `next_batch` eventually

File: crates/net/downloaders/src/headers/reverse_headers.rs [hunk 2]
```diff
@@ -616,6 +617,21 @@ where
...
+        // unchanged, so queued_validated_headers will then have only `batch_size` elements, and
+        // its original capacity. Because `rem` is initially populated with elements `[batch_size,
+        // len)` of `queued_validated_headers`, it will have a capacity of at least `len -
+        // batch_size`, and the total memory allocated by the two buffers will be around double the
+        // original size of `queued_validated_headers`.
+        //
+        // To prevent these allocations from leaking to the consumer, we shrink the capacity of the
+        // two buffers. The total memory allocated should then be not much more than the original
+        // size of `queued_validated_headers`.
+        rem.shrink_to_fit();
```
Comment (mattsse) [inline crates/net/downloaders/src/headers/reverse_headers.rs:633]: hmm, I think this is redundant because `split_off` only allocates required capacity

**Review by mattsse — CHANGES_REQUESTED** [review]
very nice find.

This also applies to the BianryHeaps which are just Vec wrappers, so we need to shrink them as well.

I think we can get away with having our own shrink_to fit functions, where we delegate the calls and only call this once when we return the next batch?

**Comment by Rjected** [comment]
> supportive as discussed - any way of testing this?

Just added some checks in the existing tests that make sure `len == capacity` for downloaded values, when the stream batch size is lower than the number of values that should be produced.

also added another test for one-by-one download with a larger request limit, so `queued_validated_headers` is hopefully larger than the batch size in that test, which should trigger the necessary condition.

**Review by rkrasiuk — APPROVED** [review]
majestic!

**Comment by Rjected** [comment]
@mattsse added calls to `shrink_to_fit` whenever buffered responses are popped in 781d786e8d2f2de9b9e97e0e3748482d1815ec1e

File: crates/net/downloaders/src/headers/reverse_headers.rs [hunk 3]
```diff
@@ -557,6 +557,9 @@ where
                 Ordering::Equal => {
                     let OrderedHeadersResponse { headers, request, peer_id } =
                         PeekMut::pop(next_response);
+
+                    // shrink the buffer so that it doesn't grow indefinitely
+                    self.buffered_responses.shrink_to_fit();
```
Comment (mattsse) [inline crates/net/downloaders/src/headers/reverse_headers.rs:562]: having this inside a loop is not ideal,

I think we can move it below the loop, since the error case would retrigger a new download

**Review by mattsse — CHANGES_REQUESTED** [review]
smol nits

just to be safe I'd also like to replace all `.clear()` calls in the `fn clear()` functions of bodies and headers downloader with new initializations because clear does not change capacity

File: crates/net/downloaders/src/bodies/bodies.rs [hunk 4]
```diff
@@ -222,6 +222,8 @@ where
     /// Removes the next response from the buffer.
     fn pop_buffered_response(&mut self) -> Option<OrderedBodiesResponse> {
         let resp = self.buffered_responses.pop()?;
+        // shrink the buffer so that it doesn't grow indefinitely
+        self.buffered_responses.shrink_to_fit();
```
[the remark this answers is not in the document]
Comment (Rjected) [reply crates/net/downloaders/src/bodies/bodies.rs]: ah right, these should definitely be moved outside loops

**Review by mattsse — APPROVED** [review]
gg

**Comment by sigridjineth** [comment]
thks for resolving this.
