### PR TITLE
Cache update on chain action

### LINKED ISSUE #6467: Remove reorged blocks from EthStateCache
### Describe the bug

currently we're only adding `committed` blocks to the state cache:

https://github.com/paradigmxyz/reth/blob/2bcdec94abcbe61fcf8fbae5a3ef62a52360f548/crates/rpc/rpc/src/eth/cache/mod.rs#L576-L577

we should also remove reorged block entries from the cache

## TODO
Extend the `CacheNewCanonicalChain` to also include reorged blocks and clean them from the cache

### Steps to reproduce

-

### Node logs

```text
-
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

-

### What database version are you on?

-

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by i-m-aditya**
Fixes #6467

### CODE REVIEW

File: crates/rpc/rpc/src/eth/cache/mod.rs [hunk 1]
```diff
@@ -359,6 +359,38 @@ where
...
+                            res.clone()
+                                .map(|maybe_block| maybe_block.map(|block| block.block.body)),
+                        );
+                    }
+                }
+            }
+        }
+    }
+
+    fn on_reorg_receipts(
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/cache/mod.rs:381]: these look good!

File: crates/rpc/rpc/src/eth/cache/mod.rs [hunk 2]
```diff
@@ -552,14 +599,39 @@ where
...
+        res: ProviderResult<Option<Arc<Vec<Receipt>>>>,
+    },
+    EnvResult {
+        block_hash: B256,
+        res: Box<ProviderResult<(CfgEnvWithHandlerCfg, BlockEnv)>>,
+    },
+    CacheUpdateNewCanonicalChain {
+        blocks: Vec<SealedBlockWithSenders>,
+        receipts: Vec<BlockReceipts>,
+        is_new: bool,
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/cache/mod.rs:633]: I'd like a separate variant for the reorg case instead

**Review by mattsse — CHANGES_REQUESTED** [review]
this is great!

only have one nit

File: crates/rpc/rpc/src/eth/cache/mod.rs [hunk 3]
```diff
@@ -599,39 +598,15 @@ where
...
-    },
+    GetBlockWithSenders { block_hash: B256, response_tx: BlockWithSendersResponseSender },
+    GetBlockTransactions { block_hash: B256, response_tx: BlockTransactionsResponseSender },
+    GetEnv { block_hash: B256, response_tx: EnvResponseSender },
+    GetReceipts { block_hash: B256, response_tx: ReceiptsResponseSender },
+    BlockWithSendersResult { block_hash: B256, res: ProviderResult<Option<BlockWithSenders>> },
+    ReceiptsResult { block_hash: B256, res: ProviderResult<Option<Arc<Vec<Receipt>>>> },
+    EnvResult { block_hash: B256, res: Box<ProviderResult<(CfgEnvWithHandlerCfg, BlockEnv)>> },
+    CacheNewCanonicalChain { blocks: Vec<SealedBlockWithSenders>, receipts: Vec<BlockReceipts> },
+    UncacheOldCanonicalChain { blocks: Vec<SealedBlockWithSenders>, receipts: Vec<BlockReceipts> },
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/cache/mod.rs:609]:
```suggestion
    RemoveReorgedChain { blocks: Vec<SealedBlockWithSenders>, receipts: Vec<BlockReceipts> },
```

Comment (mattsse) [inline crates/rpc/rpc/src/eth/cache/mod.rs:609]: I want to add a new helper type for these arguments: blocks, receipts

```rust
struct ChainChange {blocks, receipts}
```

then we can simplify the duplicated code below:

```rust

fn new(Arc<Chain>)-> ChainChange 

```

which we can reuse for both reorg and committed

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
lgtm
