### PR TITLE
fix: eth_callMany uses vec bundle

### LINKED ISSUE #15584: `eth_callMany` should take in a list of `Bundle`
### Describe the bug

The standard seems to expect multiple `Bundle`s in a single call: 
- QuickNode: https://www.quicknode.com/docs/ethereum/eth_callMany
- Alloy: https://github.com/alloy-rs/alloy/blob/abd9c563f445d0df72b8a7fbb0e974869e8b0dc1/crates/provider/src/provider/eth_call/params.rs#L78

But Reth is expecting only one:
https://github.com/paradigmxyz/reth/blob/1e1f0f8e6b762804f2cb2a822f78fdd3c61d53cc/crates/rpc/rpc-eth-api/src/core.rs#L656-L659

This leads to invalid params errors even when calling `call_many` from Alloy.
```
error code -32602: Invalid params, data: "invalid type: map, expected a sequence at line 1 column 1"
```

### Steps to reproduce

Call `call_many` from Alloy towards a Reth-hosted `eth_callMany`.

### Node logs

```text

```

### Platform(s)

_No response_

### Container Type

Not running in a container, Docker

### What version/commit are you on?

https://github.com/paradigmxyz/reth/commit/18b1c7c819d3970c7f1f7393d0247168b2f722d4

### What database version are you on?

2

### Which chain / network are you on?

Custom

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by yohanelly95**
Fixes https://github.com/paradigmxyz/reth/issues/15584

### CODE REVIEW

**Comment by yohanelly95** [comment]
Fixes https://github.com/paradigmxyz/reth/issues/15584

File: crates/rpc/rpc-eth-api/src/helpers/call.rs [hunk 1]
```diff
@@ -667,7 +679,7 @@ pub trait Call:
         for tx in transactions {
             if *tx.tx_hash() == target_tx_hash {
                 // reached the target transaction
-                break
+                break;
```
Comment (mattsse) [inline crates/rpc/rpc-eth-api/src/helpers/call.rs:682]: please undo all additional `;`

**Review by mattsse — CHANGES_REQUESTED** [review]
thanks

File: crates/rpc/rpc-eth-api/src/helpers/call.rs (hunk 1 above)
Comment (yohanelly95) [reply crates/rpc/rpc-eth-api/src/helpers/call.rs]: @mattsse resolved (my ide formats on saving the file, undone)

**Review by mattsse — APPROVED** [review]
ty
