### PR TITLE
fix: ban trusted peer for a short period

### LINKED ISSUE #7056: Prevent banning trusted peers for a long time
### Describe the feature

ref #7052

with #7052 we provided a bit more leeway when penalizing misbehaving trusted peers, but we would still endup banning them, which basically puts them into a timeout for:

https://github.com/paradigmxyz/reth/blob/54449917b1dc31e996bbcf5dfbb0dc169eed18b8/crates/net/network/src/peers/manager.rs#L1217-L1218

## TODO
* ban misbehaving trusted peers for shorter durations:

https://github.com/paradigmxyz/reth/blob/54449917b1dc31e996bbcf5dfbb0dc169eed18b8/crates/net/network/src/peers/manager.rs#L299-L301

we should use the default uban interval here so trusted peers get unbanned with the next interval

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by int88**
fixes: #7056

### CODE REVIEW

File: crates/net/network/src/peers/manager.rs [hunk 1]
```diff
@@ -298,8 +298,18 @@ impl PeersManager {
 
     /// Bans the peer temporarily with the configured ban timeout
     fn ban_peer(&mut self, peer_id: PeerId) {
-        self.ban_list.ban_peer_until(peer_id, std::time::Instant::now() + self.ban_duration);
-        self.queued_actions.push_back(PeerAction::BanPeer { peer_id });
+        if let Some(peer) = self.peers.get(&peer_id) {
+            if peer.is_trusted() {
+                self.ban_list.ban_peer_until(
+                    peer_id,
+                    std::time::Instant::now() + self.backoff_durations.medium,
```
Comment (emhane) [inline crates/net/network/src/peers/manager.rs:305]: where did `self.backoff_durations.medium` come from? isn't it supposed to use a fraction of `self.ban_duration`?

**Review by emhane — DISMISSED** [review]

File: crates/net/network/src/peers/manager.rs (hunk 1 above)
Comment (int88) [reply crates/net/network/src/peers/manager.rs:305]: As discussed with @mattsse

Comment (emhane) [reply crates/net/network/src/peers/manager.rs:305]: Then will let @mattsse continue review :)

[the remark this answers is not in the document]
Comment (int88) [reply crates/net/network/src/peers/manager.rs:305]: Already prelude `Instant` of `tokio`, conflict?

**Comment by int88** [comment]
@mattsse @emhane updated! :)

File: crates/net/network/src/peers/manager.rs [hunk 2]
```diff
@@ -298,7 +298,14 @@ impl PeersManager {
 
     /// Bans the peer temporarily with the configured ban timeout
     fn ban_peer(&mut self, peer_id: PeerId) {
-        self.ban_list.ban_peer_until(peer_id, std::time::Instant::now() + self.ban_duration);
+        let mut until = std::time::Instant::now() + self.ban_duration;
+        if let Some(peer) = self.peers.get(&peer_id) {
+            if peer.is_trusted() {
+                until = std::time::Instant::now() + self.backoff_durations.medium;
+            }
+        }
```
Comment (mattsse) [inline crates/net/network/src/peers/manager.rs:306]: this can be simplified a bit by tracking only the ban_duration as mut and constructing the until = Instant + banduration after the if check, this way we're not creating two instants.

this also needs an additional note on the function docs

**Review by mattsse — CHANGES_REQUESTED** [review]
smol nit

**Review by mattsse — APPROVED** [review]
