### PR TITLE
fix: make into_transaction fallible

### LINKED ISSUE #4704: Bug in TypedTransactionRequest .into_transaction()
### Describe the bug

We are using reth rpc-types crate in our project and discovered this bug.

Basically while converting TypedTransactionRequest into Transaction, conversion of `U256` nonce to `u64` nonce is failing. You can see the panicing section and test to reproduce it [here](https://github.com/bkolad/reth/pull/1).

Line failing: https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-types/src/eth/transaction/typed.rs#L50
Exact assertion failing: https://github.com/recmo/uint/blob/main/src/bytes.rs#L93

### Steps to reproduce

Pull https://github.com/bkolad/reth/pull/1
Run added test
It will panic in conversion

### Node logs

_No response_

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

_No response_

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by DaniPopes**
Fixes #4704

### CODE REVIEW

File: crates/rpc/rpc-types/src/eth/transaction/typed.rs [hunk 1]
```diff
@@ -23,42 +23,45 @@ pub enum TypedTransactionRequest {
 }
 
 impl TypedTransactionRequest {
-    /// coverts a typed transaction request into a primitive transaction
-    pub fn into_transaction(self) -> Transaction {
-        match self {
+    /// Converts a typed transaction request into a primitive transaction.
+    ///
+    /// Returns `None` if any of the following are true:
+    /// - `nonce` is greater than [`u64::MAX`]
```
Comment (mattsse) [inline crates/rpc/rpc-types/src/eth/transaction/typed.rs:29]: just checked geth reference and nonce on rpc methods is U64, 

I think we can also change this in our types?

**Review by mattsse — APPROVED** [review]
lgtm,

pending suggestion re nonce U256 -> U64

File: crates/rpc/rpc-types/src/eth/transaction/typed.rs (hunk 1 above)
Comment (mattsse) [reply crates/rpc/rpc-types/src/eth/transaction/typed.rs:29]: https://github.com/ethereum/go-ethereum/blob/5b9cbe30f8ca2487c8991e50e9c939d5e6ec3cc2/internal/ethapi/transaction_args.go#L45-L45

Comment (DaniPopes) [reply crates/rpc/rpc-types/src/eth/transaction/typed.rs:29]: Is there a reason we're using ruint for these anyway? I don't see any serde or whatever

Comment (mattsse) [reply crates/rpc/rpc-types/src/eth/transaction/typed.rs:29]: there are two steps here

`TransactionRequest` -> `TypedTransactionRequest` -> `Transaction`

arguably this could also be one step, but having a typed request is still useful

**Review by mattsse — APPROVED** [review]
