### PR TITLE
fix(op-reth): non-deposit txs have depositReceiptVersion=1

### LINKED ISSUE #6604: Non-deposit transactions have depositReceiptVersion=1
### Describe the bug

All non-deposit transactions are stored in the db with depositReceiptVersion=1, but it should be null.

### Steps to reproduce

Find a non-deposit and print it.
```shell
> op-reth get TxHashNumber 0xc76c50bee5cffb7e6a4fea31d0fd360369037d26ff010bec2270916d086aa365
96808239
> op-reth db get Receipts 96808239
```

### Node logs

_No response_

### Platform(s)

Linux (x86)

### What version/commit are you on?

0.1.0-alpha.17

### What database version are you on?

Current database version: 1
Local database version: 1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by 0xZerohero**
Fixes #6604

### CODE REVIEW

File: crates/revm/src/optimism/processor.rs [hunk 1]
```diff
@@ -202,3 +202,199 @@ where
...
+        );
+
+        let tx_deposit = TransactionSigned::from_transaction_and_signature(
+            Transaction::Deposit(reth_primitives::TxDeposit {
+                from: addr,
+                to: TransactionKind::Call(addr),
+                gas_limit: 21_000,
+                ..Default::default()
+            }),
+            Signature::default(),
```
Comment (mattsse) [inline crates/revm/src/optimism/processor.rs:368]:
```suggestion
            Signature::optimism_deposit_tx_signature(),
```

File: crates/revm/src/optimism/processor.rs [hunk 2]
```diff
@@ -179,10 +179,10 @@ where
...
                 // this is only set for post-Canyon deposit transactions.
                 #[cfg(feature = "optimism")]
-                deposit_receipt_version: self
-                    .chain_spec()
-                    .is_fork_active_at_timestamp(Hardfork::Canyon, block.timestamp)
-                    .then_some(1),
+                deposit_receipt_version: (transaction.is_deposit() &&
+                    self.chain_spec()
+                        .is_fork_active_at_timestamp(Hardfork::Canyon, block.timestamp))
+                .then_some(1),
```
Comment (mattsse) [inline crates/revm/src/optimism/processor.rs:185]: @clabby this looks right to me, wdyt?

**Review by mattsse — CHANGES_REQUESTED** [review]
thanks!

this untangles the evm tests from node-ethereum, which is nice.

pta closer look @Rjected

File: crates/revm/src/test_utils.rs [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+}
+
+impl ConfigureEvm for TestEvmConfig {
+    #[cfg(feature = "optimism")]
+    fn evm<'a, DB: Database + 'a>(&self, db: DB) -> Evm<'a, (), DB> {
+        let handler_cfg = HandlerCfg { spec_id: SpecId::LATEST, is_optimism: true };
+        EvmBuilder::default().with_db(db).with_handler_cfg(handler_cfg).build()
+    }
+
+    #[cfg(feature = "optimism")]
```
Comment (Rjected) [inline crates/revm/src/test_utils.rs:164]: does it work if you move the `#[cfg(..)]` above the impl?

File: crates/revm/src/test_utils.rs [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+    type TxMeta = ();
+    #[cfg(feature = "optimism")]
+    type TxMeta = Bytes;
+
+    #[allow(unused_variables)]
+    fn fill_tx_env<T>(tx_env: &mut TxEnv, transaction: T, sender: Address, meta: Self::TxMeta)
+    where
+        T: AsRef<Transaction>,
+    {
+        #[cfg(not(feature = "optimism"))]
```
Comment (Rjected) [inline crates/revm/src/test_utils.rs:123]: i see, so this is needed to remove the dependency on node-ethereum

File: crates/revm/src/processor.rs [hunk 5]
```diff
@@ -364,15 +364,15 @@ where
             self.prune_modes.receipts.map_or(false, |mode| mode.should_prune(block_number, tip))
         {
             receipts.clear();
-            return Ok(())
+            return Ok(());
```
Comment (Rjected) [inline crates/revm/src/processor.rs:367]: let's revert all these semicolon changes

**Review by Rjected — CHANGES_REQUESTED** [review]
mainly have a nit about semicolons, otherwise this looks good to me. when we improve the processor / executor abstraction, the tests can then be moved to the node-ethereum and node-optimism crates. Then we won't need the test config any more

File: crates/revm/src/optimism/processor.rs (hunk 2 above)
Comment (clabby) [reply crates/revm/src/optimism/processor.rs:185]: This does look correct! Working right now because the receipt version isn't included in the RLP if the `deposit_nonce` isn't set. Better to not set the receipt version if the tx isn't a deposit.

**Review by Rjected — APPROVED** [review]
looks good to me, thanks!

**Review by mattsse — APPROVED** [review]
