### PR TITLE
fix: make reth-db compile without default features

### LINKED ISSUE #8477: reth-db does not compile without default features
### Describe the feature

the function signature uses a type that only exists if the feature is enabled because this is a mdbx type

https://github.com/paradigmxyz/reth/blob/ab938e7923882bd2127064b08aa11a3a8b84b1fb/crates/storage/db/src/lib.rs#L153-L156

```
cargo c --no-default-features
```

```
error[E0412]: cannot find type `DatabaseEnv` in this scope
   --> crates/storage/db/src/lib.rs:155:70
    |
155 | pub fn open_db(path: &Path, args: DatabaseArguments) -> eyre::Result<DatabaseEnv> {
    |                                                                      ^^^^^^^^^^^ not found in this scope
```

todo make it compile without mdbx

imo this function should only exist if the mdbx feature is enabled, this would also prevent issues when the crate is used without mdbx feature which would result in a runtime panic 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
closes #8477

This crate is a little bit busted because it mixes the db abstraction with a feature gated implementation.

imo this should be split into `reth-mdbx`

### CODE REVIEW

File: crates/storage/db/src/lib.rs [hunk 1]
```diff
@@ -73,98 +73,17 @@ pub mod tables;
 mod utils;
 pub mod version;
 
-#[cfg(feature = "mdbx")]
 /// Bindings for [MDBX](https://libmdbx.dqdkfa.ru/).
```
Comment (DaniPopes) [inline crates/storage/db/src/lib.rs:76]: move doc to module file

**Review by DaniPopes — APPROVED** [review]
