### PR TITLE
dev: use U64 for `transaction_index`

### LINKED ISSUE #4260: bug: Forge scripts fail when `TransactionReceipt` field `transaction_index` is set to `None`
### Issue
Currently in our RPC implementation, we are setting the [`transaction_index`](https://github.com/kkrt-labs/kakarot-rpc/blob/f2ca11e31f3d5042b28274ab8eca800857bad998/crates/core/src/models/transaction_receipt.rs#L109) to `None`. When we run forge scripts against it, we are getting deserialization errors as it gets serialized to `null`

```shell
Deserialization Error: invalid type: null, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 8] bytes at line 1 column 111. Response: 
{
  "transactionHash": "0x03ce61d5642cbb216ce62dbabdc5ad84c290760dbbc138cd9683e97c8e452949",
  "transactionIndex": null,
  "blockHash": "0x02c9e63a66f5b91714f9b132df3cce6da9866e5c1d6ee54598c555a202b2101b",
  "blockNumber": "0xe",
  "from": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
  "to": null,
  "cumulativeGasUsed": "0xf4240",
  "gasUsed": "0x7a120",
  "contractAddress": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": "0x1",
  "effectiveGasPrice": "0xf4240",
  "type": "0x0"
}
```

### Possible Solution
This can be added to some fields that expect an Option type
`#[serde(skip_serializing_if = "Option::is_none")]`

### Steps to reproduce

1. Clone Kakarot RPC repo `git clone https://github.com/kkrt-labs/kakarot-rpc.git`
2. `make build-kakarot`
3. `make katana-rpc-up`
4. Run `forge script scripts/PlainOpcodes.s.sol --rpc-url http://127.0.0.1:3030 --broadcast`

### Node logs

_No response_

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

fb710e5

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by ftupas**
Hello, this smol pr does the following
- ~add skipping of serialization for `transaction_index` and `to`~
- use U64 for `transaction_index`
- resolve #4260

### CODE REVIEW

File: crates/rpc/rpc-types/src/eth/transaction/receipt.rs [hunk 1]
```diff
@@ -9,14 +9,16 @@ pub struct TransactionReceipt {
...
     /// Hash of the block this transaction was included within.
     pub block_hash: Option<H256>,
     /// Number of the block this transaction was included within.
     pub block_number: Option<U256>,
     /// Address of the sender
     pub from: Address,
-    /// Address of the receiver. null when its a contract creation transaction.
+    /// Address of the receiver. None when it's a contract creation transaction.
+    #[serde(skip_serializing_if = "Option::is_none")]
     pub to: Option<Address>,
```
Comment (mattsse) [inline crates/rpc/rpc-types/src/eth/transaction/receipt.rs:22]: I think this should be null for creations, but it could be that some clients differ

File: crates/rpc/rpc-types/src/eth/transaction/receipt.rs [hunk 2]
```diff
@@ -9,14 +9,16 @@ pub struct TransactionReceipt {
     /// Transaction Hash.
     pub transaction_hash: Option<H256>,
     /// Index within the block.
+    #[serde(skip_serializing_if = "Option::is_none")]
     pub transaction_index: Option<U256>,
```
Comment (mattsse) [inline crates/rpc/rpc-types/src/eth/transaction/receipt.rs:13]: this should actually not be an Option at all.

so we should change this to U64 probably

**Review by mattsse — CHANGES_REQUESTED** [review]
index should always be set in receipt and I believe it is always set by reth.

apparently, some clients include to: null, some skip it, I'd like to keep null

**Comment by ftupas** [comment]
> index should always be set in receipt and I believe it is always set by reth.
> 
> apparently, some clients include to: null, some skip it, I'd like to keep null

Gotcha, thanks for the review! I've updated the pr to use u64 and remove the skip

File: crates/rpc/rpc-types/src/eth/transaction/receipt.rs [hunk 3]
```diff
@@ -9,7 +9,7 @@ pub struct TransactionReceipt {
     /// Transaction Hash.
     pub transaction_hash: Option<H256>,
     /// Index within the block.
-    pub transaction_index: Option<U256>,
+    pub transaction_index: u64,
```
Comment (mattsse) [inline crates/rpc/rpc-types/src/eth/transaction/receipt.rs:12]: this should be U64 because should be hex

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/rpc/rpc-types/src/eth/transaction/receipt.rs (hunk 3 above)
Comment (ftupas) [reply crates/rpc/rpc-types/src/eth/transaction/receipt.rs]: Gotcha makes sense, thanks! Just changed it to U64 🙂

File: crates/rpc/rpc/src/eth/api/transactions.rs [hunk 4]
```diff
@@ -712,7 +712,7 @@ where
                 return match signer.sign_transaction(request, from) {
                     Ok(tx) => Ok(tx),
                     Err(e) => Err(e.into()),
-                }
+                };
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/api/transactions.rs:715]:
```suggestion
                }
```

File: crates/rpc/rpc/src/eth/api/transactions.rs [hunk 5]
```diff
@@ -740,7 +740,7 @@ where
                     block.header.number,
                     block.header.base_fee_per_gas,
                     index.into(),
-                )))
+                )));
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/api/transactions.rs:743]:
```suggestion
                )))
```

**Review by mattsse — APPROVED** [review]
