### PR TITLE
fix: only terminate the stream if range is empty

### LINKED ISSUE #13279: Backfill stream returns after first iteration when parallelism is set to 1
### Describe the bug

Not sure if it's expected but I was trying to use parallelism = 1 in a backfill job and in that case, the stream ends after returning a single chunk, instead of continuing executing the next chunk in the full backfill range.

### Steps to reproduce

Simplest reproduction I've found is in the [test_batch](https://github.com/paradigmxyz/reth/blob/v1.1.3/crates/exex/exex/src/backfill/stream.rs#L291) test, if you change the code to:
```rust
let factory = BackfillJobFactory::new(executor.clone(), blockchain_db.clone())
            .with_thresholds(ExecutionStageThresholds { max_blocks: Some(1), ..Default::default() });
        let mut backfill_stream = factory.backfill(1..=2).into_stream();
        let mut chain = backfill_stream.next().await.unwrap().unwrap();
        chain.execution_outcome_mut().state_mut().reverts.sort();

        assert!(chain.blocks_iter().eq(&blocks[0..1]));

        // expect no more blocks
        assert!(backfill_stream.next().await.is_none());
```
so backfilling one block at a time it fails because `assert!(backfill_stream.next().await.is_none())` is not none (as expected) however when using
```rust
let factory = BackfillJobFactory::new(executor.clone(), blockchain_db.clone())
            .with_thresholds(ExecutionStageThresholds { max_blocks: Some(1), ..Default::default() })
            .with_stream_parallelism(1);
        let mut backfill_stream = factory.backfill(1..=2).into_stream();
        let mut chain = backfill_stream.next().await.unwrap().unwrap();
        chain.execution_outcome_mut().state_mut().reverts.sort();

        assert!(chain.blocks_iter().eq(&blocks[0..1]));

        // expect no more blocks
        assert!(backfill_stream.next().await.is_none());
```
so adding the stream parallelism 1,`next()` returns none, ending the stream

### Node logs

```text
2024-12-10T19:22:57.969204Z DEBUG exex::backfill: Executing block range range=0..=499999
2024-12-10T19:23:16.131201Z DEBUG exex::backfill: Finished executing block range range=0..=499999 block_fetch=2.753609197s execution=15.289312944s throughput="1.89 Ggas/second"
(and then the stream returns)
```

### Platform(s)

_No response_

### Container Type

Not running in a container

### What version/commit are you on?

v1.1.3

### What database version are you on?

2

### Which chain / network are you on?

dev

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
closes https://github.com/paradigmxyz/reth/issues/13279

@shekhirin this fixes a logic bug that would terminate the entire stream after the first task because we'd end up

here https://github.com/paradigmxyz/reth/blob/7610cb4cf3f227323b8f4f3d8e71f77b7405c0dc/crates/exex/exex/src/backfill/stream.rs#L113-L113 

but the range can still have blocks

perhaps there's a nicer way to solve this

### CODE REVIEW

File: crates/exex/exex/src/backfill/stream.rs [hunk 1]
```diff
@@ -157,33 +156,44 @@ where
...
+            }
+
+            let res = ready!(this.poll_next_task(cx));
+
+            if res.is_some() {
+                return Poll::Ready(res);
+            }
+
+            if this.range.peek().is_none() {
+                // only terminate the stream if there are blocks to process
```
Comment (shekhirin) [inline crates/exex/exex/src/backfill/stream.rs:193]:
```suggestion
                // only terminate the stream if there are no more blocks to process
```

File: crates/exex/exex/src/backfill/stream.rs [hunk 2]
```diff
@@ -157,33 +156,44 @@ where
...
+                this.push_back(job);
+            }
+
+            let res = ready!(this.poll_next_task(cx));
+
+            if res.is_some() {
+                return Poll::Ready(res);
+            }
+
+            if this.range.peek().is_none() {
```
Comment (shekhirin) [inline crates/exex/exex/src/backfill/stream.rs:192]: just https://doc.rust-lang.org/std/ops/struct.Range.html#method.is_empty should work i think?

**Review by shekhirin — COMMENTED** [review]
makes sense to me, minor comments

**Review by shekhirin — APPROVED** [review]
