### PR TITLE
fix(txpool): differentiate pool error variants

### LINKED ISSUE #2006: Treat DB related validation errors as non fatal
### Describe the feature

rn we're treating all failed tx imports as bad messages:

https://github.com/paradigmxyz/reth/blob/b310103bddf5138533a1bb1cba67a90f8186faca/crates/net/network/src/transactions.rs#L525-L525

This is not necessarily the case, as there may be issues such as DB errors that should not result in penalizing peers.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
Closes #2006

only penalize peers if the tx was actually bad and the insert error was not caused by something else (like db error) etc.

### CODE REVIEW

File: crates/transaction-pool/src/error.rs [hunk 1]
```diff
@@ -37,13 +37,56 @@ impl PoolError {
...
+    /// [InvalidPoolTransactionError]) and can be caused by the current state of the transaction
+    /// pool. For example the transaction pool is already full or the error was caused my an
+    /// internal error, such as database errors.
+    ///
+    /// This function returns true only if the transaction will never make it into the pool because
+    /// its composition is invalid and the original sender should have detected this as well. This
+    /// is used to determine whether the original sender should be penalized for sending an
+    /// erroneous transaction.
+    #[inline]
+    pub fn is_bad_transaction(&self) -> bool {
```
Comment (Rjected) [inline crates/transaction-pool/src/error.rs:61]: Nice comment 👍

**Review by Rjected — APPROVED** [review]
