### PR TITLE
Fix code spell lint in CI

### LINKED ISSUE #8587: `make lint` fails
### Describe the bug

If `make pr` is executed we can see that make lint-codespell fails:

```sh
$ make pr  
...
...
...
codespell
./crates/stages/stages/src/stages/headers.rs:355: checkpoin ==> checkpoint
./crates/storage/provider/src/providers/static_file/writer.rs:596: comitted ==> committed
./crates/blockchain-tree/src/blockchain_tree.rs:1193: childs ==> children, child's
./crates/blockchain-tree/src/metrics.rs:91: childs ==> children, child's
./crates/blockchain-tree/src/metrics.rs:119: childs ==> children, child's
./crates/node/builder/src/components/builder.rs:284: crated ==> created
./crates/rpc/rpc-types-compat/src/engine/payload.rs:46: extremelly ==> extremely
./examples/exex/rollup/rollup_abi.json:1: doens't ==> doesn't
./examples/exex/rollup/rollup_abi.json:1: transctions ==> transactions
./examples/exex/rollup/rollup_abi.json:1: doens't ==> doesn't
./examples/exex/rollup/rollup_abi.json:1: transctions ==> transactions
./examples/exex/rollup/rollup_abi.json:1: doens't ==> doesn't
make[2]: *** [lint-codespell] Error 65
make[1]: *** [lint] Error 2
make: *** [pr] Error 2
```

I suppose CI should have caught these.

### Steps to reproduce

1. Checkout main
2. Run `make pr` or `make lint-codespell`

### Node logs

_No response_

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

Commit `4c6e5be`

### What database version are you on?

not relevant

### Which chain / network are you on?

not relevant

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by nishuyes**
Fix #8587.

Fix the code spell check in CI. Fix existing typo.

### CODE REVIEW

**Review by shekhirin — APPROVED** [review]
LGTM, thanks! Also nice catch regarding the checkout of repo in CI.

File: crates/blockchain-tree/src/metrics.rs [hunk 1]
```diff
@@ -116,7 +116,7 @@ struct MakeCanonicalMetrics {
     revert_canonical_chain_from_database: Histogram,
     /// Duration of the insert old canonical chain action.
     insert_old_canonical_chain: Histogram,
-    /// Duration of the clear trie updates of other childs chains after fork choice update action.
+    /// Duration of the clear trie updates of other children chains after fork choice update action.
```
Comment (shekhirin) [inline crates/blockchain-tree/src/metrics.rs:119]:
```suggestion
    /// Duration of the clear trie updates of other children chains after fork choice update
    /// action.
```
