### PR TITLE
fix: ensure backfill and persistence dont happen at the same time

### LINKED ISSUE #9893: ensure backfill only starts if persistence task finished
Currently it's possible that we trigger a backfillrun while we're currently persisting data.

we need to delay emitting an event to start backfill sync until the persistence job finishes

### PR DESCRIPTION
**Pull request by mattsse**
closes #9893

this ensures
* no new backfill while we're persisting block
* dont persist blocks during backfill sync

### CODE REVIEW

File: crates/engine/tree/src/tree/mod.rs [hunk 1]
```diff
@@ -709,6 +717,11 @@ where
     /// Returns true if the canonical chain length minus the last persisted
     /// block is greater than or equal to the persistence threshold.
```
Comment (fgimenez) [inline crates/engine/tree/src/tree/mod.rs:718]:
```suggestion
    /// block is greater than or equal to the persistence threshold and
    /// backfill is not running.
```

**Review by fgimenez — APPROVED** [review]
awesome, small doc nit
