### PR TITLE
fix: advance buffer after enr decode

### LINKED ISSUE #482: Add native reth_rlp decoding for ENR
### Describe the feature

currently the `reth_rlp::Decode` impl for ENR does not advance the buffer correctly.

Ideally we have native `reth_rlp::Decode` instead of delegating to `rlp` crate

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TechieBoy**
After ENR has been decoded, advance the buffer.
Fixes #482

### CODE REVIEW

File: crates/common/rlp/src/decode.rs [hunk 1]
```diff
@@ -638,14 +644,17 @@ mod tests {
...
         use std::net::Ipv4Addr;
 
-        let valid_record = hex!("f884b8407098ad865b00a582051940cb9cf36836572411a47278783077011599ed5cd16b76f2635f4e234738f30813a89eb9137e3e3df5266e3a1f11df72ecf1145ccb9c01826964827634826970847f00000189736563703235366b31a103ca634cae0d49acb401d8a4c6b6fe8c55b70d115bf400769cc1400f3258cd31388375647082765f");
+        let mut valid_record = &hex!("f884b8407098ad865b00a582051940cb9cf36836572411a47278783077011599ed5cd16b76f2635f4e234738f30813a89eb9137e3e3df5266e3a1f11df72ecf1145ccb9c01826964827634826970847f00000189736563703235366b31a103ca634cae0d49acb401d8a4c6b6fe8c55b70d115bf400769cc1400f3258cd31388375647082765f")[..];
         let signature = hex!("7098ad865b00a582051940cb9cf36836572411a47278783077011599ed5cd16b76f2635f4e234738f30813a89eb9137e3e3df5266e3a1f11df72ecf1145ccb9c");
         let expected_pubkey =
             hex!("03ca634cae0d49acb401d8a4c6b6fe8c55b70d115bf400769cc1400f3258cd3138");
 
-        let enr = Enr::<SecretKey>::decode(&mut &valid_record[..]).unwrap();
+        let enr = Enr::<SecretKey>::decode(&mut valid_record).unwrap();
```
Comment (rkrasiuk) [inline crates/common/rlp/src/decode.rs:652]: smol nit: preserve `valid_record` as it was and
```rust
let mut valid_record_buf = valid_record.as_slice();
let enr = Enr::<SecretKey>::decode(&mut valid_record_buf).unwrap();

assert!(valid_record_buf.is_empty());
```

**Review by rkrasiuk — APPROVED** [review]
lgtm

**Review by mattsse — APPROVED** [review]
pending nit

**Review by mattsse — APPROVED** [review]
tysm!
