### PR TITLE
fix(sync): return control from `HeaderStage` back to pipeline

### LINKED ISSUE #607: Headers stage commits when the full range is synced
### Describe the bug

We used to (as a workaround) commit directly in the header stage, but since it was no longer needed, it was removed again.

However, the header stage still uses `commit_threshold` to chunk the header stream:

And not as an exit condition, which effectively means that the header stage will run, and not hand control over to the pipeline for checkpointing until the full range is synced.

Instead, the stream should not be chunked as we can validate the headers one-by-one as they come in and write them to the transaction. This simplifies the stage a bit.

Once we have either (1) gotten all of the headers we want (i.e. synced the full range) or (2) received `commit_threshold` headers, we should return control to the pipeline. In the first case we should return with `done: true` (signifying the pipeline can progress), in the second case we should return with `done: false` (signifying we have more headers to sync)

### Steps to reproduce

Run the node, setting `--debug.tip` to some arbitrarily large number (e.g. block 2m)

### Node logs

_No response_

### Platform(s)

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by TechieBoy**
We only write commit_threshold blocks after fetching them with the downloader.

Closes #607

### CODE REVIEW

**Comment by TechieBoy** [comment]
I think we can make this more efficient by only streaming  `head + commit_threshold` blocks instead of `head + fork choice tip`, or by downloading from head onwards instead of downloading in reverse order from tip??

**Comment by rkrasiuk** [comment]
thanks for the PR @TechieBoy! unfortunately, we cannot download headers onwards, because of long-range attack (refer to [the headers section](https://github.com/paradigmxyz/reth/tree/main/book/stages#headerstage) of the book for more details). it's better to trust the CL and walk the canonical chain from the tip to prevent peers from advertising bad blocks to us. we are planning to add some onward logic for chains that don't have EL/CL separation and possibly for pre-merge headers

File: crates/stages/src/stages/headers.rs [hunk 1]
```diff
@@ -74,63 +74,57 @@ impl<DB: Database, D: HeaderDownloader, C: Consensus, H: HeadersClient, S: Statu
...
+                self.validate_header_response(&res)?;
+
+                let write_progress = self
+                    .write_headers::<DB>(tx, res, self.commit_threshold)
+                    .await?
+                    .unwrap_or_default();
+                current_progress = current_progress.max(write_progress);
+                // Write total difficulty values after headers have been inserted
+                debug!(target: "sync::stages::headers", head = ?head.hash(), "Writing total difficulty");
+                self.write_td::<DB>(tx, &head)?;
```
Comment (rkrasiuk) [inline crates/stages/src/stages/headers.rs:105]: this is not correct: total difficulty has to be written onwards since it's a cumulative sum based on the previous value

**Review by rkrasiuk — CHANGES_REQUESTED** [review]

File: crates/stages/src/stages/headers.rs [hunk 2]
```diff
@@ -74,63 +74,57 @@ impl<DB: Database, D: HeaderDownloader, C: Consensus, H: HeadersClient, S: Statu
...
+
+                let done = current_progress == max_received_block_number;
```
Comment (rkrasiuk) [inline crates/stages/src/stages/headers.rs:107]: this check will never be true since the stream never returns the local head (current_progress)

**Comment by TechieBoy** [comment]
> we cannot download headers onwards, because of long-range attack

Makes sense, but we do have write the headers to db from head onwards, correct? Otherwise the `stage_progress` value in `ExecOutput` will stay the same until the entire stage is done. That is what I am doing here:
https://github.com/paradigmxyz/reth/blob/92f4bb543e6f07adb2c1facfa37e6373d1fa0655/crates/stages/src/stages/headers.rs#L98-L102

Or do you want me to change it so it writes to db from tip downwards?

**Comment by rkrasiuk** [comment]
> we do want to write the headers to db from head onwards
Since we are not appending anymore, it shouldn't matter really. 
> stage_progress value in ExecOutput will stay the same until the entire stage is done
that's the desired behavior. otherwise we wouldn't know the local "head"

File: crates/stages/src/stages/headers.rs [hunk 3]
```diff
@@ -74,63 +74,59 @@ impl<DB: Database, D: HeaderDownloader, C: Consensus, H: HeadersClient, S: Statu
...
-                            return Err(StageError::Validation { block: stage_progress, error })
-                        }
-                        error => {
-                            error!(target: "sync::stages::headers", ?error, "Unexpected error");
-                            return Err(StageError::Recoverable(error.into()))
-                        }
+        // The downloader returns the headers in descending order starting from the tip
+        // down to the local head (latest block in db)
+        let downloaded_headers: Result<Vec<SealedHeader>, DownloadError> =
+            self.downloader.stream(head.clone(), tip).try_collect().await;
```
Comment (gakonst) [inline crates/stages/src/stages/headers.rs:87]: Is this right? Doesn't this mean that we'll take all the headers from the tip to the head and keep them in memory? And that can be the entire chain the first time we run this, which is something we wanted to avoid? Should this stream instead `.take(self.commit_threshold)` headers before collecting?

File: crates/stages/src/stages/headers.rs [hunk 4]
```diff
@@ -74,63 +74,59 @@ impl<DB: Database, D: HeaderDownloader, C: Consensus, H: HeadersClient, S: Statu
...
+                info!(target: "sync::stages::headers", len = res.len(), "Received headers");
+                self.metrics.headers_counter.increment(res.len() as u64);
+                let max_received_block_number = res[0].number;
+
+                // Perform basic response validation
+                self.validate_header_response(&res)?;
+
+                // Write a maximum of `commit_threshold` headers, starting from local head onwards
+                let write_progress = self
+                    .write_headers::<DB>(tx, res, self.commit_threshold)
```
Comment (gakonst) [inline crates/stages/src/stages/headers.rs:100]: See my note above on `self.commit_threshold`

**Review by gakonst — CHANGES_REQUESTED** [review]

File: crates/stages/src/stages/headers.rs (hunk 3 above)
Comment (TechieBoy) [reply crates/stages/src/stages/headers.rs:87]: I assumed that we want to write to db from head onwards and update `stage_progress` after every execution. Will change this.

**Comment by TechieBoy** [comment]
- Take only `commit_threhold` headers from head.
- Use headers stored in local db + fork choice state to check if we haved finished the stage.

File: crates/stages/src/stages/headers.rs [hunk 5]
```diff
@@ -73,63 +73,60 @@ impl<DB: Database, D: HeaderDownloader, C: Consensus, H: HeadersClient, S: Statu
...
+                // Write the headers to db
+                self.write_headers::<DB>(tx, res).await?.unwrap_or_default();
+
+                if let Some(last_header_num) = self.has_reached_sync(tx, current_progress).await? {
+                    // Update total difficulty values after we have reached fork choice
+                    debug!(target: "sync::stages::headers", head = ?head.hash(), "Writing total difficulty");
+                    self.write_td::<DB>(tx, &head)?;
+                    return Ok(ExecOutput { stage_progress: last_header_num, done: true })
+                } else {
+                    return Ok(ExecOutput { stage_progress: current_progress, done: false })
```
Comment (rkrasiuk) [inline crates/stages/src/stages/headers.rs:109]: Then simply query if it's done and lookup last inserted header only if needed
```suggestion
            if self.is_stage_done(tx, current_progress)? {
                    // Update total difficulty values after we have reached fork choice
                    debug!(target: "sync::stages::headers", head = ?head.hash(), "Writing total difficulty");
                    self.write_td::<DB>(tx, &head)?;

                    // Look up the current stage progress in the database
                    let stage_progress = current_progress.max(
                        tx.cursor::<tables::CanonicalHeaders>()?
                            .last()?
                            .map(|(num, _)| num)
                            .unwrap_or_default(),
                    );
                    Ok(ExecOutput { stage_progress, done: true })
                } else {
                    Ok(ExecOutput { stage_progress: current_progress, done: false })
```

Comment (rkrasiuk) [inline crates/stages/src/stages/headers.rs:109]: Then simply query if it's done and lookup last inserted header only if needed
```suggestion
            if self.is_stage_done(tx, current_progress)? {
                    // Update total difficulty values after we have reached fork choice
                    debug!(target: "sync::stages::headers", head = ?head.hash(), "Writing total difficulty");
                    self.write_td::<DB>(tx, &head)?;

                    // Look up the current stage progress in the database
                    let stage_progress = current_progress.max(
                        tx.cursor::<tables::CanonicalHeaders>()?
                            .last()?
                            .map(|(num, _)| num)
                            .unwrap_or_default(),
                    );
                    Ok(ExecOutput { stage_progress, done: true })
                } else {
                    Ok(ExecOutput { stage_progress: current_progress, done: false })
```

**Review by rkrasiuk — CHANGES_REQUESTED** [review]

**Review by rkrasiuk — APPROVED** [review]
lgtm, great job!

**Comment by TechieBoy** [comment]
> lgtm, great job!

👍🏻 Thanks for being so patient and helpful and answering all my questions!

File: crates/stages/src/stages/headers.rs [hunk 6]
```diff
@@ -166,6 +169,19 @@ impl<D: HeaderDownloader, C: Consensus, H: HeadersClient, S: StatusUpdater>
         Ok(())
     }
 
+    async fn is_stage_done<DB: Database>(
```
Comment (gakonst) [inline crates/stages/src/stages/headers.rs:172]: @onbjerg PTAL

**Review by gakonst — APPROVED** [review]
Good from me - pending @onbjerg approval

**Comment by rkrasiuk** [comment]
lgtm, merging
