### PR TITLE
fix: set fees to zero if not provided

### LINKED ISSUE #1907: `eth_call` returns `insufficient funds` in call-simple-transfer test
### Describe the bug

The `rpc-compat` test `eth_call/call-simple-transfer` returns insufficient funds:

```diff
>>  {"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"from":"0xaa00000000000000000000000000000000000000","gas":"0x186a0","to":"0x0100000000000000000000000000000000000000"},"latest"]}
<<  {"jsonrpc":"2.0","error":{"code":-32003,"message":"Insufficient funds for gas * price + value"},"id":1}
response differs from expected:
 {
-  "error": {
-    "code": -32003,
-    "message": "Insufficient funds for gas * price + value"
-  },
   "id": 1,
   "jsonrpc": "2.0"
+  "result": "0x"
 }
```

### Steps to reproduce

Run hive (#851):
```
./hive --client reth --sim ethereum/rpc-compat --sim.limit "/eth_call/call-simple-transfer"
```

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
This sets the base fee to zero in `eth_call`, and sets fees to zero if none are provided in the request.

The logic from geth that we should try to emulate for this is here:
https://github.com/ethereum/go-ethereum/blob/ee8e83fa5f6cb261dad2ed0a7bbcde4930c41e6c/internal/ethapi/transaction_args.go#L228-L257

Called here for geth's `DoCall`:
https://github.com/ethereum/go-ethereum/blob/ee8e83fa5f6cb261dad2ed0a7bbcde4930c41e6c/internal/ethapi/api.go#L981

Fixes #1907

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
lgtm

File: crates/rpc/rpc/src/eth/api/call.rs [hunk 1]
```diff
@@ -86,11 +87,18 @@ where
             apply_state_overrides(state_overrides, &mut db)?;
         }
 
+        // The basefee should be ignored for eth_call
+        // See:
+        // <https://github.com/ethereum/go-ethereum/blob/ee8e83fa5f6cb261dad2ed0a7bbcde4930c41e6c/internal/ethapi/api.go#L985>
+        env.block.basefee = U256::ZERO;
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/api/call.rs:93]: TIL

**Review by mattsse — APPROVED** [review]
nice fix!
