### PR TITLE
fix(tree): make state methods work for historical blocks

### LINKED ISSUE #8305: Failing hive engine-api tests
#### Inconsistent Head in ForkchoiceState

- [ ]  test=60 name="Inconsistent Head in ForkchoiceState (Cancun) (reth)"

#### Invalid Missing Ancestor

- [ ]  test=135 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=False, Invalid P9 (Cancun) (reth)"
- [ ]  test=136 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (reth)"
- [ ]  test=137 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=True, Invalid P9 (Cancun) (reth)"
- [ ]  test=138 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (reth)"
- [ ]  test=141 name="Invalid Missing Ancestor Syncing ReOrg, GasLimit, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (reth)"
- [ ]  test=145 name="Invalid Missing Ancestor Syncing ReOrg, Timestamp, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (reth)"

#### Invalid NewPayload

- [ ]  test=84 name="Invalid NewPayload, StateRoot, Syncing=True, EmptyTxs=True, DynFeeTxs=False (Cancun) (reth)"
- [ ]  test=85 name="Invalid NewPayload, StateRoot, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"
- [ ]  test=97 name="Invalid NewPayload, PrevRandao, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"

### Additional context

_No response_
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/6217
- [ ] https://github.com/paradigmxyz/reth/issues/7146
```

### LINKED ISSUE #10875: Hive failures on engine suites with experimental flag
### Describe the feature

After #10717 was merged we started getting new failures in the hive executions with `--experimental.engine`.  There was an initial attempt to fix them #10837 but we are still getting errors https://github.com/paradigmxyz/reth/actions/runs/10840604395

### Additional context

_No response_

### LINKED ISSUE #11251: bug(engine): persisted executed block retrieval
## Description

Currently, new tree constructs executed persisted blocks by calling `provider.get_state`

https://github.com/paradigmxyz/reth/blob/5f9c43cc15720a9ebf9afbc4ffaa4fb0cfc112c6/crates/engine/tree/src/tree/mod.rs#L1496-L1504

However, this function can only retrieve the state for blocks at tip as it only looks at plain state tables

https://github.com/paradigmxyz/reth/blob/5f9c43cc15720a9ebf9afbc4ffaa4fb0cfc112c6/crates/storage/provider/src/providers/database/provider.rs#L827-L832

### PR DESCRIPTION
**Pull request by Rjected**
This fixes https://github.com/paradigmxyz/reth/issues/11251 by allowing fetching state from disk OR from in-memory state.

Closes: #10875
Closes: #8305

### CODE REVIEW

File: crates/chain-state/src/in_memory.rs [hunk 1]
```diff
@@ -494,6 +504,23 @@ impl CanonicalInMemoryState {
...
+    pub fn state_provider_from_state(
+        &self,
+        state: &BlockState,
+        historical: StateProviderBox,
+    ) -> MemoryOverlayStateProvider {
+        trace!(target: "providers::blockchain", state_hash=?state.hash(), "Constructing memory overlay state provider from state");
+        let in_memory: Vec<_> =
+            state.chain().into_iter().map(|block_state| block_state.block()).collect();
+
+        trace!(target: "providers::blockchain", first_mem_state=?in_memory.first().map(|block| block.block.num_hash()), last_mem_state=?in_memory.last().map(|block| block.block.num_hash()), "Constructed memory overlay state provider from state");
```
Comment (rkrasiuk) [inline crates/chain-state/src/in_memory.rs:520]: these two traces can be merged

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 2]
```diff
@@ -122,6 +128,171 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+        if range.is_empty() {
+            return Ok(None)
+        }
+        let start_block_number = *range.start();
+        let end_block_number = *range.end();
+
+        // We are not removing block meta as it is used to get block changesets.
+        let mut block_bodies = Vec::new();
+        for block_num in range.clone() {
+            let Some(block_body) = self.block_body_indices(block_num)? else { break };
```
Comment (rkrasiuk) [inline crates/storage/provider/src/providers/blockchain_provider.rs:165]: should we error here instead of providing only partial response to range query?

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 3]
```diff
@@ -122,6 +128,171 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+
+        // get transaction receipts
+        let Some(from_transaction_num) = block_bodies.first().map(|bodies| bodies.1.first_tx_num())
+        else {
+            return Ok(None)
+        };
+        let Some(to_transaction_num) = block_bodies.last().map(|bodies| bodies.1.last_tx_num())
+        else {
+            return Ok(None)
+        };
```
Comment (rkrasiuk) [inline crates/storage/provider/src/providers/blockchain_provider.rs:177]: nit
```suggestion
        let Some(from_transaction_num) = block_bodies.first().map(|body| body.1.first_tx_num())
        else {
            return Ok(None)
        };
        let Some(to_transaction_num) = block_bodies.last().map(|body| body.1.last_tx_num())
        else {
            return Ok(None)
        };
```

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 4]
```diff
@@ -122,6 +128,171 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+    ///     2. Take the new value from the plain state
+    ///     3. Save the old value to the local state
+    /// 4. While iterating over the changeset tables, if we encounter an account/storage slot we
+    ///    have seen before we:
+    ///     1. Take the old value from the changeset
+    ///     2. Take the new value from the local state
+    ///     3. Set the local state to the value in the changeset
+    ///
+    /// If the range is empty, or there are no blocks for the given range, then this returns `None`.
+    pub fn get_state(
```
Comment (rkrasiuk) [inline crates/storage/provider/src/providers/blockchain_provider.rs:152]: akin to checks in historical provider this method should check lowest available history blocks in case of a pruned node

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 5]
```diff
@@ -122,6 +128,171 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+        // iterate over block body and create ExecutionResult
+        let mut receipt_iter =
+            self.receipts_by_tx_range(from_transaction_num..=to_transaction_num)?.into_iter();
+
+        let mut receipts = Vec::with_capacity(block_bodies.len());
+        // loop break if we are at the end of the blocks.
+        for (_, block_body) in block_bodies {
+            let mut block_receipts = Vec::with_capacity(block_body.tx_count as usize);
+            for _ in block_body.tx_num_range() {
+                if let Some(receipt) = receipt_iter.next() {
```
Comment (rkrasiuk) [inline crates/storage/provider/src/providers/blockchain_provider.rs:204]: should be a hard error if we don't have all necessary receipts to construct an `ExecutedBlock`

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 6]
```diff
@@ -122,6 +128,171 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+                    block_receipts.push(Some(receipt));
+                }
+            }
+            receipts.push(block_receipts);
+        }
+
+        Ok(Some(ExecutionOutcome::new_init(
+            state,
+            reverts,
+            Vec::new(),
```
Comment (rkrasiuk) [inline crates/storage/provider/src/providers/blockchain_provider.rs:214]:
```suggestion
            // We skip new contracts since we never delete them from the database
            Vec::new(),
```

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 7]
```diff
@@ -122,6 +128,171 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+            receipts.into(),
+            start_block_number,
+            Vec::new(),
```
Comment (rkrasiuk) [inline crates/storage/provider/src/providers/blockchain_provider.rs:217]: what should we do with requests here?

**Review by rkrasiuk — CHANGES_REQUESTED** [review]

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 8]
```diff
@@ -122,6 +128,172 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+        let mut storage_changeset = Vec::new();
+        for block_num in range {
+            let changeset = self.storage_changeset(block_num)?;
+            storage_changeset.extend(changeset);
+        }
+
+        let (state, reverts) =
+            self.populate_bundle_state(account_changeset, storage_changeset, end_block_number)?;
+
+        // iterate over block body and create ExecutionResult
```
Comment (fgimenez) [inline crates/storage/provider/src/providers/blockchain_provider.rs:195]: this comment seems to be out of place?
```suggestion
```

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 9]
```diff
@@ -122,6 +128,172 @@ impl<N: ProviderNodeTypes> BlockchainProvider2<N> {
...
+    /// storage and account changesets.
+    fn populate_bundle_state(
+        &self,
+        account_changeset: Vec<(u64, AccountBeforeTx)>,
+        storage_changeset: Vec<(BlockNumberAddress, StorageEntry)>,
+        block_range_end: BlockNumber,
+    ) -> ProviderResult<(BundleStateInit, RevertsInit)> {
+        // iterate previous value and get plain state value to create changeset
+        // Double option around Account represent if Account state is know (first option) and
+        // account is removed (Second Option)
```
Comment (fgimenez) [inline crates/storage/provider/src/providers/blockchain_provider.rs:233]: same, seems outdated?
```suggestion
```

**Review by fgimenez — APPROVED** [review]
awesome work, lgtm!

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 2 above)
Comment (Rjected) [reply crates/storage/provider/src/providers/blockchain_provider.rs:165]: I think so, although current range methods on the db provider provide partial response over erroring, so we may want to refactor those separately

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 7 above)
Comment (Rjected) [reply crates/storage/provider/src/providers/blockchain_provider.rs:218]: We should really be fetching them using the `RequestsProvider`, but that method requires a timestamp, which I'm not sure how to deal with yet

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 5 above)
Comment (Rjected) [reply crates/storage/provider/src/providers/blockchain_provider.rs]: we error now here

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 4 above)
Comment (Rjected) [reply crates/storage/provider/src/providers/blockchain_provider.rs:152]: Now done in `ChangeSetReader` and `StorageChangeSetReader`, ensuring we don't create a db provider without checking prune checkpoints first: https://github.com/paradigmxyz/reth/pull/11265/commits/d7e6542327fe3098cb1e634706ed752fcf2e57eb

**Comment by Rjected** [comment]
> might be wrong but this feels unsafe when it touches in-memory ranges.

When this is used outside of the tree, yes, calling `get_state` in a loop could result in different views. I think most of the provider methods suffer from this. In those cases we need to provide a safer API that is aware of the `CanonicalInMemoryState` locks. For example, right now it is unsafe to call most combinations of providers in sequence. For a safer API, do we want to put the provider methods behind a lock? Similar to how the `DatabaseProvider` works:
```rust
let blockchain_provider = BlockchainProvider::new(/* stuff */);
let provider_ro = blockchain_provider.read(); // acquires ro `CanonicalInMemoryState` lock
for block in blocks {
    let state = provider_ro.get_state(block);
}
```

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 7 above)
Comment (mattsse) [reply crates/storage/provider/src/providers/blockchain_provider.rs:200]: whether we actually need to store requests is still tbd so imo this is fine, but please track so we don't forget

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 10]
```diff
@@ -1319,6 +1464,57 @@ impl<N: NodeTypesWithDB> ForkChoiceSubscriptions for BlockchainProvider2<N> {
...
+                .execution_output
+                .bundle
+                .reverts
+                .clone()
+                .into_plain_state_reverts()
+                .storage
+                .into_iter()
+                .flatten()
+                .flat_map(|revert: PlainStorageRevert| {
+                    revert.storage_revert.into_iter().map(move |(key, value)| {
```
Comment (mattsse) [inline crates/storage/provider/src/providers/blockchain_provider.rs:1484]: -.-

**Review by mattsse — CHANGES_REQUESTED** [review]
pending @rkrasiuk

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 7 above)
Comment (Rjected) [reply crates/storage/provider/src/providers/blockchain_provider.rs:200]: https://github.com/paradigmxyz/reth/issues/11437

**Review by mattsse — APPROVED** [review]

File: crates/storage/provider/src/providers/blockchain_provider.rs (hunk 4 above)
Comment (rkrasiuk) [reply crates/storage/provider/src/providers/blockchain_provider.rs:134]: @Rjected a valid point from @joshieDo here. in scope of this function we perform a ton of lookups by block number, but there is no consistency guarantee here

**Review by rkrasiuk — DISMISSED** [review]

File: crates/storage/provider/src/providers/blockchain_provider.rs [hunk 11]
```diff
@@ -1440,28 +1807,23 @@ impl<N: NodeTypesWithDB> ForkChoiceSubscriptions for BlockchainProvider2<N> {
     }
 }
 
+impl<N: ProviderNodeTypes> StorageChangeSetReader for BlockchainProvider2<N> {
+    fn storage_changeset(
+        &self,
+        block_number: BlockNumber,
+    ) -> ProviderResult<Vec<(BlockNumberAddress, StorageEntry)>> {
+        let provider = self.database_provider_ro()?;
+        self.storage_block_changeset_with_provider(block_number, &provider)
```
[the remark this answers is not in the document]
Comment (mattsse) [reply crates/storage/provider/src/providers/blockchain_provider.rs:1816]: for engine usecase this is fine because the engine itself calls this, so for now this is ok.

File: crates/storage/storage-api/src/state.rs [hunk 12]
```diff
@@ -84,10 +84,14 @@ pub trait StateProvider:
 /// Trait implemented for database providers that can be converted into a historical state provider.
 pub trait TryIntoHistoricalStateProvider {
     /// Returns a historical [`StateProvider`] indexed by the given historic block number.
+    ///
+    /// This gives the provider back if creating the historical state provider is not successful.
```
Comment (mattsse) [inline crates/storage/storage-api/src/state.rs:88]:
```suggestion
```

**Review by mattsse — COMMENTED** [review]
is this good to go?

imo the memory concerns that @joshieDo raised are valid but not an issue for the engine, because by the time this is called no disk io should be in progress.
I'd like to get this in and then look how to make it sound

**Review by joshieDo — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
