### PR TITLE
fix(p2p): network sync state

### LINKED ISSUE #2678: Lift SyncStatus update from the pipeline impl and move to consensus engine
### Describe the feature

ref #2669

now that beacon consensus engine controlls sync, it should be responsible for updating the sync status and not the pipeline.

## TODO
* remove syncstatus update from pipeline
* integrate in consensus engine instead

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rkrasiuk**
Closes #2678

Move sync state and head update from the `Pipeline` and `Finish` stage to the `BeaconConsensusEngine`.
In the context of the consensus engine, the network sync state is optimistically assumed as idle, until the pipeline run is triggered.

### <samp>🤖 Generated by Copilot at 9cb9a13</samp>

> _`SyncStateUpdater` is no more, we have a new trait to explore_
> _`NetworkSyncUpdater` is the name, it gives us more power and fame_
> _We simplify the code and reduce the load, we remove the features that we don't need_
> _We refactor and relocate, we make our codebase great_

### <samp>🤖 Generated by Copilot at 9cb9a13</samp>

Refactored the code to use a new `NetworkSyncUpdater` trait to handle network status and sync state updates. Removed unused and outdated code that depended on the old `StatusUpdater` and `SyncStateUpdater` traits. Simplified the code and reduced dependencies in various modules.

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -238,6 +245,9 @@ where
             metrics: Metrics::default(),
         };
 
+        // Optimistically assume that the network state is idle from the start.
+        this.sync_state_updater.update_sync_state(SyncState::Idle);
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:249]: while this is technically true, this could cause some issues if launched without CL because then the pipeline isn't triggered.

this should be moved to a new function that 
calls `sync.set_pipeline_sync_target` and also sets the sync state to syncing.

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/consensus/beacon/src/engine/mod.rs (hunk 1 above)
Comment (rkrasiuk) [reply crates/consensus/beacon/src/engine/mod.rs:249]: what are the issues that can be caused by this call? 

> this should be moved to a new function that
calls sync.set_pipeline_sync_target and also sets the sync state to syncing.

this is already handled in `on_sync_event` fn

Comment (mattsse) [reply crates/consensus/beacon/src/engine/mod.rs:249]: the issue is that if we set it to idle by default and don't have a CL that sends us FCU we will never trigger the pipeline, but the state is still marked at idle.

eth_syncing will be incorrect and txpool wastes resources inserting into the pool

**Review by mattsse — APPROVED** [review]
less generic type bounds 🙏
