### PR TITLE
fix(discv5): fix bug flip byte lookup tgt

### LINKED ISSUE #7763: fix(discv5): flip exact bit in node id
### Describe the feature

Rn FINDNODE target selection in discv5, flips a whole byte. Actually it should flip only the specific bit at the given `kbucket_index` in the local node id. The `bits[kbucket_index + 1..]` should all be random. 

https://github.com/paradigmxyz/reth/blob/d599ce46835891a1afe7970ac8b0cab4efe8b391/crates/net/discv5/src/lib.rs#L535-L556

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
- Flips index 0 (log2distance 1) in lookup target selection. Previously the code was taking log2distance as param, now it takes kbucket index as param to be easier to follow along.
- Fixes flaky test at boundary where log2distance is a multiple of 8

~leaving bit flipping up to~ closes https://github.com/paradigmxyz/reth/issues/7763

### CODE REVIEW

File: crates/net/discv5/src/lib.rs [hunk 1]
```diff
@@ -541,18 +541,14 @@ pub fn get_lookup_target(
...
-        if suffix_byte_offset != 31 {
-            for b in target.iter_mut().take(31).skip(suffix_byte_offset + 1) {
-                *b = rand::random::<u8>();
-            }
-        }
+    let suffix_bit_offset = MAX_KBUCKET_INDEX.saturating_sub(kbucket_index);
+    let suffix_byte_offset = suffix_bit_offset / 8;
+    // todo: flip the precise bit
+    // let rel_suffix_bit_offset = suffix_bit_offset % 8;
+    target[suffix_byte_offset] = !target[suffix_byte_offset];
```
Comment (DaniPopes) [inline crates/net/discv5/src/lib.rs:548]: Closes https://github.com/paradigmxyz/reth/issues/7763

```suggestion
    target[suffix_byte_offset] ^= 1 << (suffix_bit_offset % 8);
```

File: crates/net/discv5/src/lib.rs [hunk 2]
```diff
@@ -541,18 +541,14 @@ pub fn get_lookup_target(
...
+
+    for b in target.iter_mut().skip(suffix_byte_offset + 1) {
+        *b = rand::random::<u8>();
     }
```
Comment (DaniPopes) [inline crates/net/discv5/src/lib.rs:552]:
```suggestion
    rand::thread_rng().fill_bytes(&mut target[suffix_byte_offset..]);
```

File: crates/net/discv5/src/lib.rs [hunk 3]
```diff
@@ -807,9 +803,12 @@ mod tests {
 
     #[test]
     fn select_lookup_target() {
-        // bucket index ceiled to the next multiple of 4
+        // bucket index ceiled to the next multiple of 8
```
Comment (DaniPopes) [inline crates/net/discv5/src/lib.rs:806]: there's `.div_ceil(8)`

File: crates/net/discv5/src/lib.rs (hunk 1 above)
Comment (emhane) [reply crates/net/discv5/src/lib.rs]: this flips other bits too

File: crates/net/discv5/src/lib.rs (hunk 2 above)
Comment (emhane) [reply crates/net/discv5/src/lib.rs]: wouldn't the slice start at `suffix_byte_offset + 1`?

Comment (DaniPopes) [reply crates/net/discv5/src/lib.rs]: yep according to the previous code, typo

Comment (emhane) [reply crates/net/discv5/src/lib.rs]: was also wrong in the issue saw now

File: crates/net/discv5/src/lib.rs (hunk 1 above)
Comment (emhane) [reply crates/net/discv5/src/lib.rs]: here the issue says: should flip *only* the specific bit @DaniPopes

Comment (emhane) [reply crates/net/discv5/src/lib.rs:548]: reverting these suggestions, out of scope

**Review by DaniPopes — APPROVED** [review]
