### PR TITLE
fix: return zero latestValidHash pre-merge

### LINKED ISSUE #1676: `engine_NewPayload` does not respond with the correct `latestValidHash` on incorrect terminal block
We currently do not respond with the correct `latestValidHash` when given a `engine_newPayload` request for a block that does not meet the TTD requirement. This was uncovered from a hive `engine-api` test failure, for the `Invalid Terminal Block in NewPayload` test:
```
Start test (reth): Invalid Terminal Block in NewPayload
Randomness seed: 1678303098
txsHash: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
>> (ced2335b) {"jsonrpc":"2.0","id":1,"method":"engine_newPayloadV1","params":[{"parentHash":"0x67ead97eb79b47a1638659942384143f36ed44275d4182799875ab5a87324055","feeRecipient":"0x0000000000000000000000000000000000000000","stateRoot":"0x84308e7d0abf860412f4a0c6fc25709a6e9eaba20a0d085a0344d271f40109ec","receiptsRoot":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","prevRandao":"0x0000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x1","gasLimit":"0x2fefd8","gasUsed":"0x0","timestamp":"0x1235","extraData":"0x","baseFeePerGas":"0x3b9aca00","blockHash":"0xfdb2ebe65d6cc70f97e5de775c8445f34b7a2566bfe708eb7c2beb8684df85a9","transactions":[]}]}
<< (ced2335b) {"jsonrpc":"2.0","result":{"status":"INVALID","validationError":"Received pre-merge payload.","latestValidHash":null},"id":1}
DEBUG (Invalid Terminal Block in NewPayload): Failed `Expect*` routine called from: file=/source/suites/engine/tests.go, line=1263
FAIL (Invalid Terminal Block in NewPayload): Unexpected LatestValidHash on EngineNewPayloadV1: <nil>, expected=0x0000000000000000000000000000000000000000000000000000000000000000
End test (reth): Invalid Terminal Block in NewPayload
```

So we should be returning `latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000` in the response if the TTD is not satisfied.

The test is part of the [negative engine API test cases](https://github.com/ethereum/hive/blob/d7cb48a5d3246d2b1fd8e6c018126b6a196ae26f/simulators/ethereum/engine/README.md#engine-api-negative-test-cases):
> * Invalid Terminal Block in NewPayload:
Client must reject NewPayload directives if the referenced ParentHash does not meet the TTD requirement.

The [engine API spec for NewPayload](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#specification):
> Client software MUST respond to this method call in the following way:
> 
> ... other specs
> * `{status: INVALID, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, validationError: errorMessage | null}` if terminal block conditions are not satisfied

### PR DESCRIPTION
**Pull request by Rjected**
Returns a zero `latestValidHash` when `engine_newPayload` is called with a pre-merge parent hash. Modified existing tests to reflect the correct behavior.

Introduces `PayloadStatus::with_latest_valid_hash` for using a non-null `latestValidHash` with an invalid `PayloadStatus`.  

Satisfies this condition of the [engine API spec for NewPayload](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#specification):

> Client software MUST respond to this method call in the following way:
>
> ... other conditions
>
> * `{status: INVALID, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, validationError: errorMessage | null}` if terminal block conditions are not satisfied
 
Fixes #1676

### CODE REVIEW

File: crates/rpc/rpc-engine-api/src/engine_api.rs [hunk 1]
```diff
@@ -291,7 +291,8 @@ impl<Client: HeaderProvider + BlockProvider + StateProviderFactory + EvmEnvProvi
         if !self.chain_spec.fork(Hardfork::Paris).active_at_ttd(parent_td, U256::ZERO) {
             return Ok(PayloadStatus::from_status(PayloadStatusEnum::Invalid {
                 validation_error: EngineApiError::PayloadPreMerge.to_string(),
-            }))
+            })
+            .with_latest_valid_hash(H256::zero()))
```
Comment (mattsse) [inline crates/rpc/rpc-engine-api/src/engine_api.rs:295]: worth adding a note here

**Review by mattsse — APPROVED** [review]
lgtm

**Review by rkrasiuk — COMMENTED** [review]
good catch!
