### PR TITLE
fix(discv5): `ForkId` set to head block

### LINKED ISSUE #15767: Use forkid for current head in discv5
### Describe the feature

this currenlty uses the latest forkid, which would technically be in the future if we already added future hardforks

https://github.com/paradigmxyz/reth/blob/8572989ab559d62416801be300c9819a73f625b5/crates/net/network/src/config.rs#L603-L603

we should also use the `head` here

https://github.com/paradigmxyz/reth/blob/8572989ab559d62416801be300c9819a73f625b5/crates/net/network/src/config.rs#L616-L622

like:

we do for the network

https://github.com/paradigmxyz/reth/blob/8572989ab559d62416801be300c9819a73f625b5/crates/net/network/src/config.rs#L627-L628

@emhane 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/15767

### CODE REVIEW

File: crates/ethereum-forks/src/hardforks/mod.rs [hunk 1]
```diff
@@ -34,9 +34,6 @@ pub trait Hardforks: Clone {
     /// Compute the [`ForkId`] for the given [`Head`] following eip-6122 spec
     fn fork_id(&self, head: &Head) -> ForkId;
 
-    /// Returns the [`ForkId`] for the last fork.
-    fn latest_fork_id(&self) -> ForkId;
-
```
Comment (mattsse) [inline crates/ethereum-forks/src/hardforks/mod.rs:39]: I'd still like to keep this for now

**Review by mattsse — CHANGES_REQUESTED** [review]
ty, nits.

for this pr we can limit this to changing the discv5 setup then we still can remove the latest_forkid fn later

**Review by mattsse — APPROVED** [review]
lgtm, ty!
