### PR TITLE
Fix: check canonical head first

### LINKED ISSUE #15088: Ignore FCU if head is already part of the canonical chain
### Describe the feature

ref #15086

> Client software MAY skip an update of the forkchoice state and MUST NOT begin a payload build process if forkchoiceState.headBlockHash references a VALID ancestor of the head of canonical chain, i.e. the ancestor passed [payload validation](https://github.com/ethereum/execution-apis/blob/main/src/engine/paris.md#payload-validation) process and deemed VALID. In the case of such an event, client software MUST return {payloadStatus: {status: VALID, latestValidHash: forkchoiceState.headBlockHash, validationError: null}, payloadId: null}.

if this is the case then we're free and even should ignore the update.

this is similar to:

https://github.com/paradigmxyz/reth/blob/ed9be76244e24e112251231cd9f8355bee8ba8f9/crates/engine/tree/src/tree/mod.rs#L1152-L1152

but we need to check if the block number is lower than the current head and the fcu head is part of the canonical chain, the we can ignore the update

one thing we need to consider is that we don't update the trackers:

https://github.com/paradigmxyz/reth/blob/ed9be76244e24e112251231cd9f8355bee8ba8f9/crates/engine/tree/src/tree/mod.rs#L1408-L1418

and need a way to distinguish this case: VALID but not latest

## TODO
* add checks for when fcu.head is already canonical
* add new response helper for this case

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by startup-dreamer**
Closes: #15088

This PR introduces an optimization where, if a forkchoice update (FCU) points to a valid ancestor of the current canonical head, we can skip the FCU processing and return a valid response immediately.

### Points of Consideration
- Avoids unnecessary state updates when the FCU refers to a valid ancestor.
- Intentionally does not update fork choice state trackers or emit events.
- Returns a valid payload status with a `null` payload ID, as required by the specification.

### CODE REVIEW

File: crates/engine/tree/src/tree/mod.rs [hunk 1]
```diff
@@ -2988,6 +2999,19 @@ where
...
+    ///
+    /// Returns true if the block is a valid ancestor of the canonical head.
+    fn is_valid_canonical_ancestor(&self, hash: B256) -> ProviderResult<bool> {
+        let canonical_head_num = self.state.tree_state.canonical_block_number();
+        let Some(header) = self.find_canonical_header(hash)? else {
+            return Ok(false);
+        };
+
+        // It's a valid ancestor if it's in canonical chain and has a lower block number
+        Ok(header.number() < canonical_head_num)
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:3013]: I think this makes sense

File: crates/engine/tree/src/tree/mod.rs [hunk 2]
```diff
@@ -1175,7 +1175,18 @@ where
...
+        // 2. Check if forkchoice state points to a valid ancestor of the canonical head.
+        if self.is_valid_canonical_ancestor(state.head_block_hash)? {
+            trace!(
+                target: "engine::tree",
+                head=?state.head_block_hash,
+                "fcu head block is a valid ancestor of the canonical head, skipping update"
+            );
+
+            return Ok(valid_outcome(state.head_block_hash));
+        }
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:1187]: this check makes sense, but I know wonder if we're not actually doing this already in

> // 4. check if the head is already part of the canonical chain

this actually clashes with with this opstack specialization that we have here which I forgot about:

https://github.com/paradigmxyz/reth/blob/03c5abba887452a00680ab5e8a1aee34811158a1/crates/engine/tree/src/tree/mod.rs#L1202-L1204

**Review by mattsse — COMMENTED** [review]
need to clarify some things first,
because it turns out we actually have this check already, it's just ignored for opstack

cc @ferranbt 

https://github.com/paradigmxyz/reth/blob/03c5abba887452a00680ab5e8a1aee34811158a1/crates/engine/tree/src/tree/mod.rs#L1198-L1223

unsure if we can simply remove the opstack specialization here

EDIT:

I think we should actually swap the order here 2 vs 3

https://github.com/paradigmxyz/reth/blob/03c5abba887452a00680ab5e8a1aee34811158a1/crates/engine/tree/src/tree/mod.rs#L1179-L1199

yeah I believe this is actually the issue here @startup-dreamer

**Comment by mattsse** [comment]
@startup-dreamer do you want to work on the fix instead? which is swapping 2. and 3.?

**Comment by startup-dreamer** [comment]
> @startup-dreamer do you want to work on the fix instead? which is swapping 2. and 3.?

Will do @mattsse in sometime today meanwhile what do you think about https://github.com/paradigmxyz/reth/pull/15101#discussion_r2001162710 will swaping fix this as well.

**Comment by mattsse** [comment]
@startup-dreamer I think we don't actually need this additional that you added here because already have this, I just misattributed the reported issue and the root cause is 2. vs 3. order

File: crates/engine/tree/src/tree/mod.rs [hunk 3]
```diff
@@ -2988,6 +2999,19 @@ where
         debug!(target: "engine::tree", %hash, "no canonical state found for block");
         Ok(None)
     }
+
+    /// Checks if the given block hash is a valid ancestor of the current canonical head
+    ///
+    /// Returns true if the block is a valid ancestor of the canonical head.
+    fn is_valid_canonical_ancestor(&self, hash: B256) -> ProviderResult<bool> {
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:3006]: I think we can remove this function entirely?

File: crates/engine/tree/src/tree/mod.rs [hunk 4]
```diff
@@ -1194,7 +1194,18 @@ where
...
+        // 3. Check if forkchoice state points to a valid ancestor of the canonical head.
+        if self.is_valid_canonical_ancestor(state.head_block_hash)? {
+            trace!(
+                target: "engine::tree",
+                head=?state.head_block_hash,
+                "fcu head block is a valid ancestor of the canonical head, skipping update"
+            );
+
+            return Ok(valid_outcome(state.head_block_hash));
+        }
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:1206]: tis basically the same as 4 now, so we can remove this entirely.

and only need to swap 2,3

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
hive run https://github.com/paradigmxyz/reth/actions/runs/14059838297
