### PR TITLE
fix(cli): event reporting

### LINKED ISSUE #2034: No events logged for the reth::cli=info target in Execution Stage
### Describe the bug

when transitioning from SenderRecovery to Execution, default cli logs are stuck at:

> 2023-03-29T21:02:50.056149Z  INFO Stage committed progress stage=SenderRecovery checkpoint=3185000

however, it moved into Execution Stage

when restarting the node the last thing logged is

> INFO Starting consensus engine

seems like there's no reporting from execution that is logged to stdout

this is possibly a dup of #2000

### Steps to reproduce

-

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
Closes #2034

the Pipeline future is blocking and _must_ be spawned on a blocking task.

otherwise this can cause severe side-effects such as #2034

### CODE REVIEW

File: bin/reth/src/node/events.rs [hunk 1]
```diff
@@ -86,33 +93,60 @@ impl From<PipelineEvent> for NodeEvent {
...
+#[pin_project::pin_project]
+struct EventHandler<St> {
+    state: NodeState,
+    #[pin]
+    events: St,
+    #[pin]
+    info_interval: Interval,
+}
+
+impl<St> Future for EventHandler<St>
```
Comment (rkrasiuk) [inline bin/reth/src/node/events.rs:121]: nice!

**Review by rkrasiuk — APPROVED** [review]
lgtm
