### PR TITLE
fix(engine): perform cache updates with guard

### LINKED ISSUE #18409: Perform cache updates with guard
### Describe the feature

the order of these operations isn't quite right

https://github.com/paradigmxyz/reth/blob/72c2d1b6a0bc4a1d04b66ef85142d1a2c9700d91/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L135-L149

we should only insert the outcome into the cache after we obtained the mutex:

https://github.com/paradigmxyz/reth/blob/72c2d1b6a0bc4a1d04b66ef85142d1a2c9700d91/crates/engine/tree/src/tree/payload_processor/mod.rs#L553-L553

so that the hash and the tracked cache are updated at the same time
this lock shouldnt take too long, but an alternative here would be to clear the cache first, but 

1. lock
2. update
3. insert

feels better

what we can do here is add a fn to `ExecutionCache` that take a simple closure with the mutexguard
and we perform this in there
https://github.com/paradigmxyz/reth/blob/72c2d1b6a0bc4a1d04b66ef85142d1a2c9700d91/crates/engine/tree/src/tree/payload_processor/prewarm.rs#L140-L140

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yongkangc**
## Summary

This PR fixes a race condition in cache updates where cache outcomes were being inserted before obtaining the mutex lock, which could lead to synchronization issues.

## Problem

As identified in #18409, the current implementation has a problematic order of operations:
1. Cache outcomes are inserted
2. Metrics are updated  
3. **Then** the mutex is acquired to save the cache

This creates a window where another thread could replace the cache, causing the first thread's changes to be lost.

## Solution  

This PR ensures all cache operations happen atomically by:
- Adding `update_with_guard` method to `ExecutionCache` that takes a closure with exclusive access to the mutex guard
- Refactoring `PrewarmCacheTask::save_cache` to perform all operations (state insertion, metrics update, cache replacement) under the lock

## TODO
- [x] Reth Bench Compare on Mainnet to see regression by 2000
- [x] Run Reproduction Script https://gist.github.com/yongkangc/16f80fb48a3fe8180bd7e990c97124c8
- [x] Benching to see deadlock or any other race condition

### CODE REVIEW

**Review by mediocregopher — APPROVED** [review]

File: crates/engine/tree/src/tree/payload_processor/prewarm.rs [hunk 1]
```diff
@@ -132,21 +132,28 @@ where
...
+        let caches = self.ctx.cache.clone();
+        let metrics = self.ctx.cache_metrics.clone();
+
+        // Perform all cache operations atomically under the lock
+        self.execution_cache.update_with_guard(|cached| {
+            let cache = SavedCache::new(hash, caches, metrics);
+
+            // Note: Write lock is held while insert which could block readers briefly
+            if cache.cache().insert_state(&state).is_err() {
+                return;
```
Comment (mattsse) [inline crates/engine/tree/src/tree/payload_processor/prewarm.rs:149]: in this case we should fully clear/take the `cached` because this can endup having a polluted cache

**Review by mattsse — CHANGES_REQUESTED** [review]
smol suggestion

File: crates/engine/tree/src/tree/payload_processor/prewarm.rs (hunk 1 above)
Comment (yongkangc) [reply crates/engine/tree/src/tree/payload_processor/prewarm.rs:149]: thanks for the good catch on cache pollution! addressed that by clearing with *cache=None

**Review by mattsse — APPROVED** [review]
lgtm!
