### PR TITLE
fix: return an error if block does nit exist

### LINKED ISSUE #7371: `eth_getLogs` querying by block hash returns empty list for a non-existent block hash
### Describe the bug

When filtering using `eth_getLogs`, the RPC returns an empty list as opposed to indicating the block was not found (if the block doesn't exist).

### Steps to reproduce

1. Start `reth`
2. Query for `eth_getLogs` by block hash that **does exist**:

```
# curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"blockHash":"0x60655a6d56abab50eceb622679656ed9b5d2c969b95938662b8b880163457cec","address":"0x9008d19f58aabd9ed0d60971565aa8510560ab41","topics":["0x40338ce1a7c49204f0099533b1e9a7ee0a3d261f84974ab7af36105b8c4e9db4"]}],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","result":[{"address":"0x9008d19f58aabd9ed0d60971565aa8510560ab41","topics":["0x40338ce1a7c49204f0099533b1e9a7ee0a3d261f84974ab7af36105b8c4e9db4","0x000000000000000000000000bf54079c9bc879ae4dd6bc79bce11d3988fd9c2b"],"data":"0x","blockHash":"0x60655a6d56abab50eceb622679656ed9b5d2c969b95938662b8b880163457cec","blockNumber":"0x12a09a8","transactionHash":"0xe1fac944aa178512db7ba05b63521b11d6c2ab23a2ff529eba18c46c73b42647","transactionIndex":"0x8","logIndex":"0x2a","removed":false}],"id":1}
```

3. Query for `eth_getLogs` by block hash that does **not** exist (for this example's purpose, let's use the `transactionHash` from the previous log:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"blockHash":"0xe1fac944aa178512db7ba05b63521b11d6c2ab23a2ff529eba18c46c73b42647","address":"0x9008d19f58aabd9ed0d60971565aa8510560ab41","topics":["0x40338ce1a7c49204f0099533b1e9a7ee0a3d261f84974ab7af36105b8c4e9db4"]}],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","result":[],"id":1}
```

4. Contrast this with another RPC:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"blockHash":"0xe1fac944aa178512db7ba05b63521b11d6c2ab23a2ff529eba18c46c73b42647","address":"0x9008d19f58aabd9ed0d60971565aa8510560ab41","topics":["0x40338ce1a7c49204f0099533b1e9a7ee0a3d261f84974ab7af36105b8c4e9db4"]}],"id":1}' https://rpc.mevblocker.io
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"block not found: e1fac944aa178512db7ba05b63521b11d6c2ab23a2ff529eba18c46c73b42647"}}
```

### Node logs

_No response_

### Platform(s)

Linux (x86)

### What version/commit are you on?

v0.2.0-beta.3

### What database version are you on?

Current database version: 2
Local database version: 2

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
closes #7371

previously we returned an empty list for a ethGetLogs request with a hash if we were unable to find that block.
This is incorrect behaviour because this indicates that there are no matches for the filter.

this returns an error instead

### CODE REVIEW

File: crates/rpc/rpc-builder/tests/it/http.rs [hunk 1]
```diff
@@ -546,7 +546,9 @@ async fn test_eth_logs_args() {
     let mut params = ArrayParams::default();
     params.insert( serde_json::json!({"blockHash":"0x58dc57ab582b282c143424bd01e8d923cddfdcda9455bad02a29522f6274a948"})).unwrap();
 
-    let _resp = client.request::<Vec<Log>, _>("eth_getLogs", params).await.unwrap();
+    let resp = client.request::<Vec<Log>, _>("eth_getLogs", params).await;
+    // block does not exist
+    assert!(resp.is_err());
```
Comment (Rjected) [inline crates/rpc/rpc-builder/tests/it/http.rs:551]: nice

**Review by Rjected — APPROVED** [review]
LGTM
