### PR TITLE
fix: apply FCU on invalid PayloadAttributes

### LINKED ISSUE #4589: Reth does not apply FCU on invalid payload attributes
### Describe the bug

The hive test `Invalid PayloadAttributes: Missing BeaconRoot` (and many others) fail because we currently do not apply the forkchoice update when the payload attributes are invalid:
```
CLMocker: Executed payload on 663a43d9: {VALID 0xbdad45b98507a30b96751d6f4367b9703a52a1d6dffd44fc5cc47c2ef8938d4b <nil>}
INFO (Invalid PayloadAttributes: Missing BeaconRoot): Sending EngineForkchoiceUpdated (Syncing=false) with invalid payload attributes: Missing BeaconRoot
>> (663a43d9) {"jsonrpc":"2.0","id":24,"method":"engine_forkchoiceUpdatedV3","params":[{"headBlockHash":"0xbdad45b98507a30b96751d6f4367b9703a52a1d6dffd44fc5cc47c2ef8938d4b","safeBlockHash":"0xbc2e71f6af968fb9e0faf848d50caddffb3bfae4a9e84cd869d9c1e98b808dd7","finalizedBlockHash":"0xd8af88ccf2557e6aeeff042279bcfeac88effa3ce7d464408e342d77463f174b"},{"timestamp":"0x123b","prevRandao":"0x7bc693051ebf64aa16b772e377672230a387038b488995aaa0b7a61d275b1b7a","suggestedFeeRecipient":"0x0000000000000000000000000000000000000000","withdrawals":[{"index":"0x33","validatorIndex":"0x0","address":"0x0000000000000000000000000000000000000000","amount":"0x64"},{"index":"0x34","validatorIndex":"0x1","address":"0x0100000000000000000000000000000000000000","amount":"0x64"},{"index":"0x35","validatorIndex":"0x2","address":"0x0200000000000000000000000000000000000000","amount":"0x64"},{"index":"0x36","validatorIndex":"0x3","address":"0x0300000000000000000000000000000000000000","amount":"0x64"},{"index":"0x37","validatorIndex":"0x4","address":"0x0400000000000000000000000000000000000000","amount":"0x64"},{"index":"0x38","validatorIndex":"0x5","address":"0x0500000000000000000000000000000000000000","amount":"0x64"},{"index":"0x39","validatorIndex":"0x6","address":"0x0600000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3a","validatorIndex":"0x7","address":"0x0700000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3b","validatorIndex":"0x8","address":"0x0800000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3c","validatorIndex":"0x9","address":"0x0900000000000000000000000000000000000000","amount":"0x64"}],"parentBeaconBlockRoot":null}]}
<< (663a43d9) {"jsonrpc":"2.0","error":{"code":-32602,"message":"no parent beacon block root post-cancun"},"id":24}
>> (663a43d9) {"jsonrpc":"2.0","id":15,"method":"eth_getBlockByNumber","params":["latest",false]}
<< (663a43d9) {"jsonrpc":"2.0","result":{"hash":"0x54224efb6b2124fbd3d4b88508c024d103c9e12a9dad9bbb48f61226e8f12b3d","parentHash":"0xbc2e71f6af968fb9e0faf848d50caddffb3bfae4a9e84cd869d9c1e98b808dd7","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x7c87664e7b8b3815f0077148a6a1254cdf584079a4e3e8833d2d9f645ffbfdf6","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":"0x0","number":"0x5","gasLimit":"0x2fefd8","gasUsed":"0x0","timestamp":"0x1239","extraData":"0x99726574682f76302e312e302d616c7068612e382f6c696e7578","mixHash":"0xc38ccf102062c3e1a03fc92859d7221dde80a403f99579949bafd85233da49fb","nonce":"0x0000000000000000","baseFeePerGas":"0x1e925e88","withdrawalsRoot":"0xd7a62a88f1c0486895fc23eaaa784c7d7c5d1efd112705af64220c91f5c59168","blobGasUsed":"0x0","excessBlobGas":"0x0","parentBeaconBlockRoot":"0x17f4cecbf4aebade2bef96553b4036b6c81a4000859845057edc4107d2122218","totalDifficulty":"0x0","uncles":[],"transactions":[],"size":"0x359","withdrawals":[{"index":"0x29","validatorIndex":"0x0","address":"0x0000000000000000000000000000000000000000","amount":"0x64"},{"index":"0x2a","validatorIndex":"0x1","address":"0x0100000000000000000000000000000000000000","amount":"0x64"},{"index":"0x2b","validatorIndex":"0x2","address":"0x0200000000000000000000000000000000000000","amount":"0x64"},{"index":"0x2c","validatorIndex":"0x3","address":"0x0300000000000000000000000000000000000000","amount":"0x64"},{"index":"0x2d","validatorIndex":"0x4","address":"0x0400000000000000000000000000000000000000","amount":"0x64"},{"index":"0x2e","validatorIndex":"0x5","address":"0x0500000000000000000000000000000000000000","amount":"0x64"},{"index":"0x2f","validatorIndex":"0x6","address":"0x0600000000000000000000000000000000000000","amount":"0x64"},{"index":"0x30","validatorIndex":"0x7","address":"0x0700000000000000000000000000000000000000","amount":"0x64"},{"index":"0x31","validatorIndex":"0x8","address":"0x0800000000000000000000000000000000000000","amount":"0x64"},{"index":"0x32","validatorIndex":"0x9","address":"0x0900000000000000000000000000000000000000","amount":"0x64"}]},"id":15}
DEBUG (Invalid PayloadAttributes: Missing BeaconRoot): Failed `Expect*` routine called from: file=/source/suites/engine/payload_attributes.go, line=84
DEBUG (Invalid PayloadAttributes: Missing BeaconRoot): Forkchoice is applied even on invalid payload attributes
FAIL (Invalid PayloadAttributes: Missing BeaconRoot): Unexpected hash on HeaderByNumber: 0x54224efb6b2124fbd3d4b88508c024d103c9e12a9dad9bbb48f61226e8f12b3d, expected=0xbdad45b98507a30b96751d6f4367b9703a52a1d6dffd44fc5cc47c2ef8938d4b
```

So we may need to call `fork_choice_updated`, with `None` payload attributes, but still return `INVALID` if the attributes are invalid.
https://github.com/paradigmxyz/reth/blob/9a9a6e009373410cb356acb86d3eef6836368e4b/crates/rpc/rpc-engine-api/src/engine_api.rs#L121-L124

### Steps to reproduce

Run hive on the `dan/cancun-hive-branch` of reth:
```
./hive --client reth --sim "ethereum/engine" --sim.limit "cancun/Invalid PayloadAttributes: Missing BeaconRoot"
```

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
Closes #4589 

Makes the `Invalid PayloadAttributes: Missing BeaconRoot` hive test pass

This will call `fork_choice_updated` with `None` if the payload attributes fail validation.

### CODE REVIEW

File: crates/rpc/rpc-engine-api/src/engine_api.rs [hunk 1]
```diff
@@ -134,7 +155,31 @@ where
...
+            // update MUST NOT be rolled back.
+            //
+            // NOTE: This will also apply to the validation result for the shanghai-specific fields
+            // provided in the payload attributes.
+            //
+            // To do this, we set the payload attrs to `None` if attribute validation failed, but
+            // we still apply the forkchoice update.
+            if let Err(err) = attr_validation_res {
+                let fcu_res = self.inner.beacon_consensus.fork_choice_updated(state, None).await?;
+                // TODO: decide if we want this branch - the FCU INVALID response might be more
```
Comment (mattsse) [inline crates/rpc/rpc-engine-api/src/engine_api.rs:176]: this is duplicated code, right?

I think this could be moved to a helper function instead

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/rpc/rpc-engine-api/src/engine_api.rs (hunk 1 above)
Comment (Rjected) [reply crates/rpc/rpc-engine-api/src/engine_api.rs]: yep, added a helper

**Review by mattsse — APPROVED** [review]
lgtm
