### PR TITLE
fix(rpc): improve/preserve error messages for TransactionConversionError

### LINKED ISSUE #20052: Improve error message for TransactionConversionError
### Describe the feature

we're currently ignoring the message for
https://github.com/paradigmxyz/reth/blob/b3c00ed602f2a8805974f25be714a3bea26901e9/crates/rpc/rpc-eth-types/src/error/mod.rs#L166-L168

when doing:

https://github.com/paradigmxyz/reth/blob/b3c00ed602f2a8805974f25be714a3bea26901e9/crates/rpc/rpc-eth-types/src/error/mod.rs#L339-L343

## TODO
* convert this into an enum: https://github.com/paradigmxyz/reth/blob/b3c00ed602f2a8805974f25be714a3bea26901e9/crates/rpc/rpc-convert/src/transaction.rs#L486-L489 with the string as one variant
* introduce other variant for cases like https://github.com/paradigmxyz/reth/blob/b3c00ed602f2a8805974f25be714a3bea26901e9/crates/rpc/rpc-eth-api/src/helpers/transaction.rs#L436-L436

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by figtracer**
fixes #20052

### CODE REVIEW

File: crates/rpc/rpc-convert/src/transaction.rs [hunk 1]
```diff
@@ -484,9 +483,16 @@ where
...
-pub struct TransactionConversionError(String);
+#[derive(Debug, thiserror::Error)]
+pub enum TransactionConversionError {
+    /// Conversion from `TxReq` to `SimTx` failed
+    #[error("Failed to convert RPC transaction request: {0}")]
+    FromTxReq(String),
+
+    /// Conversion from `Consensus` type failed
+    #[error("Failed to convert transaction from consensus: {0}")]
+    FromConsensus(String),
```
Comment (emhane) [inline crates/rpc/rpc-convert/src/transaction.rs]: matching on string isn't type safe. better make new error enums `FromTxReqError` and `FromConsensusError` if you need, with variants for each possible error.

**Review by emhane — CHANGES_REQUESTED** [review]

File: crates/rpc/rpc-convert/src/transaction.rs [hunk 2]
```diff
@@ -485,15 +485,38 @@ where
...
+    FromConsensus(#[from] FromConsensusError),
 }
 
+/// Error when converting from RPC transaction request to simulated transaction.
+#[derive(Debug, thiserror::Error)]
+pub enum FromTxReqError {
+    /// Required fields are missing from the transaction request.
+    #[error("required fields missing from transaction request")]
+    MissingRequiredFields,
+}
```
Comment (figtracer) [inline crates/rpc/rpc-convert/src/transaction.rs]: what variants are important here? @emhane

Comment (emhane) [reply crates/rpc/rpc-convert/src/transaction.rs]: since you are able to have 
```rust
pub enum TransactionConversionError {
    /// Conversion from `TxReq` to `SimTx` failed.
    #[error(transparent)]
    FromTxReq(#[from] FromTxReqError),
    ..
}
```
instead of
```rust
pub enum TransactionConversionError {
    /// Conversion from `TxReq` to `SimTx` failed.
    #[error(transparent)]
    FromTxReq(String),
    ..
}
```
already, that means you have covered all the necessary variants. I agree that it doesn't make sense to have an enum with one variant only, so let's collapse this by removing this error and simply having
```rust
pub enum TransactionConversionError {
    /// Required fields are missing from the transaction request.
    #[error("required fields missing from transaction request")]
    MissingRequiredFields,

    /// Conversion from `Consensus` failed.
    #[error(transparent)]
    FromConsensus(#[from] FromConsensusError),
}
```
ok?

**Review by emhane — CHANGES_REQUESTED** [review]

File: crates/rpc/rpc-convert/src/transaction.rs (hunk 2 above)
Comment (figtracer) [reply crates/rpc/rpc-convert/src/transaction.rs]: on it

File: crates/rpc/rpc-convert/src/transaction.rs [hunk 3]
```diff
@@ -826,7 +847,7 @@ where
         Ok(self
             .sim_tx_converter
             .convert_sim_tx(request)
-            .map_err(|e| TransactionConversionError(e.to_string()))?)
+            .map_err(|_| TransactionConversionError::MissingRequiredFields)?)
```
Comment (emhane) [inline crates/rpc/rpc-convert/src/transaction.rs]: we don't want to loose the error returned by `convert_sim_tx` as it may have valuable info, what error type is that? we should have the `MissingRequiredFields` variant wrap that error type i.e. `MissingRequiredFields(TheErrorType)`

**Review by emhane — DISMISSED** [review]

File: crates/rpc/rpc-convert/src/transaction.rs (hunk 3 above)
Comment (figtracer) [reply crates/rpc/rpc-convert/src/transaction.rs]: this is `convert_sim_tx`:
```rust
pub trait SimTxConverter<TxReq, SimTx>: Clone + Debug + Unpin + Send + Sync + 'static {
    type Err: Error;

    fn convert_sim_tx(&self, tx_req: TxReq) -> Result<SimTx, Self::Err>;
}

impl<TxReq, SimTx> SimTxConverter<TxReq, SimTx> for ()
where
    TxReq: TryIntoSimTx<SimTx> + Debug,
{
    type Err = ValueError<TxReq>;

    fn convert_sim_tx(&self, tx_req: TxReq) -> Result<SimTx, Self::Err> {
        tx_req.try_into_sim_tx()
    }
}

impl<TxReq, SimTx, F, E> SimTxConverter<TxReq, SimTx> for F
where
    TxReq: Debug,
    E: Error,
    F: Fn(TxReq) -> Result<SimTx, E> + Clone + Debug + Unpin + Send + Sync + 'static,
{
    type Err = E;

    fn convert_sim_tx(&self, tx_req: TxReq) -> Result<SimTx, Self::Err> {
        self(tx_req)
    }
}
```
since `TxReq` varies per network, i can't see any good way of solving this besides matching on `String` type which is not desirable, or:
```rust
    /// Required fields are missing from the transaction request.
    #[error("required fields missing from transaction request: {0}")]
    MissingRequiredFields(Box<dyn Error>),
```
but isn't that effectively doing the same thing as matching on `String`?

File: crates/rpc/rpc-convert/src/transaction.rs [hunk 4]
```diff
@@ -484,10 +483,32 @@ where
...
+    #[error("deposit transactions cannot be pooled")]
+    DepositTransaction,
+    /// Blob transactions without sidecars cannot be pooled. After being included
+    /// in a block, the sidecar data is pruned, making the transaction unpoolable.
+    #[error("blob transaction missing sidecar")]
+    BlobSidecarMissing,
+    /// Transaction type is not supported for pool submission.
+    #[error("transaction type not supported for pool")]
+    UnsupportedForPool,
+}
```
Comment (mattsse) [inline crates/rpc/rpc-convert/src/transaction.rs]: I don't think we need to limit this to a specific set

we can make one variant for

```
#[error("Failed to convert transaction into RPC response: {0}")]
```

and then have an `Other(String)` variant that only holds the error message

**Review by mattsse — CHANGES_REQUESTED** [review]
cool, only one suggestion re the TransactionConversionError variants, fine if these just use (String) messages

File: crates/rpc/rpc-convert/src/transaction.rs (hunk 4 above)
Comment (figtracer) [reply crates/rpc/rpc-convert/src/transaction.rs]: i think we should just collapse everything into the initial approach since we can use String here; just commited the changes

**Review by mattsse — APPROVED** [review]
lgtm, pending @klkvr

**Review by klkvr — APPROVED** [review]
