### PR TITLE
fix(poststate): introduce wiped counter

### LINKED ISSUE #2476: Invalid poststate revert after selfdestruct
## Description

If the account was destroyed and its storage was updated within the same poststate and then this poststate is reverted to any block up to the one where self destruct happened (including), then the plain state storage field for that entry would end up with the wrong value of the wiped field - it must be true, but the wiped field value would end up equal to false.

## Additional Context

Bug demonstrated in https://github.com/paradigmxyz/reth/pull/2445

### PR DESCRIPTION
**Pull request by rkrasiuk**
Closes #2476

Introduces the counter for the number of times the storage was wiped.

cc @onbjerg ptal and tell me how much of an impact this has on your PR

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
lgtm except I will need to use `ChangedStorage` which will look a bit weird

File: crates/storage/provider/src/post_state.rs [hunk 1]
```diff
@@ -39,13 +39,29 @@ pub type StorageChanges = BTreeMap<BlockNumber, BTreeMap<Address, Storage>>;
...
 #[derive(Debug, Default, Clone, Eq, PartialEq)]
-pub struct Storage {
+pub struct ChangedStorage {
     /// Whether the storage was wiped or not.
     pub wiped: bool,
     /// The storage slots.
     pub storage: BTreeMap<U256, U256>,
 }
 
+/// TODO:
```
Comment (onbjerg) [inline crates/storage/provider/src/post_state.rs:49]: bump
