### PR TITLE
fix(pipeline): prevent unwind beyond history limits

### LINKED ISSUE #16579: Prevent unwind and log when manual unwind is attempted past pruning config
### Describe the feature

Right now if you attempt to unwind past the account / storage history limit, for example the one configured here:
https://github.com/paradigmxyz/reth/blob/672d97307ae07ce01c9a4a571d09f837d540cd7c/crates/node/core/src/args/pruning.rs#L105-L106

This will result in an error in the merkle stage. It makes sense that the merkle unwind would fail, because we don't have enough history. However, we should instead return an error and add a log for the user before running _any_ stages if we find that we don't have enough history and can't unwind to the desired block

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by i-m-aditya**
Fixing #16579

### CODE REVIEW

File: crates/stages/api/src/pipeline/mod.rs [hunk 1]
```diff
@@ -280,6 +280,51 @@ impl<N: ProviderNodeTypes> Pipeline<N> {
...
+                    "Cannot unwind: target block is beyond storage history limit"
+                );
+                return Err(PipelineError::UnwindTargetBeyondHistoryLimit {
+                    target: to,
+                    latest: latest_block,
+                    history_limit,
+                    history_type: "storage".into(),
+                });
+            }
+        }
```
Comment (Rjected) [inline crates/stages/api/src/pipeline/mod.rs]: nice, the only change that I would like, is to introduce an enum for the history type, and include this logic in a separate method if possible

**Review by Rjected — CHANGES_REQUESTED** [review]
ty for this! the only things I think we need to change here are pretty small

File: crates/stages/api/src/pipeline/mod.rs [hunk 2]
```diff
@@ -280,6 +280,51 @@ impl<N: ProviderNodeTypes> Pipeline<N> {
...
+        // Add validation before starting unwind
+        let provider = self.provider_factory.provider()?;
+        let latest_block = provider.last_block_number()?;
+
+        // Get the actual pruning configuration
+        let prune_modes = provider.prune_modes_ref();
+
+        // Check account history pruning
+        if let Some(PruneMode::Distance(history_limit)) = prune_modes.account_history {
+            if latest_block.saturating_sub(to) > history_limit {
```
Comment (mattsse) [inline crates/stages/api/src/pipeline/mod.rs]: as @Rjected requested, I'd like to convert this to a function of prune_modes that returns a bool if this is the case

**Review by mattsse — CHANGES_REQUESTED** [review]

**Comment by i-m-aditya** [comment]
@Rjected @mattsse quick follow-up on this — would love your input!

File: crates/stages/api/src/pipeline/mod.rs [hunk 3]
```diff
@@ -294,6 +294,33 @@ impl<N: ProviderNodeTypes> Pipeline<N> {
...
+                %history_type,
+                "Cannot unwind: target block is beyond history limit"
+            );
+            return Err(PipelineError::UnwindTargetBeyondHistoryLimit {
+                target_block: to,
+                latest_block,
+                history_limit,
+                history_type,
+            });
+        }
```
Comment (mattsse) [inline crates/stages/api/src/pipeline/mod.rs]: this is a bit too much, this should be something like a `ensure_unwind_target_unpruned -> Result` or smth

File: crates/prune/types/src/target.rs [hunk 4]
```diff
@@ -81,6 +92,29 @@ impl PruneModes {
     pub fn is_empty(&self) -> bool {
         self == &Self::none()
     }
+
+    /// Returns true if target block is within history limit
+    pub fn is_target_block_within_history_limit(
+        &self,
+        latest_block: u64,
+        target_block: u64,
+    ) -> (bool, Option<(HistoryType, u64)>) {
```
Comment (mattsse) [inline crates/prune/types/src/target.rs]: this type is a bit hard to read,

**Review by mattsse — CHANGES_REQUESTED** [review]
all of this makes sense, but we can try to make this a bit nicer

**Review by Rjected — APPROVED** [review]
lgtm, pending @mattsse

**Review by mattsse — APPROVED** [review]
this should work for full nodes and only kick in after we've crossed that distance, so this seems appropriate, 

history expiry we can add as followup, which can be added similarily
