### PR TITLE
fix(consensus): call `finalize_block` when finalized block changes.

### LINKED ISSUE #3722: call finalize_block when finalized block changes
### Describe the bug

Blockchaintree has a function

https://github.com/paradigmxyz/reth/blob/1763b5ea7a936c0deff36380838bee4858ee7758/crates/blockchain-tree/src/blockchain_tree.rs#L726-L727

that should be called when we know a new block was finalized

we need to call this when we update the finalized block from inside the engine

### Steps to reproduce

- 

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Sabnock01**
This PR calls `finalize_block` from the `reth-blockchain-tree` crate in `update_finalized_block` on the `BeaconConsensusEngine`.

Closes #3722

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -715,6 +715,13 @@ where
                 return Ok(())
             }
 
+            let block_number =
+                self.blockchain.block_number(finalized_block_hash)?.ok_or_else(|| {
+                    Error::Provider(ProviderError::UnknownBlockHash(finalized_block_hash))
+                })?;
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:721]: this fetch is redundant because we already do this on L725

we can use `finalized.number` directly

**Review by mattsse — CHANGES_REQUESTED** [review]
ty, smol nit

File: crates/consensus/beacon/src/engine/mod.rs (hunk 1 above)
Comment (Sabnock01) [reply crates/consensus/beacon/src/engine/mod.rs]: Actually (just learning how `Deref` works) wouldn't it be more idiomatic to do `finalized.header.number`?

**Comment by gakonst** [comment]
Nice! Does this need a test? @mattsse

**Comment by mattsse** [comment]
this is already tested in tree, we merely ensure here that we discard unreachable sidechains

**Review by mattsse — APPROVED** [review]
