### PR TITLE
fix(cli): always commit the unwind for stage run headers

### LINKED ISSUE #19766: `reth stage run headers` always fails with static file prune error
### Describe the bug

If you try `reth stage run headers`, for any range, this happens:
```
2025-11-14T21:15:58.521236Z  INFO Initialized tracing, debug log directory: /home/ubuntu/.cache/reth/logs/mainnet
2025-11-14T21:15:58.522207Z  INFO Opening storage db_path="/home/ubuntu/test-datadir/db" sf_path="/home/ubuntu/test-datadir/static_files"
2025-11-14T21:15:58.525536Z  INFO Verifying storage consistency.
2025-11-14T21:16:04.108527Z  INFO Executing stage stage=Headers
2025-11-14T21:16:05.317604Z  INFO Received headers total=10000 from_block=20000 to_block=10001
2025-11-14T21:16:06.319245Z  INFO Received headers total=10000 from_block=10000 to_block=1
2025-11-14T21:16:06.322853Z  INFO Writing headers total=20000
2025-11-14T21:16:06.328251Z ERROR shutting down due to error
Error: database integrity error occurred: Pruning should be committed before appending or pruning more data

Caused by:
    Pruning should be committed before appending or pruning more data

Location:
    /home/ubuntu/reth/crates/cli/commands/src/stage/run.rs:359:51
```

### Steps to reproduce

simplest repro: `reth stage run --datadir ~/test-datadir --from 0 --to 20000`

### Node logs

```text

```

### Platform(s)

_No response_

### Container Type

Not running in a container

### What version/commit are you on?

main

### What database version are you on?

n/a

### Which chain / network are you on?

mainnet

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
fixes https://github.com/paradigmxyz/reth/issues/19766

Static files do not have transactions and we cannot change our local view of headers in the provider without committing. This caused problems with `stage run headers` which first unwinds the headers stage, queueing a prune but not committing it. Then, when the stage tried to write headers, it noticed the queued prune, which caused `Pruning should be committed before appending or pruning more data`

This causes `stage run` to require `--commit` for the headers, bodies, and execution stage.

### CODE REVIEW

File: crates/cli/commands/src/stage/run.rs [hunk 1]
```diff
@@ -340,7 +340,13 @@ impl<C: ChainSpecParser<ChainSpec: EthChainSpec + Hardforks + EthereumHardforks>
                     provider_rw.save_stage_checkpoint(unwind_stage.id(), checkpoint)?;
                 }
 
-                if self.commit {
+                // NOTE: headers must be committed because headers cannot be written to if static
+                // file pruning is already queued.
+                //
+                // This also means that all `stage run header` commands commit for unwinding. This
+                // is because static files do not have transactions and we cannot change the view of
+                // headers without writing.
```
Comment (mattsse) [inline crates/cli/commands/src/stage/run.rs]: oh, right, I believe this is correct

pending @joshieDo or @shekhirin

**Review by mattsse — APPROVED** [review]

File: crates/cli/commands/src/stage/run.rs (hunk 1 above)
Comment (joshieDo) [reply crates/cli/commands/src/stage/run.rs]: this might be confusing to whoever is using this - should we instead add a cli requirment that `run headers` should have `--commit` ?

Comment (joshieDo) [reply crates/cli/commands/src/stage/run.rs]: and i guess this should also happen with ::Bodies and ::Execution (txs, receipts) ?

Comment (Rjected) [reply crates/cli/commands/src/stage/run.rs]: actually yeah that makes sense, will forbid running without `--commit` for headers, bodies, and execution stage

Comment (Rjected) [reply crates/cli/commands/src/stage/run.rs]: @joshieDo this now requires `--commit` for these stages and quits if not provided

**Review by joshieDo — APPROVED** [review]
