### PR TITLE
fix: use DatabaseRef impl when fetching overriden account

### LINKED ISSUE #3583: eth_Call with stateOverride returns  empty data
### Describe the bug

I am using eth_call to call a function at an address that has no bytecode, but i use the stateOverride option in eth_Call to insert bytecode.

Using erigon:
1) In the case of reverts, it returns the revert message
2) In the case success, it returns the encoded boolean.

Using reth:
1) I always get 0x as the result

### Steps to reproduce

Consider this minimal contract:
```
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

contract EthCallTest {
    function getValue() external view returns (bool) {
        if (block.timestamp % 2 == 0) {
            return true;
        }
        return false;
    }
}

```

We use stateOverride to override the code at `0x0000000000000000000000000000000000000124` with the contract deployed bytecode

Payload:
```
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "to": "0x0000000000000000000000000000000000000124",
            "data": "0x20965255"
        },
        "0x10ce42e",
        {
            "0x0000000000000000000000000000000000000124": {
                "code": "0x6080604052348015600e575f80fd5b50600436106026575f3560e01c80632096525514602a575b5f80fd5b60306044565b604051901515815260200160405180910390f35b5f604e600242605e565b5f0360595750600190565b505f90565b5f82607757634e487b7160e01b5f52601260045260245ffd5b50069056fea2646970667358221220287f77a4262e88659e3fb402138d2ee6a7ff9ba86bae487a95aa28156367d09c64736f6c63430008140033"
            }

        }
    ],
    "id": 1
}
```
# Erigon Response
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

# Reth Response
```
{
    "jsonrpc": "2.0",
    "result": "0x",
    "id": 1
}
```

### Node logs

_No response_

### Platform(s)

Linux (x86)

### What version/commit are you on?

b4801f9e

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
Closes #3583

account needs to be fetched via databaseref trait

### CODE REVIEW

File: crates/rpc/rpc/src/eth/revm_utils.rs [hunk 1]
```diff
@@ -459,7 +459,9 @@ where
     DB: DatabaseRef,
     EthApiError: From<<DB as DatabaseRef>::Error>,
 {
-    let mut account_info = db.basic(account)?.unwrap_or_default();
+    // we need to fetch the account via the `DatabaseRef` to not update the state of the account,
+    // which is modified via `Database::base`
```
Comment (rkrasiuk) [inline crates/rpc/rpc/src/eth/revm_utils.rs:463]:
```suggestion
    // which is modified via `Database::basic`
```

**Review by rkrasiuk — APPROVED** [review]

**Comment by gakonst** [comment]
Oh man - this seems like a big footgun? How can we avoid this in the future?
