### PR TITLE
fix(prune): reth prune requires being run twice to actually prune

### LINKED ISSUE #21784: `reth prune` requires being run twice to actually prune
Right now if `reth prune` is run after changing the node's prune config, for example going from an archive node to `--minimal`, pruning appears to finish:
```
$ RUST_LOG=info,pruner ./target/profiling/reth prune --datadir ~/rocksdb-snapshot --metrics 9002 --log.file.directory ~/rocksdb-logs
2026-02-04T02:25:18.390940Z  INFO reth::cli: Initialized tracing, debug log directory: /home/ubuntu/rocksdb-logs/mainnet
2026-02-04T02:25:18.391815Z  INFO reth::cli: Opening storage db_path="/home/ubuntu/rocksdb-snapshot/db" sf_path="/home/ubuntu/rocksdb-snapshot/static_files"
2026-02-04T02:25:19.026914Z  INFO reth::cli: Verifying storage consistency.
2026-02-04T02:25:19.531077Z  INFO reth::cli: Starting metrics endpoint at 127.0.0.1:9002
2026-02-04T02:25:19.531142Z  INFO reth::cli: Copying data from database to static files...
2026-02-04T02:25:19.531157Z  INFO reth::cli: Copied data from database to static files lowest_static_file_height=Some(24353818)
2026-02-04T02:25:19.531164Z  INFO reth::cli: Pruning data from database... prune_tip=24353818 config=PruneConfig { block_interval: 5, segments: PruneModes { sender_recovery: Some(Full), transaction_lookup: Some(Full
), receipts: Some(Distance(64)), account_history: Some(Distance(10064)), storage_history: Some(Distance(10064)), bodies_history: Some(Distance(10064)), receipts_log_filter: ReceiptsLogPruneConfig({}) } }
2026-02-04T02:25:19.531221Z DEBUG pruner: Pruner started tip_block_number=24353818
2026-02-04T02:25:19.531232Z DEBUG pruner: Segment pruning started segment=TransactionLookup purpose=User to_block=24353818 prune_mode=Full
2026-02-04T02:25:19.531264Z TRACE prune{input=PruneInput { previous_checkpoint: Some(PruneCheckpoint { block_number: Some(24353818), tx_number: Some(3232274537), prune_mode: Full }), to_block: 24353818, limiter: Pru
neLimiter { deleted_entries_limit: Some(PruneDeletedEntriesLimit { limit: 20000000, deleted: 0 }), time_limit: None } }}: pruner: No transaction lookup entries to prune
2026-02-04T02:25:19.531271Z TRACE prune{input=PruneInput { previous_checkpoint: Some(PruneCheckpoint { block_number: Some(24353818), tx_number: Some(3232274537), prune_mode: Full }), to_block: 24353818, limiter: Pru
neLimiter { deleted_entries_limit: Some(PruneDeletedEntriesLimit { limit: 20000000, deleted: 0 }), time_limit: None } }}: pruner: return=Ok(SegmentOutput { progress: Finished, pruned: 0, checkpoint: None })
2026-02-04T02:25:19.531295Z DEBUG pruner: Segment pruning finished segment=TransactionLookup purpose=User to_block=24353818 prune_mode=Full segment_output.pruned=0
2026-02-04T02:25:19.531300Z DEBUG pruner: Segment pruning started segment=Bodies purpose=User to_block=24343754 prune_mode=Distance(10064)
2026-02-04T02:25:46.475395Z DEBUG pruner: Segment pruning finished segment=Bodies purpose=User to_block=24343754 prune_mode=Distance(10064) segment_output.pruned=3131022256
2026-02-04T02:25:46.475430Z DEBUG pruner: Pruner finished tip_block_number=24353818 deleted_entries=3131022256 elapsed=26.94419371s segments=Bodies[23999999, done]
2026-02-04T02:25:46.475618Z  INFO reth::cli: Pruned data from database total_pruned=3131022256
```

However, this is not accurate, because clearly not all segments have run, we would expect to see some account history deleted via pruning, when based on `db stats` we see both changesets and account / storage history:
```
| RocksDB Table Name     | # Entries  | SST Size | Memtable Size | Total Size | Pending Compaction |
|------------------------|------------|----------|---------------|------------|--------------------|
| StoragesHistory        | 1929341542 | 70.9 GiB | 2 KiB         | 70.9 GiB   | 0 B                |
| AccountsHistory        | 399940294  | 21.3 GiB | 2 KiB         | 21.3 GiB   | 0 B                |


| Segment            | Block Range  | Transaction Range | Shape (columns x rows) | Size      |
|--------------------|--------------|-------------------|------------------------|-----------|
| AccountChangeSets  | 0..=24353818 | N/A               | 1 x 4257742460         | 158.4 GiB |
| StorageChangeSets  | 0..=24353818 | N/A               | 1 x 7852739980         | 502.6 GiB |
```

Ideally we would prune everything on the first run. If `reth prune` is run again, then we get more things being pruned:
```
2026-02-04T02:34:51.287184Z DEBUG pruner: Segment pruning started segment=AccountHistory purpose=User to_block=24343754 prune_mode=Distance(10064)
2026-02-04T02:34:53.694509Z TRACE prune{input=PruneInput { previous_checkpoint: None, to_block: 24343754, limiter: PruneLimiter { deleted_entries_limit: Some(PruneDeletedEntriesLimit { limit: 20000000, deleted: 0 }), time_limit: None } }}: pruner: Scanned account changesets from static files processed=20000000 done=false
... rest of logs
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yongkangc**
**Summary**

`reth prune` requires being run twice to fully prune all segments. On the first run, only Bodies is pruned, then the CLI exits. AccountHistory/StorageHistory require a second run.

Closes #21784

**Root Cause**

[#21649](https://github.com/paradigmxyz/reth/pull/21649) introduced batched pruning with a delete limit to prevent OOM. Two bugs cause premature exit:

1. When the limiter breaks the segment loop early, `output.progress` was set from the last processed segment (which may report `Finished`), not reflecting that remaining segments were skipped.

2. If an early segment returns `HasMoreData` but a later segment returns `Finished`, the direct assignment `output.progress = segment_output.progress` overwrites with `Finished`.

**Fix**

This PR adds `PruneProgress::combine()` with "worst wins" semantics so any `HasMoreData` is preserved, and uses it at the limiter break site to ensure callers know to continue pruning.

**Before Fix**
```
DEBUG pruner: Segment pruning finished segment=Bodies ... progress=Finished
INFO  reth::cli: Pruning finished!  ← exits before StorageHistory
```

**After Fix**
```
DEBUG pruner: Pruner interrupted, has more data ... segments=StorageHistory[7871813, in_progress]
INFO  reth::cli: Pruning batch complete, continuing... batch_pruned=3131122256 total_pruned=3131122256
DEBUG pruner: Pruner started tip_block_number=24353818
...
DEBUG pruner: Segment pruning finished segment=StorageHistory ... segment_output.pruned=100000
INFO  reth::cli: Pruning batch complete, continuing... batch_pruned=100000 total_pruned=6363696794
```

CLI correctly detects `HasMoreData` and continues pruning StorageHistory in subsequent batches.

### CODE REVIEW

File: crates/prune/prune/src/segments/user/transaction_lookup.rs [hunk 1]
```diff
@@ -59,25 +59,27 @@ where
...
+            input.previous_checkpoint = Some(PruneCheckpoint {
+                block_number: Some(new_checkpoint),
+                tx_number: Some(body_indices.last_tx_num()),
+                prune_mode: self.mode,
+            });
+            debug!(
+                target: "pruner",
+                static_file_checkpoint = ?input.previous_checkpoint,
+                "Using static file transaction checkpoint as TransactionLookup starting point"
+            );
```
Comment (Rjected) [inline crates/prune/prune/src/segments/user/transaction_lookup.rs]: I'm skeptical that we need this, are these related?

File: crates/prune/prune/src/segments/user/bodies.rs [hunk 2]
```diff
@@ -141,7 +138,7 @@ mod tests {
     ///
     /// Each jar contains sequential transaction ranges for testing deletion logic.
     fn setup_static_file_jars<P: StaticFileProviderFactory>(provider: &P, tip_block: u64) {
-        let num_jars = (tip_block + 1) / DEFAULT_BLOCKS_PER_STATIC_FILE;
+        let num_jars = (tip_block / DEFAULT_BLOCKS_PER_STATIC_FILE) + 1;
```
Comment (Rjected) [inline crates/prune/prune/src/segments/user/bodies.rs]: also the changes in this file - why are they related to the prune cmd bug?

**Review by Rjected — CHANGES_REQUESTED** [review]
the combine fn / modifications to the pruner look good to me, just some comments on the bodies / txlookup changes in this PR

**Review by Rjected — APPROVED** [review]
lgtm
