### PR TITLE
fix: apply default values for transactions

### LINKED ISSUE #15462: Properly apply default values for transactions
### Describe the feature

See also section on default values:

https://github.com/ethereum/execution-apis/blob/e56d3208789259d0b09fa68e9d8594aa4d73c725/docs/ethsimulatev1-notes.md#default-values-for-transactions

we currently require that the tx can be converted to tx if validation is requested:

https://github.com/paradigmxyz/reth/blob/7305c9ee0d1d9a5e3948d1a3df35fb400c7561f3/crates/rpc/rpc-eth-types/src/simulate.rs#L124-L126

see also `buildable_type`

https://github.com/alloy-rs/alloy/blob/def933930b5fac1b3278477cbe9c01f99b7a21db/crates/rpc-types-eth/src/transaction/request.rs#L661-L673

however we should skip the validation check and instead fill all the defaults if missing like we already do for:

https://github.com/paradigmxyz/reth/blob/7305c9ee0d1d9a5e3948d1a3df35fb400c7561f3/crates/rpc/rpc-eth-types/src/simulate.rs#L138-L153

since the default type is 0x2 (eip1559) we should try to convert into a eip1559 if the tx can not be completed into a different type (e.g. in case all fields have been provided).

## TODO
* remove validation check
* add a few tests for `resolve_transaction` with `EthTxBuilder` as Txcompat and `revm::CacheDB` as the `Database`arg

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Soubhik-10**
closes #15462

### CODE REVIEW

File: crates/rpc/rpc-eth-types/src/simulate.rs [hunk 1]
```diff
@@ -110,12 +110,9 @@ where
 
 /// Goes over the list of [`TransactionRequest`]s and populates missing fields trying to resolve
 /// them into primitive transactions.
-///
-/// If validation is enabled, the function will return error if any of the transactions can't be
-/// built right away.
 pub fn resolve_transaction<DB: Database, Tx, T: TransactionCompat<Tx>>(
     mut tx: TransactionRequest,
-    validation: bool,
+    _validation: bool,
```
Comment (mattsse) [inline crates/rpc/rpc-eth-types/src/simulate.rs:115]: we can remove this argument now

File: crates/rpc/rpc-eth-types/src/simulate.rs [hunk 2]
```diff
@@ -155,17 +149,14 @@ where
...
-        _ => {
-            if tx.max_fee_per_gas.is_none() {
-                tx.max_fee_per_gas = Some(0);
-                tx.max_priority_fee_per_gas = Some(0);
-            }
+    } else {
+        if tx.gas_price.is_none() {
+            tx.gas_price = Some(0);
         }
     }
```
Comment (mattsse) [inline crates/rpc/rpc-eth-types/src/simulate.rs:161]: this match we can keep, but we only need to do this if `tx.buildable_type().is_none()`

**Review by mattsse — CHANGES_REQUESTED** [review]
smol nits,

as discussed we want som simple tests for this as well, ideally where `TransactionCompat` for eth is defined

**Comment by Soubhik-10** [comment]
@mattsse please check :)

**Review by mattsse — APPROVED** [review]
very nice, ty
