### PR TITLE
fix(tracing): fix the parity vmTrace stack pushes #5561

### LINKED ISSUE #5561: parity `vmTrace` stack pushes are incorrect
### Describe the bug

The code which reports the newly pushed stack elements for each executed opcode is broken, and gives some obviously wrong answers, like this, which shows two elements pushed by a PUSH1:

```
      {
        "cost": 3,
        "ex": {
          "used": 180751,
          "push": [
            "0x20",
            "0x40"
          ],
          "mem": {
            "off": 2688,
            "data": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
          },
          "store": null
        },
        "pc": 371,
        "sub": null,
        "op": "PUSH1"
      },
```

Looking at the code, I can see that the issue is in trying to use both `stack` and `push_stack` to produce this value. I'll put up a PR soon to fix it.

### Steps to reproduce

cast rpc trace_replayTransaction --raw '[ "txhash", ["vmTrace"]]'

You'll get wrong answers for basically any transaction.

### Node logs

_No response_

### Platform(s)

Linux (x86)

### What version/commit are you on?

af8885172313aca66816dfc72537728d0c3c4e36

### What database version are you on?

1

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

None

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by gbrew**
Fix #5561 

Change tracing config to keep track of No stack, only pushed items, or whole stack.

Fix the parity tracer to just use the pushed items directly.

### CODE REVIEW

File: crates/revm/revm-inspectors/src/tracing/builder/parity.rs [hunk 1]
```diff
@@ -637,3 +562,76 @@ where
...
+
+/// Returns the number of items pushed on the stack by a given opcode.
+/// This used to determine how many stack etries to put in the `push` element
+/// in a parity vmTrace.
+/// The value is obvious for most opcodes, but SWAP* and DUP* are a bit weird,
+/// and we handle those as they are handled in parity vmtraces.
+/// For reference: <https://github.com/ledgerwatch/erigon/blob/9b74cf0384385817459f88250d1d9c459a18eab1/turbo/jsonrpc/trace_adhoc.go#L451>
+pub(crate) fn stack_push_count(step_op: OpCode) -> usize {
+    let step_op = step_op.get();
+    if (opcode::PUSH0..=opcode::PUSH32).contains(&step_op) {
```
Comment (DaniPopes) [inline crates/revm/revm-inspectors/src/tracing/builder/parity.rs:574]: I believe this can be a single match expression just like the Go switch reference

Comment (gbrew) [reply crates/revm/revm-inspectors/src/tracing/builder/parity.rs]: > I believe this can be a single match expression just like the Go switch reference

Good call, just pushed that change.

**Review by mattsse — APPROVED** [review]
this is great, tysm!

I only replaces the `==` with `is_` functions
