### PR TITLE
fix(revm): calculate failed transaction hash for logging

### LINKED ISSUE #6544: Transaction hash is not displayed on EVM block validation errors in the pipeline
### Describe the bug

We set the transaction hash to default https://github.com/paradigmxyz/reth/blob/8cfa5efe62e79923b317d9685fc9f8205d5a92b5/crates/storage/provider/src/providers/database/provider.rs#L1352-L1353, which is why it's zeroed when we report the error https://github.com/paradigmxyz/reth/blob/8cfa5efe62e79923b317d9685fc9f8205d5a92b5/crates/revm/src/processor.rs#L288

We need to calculate the hash for the provided transaction when such an error occurs.

### Steps to reproduce

-

### Node logs

```text
Feb 10 11:29:44 high reth[10996]: 2024-02-10T18:29:44.107025Z ERROR sync::pipeline: Stage encountered an execution error: EVM reported invalid transaction (0x0000000000000000000000000000000000000000000000000000000000000000): Transaction er
ror: NonceTooHigh { tx: 1, state: 0 } stage=Execution bad_block=15703508                 

Feb 10 11:29:44 high reth[10996]: Stage encountered an execution error: EVM reported invalid transaction (0x0000000000000000000000000000000000000000000000000000000000000000): Transaction error: NonceTooHigh { tx: 1, state: 0 }
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

-

### What database version are you on?

-

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by justcode740**
Closes #6544.

### CODE REVIEW

File: crates/revm/src/processor.rs [hunk 1]
```diff
@@ -267,7 +267,7 @@ where
             fill_op_tx_env(self.evm.tx_mut(), transaction, sender, envelope_buf.into());
         }
 
-        let hash = transaction.hash();
+        let hash = transaction.recalculate_hash();
```
Comment (mattsse) [inline crates/revm/src/processor.rs:270]: why do we need to recalculate this?

Comment (shekhirin) [inline crates/revm/src/processor.rs:270]: let's recalculate the hash on-demand, i.e. only on the line 278 (in `tracing::trace` call) and on the line 288 (when the error has occurred). Otherwise, it may be not even used, but the recalculation is expensive.

Also, we might want to check if the hash is empty now, because AFAIK it's only an issue during the pipeline syncv.

File: crates/revm/src/processor.rs [hunk 2]
```diff
@@ -267,8 +268,22 @@ where
...
+            matches!(self.evm.context.external.hook, Hook::Transaction(_));
+        // TODO?: Might add as a method to transaction
+        let is_hash_empty = |hash: &B256| hash.iter().all(|&byte| byte == 0);
+
+        // need statistic to understand which condition to put first but performance gain maybe
+        // negligible
+        if needs_hash_for_inspection && is_hash_empty(&hash) {
+            hash = transaction.recalculate_hash();
+            hash_recalculated = true; // Mark that the hash has been calculated
+        }
```
Comment (mattsse) [inline crates/revm/src/processor.rs:283]: I don't think we need any of this, and instead, recalculate the hash in the error case

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/revm/src/processor.rs (hunk 2 above)
Comment (justcode740) [reply crates/revm/src/processor.rs:283]: if hash is empty, the inspection would never take effect, is it what you want?

Comment (shekhirin) [reply crates/revm/src/processor.rs:283]: same q @mattsse, i'm not familiar with the logic enough

Comment (Rjected) [reply crates/revm/src/processor.rs:283]: Pretty sure we would just recalculate the hash after `map_err`, i.e. after the inspection occurs. We don't need to do this before inspection. We don't need to do it before we inspect / call `transact`

Comment (mattsse) [reply crates/revm/src/processor.rs:283]: > if hash is empty, the inspection would never take effect

why?

Comment (justcode740) [reply crates/revm/src/processor.rs:283]: @mattsse @shekhirin opinion?

Comment (justcode740) [reply crates/revm/src/processor.rs:283]: > > if hash is empty, the inspection would never take effect
> 
> why?

oh, i guess if env hash is always same as hash, then guess this function call kinda redundant here, we'd only need to check hook is of transaction type, if the env got the actual hash from somewhere else, then should_inspect would always fail if tx_hash is 0x0.

copy should_inspect impl here:
```
/// Check if the inspector should be used.
    pub fn should_inspect(&self, env: &Env, tx_hash: B256) -> bool {
        match self.hook {
            Hook::None => false,
            Hook::Block(block) => env.block.number.to::<u64>() == block,
            Hook::Transaction(hash) => hash == tx_hash,
            Hook::All => true,
        }
    }
```

Comment (justcode740) [reply crates/revm/src/processor.rs:283]: but anyway, it's your guy's codebase at end of day so i can just put a recalc in err log

> is 0x0.

somehow the reply didn't show up at my thread at the time..

Comment (justcode740) [reply crates/revm/src/processor.rs:283]: @mattsse thoughts?

Comment (shekhirin) [reply crates/revm/src/processor.rs:283]: I think it's fine to just recalculate the hash on error, and not for inspector use. Because we don't use inspector in the `Execution` stage, and IIUC it's the only place from where the transaction comes without the hash.

Comment (justcode740) [reply crates/revm/src/processor.rs]: ok, done, i don't quite understand why execution stage doesn't need inspector, but its your guy's codebase, so your conn.

**Review by Rjected — APPROVED** [review]
looks good to me

**Review by emhane — APPROVED** [review]

**Comment by justcode740** [comment]
> looks good to me
oh, hey seem i accidentally trigger many reviewer that don't need to review this, should i revert the review request or close this and open a new one? @Rjected

**Review by mattsse — APPROVED** [review]
thanks!
