### PR TITLE
perf(trie): fix extend_sorted_vec O(n log n) → O(n+m) merge

### LINKED ISSUE #21034: Optimize *Sorted data structures merging
### Describe the feature

For example, in merge_overlay_trie_input the state is sorted for every block, when we can just merge all the values and sort once at the end

https://github.com/paradigmxyz/reth/blob/8ffc0deab49e753a82cc725a2ca03e81108c253b/crates/engine/tree/src/tree/payload_validator.rs#L1021

### Additional context

_No response_

cc @shekhirin @Rjected @mediocregopher @yongkangc

### PR DESCRIPTION
**Pull request by yongkangc**
Closes https://github.com/paradigmxyz/reth/issues/21034 Replace the previous algorithm that appended elements then re-sorted with a proper two-pointer merge that maintains O(n+m) complexity. 

Follow up to https://github.com/paradigmxyz/reth/pull/21080

The two pointer merge works much for large blocks where n is really large. but not as much when n is small. n here refers to the size HashPostStateSorted, TrieUpdateSorted.

image

The context is that our current sorting is really slow. based on the benchmark, with realistic big blocks number, it performed badly.

image

**Problem**
The old implementation would append new elements and call `sort_by()`, resulting in O(n log n) complexity per merge.

**Solution**
Use a two-pointer merge algorithm that processes both sorted inputs in a single pass, achieving O(n+m) complexity.

---

**Benchmark Results**

| Type | n | k | extend_ref_old | extend_ref_new | kway_merge | Winner |
|------|--:|--:|---------------:|---------------:|-----------:|--------|
| **HashedPostState** | 5000 | 3 | 890µs | **617µs** | 1.43ms | extend_ref_new (1.4x) |
| | 5000 | 10 | 6.17ms | 6.18ms | 7.62ms | old ≈ new |
| | 10000 | 3 | 3.23ms | **2.04ms** | 3.32ms | extend_ref_new (1.6x) |
| | 10000 | 10 | 14.2ms | **13.6ms** | 20.2ms | extend_ref_new |
| | 15000 | 3 | 5.47ms | **4.03ms** | 6.66ms | extend_ref_new (1.4x) |
| | 15000 | 10 | 24.0ms | **22.4ms** | 31.9ms | extend_ref_new |
| **TrieUpdates** | 5000 | 3 | 963µs | **581µs** | 1.02ms | extend_ref_new (1.7x) |
| | 5000 | 10 | 7.74ms | **5.56ms** | 6.97ms | extend_ref_new (1.4x) |
| | 10000 | 3 | 3.80ms | **1.86ms** | 2.67ms | extend_ref_new (2.0x) |
| | 10000 | 10 | 17.0ms | **13.0ms** | 18.5ms | extend_ref_new (1.3x) |
| | 15000 | 3 | 6.36ms | **3.74ms** | 4.96ms | extend_ref_new (1.7x) |
| | 15000 | 10 | 30.0ms | **21.1ms** | 29.3ms | extend_ref_new (1.4x) |

**Key Findings:**
- For small k (3-10 blocks), `extend_ref_new` consistently wins with 1.3-2.0x speedup

[Full benchmark results](https://gist.github.com/yongkangc/fb9dea26961d727298e342b5e242d8dd)

### CODE REVIEW

File: crates/trie/common/src/utils.rs [hunk 1]
```diff
@@ -26,46 +26,48 @@ where
...
             }
         }
     }
 
-    target.extend(other_iter.cloned());
-    if target.len() > initial_len {
-        target.sort_by(cmp);
-    }
+    // Drain remaining elements from whichever iterator has leftovers
+    result.extend(target_iter.cloned());
```
Comment (DaniPopes) [inline crates/trie/common/src/utils.rs]: target_iter should be Vec::into_iter or drain(..)

Comment (yongkangc) [reply crates/trie/common/src/utils.rs]: thanks for note, updating this

**Review by DaniPopes — APPROVED** [review]

**Review by mediocregopher — APPROVED** [review]
