### PR TITLE
fix: initialize missing fields

### LINKED ISSUE #1442: `SealedHeader::from<Block>` drops several important fields which invalidate RLP encoding
### Describe the bug

I was looking to use the `reth-primitives` crate in a project which requires me to get the RLP encoded block header as of a certain block. This RLP encoded header is then passed elsewhere and hashed however I ran into the issue of none of the hashes matching.

The root of the issue seems to be that `SealedHeader::from<Block>` drops a number of fields from `Block` which go into the RLP encoded form (e.g. tx root, parent hash, etc.) despite those fields existing on `Header`.
 https://github.com/paradigmxyz/reth/blob/5c2f96ed659222e58b93bf2934f355c5fcacabce/crates/primitives/src/header.rs#L311-L331
 
 Are these dropped for performance reasons? Ideally we'd copy across all the fields included in the block's header (happy to make a PR), but at least we should document that this conversion is lossy.

### Steps to reproduce

```
// Set up a provider

let blk: Block = anvil_provider
    .get_block(BlockNumber::Number(8509764u64.into()))
    .await
    .unwrap()
    .unwrap();

let blk_header = SealedHeader::from(blk);

let mut block_header_rlp = Vec::new();
blk_header.encode(&mut block_header_rlp);

assert_eq!(blk_header.hash(), BlockHash::from(keccak256(block_header_rlp)))
```

### Node logs

```text
N/A
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

5c2f96e

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
closes https://github.com/paradigmxyz/reth/issues/1442

inits missing fields

also reorders trait impl order

### CODE REVIEW

File: crates/primitives/src/header.rs [hunk 1]
```diff
@@ -311,17 +328,23 @@ impl<'a> arbitrary::Arbitrary<'a> for SealedHeader {
...
             timestamp: block.timestamp.as_u64(),
             mix_hash: block.mix_hash.unwrap().0.into(),
             beneficiary: block.author.unwrap().0.into(),
             base_fee_per_gas: block.base_fee_per_gas.map(|fee| fee.as_u64()),
-            ..Default::default()
+            ommers_hash: block.uncles_hash.0.into(),
+            gas_used: block.gas_used.as_u64(),
+            withdrawals_root: None,
+            logs_bloom: block.logs_bloom.unwrap_or_default().0.into(),
         };
```
Comment (TomAFrench) [inline crates/primitives/src/header.rs:348]: This is basically the implementation for `Header::From<Block>` so we should break that out and then just have `SealedHeader::From<Block>` call into it. It's cleaner plus we can create unsealed headers directly.

Comment (mattsse) [reply crates/primitives/src/header.rs:348]: I'm not following, sorry.

I don't think we have `Header::From<Block>` because Block already has the header.

this implementation is essentially just a compat impl, and should probably be phased out eventually because not actually used by reth internally.

Comment (TomAFrench) [reply crates/primitives/src/header.rs:348]: No worries, I was just saying that we're defining how to build a `Header` from a `Block` so we might as well implement `Header::From<Block>` and separate it from how we build a `SealedHeader` for flexibility.

Comment (TomAFrench) [reply crates/primitives/src/header.rs:348]: It would be a shame to lose this conversion tbh, it makes it much easier to get at the RLP encodings of block headers when using ethers-rs.

Comment (mattsse) [reply crates/primitives/src/header.rs:348]: sorry, this is all very confusing because there are multiple different Header and Block types (ethers,reth-primtive,reth-rpc). so this is hard to understand without using their fully qualified name.

Comment (mattsse) [reply crates/primitives/src/header.rs:348]: > It would be a shame to lose this implementation tbh, it makes it much easier to get at the RLP encodings of block headers when using ethers-rs.

they are fine for now but perhaps will be feature gated eventually. or additional work is done to make everything compatible

Comment (TomAFrench) [reply crates/primitives/src/header.rs:348]: > this is all very confusing because there are multiple different Header and Block types

Apologies, this is my first time looking into the reth code so I'm just speaking about things local to this file + ether-rs (ethers-rs `Block` going to a reth-primitives `Header`).

Comment (mattsse) [reply crates/primitives/src/header.rs:348]: gotcha,
yeh additional compat impl make sense

Comment (gakonst) [reply crates/primitives/src/header.rs]: fixed here https://github.com/paradigmxyz/reth/pull/1448/commits/17e66c27226d0f8d18cfbb9ede6d0c1c91dc9252

File: crates/primitives/src/header.rs [hunk 2]
```diff
@@ -308,21 +325,33 @@ impl<'a> arbitrary::Arbitrary<'a> for SealedHeader {
...
+            receipts_root: block.receipts_root.0.into(),
             timestamp: block.timestamp.as_u64(),
             mix_hash: block.mix_hash.unwrap().0.into(),
             beneficiary: block.author.unwrap().0.into(),
             base_fee_per_gas: block.base_fee_per_gas.map(|fee| fee.as_u64()),
-            ..Default::default()
-        };
+            ommers_hash: block.uncles_hash.0.into(),
+            gas_used: block.gas_used.as_u64(),
+            withdrawals_root: None,
```
Comment (gakonst) [inline crates/primitives/src/header.rs:346]: @rkrasiuk does this mean we need to update ethers-rs here to have a withdrawals root?

**Review by gakonst — APPROVED** [review]
