### PR TITLE
use `core::error::Error`

### LINKED ISSUE #11312: use core::error::Error
### Describe the feature

we already require msrv 1.81, we can now use core::error::Error

## TODO

* remove std features and use core::error

see https://github.com/paradigmxyz/reth/pull/11313 for ref

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tcoratger**
Should close https://github.com/paradigmxyz/reth/issues/11312

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]

File: crates/storage/errors/src/provider.rs [hunk 1]
```diff
@@ -172,14 +172,13 @@ impl From<UnifiedStorageWriterError> for ProviderError {
     }
 }
 
-#[cfg(feature = "std")]
-impl std::error::Error for ProviderError {
-    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
+impl core::error::Error for ProviderError {
```
Comment (onbjerg) [inline crates/storage/errors/src/provider.rs:175]: is the std feature here (and in the other changed files) used for anything in their respective crates anymore?

Comment (tcoratger) [reply crates/storage/errors/src/provider.rs:175]: Yes normally I checked and I see in the two or three crates concerned another use either for display, `std::path::PathBuf` or another use
