### PR TITLE
fix: fix tx propagation when full

### LINKED ISSUE #10235: Ensure peer receives all new transactions
### Describe the feature

transactions are broadcasted to `sqrt(peercount)` and either broadcasted as hashes or full:

https://github.com/paradigmxyz/reth/blob/e49f173f198aff4a38b4ad89aa67aceef94ceae7/crates/net/network/src/transactions/mod.rs#L459-L459

however for full txs there are size limits in place:

https://github.com/paradigmxyz/reth/blob/e49f173f198aff4a38b4ad89aa67aceef94ceae7/crates/net/network/src/transactions/mod.rs#L1411-L1411

so depending on total size of the unseen txs, the full broadcast is truncated and 4844 transactions are also not sent to that peer because they're excluded from the full broadcast.

## TODO
* in case the full transactions are truncated or a new 4844 is seen, also announce the other transactions as a separate newpooledtxhashes message to that peer so it receives all new txs including 4844 as hash or in full

This should be done by also recording the hashes that don't fit:

https://github.com/paradigmxyz/reth/blob/1d83d14e8d096cfc8cc4ac12fd1ddaa4bacc089b/crates/net/network/src/transactions/mod.rs#L1409-L1413

and also add 4844 hashes

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
closes #10235

Also tracks txs that we can't send in full and sends them to the peer as pooled hashes message.

This introduces a new builder type that is either for full txs or hashes.

The `FullTransactionsBuilder` now also tracks txs that can't be send in full (4844) or don't fit into the message as transaction.

there's some potential for code unification in a followup pr

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]

File: crates/net/network/src/transactions/mod.rs [hunk 1]
```diff
@@ -512,33 +504,45 @@ where
...
-            .get_all(txs)
-            .into_iter()
-            .filter(|tx| !tx.transaction.is_eip4844())
-            .map(PropagateTransaction::new);
+        let to_propagate = self.pool.get_all(txs).into_iter().map(PropagateTransaction::new);
 
         // Iterate through the transactions to propagate and fill the hashes and full transaction
         for tx in to_propagate {
-            if peer.seen_transactions.insert(tx.hash()) {
+            if !peer.seen_transactions.contains(&tx.hash()) {
```
Comment (emhane) [inline crates/net/network/src/transactions/mod.rs:513]: replacing this means the tx hash won't be promoted to lru anymore, not sure we want that for efficiency filling request from hashes pending fetch. will open issue to revert incase no strong argument for @mattsse
