### PR TITLE
fix(rpc): narrow getLogs retry range

### LINKED ISSUE #23810: Bug: eth_getLogs returns the same blockrange if the requests response "exceeds max results"
### Describe the bug

Im trying to sync some data with an envio indexer. Envio uses the "eth_getLogs" endpoint to ask for the topics emmitted across a block range. In this case Im just indexing the swap and poolInitialized topics emmited by UniSwapV4.

Atm my node is configured to at least export 20k logs in a request. However it seems this is reached very easily.

The problem comes with the answer returned by the node. When this limitted is reached the node specifies a range that can be used for the next request. However, in the case I have specified below it returns alwasy the same block range as the one I have requested.

The issue seems to be related on how upstream reth used by base node implements `reth_rpc::eth::EthFilter::logs()`. 

### Steps to reproduce

Example request made by ENVIO from block 25766988 (0x1892c4c) to block 25775072 (0x1894be0):

curl -s -X POST $NODE_ENDPOINT \
  -H "Content-Type: application/json" \
  -d '{"method":"eth_getLogs","id":1,"jsonrpc":"2.0","params":[{"fromBlock":"0x1892c4c","toBlock":"0x1894be0","topics":[["0xdd466e674ea557f56295e2d0218a125ea4b4f0f6f3307b95f85e6110838d6438","0x40e9cecb9f5f1f1c5b9c97dec2917b7ee92e57ba5563708daca94dd84ad7112f"]]}]}'
What the node answer

{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"query exceeds max results 20000, retry with the range 25766988-25775072"}}

### Node logs

```text

```

### Platform(s)

Linux (x86)

### Container Type

Docker

### What version/commit are you on?

Im currently running reth/v1.11.3-d6324d6/x86_64-unknown-linux-gnu/base/v0.7.6

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

Base

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by figtracer**
Closes #23810

This prevents the retry hint from echoing the original request range when the overflow happens at `toBlock`.

### CODE REVIEW

File: crates/rpc/rpc/src/eth/filter.rs [hunk 1]
```diff
@@ -737,18 +737,24 @@ where
                 is_multi_block_range &&
                 all_logs.len() > max_logs_per_response
             {
+                let (retry_from_block, retry_to_block) = if num_hash.number == from_block {
+                    (from_block, from_block)
+                } else {
+                    (from_block, num_hash.number - 1)
```
Comment (mattsse) [inline crates/rpc/rpc/src/eth/filter.rs]: from_block is in both branches so we only need `retry_to_block` here?

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
