### PR TITLE
fix: Add dummy system tx in op dev mode

### LINKED ISSUE #13991: Can not use op-reth in dev mode
### Describe the bug

When using op-reth with the flag `--dev` it's not possible to send transaction, the error `could not get L1 block info from L2 block` is triggered.  
https://github.com/paradigmxyz/reth/blob/8a453ba1ed7418a15c30f8f5af6c4c54c3149644/crates/optimism/node/src/txpool.rs#L313-L315
https://github.com/paradigmxyz/reth/blob/8a453ba1ed7418a15c30f8f5af6c4c54c3149644/crates/optimism/rpc/src/eth/block.rs#L43-L44

The extraction should not occur, or the error should be handled in dev mode.

### Steps to reproduce

1. Run `op-reth` in dev mode: `op-reth node --dev --http --http.api all --dev.block-max-transactions 1`
2. Use cast to make a native transfer: `cast send --value 1000000000000000000 0x3fAB184622Dc19b6109349B94811493BF2a45362 --rpc-url=http://localhost:8545 --private-key "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"`

### Node logs

```text
From cast:

Error: server returned an error response: error code -32603: could not get L1 block info from L2 block: invalid l1 block info transaction calldata in the L2 block
```

### Platform(s)

_No response_

### Container Type

Not running in a container

### What version/commit are you on?

reth-optimism-cli Version: 1.1.5

### What database version are you on?

N/A

### Which chain / network are you on?

dev

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

make install-op

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### LINKED ISSUE #14005: Inject OP system tx during local payload building
### Describe the feature

ref #13991

OP requires that the first tx in a block is a system tx, not having this leads to broken rpc because a lot of impls rely on this behaviour.

## TODO

* include a deposit tx in Op's payload attributes, with dummy setL1BlockValuesEcotone calldata

https://github.com/paradigmxyz/reth/blob/b9a6e65d8cb9c93910b5933da77e8a0fb55a3321/crates/engine/local/src/payload.rs#L55-L55

e.g. system tx for `setL1BlockValuesEcotone`: https://specs.optimism.io/protocol/ecotone/l1-attributes.html

https://basescan.org/tx/0xd813d5cd612f2b4a43948ab2f22c8c0ac41b122ef2692bd41a2b40cd926fce02

```
{
  "blockHash": "0xf9c3f45761c6fb1b7df69e6d914c8e446d0f5a25221cbb52ca177dbfabb20b2a",
  "blockNumber": "0x1869c94",
  "depositReceiptVersion": "0x1",
  "from": "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0001",
  "gas": "0xf4240",
  "gasPrice": "0x0",
  "hash": "0xd813d5cd612f2b4a43948ab2f22c8c0ac41b122ef2692bd41a2b40cd926fce02",
  "input": "0x440a5e20000008dd00101c120000000000000002000000006797954f00000000014b5daf00000000000000000000000000000000000000000000000000000008830a89bc000000000000000000000000000000000000000000000000000000041dfd80f29f818bf989bdefd5eec65b5aefb5114e642eebf9d17bc80a5d1fb559176ad5240000000000000000000000005050f69a9786f081509234f1a7f4684b5e5b76c9",
  "mint": "0x0",
  "nonce": "0x1869c95",
  "r": "0x0",
  "s": "0x0",
  "sourceHash": "0x9725bd582b526420beab9cb4eeeee1cdaa20f081253ce04e1bf4a485aad84019",
  "to": "0x4200000000000000000000000000000000000015",
  "transactionIndex": "0x0",
  "type": "0x7e",
  "v": "0x0",
  "value": "0x0"
}
```

@clabby @refcell do we have utils/types this in kona/maili?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Bisht13**
# Description

Add dummy system transaction in op reth if it is run in `dev` mode.

closes #14005
closes #13991

### CODE REVIEW

**Comment by Bisht13** [comment]
@mattsse let me know if you want me to add tests for the same as well!

File: crates/engine/local/src/payload.rs [hunk 1]
```diff
@@ -47,12 +47,22 @@ where
 impl<ChainSpec> PayloadAttributesBuilder<op_alloy_rpc_types_engine::OpPayloadAttributes>
     for LocalPayloadAttributesBuilder<ChainSpec>
 where
-    ChainSpec: Send + Sync + EthereumHardforks + 'static,
+    ChainSpec: Send + Sync + reth_chainspec::EthChainSpec + EthereumHardforks + 'static,
 {
     fn build(&self, timestamp: u64) -> op_alloy_rpc_types_engine::OpPayloadAttributes {
+        // Add dummy system transaction if running on the `dev` chain
+        let transactions = if self.chain_spec.chain() == alloy_chains::Chain::dev() {
```
Comment (mattsse) [inline crates/engine/local/src/payload.rs:54]: I think we can remove this check here in case the user runs --dev with a modified chain id

File: crates/optimism/chainspec/src/constants.rs [hunk 2]
```diff
@@ -9,3 +11,11 @@ pub const BASE_MAINNET_MAX_GAS_LIMIT: u64 = 105_000_000;
...
 /// Max gas limit on Base Sepolia: <https://sepolia.basescan.org/block/12506483>
 pub const BASE_SEPOLIA_MAX_GAS_LIMIT: u64 = 45_000_000;
+
+//----------------------------------- DEV ------------------------------------//
+
+/// Dummy system transaction for dev mode
+/// OP Mainnet transaction at index 0 in block 124665056.
+///
+/// <https://optimistic.etherscan.io/tx/0x312e290cf36df704a2217b015d6455396830b0ce678b860ebfcc30f41403d7b1>
+pub const TX_SET_L1_BLOCK_OP_MAINNET_BLOCK_124665056: [u8; 251] = hex!("7ef8f8a0683079df94aa5b9cf86687d739a60a9b4f0835e520ec4d664e2e415dca17a6df94deaddeaddeaddeaddeaddeaddeaddeaddead00019442000000000000000000000000000000000000158080830f424080b8a4440a5e200000146b000f79c500000000000000040000000066d052e700000000013ad8a3000000000000000000000000000000000000000000000000000000003ef1278700000000000000000000000000000000000000000000000000000000000000012fdf87b89884a61e74b322bbcf60386f543bfae7827725efaaf0ab1de2294a590000000000000000000000006887246668a3b87f54deb3b94ba47a6f63f32985");
```
Comment (mattsse) [inline crates/optimism/chainspec/src/constants.rs:21]: this should probably solve the rpc issues that @Quertyy faced

I consider this a nice short term fix, we can make this a bit smarter in followups,
e.g. actually crafting a system tx.

but before we can do this we need to solve a few other things that I'll scope now

**Review by mattsse — CHANGES_REQUESTED** [review]
ty,

smol nit

File: crates/engine/local/src/payload.rs (hunk 1 above)
Comment (Bisht13) [reply crates/engine/local/src/payload.rs:54]: Good point but what's the best way to find if the node is running in dev mode then, considering that if we keep this dummy transaction here then it would always be added in the block even if the node is not running in the dev mode, ref https://github.com/paradigmxyz/reth/blob/b6875b13af2f4cb754d6ea0811a3681088fc3518/crates/optimism/payload/src/payload.rs#L68, please correct me if I'm wrong

Comment (mattsse) [reply crates/engine/local/src/payload.rs:54]: here this is not possible but we only use this type here if in dev mode so we can just make the assumption

with #14064 we can solve this properly

Comment (Bisht13) [reply crates/engine/local/src/payload.rs]: Got it, resolved

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
@Quertyy confirmed that this fixes the issue, this (hacky) solution is only temporary, working on improvements separately

**Comment by Quertyy** [comment]
> @Quertyy confirmed that this fixes the issue, this (hacky) solution is only temporary, working on improvements separately

It works well, thank u for the quick fix @Bisht13
