### PR TITLE
fix: make canonical_chain atomic and canonical

### LINKED ISSUE #11282: canonical_chain is not atomic and does include the pending block
### Describe the feature

`CanonicalInMemoryState::canonical_chain` is supposed to return the in canonical chain but currently also includes the pending block.

it also doesn't access the blocks atomically, which could lead to incorrect chains in case of a race condition

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
closes #11282

this excludes the pending block from the canonical chain and captures all blocks at the time it is called.

some (incorrect) tests were updated by leveraging the intended insert block API.

### CODE REVIEW

File: crates/chain-state/src/in_memory.rs [hunk 1]
```diff
@@ -693,6 +682,29 @@ impl BlockState {
...
+
+impl Iterator for BlockStateIter {
+    type Item = Arc<BlockState>;
+
+    fn next(&mut self) -> Option<Self::Item> {
+        let current = self.current.take()?;
+        self.current = current.parent.clone();
+        Some(current)
+    }
 }
```
Comment (DaniPopes) [inline crates/chain-state/src/in_memory.rs:708]: This is exactly the impl of std::iter::successors
```rust
std::iter::successors(Some(self), |state| state.parent.clone())
```

Comment (mattsse) [reply crates/chain-state/src/in_memory.rs:708]: yes, but I prefer having this

Comment (mattsse) [reply crates/chain-state/src/in_memory.rs:708]: actually I changed my mind, the docs in iter should be sufficient

**Review by DaniPopes — APPROVED** [review]

**Review by joshieDo — APPROVED** [review]

File: crates/chain-state/src/in_memory.rs [hunk 2]
```diff
@@ -693,6 +682,13 @@ impl BlockState {
     pub fn append_parent_chain<'a>(&'a self, chain: &mut Vec<&'a Self>) {
         chain.extend(self.parent_state_chain());
     }
+
+    /// Returns an iterator over the atomically captured chain of in memory blocks.
+    ///
+    /// This yields the blocks from newest to oldest (highest to lowest).
+    pub fn iter(self: Arc<Self>) -> impl Iterator<Item = Arc<Self>> {
+        std::iter::successors(Some(self), |state| state.parent.clone())
```
Comment (DaniPopes) [inline crates/chain-state/src/in_memory.rs:690]: Can also use this in `parent_state_chain`?
