### PR TITLE
fix: call validate_execution_requests from validate_version_specific_fields for ethereum engine validator

### LINKED ISSUE #14933: Move validate_requests fn into validate version specific fields for ethereum engine validator
### Describe the feature

ref #14932

after we transitioned the engine api to operate on the entire executiondata we stopped calling
https://github.com/paradigmxyz/reth/blob/main/crates/engine/primitives/src/lib.rs#L140-L140

so we can remove this function and move this to the ethereum specific impl instead

https://github.com/paradigmxyz/reth/blob/main/crates/ethereum/node/src/engine.rs#L54-L54

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fgimenez**
Closes #14933

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
we can likely fix some of those with additional checks but imo this is unnecessary because any malformed requests will end up as invalid payload anyway

File: crates/ethereum/node/src/engine.rs [hunk 1]
```diff
@@ -56,6 +57,15 @@ where
         version: EngineApiMessageVersion,
         payload_or_attrs: PayloadOrAttributes<'_, Self::ExecutionData, EthPayloadAttributes>,
     ) -> Result<(), EngineObjectValidationError> {
+        if let PayloadOrAttributes::ExecutionPayload(payload) = &payload_or_attrs {
+            if let Some(prague_fields) = payload.sidecar.prague() {
+                if let RequestsOrHash::Requests(requests) = &prague_fields.requests {
```
Comment (mattsse) [inline crates/ethereum/node/src/engine.rs]: there's `fn requests -> Option<&Requests>`

File: crates/payload/primitives/src/payload.rs [hunk 2]
```diff
@@ -164,3 +167,28 @@ impl ExecutionPayload for op_alloy_rpc_types_engine::OpExecutionData {
...
+    ///
+    /// This will return `Some(requests)` only if:
+    /// - The payload is an `ExecutionData` (not `PayloadAttributes`)
+    /// - The payload has Prague payload fields
+    /// - The Prague fields contain requests (not a hash)
+    ///
+    /// Returns `None` in all other cases.
+    pub fn execution_requests(&self) -> Option<&Requests> {
+        if let Self::ExecutionPayload(payload) = self {
+            payload.sidecar.prague().and_then(|prague_fields| match &prague_fields.requests {
```
Comment (mattsse) [inline crates/payload/primitives/src/payload.rs:186]: there's also fn requests -> Option<&Requests> I believe

Comment (fgimenez) [reply crates/payload/primitives/src/payload.rs]: awesome thx! changes to use it here https://github.com/paradigmxyz/reth/pull/14932/commits/3cc6d1b160114bfea103a011ac5e78b1340e35ec

**Comment by fgimenez** [comment]
successful hive execution from this branch https://github.com/paradigmxyz/reth/actions/runs/13786338679

**Review by mattsse — CHANGES_REQUESTED** [review]
lgtm!

can we remove this function entirely

https://github.com/paradigmxyz/reth/blob/aaae30930f2227500037c8a8313f3f119b96db5d/crates/engine/primitives/src/lib.rs#L139-L145

**Review by mattsse — APPROVED** [review]
