### PR TITLE
fix: track invalid payload hashes

### LINKED ISSUE #2516: Track previously rejected blocks
### Describe the feature

`engine_forkchoiceUpdate` must return INVALID if the head belongs to a previously rejected payload

https://github.com/ethereum/execution-apis/blob/6709c2a795b707202e93c4f2867fa0bf2640a84f/src/engine/paris.md#payload-validation

```
./hive --client reth --sim ethereum/engine --sim.limit "/Invalid Transaction ChainID NewPayload"
``` 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
Closes #2516

this tracks invalid payloads so FCU can be checked if they belong to point to an invalid head

fixes various hive tests

ref https://github.com/ethereum/go-ethereum/blob/8f373227ac481685148019b21ef9e1478d3ba609/eth/catalyst/api.go#L589-L589

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -314,36 +356,17 @@ where
                     if let Some(attrs) = attrs {
                         // get header for further validation
                         let header = self
-                            .db
-                            .view(|tx| tx.get::<tables::Headers>(head_block_number))??
+                            .load_header(head_block_number)
+                            .ok()
```
Comment (rkrasiuk) [inline crates/consensus/beacon/src/engine/mod.rs:360]: if any db error occurs at this point, we'd lose it to the expect call below

File: crates/consensus/beacon/src/engine/mod.rs [hunk 2]
```diff
@@ -164,6 +171,9 @@ where
     payload_builder: PayloadBuilderHandle,
     /// Listeners for engine events.
     listeners: EventListeners<BeaconConsensusEngineEvent>,
+    /// Tracks the header of invalid payloads that were rejected by the engine because they're
+    /// invalid.
+    invalid_heads: InvalidHeaderCache,
```
Comment (rkrasiuk) [inline crates/consensus/beacon/src/engine/mod.rs:176]: nit: payload is not necessarily head
```suggestion
    invalid_headers: InvalidHeaderCache,
```

**Review by rkrasiuk — APPROVED** [review]
lgtm
