### PR TITLE
fix bug: synchronized local node record with discv4

### LINKED ISSUE #6961: --nat=extIp is not respected when querying the enode via admin_nodeInfo
### Describe the feature

this is most likely a bug where the local node record is not updated correctly

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/network/src/network.rs#L223-L223

because there are different mutexes:

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/discv4/src/lib.rs#L606-L617

one in discv4 and one in network

Since discovery is optional, we can fix this in a few ways, the simplest solution would be to give the NetworkInner type an Option of `Discv4` so we can use

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/discv4/src/lib.rs#L255-L265

in:

https://github.com/paradigmxyz/reth/blob/ebe72f7ae85f690ed3b64abd1986752b45e8cdd3/crates/net/network/src/network.rs#L221-L221

 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AbnerZheng**
close https://github.com/paradigmxyz/reth/issues/6961

### CODE REVIEW

File: crates/net/network/src/discovery.rs [hunk 1]
```diff
@@ -138,6 +138,11 @@ impl Discovery {
         }
     }
 
+    /// Returns a shared reference to the discv4.
+    pub fn discv4(&self) -> Option<Discv4> {
+        self.discv4.clone()
```
Comment (AbnerZheng) [inline crates/net/network/src/discovery.rs:143]: It should be thread safe to clone discv4:

```rust
/// The Discv4 frontend
///
/// This communicates with the [Discv4Service] by sending commands over a channel.
///
/// See also [Discv4::spawn]
#[derive(Debug, Clone)]
pub struct Discv4 {
    /// The address of the udp socket
    local_addr: SocketAddr,
    /// channel to send commands over to the service
    to_service: mpsc::UnboundedSender<Discv4Command>,
    /// Tracks the local node record.
    ///
    /// This includes the currently tracked external IP address of the node.
    node_record: Arc<Mutex<NodeRecord>>,
}
```

**Review by emhane — APPROVED** [review]
lgtm

File: crates/net/network/src/network.rs [hunk 2]
```diff
@@ -219,19 +222,23 @@ impl PeersInfo for NetworkHandle {
...
+            let id = *self.peer_id();
+            let mut socket_addr = *self.inner.listener_address.lock();
+
+            if socket_addr.ip().is_unspecified() {
+                // zero address is invalid
+                if socket_addr.ip().is_ipv4() {
+                    socket_addr.set_ip(std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST));
+                } else {
+                    socket_addr.set_ip(std::net::IpAddr::V6(std::net::Ipv6Addr::LOCALHOST));
+                }
```
Comment (emhane) [inline crates/net/network/src/network.rs:237]: not sure about this behaviour, I think the node record should advertise no ip when listening on all interfaces, not localhost. it could be WAN-reachable, just still waiting on nat or discv4 to resolve its WAN-reachable address. (@mattsse )

Comment (mattsse) [reply crates/net/network/src/network.rs:237]: it should include an ip, it just cant be 0.0.0.0, this is also how geth behaves:

```text
cast rpc admin_nodeInfo --rpc-url http://localhost:8548 | jq
{
  "id": "7f88ffc891d168a87d389b9a864dce5d5681ed36c86319b262de37d4eca22574",
  "name": "Geth/v1.13.11-stable/darwin-arm64/go1.21.6",
  "enode": "enode://3aa6582fd0a5e188c449927d1e870a717312cc45ad76216744d8852d1cb2dc9577d54421203bf90c9960bee5fec4150906e757e3cfb7f66c748c02666247bce1@127.0.0.1:30303",
```

File: crates/net/network/src/discovery.rs (hunk 1 above)
Comment (mattsse) [reply crates/net/network/src/discovery.rs:143]: yep this is intended for cloning

**Review by mattsse — APPROVED** [review]
thanks!

this should do it, but perhaps we should consider extracting external IP resolving from discv4 and make this a separate component
