### PR TITLE
fix(net): batch `P2PStream` sends

### LINKED ISSUE #8399: `P2PStream`, flush once at end of egress batch
### Describe the feature

`P2Pstream` calls `poll_flush` for each queued egress message, before calling `start_send` for the next. Instead, `poll_flush` should only be called once before the loop and once after the loop. [According to docs](https://docs.rs/futures/latest/futures/sink/trait.Sink.html#tymethod.start_send), `poll_ready` should be called before each call to `start_send`. So, this also requires modifying `poll_ready`, to not call `poll_flush`

This will increase egress throughput. The `Sink` implementation on the `P2PStream`, constraints the `Sink` implementation on all layers above, like `EthStream`.

https://github.com/paradigmxyz/reth/blob/72f2f1b850a9454789f3ebb3f6efccaee4125659/crates/net/eth-wire/src/p2pstream.rs#L619-L635

https://github.com/paradigmxyz/reth/blob/72f2f1b850a9454789f3ebb3f6efccaee4125659/crates/net/eth-wire/src/p2pstream.rs#L539-L574

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/8399

Fixes `Sink` impl. Calls `poll_ready` before `start_send`, instead of `poll_flush` before each call to `start_send` - the latter defeats the purpose of using `Framed` to batch sends. 

This fix ensures we don't do more syscalls than intended by `tokio_util::codec::Framed` frame size.

### CODE REVIEW

File: crates/net/eth-wire/src/p2pstream.rs [hunk 1]
```diff
@@ -613,19 +613,23 @@ where
...
-                    if let Err(err) = this.inner.as_mut().start_send(message) {
-                        return Poll::Ready(Err(err.into()))
-                    }
-                }
+        let res = loop {
+            // P2PStream wraps `reth_ecies::stream::ECIESStream` in node. `ECIESStream`
+            // internally wraps the network connection in `tokio_util::codec::Framed`.
+            //
+            // Call to `Framed::poll_ready` will flush internally, if limit for buffered messages
+            // reached. `Framed::poll_ready`, only returns `Poll::Pending` or `Poll::Ready(Err(e))`
```
Comment (mattsse) [inline crates/net/eth-wire/src/p2pstream.rs:621]: this is true, but this means we don't necessarily flush here?

before calling flush the caller already ensured that this sink is ready to flush, so doesn't seem right to me to do this again here

Comment (emhane) [reply crates/net/eth-wire/src/p2pstream.rs:621]: it's advised by the docs to call `poll_ready` before each call to `start_send`

> Begin the process of sending a value to the sink. Each call to this function must be preceded by a successful call to poll_ready which returned Poll::Ready(Ok(())).

https://docs.rs/futures/latest/futures/sink/trait.Sink.html#tymethod.start_send

I can see how it's necessary, because `FramedImpl` controls frame size. if its buffer is too full, it calls `poll_flush` as part of its`poll_ready` impl

Comment (mattsse) [reply crates/net/eth-wire/src/p2pstream.rs:621]: this is still the wrong order here, 

```
loop {
 ready
 send
}
```

does not seem appropriate here

Comment (emhane) [reply crates/net/eth-wire/src/p2pstream.rs:621]: pls elaborate

Comment (mattsse) [reply crates/net/eth-wire/src/p2pstream.rs:621]: calling ready+send here again before doing flush is not required because the caller already did that before calling flush, but I agree that the current impl violates the sink semantics

Comment (emhane) [reply crates/net/eth-wire/src/p2pstream.rs:621]: to respect the fram size, of underlying `Frame` impl that we use in `P2PStream` in `reth-network`, we must call `poll_ready` before `start_send`, as mentioned in the comment https://docs.rs/tokio-util/latest/src/tokio_util/codec/framed_impl.rs.html#262-268

Comment (mattsse) [reply crates/net/eth-wire/src/p2pstream.rs:621]: but this is already done before calling flush so doing it again in flush seems pointless to me

Comment (emhane) [reply crates/net/eth-wire/src/p2pstream.rs:621]: sure, but for `Framed` to decide the frame size, we need to call it again before every call to its`start_send` method, so that the `Framed` interface can decide, if so many items have been queued with the previous calls to `start_send`, that it is time for `Framed` to flush again

Comment (mattsse) [reply crates/net/eth-wire/src/p2pstream.rs:621]: then this isn't the right fix
because we only need to call flush then

Comment (emhane) [reply crates/net/eth-wire/src/p2pstream.rs:621]: `poll_ready` on `Framed` calls flush

**Comment by DaniPopes** [comment]
Sorry I don't know this code or async stuff in general enough to review this

**Review by mattsse — CHANGES_REQUESTED** [review]
this loop might never flush, depending on the poll_ready impl of the wrapped sink.

we should restore the previous logic, but ensuring we can start send all buffered messages by calling poll_ready first

**Comment by emhane** [comment]
> this loop might never flush, depending on the poll_ready impl of the wrapped sink.
> 
> we should restore the previous logic, but ensuring we can start send all buffered messages by calling poll_ready first

the previous logic defeats the purpose of using `Framed` in the node. we can break on pending, instead of return early, to make sure flush is called also then.

**Comment by emhane** [comment]
ping @mattsse

**Review by mattsse — CHANGES_REQUESTED** [review]
~~again, this is specialized logic for framed as is the main version, but this type is generic over sink~~

flush should flush and also flush any remaining currently buffered items.

~~this loop logic is incorrect it should flush first then continue popping and sending + flushing buffered items.~~

sorry I reviewed an outdated state

File: crates/net/eth-wire/src/p2pstream.rs [hunk 2]
```diff
@@ -613,19 +613,31 @@ where
...
-                Err(err) => return Poll::Ready(Err(err.into())),
-                Ok(()) => {
+        let poll_res = loop {
+            // P2PStream wraps `reth_ecies::stream::ECIESStream` in node. `ECIESStream`
+            // internally wraps the network connection in `tokio_util::codec::Framed`.
+            //
+            // Call to `Framed::poll_ready` will flush internally, if limit for buffered messages
+            // reached. `Framed::poll_ready`, only returns `Poll::Pending` or `Poll::Ready(Err(e))`
+            // if it had to call flush - no need to explicitly flush the batch again before
+            // propagating pending or error.
```
Comment (mattsse) [inline crates/net/eth-wire/src/p2pstream.rs:623]: these are specialized docs for framed but this type is generic over any sink type, please rephrase to be general

**Review by mattsse — APPROVED** [review]
doc nit, otherwise this makes sense to me now
