### PR TITLE
revert: "refactor(prune): remove receipts log filter segment (#19184)"

### LINKED ISSUE #19621: `v1.9.1` crashes immediately on Hoodi
### Describe the bug

We tried to upgrade from `1.8.4` to `1.9.1`, unfortunately we are getting this log

We tried to enable trace logs (`-vvvvv`), but the output above is all we got. Downgrading to `1.8.4` fixes the issue

CL: lighthouse `8.0.0`

### Steps to reproduce

1. Update to `v1.9.1`
2. Start container

### Node logs

```text
reth_hoodi-1  | 2025-11-06T20:12:25.131782Z  INFO StaticFileProducer initialized
reth_hoodi-1  | 2025-11-06T20:12:25.135575Z ERROR shutting down due to error
reth_hoodi-1  | Error: trying to append row to Receipts at index #488 but expected index #239
reth_hoodi-1  | 
reth_hoodi-1  | Location:
reth_hoodi-1  |     /home/runner/work/reth/reth/crates/node/builder/src/launch/engine.rs:157:9
```

### Platform(s)

Linux (x86)

### Container Type

Docker

### What version/commit are you on?

`v1.9.1`

### What database version are you on?

```
Current database version: 2
Local database version: 2
```

### Which chain / network are you on?

Hoodi

### What type of node are you running?

Pruned with custom reth.toml config

### What prune config do you use, if any?

```
[prune]
block_interval = 5

# Stakewise
[prune.segments.receipts_log_filter.0xa7d1ac9d6f32b404c75626874ba56f7654c1dc0f]
before = 94070

[prune.segments.receipts_log_filter.0x00000000219ab540356cBB839Cbe05303d7705Fa]
before = 0
```

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [x] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by shekhirin**
This reverts commit b5df3f31b28adda9879b086b7d91b0863f300eec.

Fixes https://github.com/paradigmxyz/reth/issues/19621.

### CODE REVIEW

File: crates/static-file/static-file/src/static_file_producer.rs [hunk 1]
```diff
@@ -194,7 +194,9 @@ where
 
         let targets = StaticFileTargets {
             // StaticFile receipts only if they're not pruned according to the user configuration
-            receipts: if self.prune_modes.receipts.is_none() {
+            receipts: if self.prune_modes.receipts.is_none() &&
+                self.prune_modes.receipts_log_filter.is_empty()
+            {
```
Comment (joshieDo) [inline crates/static-file/static-file/src/static_file_producer.rs:199]: as discussed, we should have a follow-up PR about `StorageSettings.receipts_in_static_files`

not here, so we can have a clean revert and just cherry-pick this on top of 1.9.x

Comment (shekhirin) [reply crates/static-file/static-file/src/static_file_producer.rs:199]: but not critical for this PR that will go into 1.9.2 because `receipts_in_static_files` is always false anyway

**Review by joshieDo — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
