### PR TITLE
Patch/Auto-mine

### LINKED ISSUE #5009: RETH --dev node not able to mine blocks using auto-seal consensus
### Discussed in https://github.com/paradigmxyz/reth/discussions/5008

<div type='discussions-op-text'>

<sup>Originally posted by **bbist** October 13, 2023</sup>
I'm not sure if this is the right place to ask this question. But I'm running into an issue while running dev node deployment and testing.

I've followed the [tutorial here](https://blog.superchain.network/inside-reth-the-journey-of-a-tranaction-through-ethereum/), to setup a dev node. I'm using following command to start a node, from [reth source](https://github.com/paradigmxyz/reth).
```bash
RUST_LOG='debug,evm=trace,consensus::auto=trace,consensus::engine=trace' \
    cargo run node --dev \
    --chain ../../reth-local/genesis.json \
    --datadir ../../reth-local/data/ \
    --http.corsdomain "*"
```

Here's my `genesis.json` config file.
```json
{
  "nonce": "0x42",
  "timestamp": "0x0",
  "extraData": "0x5343",
  "gasLimit": "0x1388",
  "difficulty": "0x400000000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0x2BB7DcEeB1964D1c2EdbCbB04Cd7893F6619d4c0": {
      "balance": "1000000000000000000000000000"
    },
    "0xfCd9569Ab54097047D3b512510674826aaf444d6": {
      "balance": "1000000000000000000000000000"
    },
    "0xaD777372eBde0e5E484362581D0aE962a17fc628": {
      "balance": "1000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "config": {
    "ethash": {},
    "chainId": 1337,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "terminalTotalDifficulty": 0,
    "terminalTotalDifficultyPassed": true,
    "shanghaiTime": 0
  }
}
```

After the node has started, when I send a simple transfer transaction, it doesn't work.
```
# transfer
cast send --from 0x2BB7DcEeB1964D1c2EdbCbB04Cd7893F6619d4c0 \
    --value 1 \
    --private-key <MY_PRIVATE_KEY> \
    0x0C01B8039F5f824291E2d85E24eE59a361FD9458
```

The RETH runtime has following logs.
```log
2023-10-13T06:25:54.988323Z TRACE consensus::auto: executing transactions transactions=[TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) }]
2023-10-13T06:25:54.988770Z TRACE evm: Executed transaction transaction=TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) } result=Success { reason: Stop, gas_used: 21000, gas_refunded: 0, logs: [], output: Call(Bytes(0x)) } state={0x0000000000000000000000000000000000000000: Account { info: AccountInfo { balance: 0x0000000000000000000000000000000000000000000000000000394c549ef000_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: Some(Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }) }, storage: {}, status: AccountStatus(Touched | LoadedAsNotExisting) }, 0x2bb7dceeb1964d1c2edbcbb04cd7893f6619d4c0: Account { info: AccountInfo { balance: 0x0000000000000000000000000000000000000000033b2e3c9fd0363a500809ff_U256, nonce: 1, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: None }, storage: {}, status: AccountStatus(Touched) }, 0x0c01b8039f5f824291e2d85e24ee59a361fd9458: Account { info: AccountInfo { balance: 0x0000000000000000000000000000000000000000000000000000000000000001_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: Some(Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }) }, storage: {}, status: AccountStatus(Touched | LoadedAsNotExisting) }}
2023-10-13T06:25:54.988928Z TRACE consensus::auto: executed block, calculating state root and completing header bundle_state=BundleStateWithReceipts { bundle: BundleState { state: {0x0000000000000000000000000000000000000000: BundleAccount { info: Some(AccountInfo { balance: 0x0000000000000000000000000000000000000000000000000000394c549ef000_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: Some(Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }) }), original_info: None, storage: {}, status: InMemoryChange }, 0x2bb7dceeb1964d1c2edbcbb04cd7893f6619d4c0: BundleAccount { info: Some(AccountInfo { balance: 0x0000000000000000000000000000000000000000033b2e3c9fd0363a500809ff_U256, nonce: 1, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: None }), original_info: Some(AccountInfo { balance: 0x0000000000000000000000000000000000000000033b2e3c9fd0803ce8000000_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: None }), storage: {}, status: InMemoryChange }, 0x0c01b8039f5f824291e2d85e24ee59a361fd9458: BundleAccount { info: Some(AccountInfo { balance: 0x0000000000000000000000000000000000000000000000000000000000000001_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: Some(Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }) }), original_info: None, storage: {}, status: InMemoryChange }}, contracts: {0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470: Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }}, reverts: Reverts([[(0x0000000000000000000000000000000000000000, AccountRevert { account: DeleteIt, storage: {}, previous_status: LoadedNotExisting, wipe_storage: false }), (0x2bb7dceeb1964d1c2edbcbb04cd7893f6619d4c0, AccountRevert { account: RevertTo(AccountInfo { balance: 0x0000000000000000000000000000000000000000033b2e3c9fd0803ce8000000_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: None }), storage: {}, previous_status: Loaded, wipe_storage: false }), (0x0c01b8039f5f824291e2d85e24ee59a361fd9458, AccountRevert { account: DeleteIt, storage: {}, previous_status: LoadedNotExisting, wipe_storage: false })]]), state_size: 3, reverts_size: 3 }, receipts: Receipts { receipt_vec: [[Some(Receipt { tx_type: EIP1559, success: true, cumulative_gas_used: 21000, logs: [] })]] }, first_block: 0 } header=Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x0000000000000000000000000000000000000000000000000000000000000000, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x0000000000000000000000000000000000000000000000000000000000000000, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 0, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) } body=BlockBody { transactions: [TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) }], ommers: [], withdrawals: None }
2023-10-13T06:25:54.989104Z TRACE consensus::auto: complete header receipts receipts=Receipts { receipt_vec: [[Some(Receipt { tx_type: EIP1559, success: true, cumulative_gas_used: 21000, logs: [] })]] } header=Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x0000000000000000000000000000000000000000000000000000000000000000, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x0000000000000000000000000000000000000000000000000000000000000000, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 0, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) } first_block=0
2023-10-13T06:25:54.989598Z DEBUG loader: calculating state root
2023-10-13T06:25:54.989705Z DEBUG trie::storage_root: calculating storage root hashed_address=0x2964adcee560331669beab7866a3e713e48b6de5e6c5c5c2f6eaaa1aefc1bdf5
2023-10-13T06:25:54.989761Z DEBUG trie::storage_root: calculating storage root hashed_address=0x2f79bcb7e2c8c62a17964aa9ee585f5cfd53e88460d7f057bc03ba6c62947915
2023-10-13T06:25:54.989774Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "020906040a0d0c0e0e0506000303010606090b0e0a0b070806060a030e0701030e04080b060d0e050e060c050c050c020f060e0a0a0a010a0e0f0c010b0d0f05" } succeeding=Nibbles { hex_data: "020f07090b0c0b070e020c080c06020a01070906040a0a090e0e0508050f050c0f0d05030e08080406000d070f0005070b0c00030b0a060c0602090407090105" }
2023-10-13T06:25:54.989793Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "2064adcee560331669beab7866a3e713e48b6de5e6c5c5c2f6eaaa1aefc1bdf5", value: "f850808c033b2e3c9fd0803ce8000000a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470" }
2023-10-13T06:25:54.989848Z DEBUG trie::storage_root: calculating storage root hashed_address=0x5380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a
2023-10-13T06:25:54.989897Z DEBUG trie::storage_root: calculated storage root root=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 hashed_address=0x5380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a
2023-10-13T06:25:54.989907Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "020f07090b0c0b070e020c080c06020a01070906040a0a090e0e0508050f050c0f0d05030e08080406000d070f0005070b0c00030b0a060c0602090407090105" } succeeding=Nibbles { hex_data: "050308000c070b070a0e08010a05080e0b09080d090c07080d0e040a010f0d070f0d090503050f0c0905030e0d020b0e0600020d0a0a0a04010706070301020a" }
2023-10-13T06:25:54.989919Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "2079bcb7e2c8c62a17964aa9ee585f5cfd53e88460d7f057bc03ba6c62947915", value: "f850808c033b2e3c9fd0803ce8000000a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470" }
2023-10-13T06:25:54.989972Z DEBUG trie::hash_builder: resizing stack to prepare branch node new_len=0 old_len=2
2023-10-13T06:25:54.989982Z DEBUG trie::hash_builder: pushing branch node with TrieMask(1000001000000000) mask from stack
2023-10-13T06:25:54.990005Z DEBUG trie::storage_root: calculating storage root hashed_address=0x7d3e1148548d449b3cdd831ae135ddfbba58bd768125a7d61ac5c76212c83d53
2023-10-13T06:25:54.990021Z DEBUG trie::storage_root: calculated storage root root=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 hashed_address=0x7d3e1148548d449b3cdd831ae135ddfbba58bd768125a7d61ac5c76212c83d53
2023-10-13T06:25:54.990031Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "050308000c070b070a0e08010a05080e0b09080d090c07080d0e040a010f0d070f0d090503050f0c0905030e0d020b0e0600020d0a0a0a04010706070301020a" } succeeding=Nibbles { hex_data: "070d030e010104080504080d0404090b030c0d0d0803010a0e0103050d0d0f0b0b0a05080b0d0706080102050a070d06010a0c050c07060201020c08030d0503" }
2023-10-13T06:25:54.990044Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "3380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a", value: "f84a8086394c549ef000a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470" }
2023-10-13T06:25:54.990084Z DEBUG trie::storage_root: calculating storage root hashed_address=0x9e2a364ec23697a60e55a25ed6c9c33f315aa65fb02caa0369e0e79e26b82c37
2023-10-13T06:25:54.990100Z DEBUG trie::storage_root: calculated storage root root=0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 hashed_address=0x9e2a364ec23697a60e55a25ed6c9c33f315aa65fb02caa0369e0e79e26b82c37
2023-10-13T06:25:54.990109Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "070d030e010104080504080d0404090b030c0d0d0803010a0e0103050d0d0f0b0b0a05080b0d0706080102050a070d06010a0c050c07060201020c08030d0503" } succeeding=Nibbles { hex_data: "090e020a0306040e0c02030609070a06000e05050a02050e0d060c090c03030f0301050a0a06050f0b00020c0a0a000306090e000e07090e02060b08020c0307" }
2023-10-13T06:25:54.990121Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "3d3e1148548d449b3cdd831ae135ddfbba58bd768125a7d61ac5c76212c83d53", value: "f8448001a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470" }
2023-10-13T06:25:54.990150Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "090e020a0306040e0c02030609070a06000e05050a02050e0d060c090c03030f0301050a0a06050f0b00020c0a0a000306090e000e07090e02060b08020c0307" } succeeding=Nibbles { hex_data: "" }
2023-10-13T06:25:54.990161Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "3e2a364ec23697a60e55a25ed6c9c33f315aa65fb02caa0369e0e79e26b82c37", value: "f850018c033b2e3c9fd0363a500809ffa056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a0c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470" }
2023-10-13T06:25:54.990220Z DEBUG trie::hash_builder: resizing stack to prepare branch node new_len=0 old_len=4
2023-10-13T06:25:54.990228Z DEBUG trie::hash_builder: pushing branch node with TrieMask(0000001010100100) mask from stack
2023-10-13T06:25:54.990233Z DEBUG trie::hash_builder: intermediate node node=BranchNodeCompact { state_mask: TrieMask(0000001010100100), tree_mask: TrieMask(0000000000000000), hash_mask: TrieMask(0000000000000100), hashes: [0x6efb0f2ab046d6e43d3ce0043306883d4dca4b3b70db468c7fd76e5a7e1a1a0d], root_hash: Some(0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7) }
2023-10-13T06:25:54.990255Z TRACE consensus::auto: calculated root root=0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7 body=BlockBody { transactions: [TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) }], ommers: [], withdrawals: None } header=Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 21000, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) }
2023-10-13T06:25:54.990388Z TRACE consensus::auto: inserting new block num=1 hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9
2023-10-13T06:25:54.990458Z DEBUG consensus::auto: Sent fork choice update state=ForkchoiceState { head_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, safe_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, finalized_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 }
2023-10-13T06:25:54.990533Z TRACE consensus::engine: Received new forkchoice state update state=ForkchoiceState { head_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, safe_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, finalized_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 }
2023-10-13T06:25:54.990678Z DEBUG blockchain_tree: Block hash not found in block indices block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9
2023-10-13T06:25:54.990760Z  WARN consensus::engine: Failed to canonicalize the head hash error=Canonical(BlockchainTree(BlockHashNotFoundInChain { block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 })) state=ForkchoiceState { head_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, safe_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, finalized_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 }
2023-10-13T06:25:54.990808Z TRACE consensus::engine: Triggering full block download for missing ancestors of the new head request=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9
2023-10-13T06:25:54.990816Z TRACE consensus::engine::sync: Start downloading full block hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9
2023-10-13T06:25:54.990844Z DEBUG consensus::engine: Syncing to new target target=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9
2023-10-13T06:25:54.990853Z TRACE consensus::engine: Returning forkchoice status status=PayloadStatus { status: Syncing, latest_valid_hash: None } state=ForkchoiceState { head_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, safe_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, finalized_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 }
2023-10-13T06:25:54.990878Z TRACE consensus::auto: received headers request request=HeadersRequest { start: Hash(0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9), limit: 1, direction: Rising }
2023-10-13T06:25:54.990887Z DEBUG consensus::auto: Forkchoice update returned SYNCING, waiting for VALID fcu_response=OnForkChoiceUpdated { forkchoice_status: Syncing, fut: Left(Ready(Some(Ok(ForkchoiceUpdated { payload_status: PayloadStatus { status: Syncing, latest_valid_hash: None }, payload_id: None })))) }
2023-10-13T06:25:54.990907Z  INFO reth::node::events: Forkchoice updated head_block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 safe_block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 finalized_block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 status=Syncing
2023-10-13T06:25:54.990922Z DEBUG consensus::auto: Sent fork choice update state=ForkchoiceState { head_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, safe_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, finalized_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 }
2023-10-13T06:25:54.990917Z TRACE consensus::auto: returning headers headers=[Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 21000, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) }]
2023-10-13T06:25:54.991086Z TRACE consensus::auto: received bodies request hashes=[0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9]
2023-10-13T06:25:54.991101Z TRACE consensus::auto: returning bodies bodies=[BlockBody { transactions: [TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) }], ommers: [], withdrawals: None }]
2023-10-13T06:25:54.991150Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "0800" } succeeding=Nibbles { hex_data: "" }
2023-10-13T06:25:54.991162Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "2080", value: "02f86d8205398084b2d05e0085012a05f200825208940c01b8039f5f824291e2d85e24ee59a361fd94580180c080a0de38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cca00257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361" }
2023-10-13T06:25:54.991222Z TRACE consensus::engine: Received single full block, buffering block=(1, 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9)
2023-10-13T06:25:54.991258Z TRACE consensus::engine: Downloaded full block hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 number=1
2023-10-13T06:25:54.991609Z DEBUG blockchain_tree: Appending block to canonical chain head=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 parent=(0, 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4)
2023-10-13T06:25:54.991717Z TRACE evm: Executed transaction transaction=TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) } result=Success { reason: Stop, gas_used: 21000, gas_refunded: 0, logs: [], output: Call(Bytes(0x)) } state={0x0000000000000000000000000000000000000000: Account { info: AccountInfo { balance: 0x0000000000000000000000000000000000000000000000000000394c549ef000_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: Some(Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }) }, storage: {}, status: AccountStatus(Touched | LoadedAsNotExisting) }, 0x2bb7dceeb1964d1c2edbcbb04cd7893f6619d4c0: Account { info: AccountInfo { balance: 0x0000000000000000000000000000000000000000033b2e3c9fd0363a500809ff_U256, nonce: 1, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: None }, storage: {}, status: AccountStatus(Touched) }, 0x0c01b8039f5f824291e2d85e24ee59a361fd9458: Account { info: AccountInfo { balance: 0x0000000000000000000000000000000000000000000000000000000000000001_U256, nonce: 0, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470, code: Some(Bytecode { bytecode: Bytes(0x00), state: Analysed { len: 0, jump_map: JumpMap { map: "00" } } }) }, storage: {}, status: AccountStatus(Touched | LoadedAsNotExisting) }}
2023-10-13T06:25:54.991819Z DEBUG trie::hash_builder: updating merkle tree current=Nibbles { hex_data: "0800" } succeeding=Nibbles { hex_data: "" }
2023-10-13T06:25:54.991830Z DEBUG trie::hash_builder: pushing leaf node leaf_node=LeafNode { key: "2080", value: "02f9010801825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0" }
2023-10-13T06:25:54.991894Z DEBUG evm: receipts verification failed error=Validation(ReceiptRootDiff { got: 0xf78dfb743fbd92ade140711c8bbc542b5e307f0ab7984eff35d751969fe57efa, expected: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 }) receipts=[Receipt { tx_type: EIP1559, success: true, cumulative_gas_used: 21000, logs: [] }]
2023-10-13T06:25:54.991934Z  WARN consensus::engine: Failed to insert downloaded block err=InsertBlockError { error: Execution(Validation(ReceiptRootDiff { got: 0xf78dfb743fbd92ade140711c8bbc542b5e307f0ab7984eff35d751969fe57efa, expected: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 })), hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, number: 1, parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, num_txs: 1, .. }
2023-10-13T06:25:54.991960Z  WARN consensus::engine: Marking block as invalid invalid_number=1 invalid_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 err=Execution(Validation(ReceiptRootDiff { got: 0xf78dfb743fbd92ade140711c8bbc542b5e307f0ab7984eff35d751969fe57efa, expected: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 }))
2023-10-13T06:25:54.991972Z  WARN consensus::engine: Bad block with hash hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 header=Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 21000, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) }
2023-10-13T06:25:54.992021Z TRACE consensus::engine: Received new forkchoice state update state=ForkchoiceState { head_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, safe_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9, finalized_block_hash: 0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 }
2023-10-13T06:25:54.992069Z ERROR consensus::auto: Forkchoice update returned invalid response fcu_response=OnForkChoiceUpdated { forkchoice_status: Invalid, fut: Left(Ready(Some(Ok(ForkchoiceUpdated { payload_status: PayloadStatus { status: Invalid { validation_error: "links to previously rejected block" }, latest_valid_hash: Some(0x0000000000000000000000000000000000000000000000000000000000000000) }, payload_id: None })))) }
2023-10-13T06:25:54.992074Z  INFO reth::node::events: Forkchoice updated head_block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 safe_block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 finalized_block_hash=0xb842fc028a751a76653c579b5f36452df7e1fc71b287d5cff208b55f165ed6d9 status=Invalid
2023-10-13T06:25:55.093006Z DEBUG hyper::proto::h1::io: parsed 4 headers
2023-10-13T06:25:55.093020Z DEBUG hyper::proto::h1::conn: incoming body is content-length (140 bytes)
2023-10-13T06:25:55.093053Z DEBUG hyper::proto::h1::conn: incoming body completed
2023-10-13T06:25:55.093335Z DEBUG hyper::proto::h1::io: flushed 282 bytes
```

It shows a forkchoiceUpdate error:
```
2023-10-13T06:25:54.992069Z ERROR consensus::auto: Forkchoice update returned invalid response fcu_response=OnForkChoiceUpdated { forkchoice_status: Invalid, fut: Left(Ready(Some(Ok(ForkchoiceUpdated { payload_status: PayloadStatus { status: Invalid { validation_error: "links to previously rejected block" }, latest_valid_hash: Some(0x0000000000000000000000000000000000000000000000000000000000000000) }, payload_id: None })))) }
```

To debug, I've added a trace log in the `crates/consensus/auto-seal/src/lib.rs` file.
```rust
    /// Fills in the post-execution header fields based on the given BundleState and gas used.
    /// In doing this, the state root is calculated and the final header is returned.
    pub(crate) fn complete_header<S: StateProviderFactory>(
        &self,
        mut header: Header,
        bundle_state: &BundleStateWithReceipts,
        client: &S,
        gas_used: u64,
    ) -> Result<Header, BlockExecutionError> {
        let receipts = bundle_state.receipts_by_block(header.number);
==>     trace!(target: "consensus::auto", receipts=?bundle_state.receipts(), header=?&header, first_block=?&bundle_state.first_block(), "complete header receipts");

        header.receipts_root = if receipts.is_empty() {
            EMPTY_RECEIPTS
        } else {
            let receipts_with_bloom = receipts
                .iter()
                .map(|r| (*r).clone().expect("receipts have not been pruned").into())
                .collect::<Vec<ReceiptWithBloom>>();
            header.logs_bloom =
                receipts_with_bloom.iter().fold(Bloom::ZERO, |bloom, r| bloom | r.bloom);
            proofs::calculate_receipt_root(&receipts_with_bloom)
        };
```

It shows following trace in the above log.
```
2023-10-13T06:25:54.989104Z TRACE consensus::auto: complete header receipts receipts=Receipts { receipt_vec: [[Some(Receipt { tx_type: EIP1559, success: true, cumulative_gas_used: 21000, logs: [] })]] } header=Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x0000000000000000000000000000000000000000000000000000000000000000, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x0000000000000000000000000000000000000000000000000000000000000000, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 0, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) } first_block=0
```

Even though the receipts contains relevant data for the produced block, it's not used while completing the header inside the `build_and_execute()` method in the same file.
```rust
pub(crate) fn build_and_execute(
...
        // fill in the rest of the fields
        let header = self.complete_header(header, &bundle_state, client, gas_used)?;
==>     trace!(target: "consensus::auto", root=?header.state_root, ?body, ?header, "calculated root");
...
```

It shows the calculated root inside the complete header to be an empty receipts root.
```
2023-10-13T06:25:54.990255Z TRACE consensus::auto: calculated root root=0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7 body=BlockBody { transactions: [TransactionSigned { hash: 0xfc66ec132b671c65ec719a0c2e1c5a31f9529677f498bd19c3fbcd298b573569, signature: Signature { r: 0xde38130211eda40106644652017ed2893aaba7b7c16ad9d0932cc2df1dda08cc_U256, s: 0x0257f2c26a41caede387d2447f5632cbe70913d8355ec1c3b0f8fece8c996361_U256, odd_y_parity: false }, transaction: Eip1559(TxEip1559 { chain_id: 1337, nonce: 0, gas_limit: 21000, max_fee_per_gas: 5000000000, max_priority_fee_per_gas: 3000000000, to: Call(0x0c01b8039f5f824291e2d85e24ee59a361fd9458), value: TxValue(0x0000000000000000000000000000000000000000000000000000000000000001_U256), access_list: AccessList([]), input: Bytes(0x) }) }], ommers: [], withdrawals: None } header=Header { parent_hash: 0x0a65fa8e42a3df5c297546d7dc2804223860d190b0518eac6d4df1cf59d623a4, ommers_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, beneficiary: 0x0000000000000000000000000000000000000000, state_root: 0x5b85b0362e9ce3dbf3a9648d7458f284ab2b658114487e81c431982f49a9fea7, transactions_root: 0x39d3fe9eedf81225a352ce051ebcb933b4ed6c3c19567198263269cf6b44d76a, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, withdrawals_root: None, logs_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, difficulty: 0x0000000000000000000000000000000000000000000000000000000000000002_U256, number: 1, gas_limit: 30000000, gas_used: 21000, timestamp: 1697178354, mix_hash: 0x0000000000000000000000000000000000000000000000000000000000000000, nonce: 0, base_fee_per_gas: Some(875000000), blob_gas_used: None, excess_blob_gas: None, parent_beacon_block_root: None, extra_data: Bytes(0x) }
```

Hence it fails to validate the reciept root of the header vs the evm execution result.

Is this a bug or I'm missing something. I'd appreciate if some can help me with this. I'm trying to implement a new consensus module, but figuring out the `auto-seal` module might be very helpful. I'm kind of new to rust as well as the `reth` codebase.</div>

### PR DESCRIPTION
**Pull request by grantkee**
- add `EVMProcessor::set_first_block` method to set the first block so `BundleStateWithReceipts` finds the correct index by block number
- integration test for auto-mine consensus

closes #5009

### CODE REVIEW

**Review by Rjected — CHANGES_REQUESTED** [review]
This mitigates the issue, but the root cause seems to be that the `first_block` field is not set in the `EvmProcessor`, causing it to be zero in the `BundleStateWithReceipts`, which messes up the index conversion. Creating a `EVMProcessor::set_first_block` method, and calling that here:
https://github.com/paradigmxyz/reth/blob/3eb02656ca5df78c62dd24a2503ad796c384eb9c/crates/consensus/auto-seal/src/lib.rs#L295-L304

seems like the best way to fix the problem

**Comment by grantkee** [comment]
Thanks for the feedback @Rjected - I'll update my PR soon!

File: crates/consensus/auto-seal/tests/it/auto_mine.rs [hunk 1]
```diff
@@ -0,0 +1,215 @@
...
+        "eip150Block": 0,
+        "eip155Block": 0,
+        "eip158Block": 0,
+        "byzantiumBlock": 0,
+        "constantinopleBlock": 0,
+        "petersburgBlock": 0,
+        "istanbulBlock": 0,
+        "berlinBlock": 0,
+        "londonBlock": 0,
+        "terminalTotalDifficulty": 0,
```
Comment (Rjected) [inline crates/consensus/auto-seal/tests/it/auto_mine.rs:190]: best to just construct the `Genesis` in memory, and use the struct to initialize the `ChainSpec`

File: bin/reth/src/node/mod.rs [hunk 2]
```diff
@@ -555,6 +559,34 @@ impl<Ext: RethCliExt> NodeCommand<Ext> {
...
+    // bob well-known private key: 0x99b3c12287537e38c90a9219d4cb074a89a16e9cdb20bf85728ebd97c343e342
+    let bob_address = reth_primitives::hex!("6Be02d1d3665660d22FF9624b7BE0551ee1Ac91b").into();
+    let bob_account = reth_primitives::GenesisAccount::default().with_balance(reth_primitives::U256::from(10_000));
+
+    let accounts: std::collections::HashMap<reth_primitives::Address, reth_primitives::GenesisAccount> = std::collections::HashMap::from([
+        (bob_address, bob_account),
+    ]);
+
+    reth_primitives::Genesis::default().extend_accounts(accounts)
+}
```
Comment (Rjected) [inline bin/reth/src/node/mod.rs:589]: we should not have any new code in `bin/reth/src/node/mod.rs`

**Review by Rjected — CHANGES_REQUESTED** [review]
if setting the first block worked, we need a few main things to get this merged:
 * test cleanup
 * remove traces

I can help debug if it didn't work

**Comment by grantkee** [comment]
@Rjected Setting the first block worked. I added an integration test and removed all my debugging. I'm ready for you to review again

**Comment by mattsse** [comment]
tests failing

**Comment by grantkee** [comment]
> tests failing

I'm seeing an error during runner's compilation. Specifically, during manual-p2p `linking with cc failed` and a note about `collect2: fatal error: ld terminated with signal 9 [Killed] compilation terminated.`

The note makes me think that the runner is running out of memory during the linking process. I'm not sure what to do next. Any suggestions?

**Comment by Rjected** [comment]
> The note makes me think that the runner is running out of memory during the linking process. I'm not sure what to do next. Any suggestions?

hmm, let me look into the worker

File: crates/consensus/auto-seal/tests/it/auto_mine.rs [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+
+                update = canon_events.recv() => {
+                    let event = update.expect("canon events stream is still open");
+                    let new_tip = event.tip();
+                    let expected_tx_root: FixedBytes<32> = hex!("c79b5383458e63fb20c6a49d9ec7917195a59003a2af4b28a01d7c6fbbcd7e35").into();
+                    assert_eq!(new_tip.transactions_root, expected_tx_root);
+                    assert_eq!(new_tip.number, 1);
+                    assert!(pool.pending_transactions().is_empty());
+                }
+            }
```
Comment (Rjected) [inline crates/consensus/auto-seal/tests/it/auto_mine.rs:53]: should be able to use tokio timeout here: https://docs.rs/tokio/latest/tokio/time/fn.timeout.html

**Review by Rjected — CHANGES_REQUESTED** [review]
Just one style nit, otherwise this looks good to me

File: crates/consensus/auto-seal/tests/it/auto_mine.rs (hunk 3 above)
Comment (grantkee) [reply crates/consensus/auto-seal/tests/it/auto_mine.rs]: good call

**Review by mattsse — APPROVED** [review]

**Review by Rjected — APPROVED** [review]
LGTM, tysm!
