### PR TITLE
Ensure consistency between aborted set and reused ptrs

### LINKED ISSUE #6843: Inconsistency aborted read transactions <> reassigned mdbx pointers
### Describe the feature

Read transactions aren't removed from the set of aborted transactions if they are successfully reassigned by mdbx. The following test fails at assertion `assert!(!read_transactions.aborted.contains(&tx_ptr))`.

```rust
#[test]
        fn txn_manager_reassign_transaction_removes_from_aborted_transactions() {
            const MAX_DURATION: Duration = Duration::from_secs(1);

            let dir = tempdir().unwrap();
            let env = Environment::builder()
                .set_max_read_transaction_duration(MaxReadTransactionDuration::Set(MAX_DURATION))
                .open(dir.path())
                .unwrap();

            let read_transactions = env.txn_manager().read_transactions.as_ref().unwrap();

            // Create a read-only transaction, wait until `MAX_DURATION` time is elapsed so the
            // manager kills it, use it and observe the `Error::ReadTransactionAborted` error.
            {
                let tx = env.begin_ro_txn().unwrap();
                let tx_ptr = tx.txn() as usize;
                assert!(read_transactions.active.contains_key(&tx_ptr));

                sleep(MAX_DURATION + READ_TRANSACTIONS_CHECK_INTERVAL);

                assert!(!read_transactions.active.contains_key(&tx_ptr));
                assert!(read_transactions.aborted.contains(&tx_ptr));
            }

            // Create a read-only transaction, ensure this removes it from aborted set if mdbx
            // reassigns same recently aborted transaction pointer.
            {
                let tx = env.begin_ro_txn().unwrap();
                let tx_ptr = tx.txn() as usize;
                assert!(!read_transactions.aborted.contains(&tx_ptr));
            }
        }
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/6843.

Removes a read transaction from the aborted set if mdbx tries to reuse it (initiated by user), regardless of error code.

### CODE REVIEW

**Review by joshieDo — APPROVED** [review]

File: crates/storage/libmdbx-rs/src/txn_manager.rs [hunk 1]
```diff
@@ -420,5 +420,39 @@ mod read_transactions {
...
+
+                assert!(!read_transactions.active.contains_key(&tx_ptr));
+                assert!(read_transactions.aborted.contains(&tx_ptr));
+            }
+
+            // Create a read-only transaction, ensure this removes it from aborted set if mdbx
+            // reassigns same recently aborted transaction pointer.
+            {
+                let tx = env.begin_ro_txn().unwrap();
+                let tx_ptr = tx.txn() as usize;
```
Comment (joshieDo) [inline crates/storage/libmdbx-rs/src/txn_manager.rs:453]: is it actually reassigning?

Comment (emhane) [reply crates/storage/libmdbx-rs/src/txn_manager.rs:453]: sometimes. we should proptest test these so they run more than once. try the test more than once on main and you will see it fail sometimes pass sometimes.
