### PR TITLE
fix: ensure no blob transactions in payloads pre-cancun

### LINKED ISSUE #4670: Ensure pre-cancun payload does not have blob transactions
### Describe the bug

The hive pyspec test `cancun/eip4844_blobs/blob_txs/blob_type_tx_pre_fork/001-fork=ShanghaiToCancunAtTime15k-one_blob_tx` fails because we do not return `INVALID_PARAMS` when processing a new payload that is pre-cancun and has blob transactions:
```
starting client with Engine API.
>> (39bd7642) {"jsonrpc":"2.0","id":1,"method":"eth_getBlockByNumber","params":["0x0",true]}
<< (39bd7642) {"jsonrpc":"2.0","result":{"hash":"0xdf0226638d1c7c0d615b99312f146907d55bb74ef58b1d97587661f20c9929cf","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x173839ea3b84b69affb8b1547337a7ea366e2087eb29c0fd7a1837fa00225b3f","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":"0x0","number":"0x0","gasLimit":"0x16345785d8a0000","gasUsed":"0x0","timestamp":"0x0","extraData":"0x00","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","baseFeePerGas":"0x7","withdrawalsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","totalDifficulty":"0x0","uncles":[],"transactions":[],"size":"0x220","withdrawals":[]},"id":1}
>> (39bd7642) {"jsonrpc":"2.0","id":1,"method":"engine_newPayloadV2","params":[{"parentHash":"0xdf0226638d1c7c0d615b99312f146907d55bb74ef58b1d97587661f20c9929cf","feeRecipient":"0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba","stateRoot":"0x173839ea3b84b69affb8b1547337a7ea366e2087eb29c0fd7a1837fa00225b3f","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","prevRandao":"0x0000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x1","gasLimit":"0x16345785d8a0000","gasUsed":"0x0","timestamp":"0xc","extraData":"0x","baseFeePerGas":"0x7","blockHash":"0xddb94557fe85c2e7eef0534ae3bfd879b6fbeb56f2da5fd894c9ccafbbfb3078","transactions":["0x03f885018080078252089400000000000000000000000000000000000001000180c001e1a0010000000000000000000000000000000000000000000000000000000000000001a0a8f4757869fbb831ba4ed3a7c8f868b0e2e0c1eda97937aab035560fffdedf3ca019d9b041540e3d6f5f56dc29deb8834a08171e92037cf567b922357e70f8e54a"],"withdrawals":[]}]}
<< (39bd7642) {"jsonrpc":"2.0","result":{"status":"INVALID","latestValidHash":null,"validationError":"blockhash mismatch, want 0xddb9…3078, got 0xf658…a833"},"id":1}
fixture expected rpc error code: -32602 but none was returned from client in test cancun/eip4844_blobs/blob_txs/blob_type_tx_pre_fork/001-fork=ShanghaiToCancunAtTime15k-one_blob_tx
failing tests:
reth/cancun/eip4844_blobs/blob_txs/blob_type_tx_pre_fork/001-fork=ShanghaiToCancunAtTime15k-one_blob_tx: fixture expected rpc error code: -32602 but none was returned from client
```

We may need to change how we use `try_into_sealed_block` and change `ensure_well_formed_payload` to support this. We will need to add a variant to `BeaconOnNewPayloadError` that maps to `INVALID_PARAMS_CODE`:
https://github.com/paradigmxyz/reth/blob/801294252ed1ba70d671e723fa771a4635aae3fd/crates/rpc/rpc-engine-api/src/error.rs#L113-L117

We should probably verify this property _after_ transactions are parsed, which is why I suggest doing this in `ensure_well_formed_payload`. We could also just check the EIP-2718 prefix before they're decoded, when they are still stored as `Bytes` in the `ExecutionPayload`:
https://github.com/paradigmxyz/reth/blob/801294252ed1ba70d671e723fa771a4635aae3fd/crates/rpc/rpc-types/src/eth/engine/payload.rs#L136-L138

But doing this after decoding seems like the best solution.

### Steps to reproduce

Run hive:
```
./hive --client reth --sim "pyspec" --sim.limit "/cancun/eip4844_blobs/blob_txs/blob_type_tx_pre_fork/001-fork=ShanghaiToCancunAtTime15k-one_blob_tx"
```

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
This ensures there are no blob transactions pre-cancun, adding a new error variant that maps to `INVALID_PARAMS_CODE`.

Makes the `/cancun/eip4844_blobs/blob_txs/blob_type_tx_pre_fork/001-fork=ShanghaiToCancunAtTime15k-one_blob_tx` test pass.

Not really happy on the new return type of `ensure_well_formed_payload` - am considering adding a separate error type that makes this easier.

Fixes #4670

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -1124,18 +1124,38 @@ where
...
+
+                validate_block_hash(block_hash, block)
+            }
+            Err(error) => Err(error),
+        };
+
+        let block = match block_res {
             Ok(block) => block,
             Err(error) => {
+                // TODO: need to fix this to use the correct type
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:1158]: correct type of what?

**Review by mattsse — APPROVED** [review]
lgtm

File: crates/consensus/beacon/src/engine/mod.rs [hunk 2]
```diff
@@ -1124,18 +1124,38 @@ where
...
+                // make sure there are no blob transactions in the payload if it is pre-cancun
+                // we perform this check before validating the block hash because INVALID_PARAMS
+                // must be returned over an INVALID response.
+                if !self.chain_spec().is_cancun_activated_at_timestamp(block.timestamp) &&
+                    block.has_blob_transactions()
+                {
+                    return Err(BeaconOnNewPayloadError::PreCancunBlockWithBlobTransactions)
+                }
+
+                validate_block_hash(block_hash, block)
```
Comment (rkrasiuk) [inline crates/consensus/beacon/src/engine/mod.rs:1150]: imo this should be handled on payload validation step inside `EngineApi` handlers

**Review by rkrasiuk — COMMENTED** [review]
~~how is this not a noop given version/fork validation performed in [`EngineApi::validate_payload_timestamp`](https://github.com/paradigmxyz/reth/blob/6d634e9ad56653f66a4284225c2dc210fd104ed1/crates/rpc/rpc-engine-api/src/engine_api.rs#L387) method?~~ disregard this q

File: crates/consensus/beacon/src/engine/mod.rs (hunk 1 above)
Comment (Rjected) [reply crates/consensus/beacon/src/engine/mod.rs:1158]: Outdated comment

File: crates/consensus/beacon/src/engine/mod.rs (hunk 2 above)
Comment (Rjected) [reply crates/consensus/beacon/src/engine/mod.rs:1150]: It's possible, but a bit more hacky to do this because the actual transaction decoding happens later, i.e. it happens in `try_into_block`. Forgot to link https://github.com/paradigmxyz/reth/issues/4670, see:
> they are still stored as Bytes in the ExecutionPayload
