### PR TITLE
fix(op): configure discv5 properly in op builder

### LINKED ISSUE #9052: Can not connect bootstrap nodes when starting an optimism node
### Describe the bug

The log shows there are no bootstrap nodes to connect when starting an optimism node:

```
2024-06-24T13:17:08.800142Z TRACE net::discv5: adding bootstrap nodes .. bootstrap_nodes={}
```

### Steps to reproduce

1. start node with command

```
RUST_LOG=trace ./op-reth node \
		--datadir=./opnode \
    --chain optimism \
    --rollup.sequencer-http https://mainnet-sequencer.optimism.io/ \
    --http \
    --ws \
    --authrpc.port 9651 \
    --authrpc.jwtsecret ./jwt.txt \
    --log.file.filter=trace \
    --log.file.directory ./opnode/logs \
    --port=60303 \
    --discovery.port=40404 \
    --discovery.v5.port=6020 \
    --debug.tip 0xc86d0b4b6e4713b048071e5cbebc0fa92fe5cfb85d529cbc39146ab159e414c0
```

2. and check the logs:

```
2024-06-24T13:17:08.799211Z TRACE net::discv5: local ENR enr=Enr { id: Some("v4"), seq: 1, NodeId: 0xec11f96fad92cfc9f84a0d6614a7fb450b0a38902314f995a52f4e516b727e62, signature: "c159db111246cbfaf0f6d7623a3f0460dd36d177a7953d7b34f127123e5dce7d47aa99910eaee776cacdb15a0d6a533289879d910d00e0bfb6b9fd2d8982298a", IpV4 UDP Socket: None, IpV6 UDP Socket: None, IpV4 TCP Socket: None, IpV6 TCP Socket: None, Other Pairs: [("opel", "c7c68449fbfe1e80"), ("secp256k1", "a102cac708f84da27fdbb808de7355a82040adec840fed2941ef6c7b7fd389e629bc")], .. }
2024-06-24T13:17:08.799714Z TRACE mio::poll: registering event source with poller: token=Token(4418848128), interests=READABLE | WRITABLE    
2024-06-24T13:17:08.800142Z TRACE net::discv5: adding bootstrap nodes .. bootstrap_nodes={}
```

### Node logs

_No response_

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

```
reth Version: 1.0.0-dev
Commit SHA: 31e247086
Build Timestamp: 2024-06-24T13:09:30.474410000Z
Build Features: jemalloc,optimism
Build Profile: release
```

### What database version are you on?

```
❯ ./reth db version

Current database version: 2
Local database is uninitialized
```

### Which chain / network are you on?

optimism

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

make install-op

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
closes #9052 #9053

the discv5 settings we apply by default were overwritten because we always enable discv5 for OP.

fx: apply discv5 settings in op network builder

the `map_discv5_config_builder` is a bit confusing and we should remove this

note: peering on op networks is still very bad and can take a while

### CODE REVIEW

File: crates/optimism/node/src/node.rs [hunk 1]
```diff
@@ -292,6 +292,18 @@ where
...
+                builder
+                    .add_unsigned_boot_nodes(ctx.chain_spec().bootnodes().unwrap_or_default())
+                    .lookup_interval(ctx.config().network.discovery.discv5_lookup_interval)
+                    .bootstrap_lookup_interval(
+                        ctx.config().network.discovery.discv5_bootstrap_lookup_interval,
+                    )
+                    .bootstrap_lookup_countdown(
+                        ctx.config().network.discovery.discv5_bootstrap_lookup_countdown,
+                    )
             });
```
Comment (Rjected) [inline crates/optimism/node/src/node.rs:307]: makes sense

**Review by Rjected — APPROVED** [review]
