### PR TITLE
fix: never ban trusted peers

### LINKED ISSUE #11244: A pre-configured trusted peer will not be retried if it is banned at startup.
### Describe the bug

Currently, when running the Reth Node with the flags

` --disable-discovery
   --trusted-only
   --trusted-peers  `. 

the node communicates exclusively with trusted peers. If a handshake with a trusted peer fails, the peer may be added to a ban list. However, even if a banned peer is later evicted, it cannot be selected again for a handshake, which can lead to the node getting stuck.

### Steps to reproduce

1. Start a node with the following flags:

` --disable-discovery
   --trusted-only
   --trusted-peers  `.

Also, adjust the configuration values:

```
[peers]
ban_duration = "30s"
```

```
[peers.backoff_durations]
low = "30s"
medium = "30s"
high = "30s"
max = "30s"
```

2. Simulate an invalid handshake https://github.com/paradigmxyz/reth/blob/353fd60d29ed9b1dac752b8d9eaed7da4b6118a2/crates/net/ecies/src/stream.rs#L85 resulting in the trusted peer being banned.

3. As a result, the node may become stuck.

### Node logs

_No response_

### Platform(s)

Mac (Apple Silicon)

### What version/commit are you on?

v1.0.6

### What database version are you on?

v1.0.6

### Which chain / network are you on?

BSC

### What type of node are you running?

Archive (default)

### What prune config do you use, if any?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
closes #11244

on a fatal connection err (which also currently has a bug), we ended up removing trusted peers.

this adds an additional check and only removes the peer from the set if it isn't trusted

### CODE REVIEW

File: crates/net/network/src/peers.rs [hunk 1]
```diff
@@ -1896,6 +1902,64 @@ mod tests {
...
+
+        let err = PendingSessionHandshakeError::Eth(EthStreamError::EthHandshakeError(
+            EthHandshakeError::NonStatusMessageInHandshake,
+        ));
+        assert!(err.is_fatal_protocol_error());
+
+        peers.on_outgoing_pending_session_dropped(&socket_addr, &peer, &err);
+        assert_eq!(peers.num_outbound_connections(), 0);
+
+        // tmp ban peer
```
Comment (emhane) [inline crates/net/network/src/peers.rs:1940]:
```suggestion
        // try tmp ban peer
```

File: crates/net/network/src/peers.rs [hunk 2]
```diff
@@ -1896,6 +1902,64 @@ mod tests {
         assert!(!peers.peers.contains_key(&peer));
     }
 
+    #[tokio::test]
+    async fn test_fatal_outgoing_connection_error_trusted() {
+        let peer = PeerId::random();
```
Comment (emhane) [inline crates/net/network/src/peers.rs:1907]:
```suggestion
        let trusted_peer = PeerId::random();
```
nitpick, helps to follow along a bit better

**Review by emhane — APPROVED** [review]
