### PR TITLE
fix: use correct type for NewPooledTransactionHashes68

### LINKED ISSUE #1533: `NewPooledTransactionHashes68` fails to decode
### Describe the bug

The [`eth/68` spec](https://eips.ethereum.org/EIPS/eip-5793) shows the following for the `NewPooledTransactionHashes` message:

Modify the `NewPooledTransactionHashes` (0x08) message:

    (eth/67): [hash_0: B_32, hash_1: B_32, ...]
    (eth/68): [[type_0: B_1, type_1: B_1, ...], [size_0: B_4, size_1: B_4, ...], [hash_0: B_32, hash_1: B_32, ...]]
    
Our struct for this message fails to decode this on the wire, with:
```
 err=P2PStreamError(Rlp(UnexpectedString)) 
```

### Steps to reproduce

One failing case from the network: `e602c281b6e1a0fecbed04c7b88d8e7221a0a3f5dc33f220212347fc167459ea5cc9c3eb4c1124`

Unit tests to be added, along with more vectors from geth.

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
Uses `Bytes` to decode the transaction types, instead of `Vec<u8>`. I have created test vectors with geth here:
https://github.com/Rjected/go-ethereum/commit/82d934b1dd80cdd8190803ea9f73ed2c345e2576

Some of these vectors are included in new roundtrip encoding and decoding tests, including the failing case from #1533.

Fixes #1533

### CODE REVIEW

**Comment by mattsse** [comment]
> Uses Bytes to decode the transaction types, instead of Vec<u8>

what's the difference in rlp?

**Comment by mattsse** [comment]
ah Bytes just grabs the payload from rlp buffer but Vec<u8> decodes byte by byte

TIL

**Comment by Rjected** [comment]
> what's the difference in rlp?

`Bytes` will also be encoded as a RLP string, so it will encode a string header (`0x80 - 0xbf`) instead of a list header (`0xc0-0xff`).

On the decode side, `Bytes` also expects a string header, but `Vec<u8>` expects a list header.

File: crates/net/eth-wire/src/types/broadcast.rs [hunk 1]
```diff
@@ -204,10 +207,84 @@ pub struct NewPooledTransactionHashes68 {
...
 }
 
+impl Encodable for NewPooledTransactionHashes68 {
+    fn length(&self) -> usize {
+        #[derive(RlpEncodable)]
+        struct EncodableNewPooledTransactionHashes68 {
+            types: Bytes,
+            sizes: Vec<usize>,
+            hashes: Vec<H256>,
+        }
```
Comment (mattsse) [inline crates/net/eth-wire/src/types/broadcast.rs:217]: Bytes is just a wrapped Vec<u8>,

I think we have two options here

1. replace `types: Vec<u8>` with `types: Bytes` and we can keep all derives
2. keep custom impl but use references instead of cloning

I guess the only argument for Vec<u8> would be that all fields are Vec but can also go with Bytes

**Review by mattsse — CHANGES_REQUESTED** [review]

**Comment by mattsse** [comment]
> > what's the difference in rlp?
> 
> `Bytes` will also be encoded as a RLP string, so it will encode a string header (`0x80 - 0xbf`) instead of a list header (`0xc0-0xff`).
> 
> On the decode side, `Bytes` also expects a string header, but `Vec<u8>` expects a list header.

but why are the other Vec fields unaffected by this?

File: crates/net/eth-wire/src/types/broadcast.rs (hunk 1 above)
Comment (Rjected) [reply crates/net/eth-wire/src/types/broadcast.rs:217]: If we use `Bytes`, we lose the ability to derive `Arbitrary` because `Bytes` does not implement it. So I'm leaning towards keeping the custom impl and using references instead of cloning

File: crates/net/eth-wire/src/types/broadcast.rs [hunk 2]
```diff
@@ -204,10 +207,80 @@ pub struct NewPooledTransactionHashes68 {
...
+    fn encode(&self, out: &mut dyn bytes::BufMut) {
+        #[derive(RlpEncodable)]
+        struct EncodableNewPooledTransactionHashes68<'a> {
+            types: Bytes,
+            sizes: &'a Vec<usize>,
+            hashes: &'a Vec<H256>,
+        }
+
+        let encodable = EncodableNewPooledTransactionHashes68 {
+            types: Bytes::from(self.types.clone()),
```
Comment (mattsse) [inline crates/net/eth-wire/src/types/broadcast.rs:236]: oh I didn't realize that we can't borrow under these circumstances.

this is pretty wasteful because now we need to clone a vec for every message we send...

So for perf reasons, we should change it to `NewPooledTransactionHashes68 {types: Bytes}` directly.

**Review by mattsse — CHANGES_REQUESTED** [review]
gotcha, thanks for explaining this!

I just realized that we can't do encode by ref because `Bytes` allocates.

File: crates/net/eth-wire/src/types/broadcast.rs (hunk 2 above)
Comment (mattsse) [reply crates/net/eth-wire/src/types/broadcast.rs:236]: or mirroring the  `Bytes::encode` impl here would also be possible

Comment (Rjected) [reply crates/net/eth-wire/src/types/broadcast.rs]: ended up mirroring the `Bytes::encode` impl, in that `EncodableNewPooledTransactionHashes68` now uses `&[u8]` instead of `Bytes`, so we do not need to clone

**Review by mattsse — APPROVED** [review]
lgtm, still incredibly weird that a list of individual u8 is encoded as string.

can we please document this before merging, because this so giga cursed that I'm almost certain there will be problems with this eventually.

**Comment by Rjected** [comment]
> can we please document this before merging, because this so giga cursed that I'm almost certain there will be problems with this eventually.

Yep, absolutely
