### PR TITLE
fix(rpc): cap request gas limit if not set

### LINKED ISSUE #1802: Cap gas limit in eth_call
### Describe the bug

we already cap the gas limit in `eth_estimateGas` to the max user allowance.

we need to do the same for `eth_call`

ref https://github.com/ethereum/go-ethereum/blob/bba2a1bac5fb896e644ff6a5307419812e0f6819/internal/ethapi/api.go#L1097-L1123

### Steps to reproduce

-

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
Closes #1802

cap tx gas limit in eth call by allowance

### CODE REVIEW

File: crates/rpc/rpc-types/src/eth/call.rs [hunk 1]
```diff
@@ -28,3 +28,12 @@ pub struct CallRequest {
     /// AccessList
     pub access_list: Option<AccessList>,
 }
+
+impl CallRequest {
+    /// Returns the configured fee cap, if any.
+    ///
+    /// The returns `gas_price` (legacy) if set or `max_fee_per_gas` (EIP1)
```
Comment (Rjected) [inline crates/rpc/rpc-types/src/eth/call.rs:35]: nit: 
```suggestion
    /// The returns `gas_price` (legacy) if set or `max_fee_per_gas` (EIP1559)
```

**Review by Rjected — APPROVED** [review]
lgtm, checked with the corresponding geth code, so hopefully we get some hive tests working now
