### PR TITLE
fix: also set configured bootnodes for discv5

### LINKED ISSUE #9883: --bootnodes are ignored for discv5
### Describe the feature

https://github.com/paradigmxyz/reth/blob/5b0f6a288551238d6f986b832b74c9573953d455/crates/optimism/node/src/node.rs#L305-L305

discv5 config is only configured with the known chain-specific defaults

https://github.com/paradigmxyz/reth/blob/5b0f6a288551238d6f986b832b74c9573953d455/crates/net/network/src/manager.rs#L206-L213

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
closes #9883

we didn't configure the provided --bootnodes for discv5.

geth also uses the --bootnodes values to initialize discv5 bootnodes:

https://github.com/ethereum/go-ethereum/blob/380688c636a654becc8f114438c2a5d93d2db032/cmd/utils/flags.go#L1087-L1087

so this fix is reasonable imo.

I also added extend the discv5 bootnodes during network launch, this is redundant if the discv5 is already configured with the bootnodes, but doesn't hurt

https://github.com/paradigmxyz/reth/blob/76513e46ecad9a0893d46af4164da23bf90511aa/crates/net/network/src/manager.rs#L217-L220

### CODE REVIEW

File: crates/optimism/node/src/node.rs [hunk 1]
```diff
@@ -300,10 +300,16 @@ where
...
-                        rlpx_socket,
-                        ctx.chain_spec().bootnodes().unwrap_or_default(),
-                    ));
+                    builder = builder.discovery_v5(
+                        args.discovery.discovery_v5_builder(
+                            rlpx_socket,
+                            ctx.config()
+                                .network
+                                .resolved_bootnodes()
+                                .or_else(|| ctx.chain_spec().bootnodes())
```
Comment (Rjected) [inline crates/optimism/node/src/node.rs:309]: makes sense

**Review by Rjected — APPROVED** [review]

**Comment by emhane** [comment]
hm, this breaks the builder pattern by adding methods to `Config` taking mutable ref to self. this worsens devex for the experienced dev, since one expects an instance built by a builder to be immutable.
