### PR TITLE
fix: relax body against validation for isthmus

### LINKED ISSUE #15771: Ignore withdrawals root check past isthmus in op consensus
### Describe the feature

this is problematic after isthmus

https://github.com/paradigmxyz/reth/blob/12c2dba821782c21d95094c4124c13f53397c452/crates/consensus/common/src/validation.rs#L108-L120

so the op census impls shouldn't use this

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
closes #15771

we need to relax the withdrawals root check after isthmus.

this function's purpose is only to check the header fields that are derived from the block body and used in p2p where we need to combine header and body.

### CODE REVIEW

File: crates/optimism/consensus/src/validation/mod.rs [hunk 1]
```diff
@@ -5,14 +5,78 @@ pub mod isthmus;
...
+    }
+
+    let tx_root = body.calculate_tx_root();
+    if header.transactions_root() != tx_root {
+        return Err(ConsensusError::BodyTransactionRootDiff(
+            GotExpected { got: tx_root, expected: header.transactions_root() }.into(),
+        ))
+    }
+
+    match (header.withdrawals_root(), body.calculate_withdrawals_root()) {
```
Comment (emhane) [inline crates/optimism/consensus/src/validation/mod.rs:51]: will open an issue to use these modules instead, because that would require changing there returned error type to `OpConsensusError` which could require a big refactor
https://github.com/paradigmxyz/reth/tree/main/crates/optimism/consensus/src/validation

**Review by emhane — APPROVED** [review]
