### PR TITLE
fix: ensure final message is always delivered

### LINKED ISSUE #4568: Guarantee that ActiveSession disconnects are sent before terminating the task
### Describe the feature

currently we rely on `.clone.try_send` this is technically still susceptible to race conditions.

Fix: Guarantee we're sending the message on before the task is closed

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
Closes #4568

This ensures a Disconnect/ClosedOnConnectionError message is always delivered, previously we were relying on clone.try_send

this makes sure that we acquire a permit for this message

### CODE REVIEW

File: crates/net/network/src/session/active.rs [hunk 1]
```diff
@@ -355,25 +360,28 @@ impl ActiveSession {
...
+    fn close_on_error(&mut self, error: EthStreamError, cx: &mut Context<'_>) -> Poll<()> {
+        let msg = ActiveSessionMessage::ClosedOnConnectionError {
+            peer_id: self.remote_peer_id,
+            remote_addr: self.remote_addr,
+            error,
+        };
+        self.terminate_message =
+            Some((PollSender::new(self.to_session_manager.inner().clone()).clone(), msg));
+        self.poll_terminate_message(cx).expect("message is set")
     }
```
Comment (Rjected) [inline crates/net/network/src/session/active.rs:385]: ah, nice, this makes sense

**Review by Rjected — APPROVED** [review]
LGTM, setting a `(PollSender, message)` for either disconnect or error makes a lot of sense here
