### PR TITLE
fix(trie): replace rayon with tokio for I/O operations in parallel trie

### LINKED ISSUE #17288: Spawn `StorageRoot` in tokio blocking task, not rayon
### Describe the feature

-

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yongkangc**
Fixes #17288

## Summary

Replaces `rayon::spawn_fifo` with `tokio::task::spawn_blocking` for database I/O operations in parallel trie computation. Rayon's CPU-bound thread pool was incorrectly used for I/O-heavy operations, causing thread pool starvation.

## Changes

- Replace `rayon::spawn_fifo` with `tokio::task::spawn_blocking` in `calculate()`
- Add `get_runtime_handle()` helper that creates runtime if not in Tokio context (e.g., Tree Task thread)
- Use fire-and-forget pattern with channels for result communication

### CODE REVIEW

**Review by mediocregopher — APPROVED** [review]
LGTM

File: crates/trie/parallel/src/root.rs [hunk 1]
```diff
@@ -98,9 +113,10 @@ where
             #[cfg(feature = "metrics")]
             let metrics = self.metrics.storage_trie.clone();
 
-            let (tx, rx) = std::sync::mpsc::sync_channel(1);
+            let (tx, rx) = mpsc::sync_channel(1);
 
-            rayon::spawn_fifo(move || {
+            // Spawn a blocking task to calculate account's storage root from database I/O
+            drop(handle.spawn_blocking(move || {
```
Comment (mattsse) [inline crates/trie/parallel/src/root.rs:119]: this drop is fine because joinhandle can be dropped although not necessary

File: crates/trie/parallel/src/root.rs [hunk 2]
```diff
@@ -261,6 +277,27 @@ impl From<alloy_rlp::Error> for ParallelStateRootError {
     }
 }
 
+/// Gets or creates a tokio runtime handle for spawning blocking tasks.
+/// This ensures we always have a runtime available for I/O operations.
+fn get_runtime_handle() -> Handle {
```
Comment (mattsse) [inline crates/trie/parallel/src/root.rs:282]: hmm, this will most likely create a new runtime with a bunch of threads because the tree task is run outside of tokio

so we'll endup with a bunch of unusable threads. which should be fine since we dont expect this to be reachable in the happy path.

and this is better than sprinkling the runtime as arg all over the place

**Review by mattsse — APPROVED** [review]

File: crates/trie/parallel/src/root.rs (hunk 2 above)
Comment (yongkangc) [reply crates/trie/parallel/src/root.rs:282]: So we clean this up in another issue maybe? Or this is fine for now

Had the same thought on what's the cleanest way to go about this! @mattsse

Comment (mattsse) [reply crates/trie/parallel/src/root.rs:282]: imo this is fine
