### PR TITLE
fix(builder): desired block gas limit

### LINKED ISSUE #13128: Use --builder.gaslimit cli argument for payload building
### Describe the feature

this field is currently unused:

https://github.com/paradigmxyz/reth/blob/53243a29f30021ee6061f1b11cb3560de1cd9ac2/crates/node/core/src/args/payload_builder.rs#L19-L21

we need to wire this to the 

https://github.com/paradigmxyz/reth/blob/53243a29f30021ee6061f1b11cb3560de1cd9ac2/crates/ethereum/payload/src/lib.rs#L59-L59

during setup:

https://github.com/paradigmxyz/reth/blob/53243a29f30021ee6061f1b11cb3560de1cd9ac2/crates/ethereum/node/src/node.rs#L256-L256

for this we should introduce a new `Config` container type

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rkrasiuk**
## Description

Closes https://github.com/paradigmxyz/reth/issues/13128

### CODE REVIEW

File: crates/ethereum/payload/src/config.rs [hunk 1]
```diff
@@ -19,4 +22,13 @@ impl EthereumBuilderConfig {
...
     }
+
+    /// Returns the gas limit for the next block based
+    /// on parent and desired gas limits.
+    pub fn gas_limit(&self, parent_gas_limit: u64) -> u64 {
+        let delta = parent_gas_limit / GAS_LIMIT_BOUND_DIVISOR;
+        let min_gas_limit = parent_gas_limit + delta - 1;
+        let max_gas_limit = parent_gas_limit - delta + 1;
+        parent_gas_limit.clamp(min_gas_limit, max_gas_limit)
+    }
```
Comment (mattsse) [inline crates/ethereum/payload/src/config.rs:33]: we need a standalone function that accepts two u64, that this fn then calls

should be upstreamed to alloy once merged

File: crates/optimism/payload/src/builder.rs [hunk 2]
```diff
@@ -175,6 +175,7 @@ where
             timestamp: attributes.timestamp(),
             suggested_fee_recipient: attributes.suggested_fee_recipient(),
             prev_randao: attributes.prev_randao(),
+            gas_limit: parent.gas_limit,
```
Comment (mattsse) [inline crates/optimism/payload/src/builder.rs:178]: this needs to do `attributes.gas_limit.unwrap_or(parent.gas_limit)`

File: examples/custom-engine-types/src/main.rs [hunk 3]
```diff
@@ -408,7 +408,7 @@ where
         // but any custom logic can be implemented here
         reth_ethereum_payload_builder::EthereumPayloadBuilder::new(
             EthEvmConfig::new(chain_spec.clone()),
-            EthereumBuilderConfig::new(default_extra_data_bytes()),
+            EthereumBuilderConfig::new(default_extra_data_bytes(), ETHEREUM_BLOCK_GAS_LIMIT),
```
Comment (mattsse) [inline examples/custom-engine-types/src/main.rs:411]: this can be avoided by making this the default, remove from new and add a `with_gas_limit` builder style fn

**Review by mattsse — CHANGES_REQUESTED** [review]
a few nits

File: crates/ethereum/payload/src/config.rs [hunk 4]
```diff
@@ -19,4 +29,18 @@ impl EthereumBuilderConfig {
...
+
+    /// Returns the gas limit for the next block based
+    /// on parent and desired gas limits.
+    pub fn gas_limit(&self, parent_gas_limit: u64) -> u64 {
+        calculate_block_gas_limit(parent_gas_limit, self.desired_gas_limit)
+    }
+}
+
+/// Calculate the gas limit for the next block based on parent and desired gas limits.
+pub fn calculate_block_gas_limit(parent_gas_limit: u64, desired_gas_limit: u64) -> u64 {
```
Comment (mattsse) [inline crates/ethereum/payload/src/config.rs:41]: is there any reference for this, I'd prefer if we could link this

**Review by mattsse — APPROVED** [review]

File: crates/ethereum/payload/src/config.rs [hunk 5]
```diff
@@ -19,4 +29,19 @@ impl EthereumBuilderConfig {
...
+    }
+}
+
+/// Calculate the gas limit for the next block based on parent and desired gas limits.
+/// Ref: <https://github.com/ethereum/go-ethereum/blob/88cbfab332c96edfbe99d161d9df6a40721bd786/core/block_validator.go#L166>
+pub fn calculate_block_gas_limit(parent_gas_limit: u64, desired_gas_limit: u64) -> u64 {
+    let delta = parent_gas_limit / GAS_LIMIT_BOUND_DIVISOR;
+    let min_gas_limit = parent_gas_limit + delta - 1;
+    let max_gas_limit = parent_gas_limit - delta + 1;
+    desired_gas_limit.clamp(min_gas_limit, max_gas_limit)
```
Comment (0xalpharush) [inline crates/ethereum/payload/src/config.rs:46]:
```suggestion
    let delta = parent_gas_limit / GAS_LIMIT_BOUND_DIVISOR - 1;
    let min_gas_limit = parent_gas_limit + delta;
    let max_gas_limit = parent_gas_limit - delta;
    desired_gas_limit.clamp(min_gas_limit, max_gas_limit)
```
