### PR TITLE
fix(tree): use only in-memory blocks when constructing trie input

### LINKED ISSUE #14688: Use latest block in DB for fetching reverts in trie input creation
Right now when creating `TrieInput` for the sparse trie we:
* Check whether we have blocks in-memory for the given parent, giving us an anchor hash and list of in-memory canonical blocks.
* Call `consistent_view.revert_state` using the anchor hash we get (this may be behind the current DB tip!), which creates a DB provider and calls `reverts_to` up to the hash
* Call `trie_input.append(revert_state)`, which constructs prefix sets based on the reverts.

This is sub optimal, if the parent hash we are computing trie input for, is in the DB, or there is a block newer than the anchor hash in the DB already.

In this function:
https://github.com/paradigmxyz/reth/blob/2101ae8918f4efbd1cfccb04f49f91cd990a5371/crates/engine/tree/src/tree/mod.rs#L2666-L2692

We should remove the in-memory blocks that are already on-disk, and use the latest hash on disk if possible when constructing reverts. This way, we can avoid creating reverts that we shouldn't need if we're computing the trie input for a block that extends the DB tip.

### PR DESCRIPTION
**Pull request by shekhirin**
Closes https://github.com/paradigmxyz/reth/issues/14688

### CODE REVIEW

File: crates/engine/tree/src/tree/mod.rs [hunk 1]
```diff
@@ -2693,13 +2729,46 @@ where
...
         }
 
         Ok(input)
     }
 
+    /// Retrieve revert hashed state down to the given block hash.
+    fn revert_state(
+        &self,
+        provider: P::Provider,
+        best_block_number: BlockNumber,
```
Comment (Rjected) [inline crates/engine/tree/src/tree/mod.rs:2743]: can we not just use the provider method for best block num here like we did in the prev consistent view method, and remove the argument? given the provider_ro should be greated already

File: crates/engine/tree/src/tree/mod.rs [hunk 2]
```diff
@@ -2680,10 +2681,45 @@ where
...
+                for block in blocks {
+                    let recovered_block = block.recovered_block();
+
+                    // Take only those blocks that are either:
+                    // 1. Higher than the highest database block
+                    // 2. Or have no associated database block, meaning that it's on a non-canonical
+                    //    chain
+                    if recovered_block.number() > best_block_number ||
+                        Some(recovered_block.hash()) !=
+                            provider.block_hash(recovered_block.number())?
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:2703]: hmm, I don't think we have to do any of that if we keep

```
if let Some((historical, blocks)) = self.state.tree_state.blocks_by_hash(parent_hash) {
```

and instead pop from blocks and shift the anchor

File: crates/engine/tree/src/tree/mod.rs [hunk 3]
```diff
@@ -2680,10 +2681,45 @@ where
...
+                    {
+                        historical = Some(recovered_block.parent_hash());
+                        filtered_blocks.push(block);
+                    } else {
+                        // Since we're iterating from highest to lowest, we can stop here, meaning
+                        // that we started seeing blocks that are present in the database.
+                        break
+                    }
+                }
+
```
Comment (Rjected) [inline crates/engine/tree/src/tree/mod.rs:2713]: I was thinking instead of doing this we maybe just check the first value in the vec returned by `blocks_by_hash`, we `pop_front` if the block is in the db, stop if we find one that is not in the db

**Review by Rjected — DISMISSED** [review]
thinking we can make the map / loop simpler

File: crates/engine/tree/src/tree/mod.rs (hunk 1 above)
Comment (shekhirin) [reply crates/engine/tree/src/tree/mod.rs:2741]: we'd query the best block number again, why not pass it as an argument if we already have it?

File: crates/engine/tree/src/tree/mod.rs [hunk 4]
```diff
@@ -2680,10 +2681,42 @@ where
...
+                    if recovered_block.number() <= best_block_number &&
+                        Some(recovered_block.hash()) ==
+                            provider.block_hash(recovered_block.number())?
+                    {
+                        blocks.pop();
+                    } else {
+                        // If the block is higher than the best block number or does not have an
+                        // associated database block, return current block's parent, as it's the
+                        // first block that's not in the database.
+                        return Ok(Some(((recovered_block.number() - 1), blocks)))
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:2706]: we shouldn't have to do any if this in this map if we do a let Some below

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/engine/tree/src/tree/mod.rs [hunk 5]
```diff
@@ -2680,10 +2681,42 @@ where
...
+            .blocks_by_hash(parent_hash)
+            .map(|(_, mut blocks)| {
+                // Iterate over the blocks from oldest to newest.
+                while let Some(block) = blocks.last() {
+                    let recovered_block = block.recovered_block();
+                    // Remove those blocks that lower than or equal to the highest database block
+                    // and have an associated database block with a matching hash.
+                    if recovered_block.number() <= best_block_number &&
+                        Some(recovered_block.hash()) ==
+                            provider.block_hash(recovered_block.number())?
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:2699]: have haven't checked this before why are we doing this now?

Comment (shekhirin) [reply crates/engine/tree/src/tree/mod.rs:2702]: does that make sense? https://github.com/paradigmxyz/reth/blob/d8c6d99be572261e6ddfb7fc620f897bc47958c1/crates/engine/tree/src/tree/mod.rs#L2698-L2702

Comment (mattsse) [reply crates/engine/tree/src/tree/mod.rs:2702]: all of this is very confusing, 
we at least need more docs on what all of this even is and why we're doing this

it's very hard for me to understand why we're even doing this

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/engine/tree/src/tree/mod.rs [hunk 6]
```diff
@@ -2336,28 +2366,34 @@ where
         }
 
         let state_provider = provider_builder.build()?;
+
+        let descendant_of_persisting_blocks =
+            self.is_descendant_of_persisting_blocks(block.header());
```
[the remark this answers is not in the document]
Comment (shekhirin) [reply crates/engine/tree/src/tree/mod.rs]: what do you mean by outdated?

File: crates/engine/tree/src/tree/mod.rs [hunk 7]
```diff
@@ -2336,28 +2342,34 @@ where
...
         // trie updates being committed are a subset of the in-memory trie updates collected before
         // fetching reverts. So any diff in reverts (pre vs post commit) is already covered by the
         // in-memory trie updates we collect in `compute_state_root_parallel`.
         //
         // See https://github.com/paradigmxyz/reth/issues/12688 for more details
-        let is_descendant_of_persisting_blocks =
+        let descendant_of_persisting_blocks =
             self.is_descendant_of_persisting_blocks(block.header());
+        let run_parallel_state_root = descendant_of_persisting_blocks.is_not_persisting() ||
+            descendant_of_persisting_blocks.is_descendant();
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:2356]: this isn't super straight forward imo

we have to do some mental gymnastic to find out which variant this is actually checks

can we make this a fn instead that matches!

File: crates/engine/tree/src/tree/mod.rs [hunk 8]
```diff
@@ -2881,6 +2969,30 @@ pub enum InsertPayloadOk {
     Inserted(BlockStatus),
 }
 
+/// Whether or not the blocks are currently persisting and the input block is a descendant.
+#[derive(Debug, Clone, Copy)]
+pub enum DescendantOfPersistingBlocks {
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:2974]: can we rename this to PersistingKind, this would be a bit easier

File: crates/engine/tree/src/tree/mod.rs [hunk 9]
```diff
@@ -2529,41 +2544,114 @@ where
...
+            debug!(target: "engine::tree", %parent_hash, %historical, blocks = blocks.len(), "Parent found in memory");
+        }
+
+        // Convert the historical block to the block number.
+        let block_number = match historical {
+            BlockHashOrNumber::Hash(block_hash) => provider
+                .block_number(block_hash)?
+                .ok_or(ProviderError::BlockHashNotFound(block_hash))?,
+            BlockHashOrNumber::Number(block_number) => block_number,
+        };
```
Comment (mattsse) [inline crates/engine/tree/src/tree/mod.rs:2627]: I believe this is just `provider.convert_hash_or_number`

**Review by mattsse — CHANGES_REQUESTED** [review]
last nits

**Review by mattsse — APPROVED** [review]
lgtm
