### PR TITLE
fix: spawn batch ranges from a tokio thread instead on `SenderRecovery` stage

### LINKED ISSUE #7298: Remove IO from senderrecovery rayon tasks
### Describe the feature

This does parallel IO inside rayon, which is suboptimal for rayon workloads
https://github.com/paradigmxyz/reth/blob/30d79a98aabcc6385beb6548f7cce9ebd85347ca/crates/stages/src/stages/sender_recovery.rs#L114-L119

instead the provider should read out of rayon and only spawn recovery CPU bound jobs onto the thread pool

we now have two things we need to handle:
1. keep reading data, spawn chunks to rayon,
2. receive results and append to cursor

I think 1. should happen on a separate new/scoped thread

wdyt @joshieDo 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joshieDo**
closes https://github.com/paradigmxyz/reth/issues/7298
hopefully closes once and for all https://github.com/paradigmxyz/reth/issues/6888

There were a couple issues with current implementation:
1) We had rayon workers fighting for IO.
2) We were only receiving from the result channels, once we would have sent all transaction job requests.
3) We would send jobs for the whole transaction range, which can be quite tough considering the previous points.  I'm guessing, we were either hanging because rayon workers were fighting for I/O or while they were fighting, we had a crazy amount of unprocessed channels on the sending and receiving side.

First and second get solved by issuing the rayon job requests from a spawn thread and let the reading from disk happen there.
For the third,  we now handle batches of 100k transactions. With each rayon worker having at most 100 transactions, it means that we have a maximum of 1000 channels in memory.

### Sepolia benchmarks
`main`: 696s
pr: 650s

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
conceptually, this should work,

would we can also do is leveraging the poll_ready function to create the task so that poll_ready awaits a batch, commits it in poll_execute, and the recovery task continues preparing the next batch, essentially parallizing the `for range in batch {` loop so we don't need to wait on commit.

but this would require a bit more benchmarking

File: crates/stages/src/stages/sender_recovery.rs [hunk 1]
```diff
@@ -84,83 +85,16 @@ impl<DB: Database> Stage<DB> for SenderRecoveryStage {
...
-        // chunks are too big, there will be idle threads waiting for work. Choosing an
-        // arbitrary smaller value to make sure it doesn't happen.
-        let chunk_size = 100;
-
-        let chunks = (tx_range.start..tx_range.end)
-            .step_by(chunk_size as usize)
-            .map(|start| start..std::cmp::min(start + chunk_size as u64, tx_range.end))
+        // Handles 100_000 transactions at a time. Since each rayon worker will hold at most 100
+        // transactions, we effectively max limit each batch to 1000 channels in memory.
+        let batch_size = 100_000;
```
Comment (shekhirin) [inline crates/stages/src/stages/sender_recovery.rs:90]: nit: think we should move these numbers to constants and reference in the comments

**Review by mattsse — APPROVED** [review]
