### PR TITLE
fix(rpc): limit cache by length

### LINKED ISSUE #3503: Memory usage limiter doesn't work as expected in `EthCache`
## Description

`schnellru::ByMemoryUsage` limiter doesn't work as expected in `EthCache` internal caches.

The metrics below show that the `memory_usage` fn, which is used by `ByMemoryUsage` limiter, reports lower usage than expected for this amount of blocks. 

Screenshot 2023-06-30 at 16 52 30

### PR DESCRIPTION
**Pull request by rkrasiuk**
Closes https://github.com/paradigmxyz/reth/issues/3503

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
also need to update the cli args:

https://github.com/paradigmxyz/reth/blob/513aaa5a15733506542243cda84a9e8a932b7c23/bin/reth/src/args/rpc_server_args.rs#L139-L145

File: bin/reth/src/args/rpc_server_args.rs [hunk 1]
```diff
@@ -160,19 +159,19 @@ impl RpcServerArgs {
...
+        self.receipt_cache_max_len
     }
 
-    /// Returns the max number of bytes for cached evm env data in bytes
-    pub fn env_cache_size_bytes(&self) -> usize {
-        self.env_cache_size * 1024 * 1024
+    /// Returns the max length for cached evm env data
+    pub fn env_cache_max_len(&self) -> u32 {
+        self.env_cache_max_len
     }
```
Comment (mattsse) [inline bin/reth/src/args/rpc_server_args.rs:175]: I guess these are no longer required and can be removed

File: bin/reth/src/args/rpc_server_args.rs [hunk 2]
```diff
@@ -136,17 +135,17 @@ pub struct RpcServerArgs {
...
+    /// Max size for cached receipt data.
+    #[arg(long, default_value_t = DEFAULT_RECEIPT_CACHE_MAX_LEN)]
+    pub receipt_cache_max_len: u32,
 
-    /// Max size for cached evm env data in megabytes.
-    #[arg(long, default_value_t = DEFAULT_ENV_CACHE_SIZE_BYTES_MB)]
-    pub env_cache_size: usize,
+    /// Max size for cached evm env data.
+    #[arg(long, default_value_t = DEFAULT_ENV_CACHE_MAX_LEN)]
+    pub env_cache_max_len: u32,
```
Comment (mattsse) [inline bin/reth/src/args/rpc_server_args.rs:148]: should we drop the `_max_`?

File: bin/reth/src/args/rpc_server_args.rs [hunk 3]
```diff
@@ -136,17 +135,17 @@ pub struct RpcServerArgs {
...
-    #[arg(long, default_value_t = DEFAULT_BLOCK_CACHE_SIZE_BYTES_MB)]
-    pub block_cache_size: usize,
+    /// Max size for cached block data.
+    #[arg(long, default_value_t = DEFAULT_BLOCK_CACHE_MAX_LEN)]
+    pub block_cache_max_len: u32,
 
-    /// Max size for cached receipt data in megabytes.
-    #[arg(long, default_value_t = DEFAULT_RECEIPT_CACHE_SIZE_BYTES_MB)]
-    pub receipt_cache_size: usize,
+    /// Max size for cached receipt data.
```
Comment (mattsse) [inline bin/reth/src/args/rpc_server_args.rs:142]: these should mention that this represents the number of cached items

**Review by mattsse — CHANGES_REQUESTED** [review]
smol nits

**Review by mattsse — APPROVED** [review]
nice one
