### PR TITLE
fix(txpool): pending subpool basefee update

### LINKED ISSUE #4609: Pending pool basefee updates are unsound
### Describe the feature

when updating the pending pool's basefee we update the transaction's priority:

https://github.com/paradigmxyz/reth/blob/455af5603b8500a6be845de7f012519ec53b8d5a/crates/transaction-pool/src/pool/pending.rs#L172-L177

this always clears the secondary sets

https://github.com/paradigmxyz/reth/blob/455af5603b8500a6be845de7f012519ec53b8d5a/crates/transaction-pool/src/pool/pending.rs#L187-L189

which means after an update sorted txs and independent txs are all empty

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rkrasiuk**
Closes #4609.

## Description 

Clear ordered lists first before the transactions are re-inserted with new priority.

### CODE REVIEW

File: crates/transaction-pool/src/pool/pending.rs [hunk 1]
```diff
@@ -184,10 +189,6 @@ impl<T: TransactionOrdering> PendingPool<T> {
             removed.push(self.remove_transaction(&id).expect("transaction exists"));
```
Comment (mattsse) [inline crates/transaction-pool/src/pool/pending.rs:189]: this now only needs to be removed from `by_id`

**Review by mattsse — CHANGES_REQUESTED** [review]

**Review by mattsse — APPROVED** [review]
lgtm,

I'll add a few tests for this
