### PR TITLE
fix(trie): track branch node updates only in ParallelSparseTrie, not subtries

### LINKED ISSUE #17172: Don't lost branch updates on `remove_leaf` calls
### Describe the feature

It's possible that during a `remove_leaf` call an entire lower subtrie will end up being deleted. If this subtrie had previously collected any branch node updates these would then be lost.

Fixing this is likely blocked on #16956, which also uses the updates set

### Additional context

* Create a ParallelSparseTrie with roughly this structure:
```
0x: Branch
0x1: Leaf
0x2: Extension
0x234: Branch
0x2345: Leaf
0x2346: Leaf
```

Deleting `0x2345` will result in the branch at `0x234` being temporarily replaced with an extension, and the lower subtrie for `0x23` will collect a corresponding branch node update in its `updates` set. Then the leaf at `0x2346` gets collapsed into the temporary extension, which gets collapsed into the extension at `0x2`. The final structure is:

```
0x: Branch
0x1: Leaf
0x2: Leaf (key: 346)
```

The `0x23` lower subtrie will have been deleted completely, losing the branch node updates.

### PR DESCRIPTION
**Pull request by mediocregopher**
This commit contains 3 bug fixes related to branch node update retention.

**Fix 1**

The ParallelSparseTrie previously kept the `Option<SparseTrieUpdates>` field, used to both enable and collect branch node updates, in multiple places:

* 1 on the ParallelSparseTrie
* 1 on the upper SparseSubtrie
* 1 on each of the 256 lower SparseSubtries.

This caused issues in `remove_leaf`, which needs to fully remove a lower subtrie if it no longer has any nodes, and would therefore lose any accumulated branch node updates.

The fix is to only track branch node updates on the ParallelSparseTrie. This introduces a new wrinkle, which is that `update_hashes` runs in parallel on each lower subtrie and needs to make changes to the global update set. To get around this we track these changes using a `Vec<SparseTrieUpdatesAction>` on each lower subtrie, and then apply those actions in `update_subtrie_hashes`.

**Fix 2**

`with_updates` wasn't properly propagating the setting to the lower subtries. Existing lower subtries wouldn't receive the setting, and any created afterwards wouldn't either. This has been fixed, in that the lower subtries don't track the setting at all anymore, and have it passed to their methods when needed.

**Fix 3**

Fixing the above revealed that `update_leaf` had a bug which went unnoticed before because update retention wasn't actually active. When turning an extension into a branch, it's possible `update_leaf` would need to reveal the previous child of the extension. This was failing in cases where the extension was on the upper trie and the child on a lower one. This has been fixed and a test case added.

Fixes #17172

### CODE REVIEW

File: crates/trie/sparse-parallel/src/trie.rs [hunk 1]
```diff
@@ -514,8 +551,10 @@ impl SparseTrieInterface for ParallelSparseTrie {
...
         drop(tx);
 
-        // Return updated subtries back to the trie
-        for (index, subtrie) in rx {
+        // Return updated subtries back to the trie after executing any actions required on the
+        // top-level `SparseTrieUpdates`.
+        for (index, mut subtrie) in rx {
+            Self::apply_subtrie_update_actions(self.updates.as_mut(), &mut subtrie);
             self.lower_subtries[index] = Some(subtrie);
         }
```
Comment (mattsse) [inline crates/trie/sparse-parallel/src/trie.rs]: the order in which we process them doesn't matter right?

Comment (mediocregopher) [reply crates/trie/sparse-parallel/src/trie.rs]: The order with respect to lower subtrie doesn't matter, because each lower subtrie is only going to produce updates for its own branch nodes (ie those branch nodes with the subtrie's two-nibble prefix)

**Review by shekhirin — APPROVED** [review]
LGTM

File: crates/trie/sparse-parallel/src/trie.rs [hunk 2]
```diff
@@ -1403,17 +1459,24 @@ impl SparseSubtrie {
...
     /// # Panics
     ///
     /// If the node at the root path does not exist.
-    #[instrument(level = "trace", target = "engine::tree", skip_all, fields(root = ?self.path), ret)]
-    pub fn update_hashes(&mut self, prefix_set: &mut PrefixSet) -> RlpNode {
+    #[instrument(level = "trace", target = "trie::parallel_sparse", skip_all, fields(root = ?self.path), ret)]
+    fn update_hashes(
+        &mut self,
+        prefix_set: &mut PrefixSet,
+        update_actions: &mut Option<Vec<SparseTrieUpdatesAction>>,
```
Comment (Rjected) [inline crates/trie/sparse-parallel/src/trie.rs:1478]: is the idea here that we will be allocation a few of these action lists and reusing then?

**Review by Rjected — APPROVED** [review]
lgtm, makes sense, I do have one question about allocation

File: crates/trie/sparse-parallel/src/trie.rs (hunk 2 above)
Comment (mediocregopher) [reply crates/trie/sparse-parallel/src/trie.rs:1478]: I wanted to leave open room to do that, yeah, also it just looked weird to me to be accepting prefix set as a `&mut` but then return the Vec. At this point it doesn't matter much either way though.

Comment (mediocregopher) [reply crates/trie/sparse-parallel/src/trie.rs:1478]: Oh! and it also moves the logic for deciding if update retention is enabled outside of `update_hashes`, because SparseSubtrie doesn't have a way of knowing that anymore
