### PR TITLE
dev: test vectors seed

### LINKED ISSUE #10610: Report seed for failed Proptest tests in CI
### Describe the feature

If `proptest` fails, we have no insight into how to reproduce the failure. We should report the seed used for the test run.

I'm sure there's a native way to do so in `proptest-rs`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by greged93**
Adds a print of the seed for the `reth-db` test vectors used in the benches. 

Unfortunately `proptest` hides the seed in an internal struct which we don't have access to, so we create a seed ourselves (using `getrandom` as done in proptest) and use this seed for the test.

Resolves #10610

### CODE REVIEW

File: crates/cli/commands/src/test_vectors/tables.rs [hunk 1]
```diff
@@ -37,6 +46,7 @@ pub(crate) fn generate_vectors(mut tables: Vec<String>) -> Result<()> {
                 tables = all_tables;
             }
 
+            println!("Seed for test vectors: {:?}", seed);
```
Comment (onbjerg) [inline crates/cli/commands/src/test_vectors/tables.rs:49]: let's move this outside of the macro, there is no reason for it to be in here

**Review by onbjerg — CHANGES_REQUESTED** [review]
smol request

**Review by shekhirin — APPROVED** [review]
LGTM modulo @onbjerg's request

**Review by onbjerg — APPROVED** [review]
