### PR TITLE
fix: perform forkchoice update consistency checks

### LINKED ISSUE #2955: Inconsistent {Head,Safe,Finalized} hive tests are failing
### Describe the bug

These tests send an inconsistent ForkchoiceState with a known payload that belongs to a side chain as head, safe or finalized.

https://github.com/mattsse/hive/blob/master/simulators/ethereum/engine/suites/engine/tests.go#L1417-L1422

geth sends here 

{"code":-38002,"message":"Invalid forkchoice state","data":{"err":"final block not in canonical chain"}}}

we're missing these checks before processing FCU

https://github.com/ethereum/go-ethereum/blob/73697529994e14996b7740730481e926d5ec3e40/eth/catalyst/api.go#L309-L317

### Steps to reproduce

./hive --client reth --sim ethereum/engine --sim.limit "/Inconsistent Head in ForkchoiceState"

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by Rjected**
Previously we didn't check that the forkchoice state was consistent with the head that was made canonical, i.e., we did not check that the safe block is an ancestor of the head block, and did not check that the finalized block is an ancestor of the head / safe blocks. This adds a method to check that a block is canonical in `BlockchainTreeViewer` so we can perform these checks.

Consistency checks are done in geth _after_ the forkchoice update is processed and head block is made canonical:
https://github.com/ethereum/go-ethereum/blob/2754b197c935ee63101cbbca2752338246384fec/eth/catalyst/api.go#L315-L318

So we do the same thing here. The safe / finalized blocks are updated in the chain tracker as they are known to be consistent with the head block.

Fixes #2955

Fixes additional hive tests:
 * `Unknown HeadBlockHash`
 * `Unknown SafeBlockHash`
 * `Unknown FinalizedBlockHash`

### CODE REVIEW

File: crates/consensus/beacon/src/engine/mod.rs [hunk 1]
```diff
@@ -639,22 +647,117 @@ where
...
+
+    /// Ensures that the given forkchoice state is consistent, assuming the head block has been
+    /// made canonical.
+    ///
+    /// If the forkchoice state is consistent, this will return Ok(None). Otherwise, this will
+    /// return an instance of [OnForkChoiceUpdated] that is INVALID.
+    ///
+    /// This also updates the safe and finalized blocks in the [CanonChainTracker], if they are
+    /// consistent with the head block.
+    fn ensure_consistent(
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:698]: I'd like to put either `_state` or `forkchoice_state` at the end of the function name

File: crates/consensus/beacon/src/engine/mod.rs [hunk 2]
```diff
@@ -639,22 +647,117 @@ where
...
+    /// Ensures that the given forkchoice state is consistent, assuming the head block has been
+    /// made canonical. This takes a status as input, and will only perform consistency checks if
+    /// the input status is VALID.
+    ///
+    /// If the forkchoice state is consistent, this will return Ok(None). Otherwise, this will
+    /// return an instance of [OnForkChoiceUpdated] that is INVALID.
+    ///
+    /// This also updates the safe and finalized blocks in the [CanonChainTracker], if they are
+    /// consistent with the head block.
+    fn ensure_consistent_with_status(
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:668]: same

File: crates/consensus/beacon/src/engine/mod.rs [hunk 3]
```diff
@@ -639,22 +647,117 @@ where
...
+
     /// Sets the state of the canon chain tracker based to the given head.
     ///
     /// This expects the given head to be the new canonical head.
     ///
     /// Additionally, updates the head used for p2p handshakes.
     ///
-    /// This should be called before issuing a VALID forkchoice update.
+    /// This also updates the tracked safe and finalized blocks, and should be called before
+    /// issuing a VALID forkchoice update.
```
Comment (mattsse) [inline crates/consensus/beacon/src/engine/mod.rs:740]:
```suggestion
    /// return a VALID forkchoice update response
```

**Review by mattsse — CHANGES_REQUESTED** [review]
nice!
love the docs

just a nit re function names

**Review by mattsse — APPROVED** [review]
lgtm, pending rebase

File: crates/consensus/beacon/src/engine/mod.rs (hunk 1 above)
Comment (Rjected) [reply crates/consensus/beacon/src/engine/mod.rs]: makes sense, changed to `ensure_consistent_state`

File: crates/consensus/beacon/src/engine/mod.rs (hunk 2 above)
Comment (Rjected) [reply crates/consensus/beacon/src/engine/mod.rs]: changed this one to `ensure_consistent_state_with_status`
