### PR TITLE
fix: Returns an error if multiplex message is empty

### LINKED ISSUE #7281: Return an error if multiplex message is empty
Right now if the message is empty, this
https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/eth-wire/src/multiplex.rs#L169
and this
https://github.com/paradigmxyz/reth/blob/66c9403ea1d3d03938eafc099e64e789aadc3616/crates/net/eth-wire/src/multiplex.rs#L512

will panic. We should use `.get(0)` here and return an error if the call returns `None`.

### PR DESCRIPTION
**Pull request by kamuik16**
Fixes #7281

Don't know if I should have defined a new error for this.

### CODE REVIEW

**Comment by kamuik16** [comment]
Most of the tests are passing but some tests fails but I don't think it is related to the changes I made.
```bash
test roundtrip_pooled_transactions_fuzz::auto_generate ... FAILED
test decode_pooled_transactions_data ... FAILED
```

File: crates/net/eth-wire/src/multiplex.rs [hunk 1]
```diff
@@ -166,7 +166,10 @@ impl<St> RlpxProtocolMultiplexer<St> {
             tokio::select! {
                 Some(Ok(msg)) = self.inner.conn.next() => {
                     // Ensure the message belongs to the primary protocol
-                    let offset = msg[0];
+                    let offset = match msg.get(0) {
+                        Some(&byte) => byte,
+                        None => return Err(P2PStreamError::EmptyProtocolMessage.into())
+                    };
```
Comment (mattsse) [inline crates/net/eth-wire/src/multiplex.rs:172]: style: this can be `let Some (offset) msg.first() else return` `

**Review by mattsse — CHANGES_REQUESTED** [review]

File: crates/net/eth-wire/src/multiplex.rs (hunk 1 above)
Comment (kamuik16) [reply crates/net/eth-wire/src/multiplex.rs:172]: > style: this can be `let Some (offset) = msg.first() else return` `

The return Err is right though, right?

File: crates/net/eth-wire/src/multiplex.rs [hunk 2]
```diff
@@ -518,7 +521,11 @@ where
                 match this.inner.conn.poll_next_unpin(cx) {
                     Poll::Ready(Some(Ok(msg))) => {
                         delegated = true;
-                        let offset = msg[0];
+                        let Some(&offset) = msg.first() else {
```
Comment (mattsse) [inline crates/net/eth-wire/src/multiplex.rs:524]:
```suggestion
                        let Some(offset) = msg.first() else {
```

File: crates/net/eth-wire/src/multiplex.rs [hunk 3]
```diff
@@ -166,7 +166,10 @@ impl<St> RlpxProtocolMultiplexer<St> {
             tokio::select! {
                 Some(Ok(msg)) = self.inner.conn.next() => {
                     // Ensure the message belongs to the primary protocol
-                    let offset = msg[0];
+                    let Some(&offset) = msg.first()
```
Comment (mattsse) [inline crates/net/eth-wire/src/multiplex.rs:169]:
```suggestion
                    let Some(offset) = msg.first()
```

Comment (mattsse) [reply crates/net/eth-wire/src/multiplex.rs:169]: perhaps firs().copied() is required here

**Review by mattsse — CHANGES_REQUESTED** [review]
pedantic last style nit :)

**Review by mattsse — APPROVED** [review]
